-- FULL SEED 2026 (PAKET A - J)
-- SCRIPT GENERATED FROM soal_tes.json

DELETE FROM soal_tes WHERE tahun = 2026;

INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, tipe_soal) VALUES
(2026, 1, 'Berdasarkan Lukas 2:52, aspek pertumbuhan Yesus yang harus diteladani remaja GMIM adalah ...', 'Fisik, hikmat, rohani, dan sosial', 'Fisik, kekayaan, popularitas, dan kuasa', 'Hikmat, umur, kasih karunia, dan kuasa', 'Rohani, sosial, ekonomi, dan politik', 'a', 'pilihan_ganda'),
(2026, 2, 'Visi pelayanan Remaja GMIM adalah ...', 'Remaja yang berakar, bertumbuh, dan berbuah', 'Remaja Bagi Kristus (Teens for Christ)', 'Remaja Teladan GMIM', 'Remaja Kreatif dan Inovatif', 'b', 'pilihan_ganda'),
(2026, 3, 'Misi pelayanan Remaja GMIM adalah ...', 'Menjadikan remaja GMIM yang berakar, bertumbuh, dan berbuah bagi Kristus', 'Menjadikan remaja GMIM yang pintar dan berprestasi', 'Menjadikan remaja GMIM yang kaya dan terkenal', 'Menjadikan remaja GMIM yang patuh pada orang tua', 'a', 'pilihan_ganda'),
(2026, 4, 'Sistem pemerintahan GMIM adalah ...', 'Episkopal', 'Kongregasional', 'Presbiterial Sinodal', 'Kharismatik', 'c', 'pilihan_ganda'),
(2026, 5, 'GMIM berdiri sendiri sebagai gereja mandiri pada tanggal ...', '17 September 1934', '30 September 1934', '28 Januari 1990', '12 Juni 1831', 'b', 'pilihan_ganda'),
(2026, 6, 'Komisi Pelayanan Remaja Sinode GMIM (KPRS) berdiri sendiri pada tanggal ...', '28 Januari 1990', '30 September 1934', '17 Agustus 1945', '28 Oktober 1928', 'a', 'pilihan_ganda'),
(2026, 7, 'Hari Persatuan Remaja GMIM diperingati setiap tanggal ...', '28 Januari', '30 September', '17 Agustus', '1 April', 'a', 'pilihan_ganda'),
(2026, 8, 'Semboyan Reformasi Gereja "Sola Fide" berarti ...', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapakah penginjil yang dijuluki "Rasul Maluku" dan datang ke Minahasa pada tahun 1817?', 'J.G. Schwarz', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'b', 'pilihan_ganda'),
(2026, 10, 'Apakah kepanjangan dari NZG?', 'Nederlands Zendeling Genootschap', 'Nederlands Zending Genootschap', 'Nederland Zending Genootschap', 'Nederlands Zendeling Genootschap', 'b', 'pilihan_ganda'),
(2026, 11, 'Siapakah nama ayah dari Samuel dalam Perjanjian Lama?', 'Elkana', 'Hana', 'Imamat', 'Saul', 'a', 'pilihan_ganda'),
(2026, 12, 'Berapa jumlah orang yang dibaptis pada hari Pentakosta?', '120 orang', '3.000 orang', '5.000 orang', '12 orang', 'b', 'pilihan_ganda'),
(2026, 13, 'Kata "Imago Dei" berarti ...', 'Manusia adalah gambar Allah', 'Manusia adalah ciptaan Allah', 'Manusia adalah hamba Allah', 'Manusia adalah teman Allah', 'a', 'pilihan_ganda'),
(2026, 14, 'Dalam Tata Gereja GMIM 2021, remaja adalah anggota GMIM berusia ...', '12-16 tahun 364 hari', '12-17 tahun', '13-17 tahun', '12-18 tahun', 'a', 'pilihan_ganda'),
(2026, 15, 'Satu periode pelayanan BPMS GMIM adalah ...', '3 tahun', '4 tahun', '5 tahun', '6 tahun', 'c', 'pilihan_ganda'),
(2026, 16, 'Siapakah nama Ketua Sinode GMIM pertama?', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'a', 'pilihan_ganda'),
(2026, 17, 'Siapakah nama Ketua Sinode GMIM orang Minahasa pertama?', 'Ds. A.Z.R. Wenas', 'Ds. E.A.A. de Vreede', 'Pdt. R.M. Luntungan', 'Pdt. M. Sondakh', 'a', 'pilihan_ganda'),
(2026, 18, 'Lambang GMIM adalah burung ...', 'Manguni', 'Garuda', 'Rajawali', 'Merpati', 'a', 'pilihan_ganda'),
(2026, 19, 'Apa makna falsafah Minahasa "Sitou Timou Tumou Tou"?', 'Manusia hidup untuk memanusiakan manusia lain', 'Manusia hidup untuk bekerja keras', 'Manusia hidup untuk beribadah', 'Manusia hidup untuk bersenang-senang', 'a', 'pilihan_ganda'),
(2026, 20, 'Kepanjangan dari LKRG adalah ...', 'Latihan Kader Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'a', 'pilihan_ganda'),
(2026, 21, 'Program pemuridan KPRS yang disebut KB3 adalah singkatan dari ...', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Keluarga Berakar, Bertumbuh, Berbuah', 'Kelompok Berakar, Bertumbuh, Berbuah', 'Kesatuan Berakar, Bertumbuh, Berbuah', 'a', 'pilihan_ganda'),
(2026, 22, 'Lagu "Menjadi Teladan" diciptakan oleh ...', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. Jantje Wowiling Sajow', 'Pnt. dr. Michaela E. Paruntu', 'Pdt. Dr. Hein Arina', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah yang menulis surat kepada jemaat di Roma?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 24, '"Aku percaya kepada satu Allah, Bapa yang mahakuasa, Pencipta langit dan bumi" adalah kalimat pembuka dari ...', 'Pengakuan Iman Rasuli', 'Pengakuan Iman Nicea-Konstantinopel', 'Pengakuan Iman Athanasius', 'Doa Bapa Kami', 'b', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang disebut sebagai "Gembala yang Baik" dalam Yohanes 10?', 'Yesus Kristus', 'Petrus', 'Paulus', 'Daud', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa inti dari Amanat Agung Yesus dalam Matius 28:19-20?', 'Pergi, jadikan semua bangsa murid, baptis, dan ajarkan', 'Kasihilah sesamamu seperti dirimu sendiri', 'Jangan membunuh dan jangan mencuri', 'Berdoalah tanpa henti', 'a', 'pilihan_ganda'),
(2026, 27, 'Buah Roh dalam Galatia 5:22-23 terdiri dari ...', 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri', 'Iman, pengharapan, kasih', 'Hikmat, pengertian, nasihat, keperkasaan', 'Kemuliaan, hormat, kuasa, kekuatan', 'a', 'pilihan_ganda'),
(2026, 28, 'Siapakah yang melempar Daud ke dalam gua singa?', 'Raja Darius', 'Raja Nebukadnezar', 'Raja Herodes', 'Raja Saul', 'a', 'pilihan_ganda'),
(2026, 29, 'Program SIKAT yang dikembangkan KPRS adalah singkatan dari ...', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Komunikasi Terpadu', 'Sistem Informasi Kegiatan Terkini', 'Sistem Informasi Keuangan Terpadu', 'a', 'pilihan_ganda'),
(2026, 30, 'Tahun 2025, KPRS mengadakan program GEMAR yang dikelola bidang ...', 'Ajaran, Persekutuan, Ibadah dan Misi (APIM)', 'Pengembangan Minat dan Bakat (PMB)', 'Pembinaan dan Pengembangan SDM (P3SDM)', 'Teknologi Informasi dan Komunikasi (TIK)', 'a', 'pilihan_ganda'),
(2026, 31, 'Untuk membantu pelayanan KPRS, dibentuk Koordinatorium Rayon Pelayanan yang dibagi dalam ... rayon', '10', '11', '12', '13', 'c', 'pilihan_ganda'),
(2026, 32, 'Siapakah nama hamba Imam Besar yang telinga kanannya putus karena dipotong Simon Petrus?', 'Malkhus', 'Yudas', 'Anas', 'Kayafas', 'a', 'pilihan_ganda'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Yeremia?', '42', '52', '62', '72', 'b', 'pilihan_ganda'),
(2026, 34, 'Kota apakah yang disebut sebagai kota Daud?', 'Betlehem', 'Yerusalem', 'Nazaret', 'Hebron', 'a', 'pilihan_ganda'),
(2026, 35, 'Pada hari ke berapakah Allah menjadikan benda-benda penerang pada cakrawala?', 'Hari kedua', 'Hari ketiga', 'Hari keempat', 'Hari kelima', 'c', 'pilihan_ganda'),
(2026, 36, 'Berapakah jumlah ikan yang diperoleh para murid setelah Yesus menyuruh menebarkan jala di sebelah kanan perahu?', '120 ekor', '150 ekor', '153 ekor', '200 ekor', 'c', 'pilihan_ganda'),
(2026, 37, 'Apakah tema mingguan MTPJ pada tanggal 25-31 Mei 2025?', 'Berbahagia dan Kuduslah Mereka yang Mendapat Bagian dalam Kebangkitan', 'Yesus Menampakkan Diri Setelah Bangkit', 'Percaya kepada Kristus yang Bangkit', 'Tuhan Allah, Pahlawan yang Memberi Kemenangan', 'a', 'pilihan_ganda'),
(2026, 38, 'Siapakah Ketua BPMS GMIM yang memimpin saat GMIM mengubah eklesiologinya menjadi Gereja Global?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. A.O. Supit', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah penginjil yang datang ke tanah Minahasa pada tahun 1817?', 'Johann Friedrich Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 40, 'Dalam Tata Dasar Bab II Pasal 7, anggota GMIM adalah ...', 'Orang-orang percaya kepada Yesus Kristus yang terdaftar di salah satu jemaat GMIM', 'Semua orang yang tinggal di Minahasa', 'Orang-orang yang lahir di Minahasa', 'Mereka yang dibaptis di GMIM', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Matahari terbit di timur dan terbenam di barat" merupakan contoh kalimat ...', 'Fakta', 'Opini', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Pemerintah Indonesia resmi memindahkan Ibu Kota Negara ke ... pada tahun 2024', 'Nusantara (Kalimantan Timur)', 'Palangkaraya', 'Balikpapan', 'Samarinda', 'a', 'pilihan_ganda'),
(2026, 43, 'The antonym of the word "victory" is ...', 'Defeat', 'Success', 'Triumph', 'Win', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah KTT G20 pada tahun ...', '2022', '2023', '2024', '2025', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 25 × 4 - 100 ÷ 5 adalah ...', '80', '100', '120', '90', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama gunung berapi di Sulawesi Utara yang meletus pada April 2024?', 'Gunung Ruang', 'Gunung Lokon', 'Gunung Soputan', 'Gunung Karangetang', 'a', 'pilihan_ganda'),
(2026, 47, 'KTT G20 tahun 2025 dilaksanakan di negara ...', 'Afrika Selatan', 'Brasil', 'India', 'Indonesia', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari AI (kecerdasan buatan) dalam bahasa Inggris adalah ...', 'Artificial Intelligence', 'Artificial Information', 'Automated Intelligence', 'Advanced Integration', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara yang tidak pernah mengalami penjajahan di Asia Tenggara adalah ...', 'Thailand', 'Indonesia', 'Malaysia', 'Vietnam', 'a', 'pilihan_ganda'),
(2026, 50, 'Ciri utama dari sistem ekonomi Pancasila adalah ...', 'Kekeluargaan dan gotong royong', 'Bebas dan liberal', 'Terpusat dan komando', 'Kapitalis dan individualis', 'a', 'pilihan_ganda'),
(2026, 1, 'Model remaja GMIM yang diharapkan berdasarkan Lukas 2:52 adalah remaja yang bertumbuh dalam ...', 'Fisik, hikmat, rohani, dan sosial', 'Fisik, ekonomi, politik, dan budaya', 'Rohani, intelektual, ekonomi, dan sosial', 'Hikmat, popularitas, kekayaan, dan kuasa', 'a', 'pilihan_ganda'),
(2026, 2, 'Visi "Remaja Bagi Kristus" mengandung makna bahwa ...', 'Seluruh hidup remaja dipersembahkan bagi Kristus', 'Remaja hanya datang ke gereja pada hari Minggu', 'Remaja harus menjadi pendeta', 'Remaja harus meninggalkan dunia', 'a', 'pilihan_ganda'),
(2026, 3, 'Tujuan program LKRG adalah ...', 'Mempersiapkan kader remaja yang militan dan berkarakter Kristus', 'Melatih remaja menjadi pengusaha sukses', 'Mempersiapkan remaja menjadi atlet', 'Mengajarkan remaja keterampilan digital', 'a', 'pilihan_ganda'),
(2026, 4, 'Sakramen yang dilayankan GMIM adalah ...', 'Baptisan Kudus dan Perjamuan Kudus', 'Baptisan, Perjamuan Kudus, dan Pernikahan', 'Baptisan, Krisma, dan Perjamuan Kudus', 'Perjamuan Kudus dan Pengakuan Dosa', 'a', 'pilihan_ganda'),
(2026, 5, 'Pembukaan Tata Gereja GMIM 2021 menyatakan bahwa GMIM adalah bagian dari ...', 'Gereja Protestan di Indonesia', 'Gereja Katolik', 'Gereja Pentakosta', 'Gereja Orthodox', 'a', 'pilihan_ganda'),
(2026, 6, 'Pemilihan Remaja Teladan GMIM memiliki tahapan akhir yang disebut ...', 'Grand Final', 'Karantina', 'Pelayanan Holistik', 'Kompetisi Potensi Diri', 'a', 'pilihan_ganda'),
(2026, 7, 'Bobot penilaian untuk tahap Karantina dan Pelayanan Holistik dalam Pemilihan Remaja Teladan adalah ...', '35%', '25%', '20%', '15%', 'a', 'pilihan_ganda'),
(2026, 8, 'Semboyan Reformasi "Sola Gratia" berarti ...', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapa yang mencetuskan Reformasi Gereja pada tahun 1517?', 'Martin Luther', 'Yohanes Calvin', 'John Knox', 'Ulrich Zwingli', 'a', 'pilihan_ganda'),
(2026, 10, 'Apakah yang dimaksud dengan "Presbiterial Sinodal"?', 'Sistem kepemimpinan kolektif para penatua dengan musyawarah', 'Sistem kepemimpinan satu uskup', 'Sistem kepemimpinan yang terpusat', 'Sistem kepemimpinan yang demokratis', 'a', 'pilihan_ganda'),
(2026, 11, 'Siapakah yang menggantikan Yudas Iskariot sebagai rasul?', 'Matias', 'Barnabas', 'Stefanus', 'Filipus', 'a', 'pilihan_ganda'),
(2026, 12, 'Berapa jumlah kitab dalam Perjanjian Baru?', '27', '39', '66', '24', 'a', 'pilihan_ganda'),
(2026, 13, 'Nats "Jangan seorang pun menganggap engkau rendah karena engkau muda" terdapat dalam ...', '1 Timotius 4:12', '2 Timotius 4:12', 'Titus 4:12', 'Efesus 4:12', 'a', 'pilihan_ganda'),
(2026, 14, 'Dalam Tata Gereja GMIM 2021, satu periode pelayanan GMIM adalah ...', '5 tahun', '4 tahun', '3 tahun', '6 tahun', 'a', 'pilihan_ganda'),
(2026, 15, 'Tahun pelayanan dan tahun anggaran GMIM dimulai tanggal ...', '1 Januari sampai 31 Desember', '1 April sampai 31 Maret', '1 Maret sampai 28 Februari', '1 Juli sampai 30 Juni', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah Ketua Sinode GMIM yang menjabat dua periode?', 'Ds. A.Z.R. Wenas dan Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'Pdt. Piet M. Tampi', 'Ds. E.A.A. de Vreede', 'a', 'pilihan_ganda'),
(2026, 17, 'Siapakah yang mengutus misionaris Schwarz dan Riedel ke Minahasa?', 'NZG (Nederlands Zending Genootschap)', 'Zending Belanda', 'Indische Kerk', 'Gereja Reformasi Belanda', 'a', 'pilihan_ganda'),
(2026, 18, 'Apa warna dasar selempang untuk finalis Remaja Teladan tingkat Sinode?', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan emas', 'Ungu dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 19, 'Apa makna burung Manguni dalam lambang GMIM?', 'Gereja sebagai terang di tengah kegelapan', 'Gereja yang kuat dan perkasa', 'Gereja yang kaya raya', 'Gereja yang modern', 'a', 'pilihan_ganda'),
(2026, 20, 'Kepanjangan dari PKRS adalah ...', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menciptakan Mars Remaja GMIM?', 'Pnt. Jantje Wowiling Sajow', 'Pnt. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pdt. Hein Arina', 'a', 'pilihan_ganda'),
(2026, 22, 'Program GEMAR (Gerakan Membaca Alkitab Remaja) bertujuan untuk ...', 'Mendorong remaja membaca Alkitab secara terstruktur', 'Mengajarkan remaja bermain musik', 'Melatih remaja menjadi pengkhotbah', 'Mengadakan lomba cerdas cermat Alkitab', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah yang menulis kitab Wahyu?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 24, '"Aku percaya kepada Allah, Bapa yang mahakuasa, Khalik langit dan bumi" adalah pengakuan iman ...', 'Pengakuan Iman Rasuli', 'Pengakuan Iman Nicea-Konstantinopel', 'Pengakuan Iman Athanasius', 'Doa Bapa Kami', 'a', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang disebut sebagai "Bapa Orang Percaya"?', 'Abraham', 'Musa', 'Daud', 'Adam', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa isi dari Sepuluh Perintah Allah (Dekalog)?', 'Perintah untuk mengasihi Tuhan dan sesama', 'Perintah untuk beribadah setiap hari', 'Perintah untuk berpuasa', 'Perintah untuk bersedekah', 'a', 'pilihan_ganda'),
(2026, 27, 'Karunia Roh Kudus dalam 1 Korintus 12 antara lain ...', 'Bernubuat, melayani, mengajar, menasihati', 'Bernyanyi, menari, bermusik, melukis', 'Berbicara dalam bahasa roh, menyembuhkan', 'Semua jawaban benar', 'a', 'pilihan_ganda'),
(2026, 28, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja Babel?', 'Daniel', 'Yusuf', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2026, 29, 'Tuan rumah Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2025 adalah ...', 'Wilayah Sinel', 'Wilayah Airmadidi', 'Wilayah Tomohon', 'Wilayah Tondano', 'a', 'pilihan_ganda'),
(2026, 30, 'Bidang P3SDM dalam KPRS memiliki kepanjangan ...', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, dan Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a', 'pilihan_ganda'),
(2026, 31, 'Wakil Sekretaris Koordinasi Program antar Komisi Pelayanan Kategorial Sinode GMIM adalah ...', 'Pdt. Jefry Saisab, S.Th, M.Si', 'Pdt. Hein Arina, Th.D', 'Pdt. DR. Joice Sondakh, M.Th', 'Pdt. Christian Luwuk, M.Th', 'a', 'pilihan_ganda'),
(2026, 32, 'Siapakah nama isteri Yusuf dalam Kejadian pasal 41?', 'Asnat', 'Dina', 'Abisag', 'Potifera', 'a', 'pilihan_ganda'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Mazmur yang paling panjang?', '119', '117', '150', '100', 'a', 'pilihan_ganda'),
(2026, 34, 'Kota apakah yang menjadi tempat kelahiran Yesus?', 'Betlehem', 'Nazaret', 'Yerusalem', 'Kapernaum', 'a', 'pilihan_ganda'),
(2026, 35, 'Siapakah nama ibu dari Samuel?', 'Hana', 'Elkana', 'Sara', 'Ribka', 'a', 'pilihan_ganda'),
(2026, 36, 'Apakah nama lain yang diberikan kepada Daniel oleh pegawai istana Babel?', 'Beltsazar', 'Sadrakh', 'Mesakh', 'Abednego', 'a', 'pilihan_ganda'),
(2026, 37, 'Apakah judul perikop dari Roma 10:4-15?', 'Kebenaran karena iman', 'Keselamatan oleh kasih karunia', 'Pembenaran oleh iman', 'Ketaatan karena iman', 'a', 'pilihan_ganda'),
(2026, 38, 'Siapakah Ketua Komisi Pelayanan Remaja Sinode GMIM periode 2022-2027?', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. Melky R. Pattiwael, S.IK, M.S', 'Pnt. Edward Saragih, SAP', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah nama misionaris yang melayani di Langowan dan Kakas?', 'J.G. Schwarz', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 40, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 1, penyelenggaraan panggilan GMIM bersumber dari ...', 'Pola pelayanan dan pemerintahan Kristus', 'Tata Gereja GMIM', 'Kesaksian Alkitab', 'Yesus Kristus', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Sayur itu akan terasa lebih sedap jika ditambah sedikit garam" merupakan contoh kalimat ...', 'Asumsi', 'Fakta', 'Opini', 'Deskripsi', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa presiden terpilih Indonesia pada Pemilu 2024?', 'Prabowo Subianto', 'Ganjar Pranowo', 'Anies Baswedan', 'Joko Widodo', 'a', 'pilihan_ganda'),
(2026, 43, 'Which sentence uses the correct conditional form?', 'If I study hard, I will pass the exam', 'If I will study hard, I will pass the exam', 'If I studied hard, I will pass the exam', 'If I study hard, I would pass the exam', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi anggota BRICS pada tahun ...', '2024', '2023', '2025', '2022', 'a', 'pilihan_ganda'),
(2026, 45, 'Sebuah kubus memiliki panjang sisi 4 cm. Volume kubus tersebut adalah ...', '64 cm³', '16 cm³', '48 cm³', '32 cm³', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama bendungan yang diresmikan Presiden Jokowi di Sulawesi Utara pada Februari 2024?', 'Bendungan Lolak', 'Bendungan Kuwi', 'Bendungan Kuwil', 'Bendungan Tondano', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia FIFA 2026 akan diselenggarakan bersama oleh negara ...', 'Amerika Serikat, Kanada, Meksiko', 'Amerika Serikat, Inggris, Prancis', 'Kanada, Meksiko, Brasil', 'Spanyol, Portugal, Maroko', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari API dalam bidang teknologi adalah ...', 'Application Programming Interface', 'Advanced Programming Interface', 'Automated Programming Integration', 'Application Processing Interface', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara dengan jumlah penduduk terbanyak di dunia adalah ...', 'India', 'China', 'Amerika Serikat', 'Indonesia', 'a', 'pilihan_ganda'),
(2026, 50, 'Kebijakan pemerintah Indonesia untuk membatasi penggunaan media sosial bagi anak di bawah umur disebut ...', 'Pembatasan usia pengguna medsos', 'Digital restriction', 'Social media ban', 'Internet filter', 'a', 'pilihan_ganda'),
(2026, 1, 'Makna dari "Remaja Teladan" menurut Pola Baku GMIM adalah ...', 'Remaja yang memiliki prestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang kaya dan terkenal', 'Remaja yang populer di media sosial', 'Remaja yang menjadi ketua OSIS', 'a', 'pilihan_ganda'),
(2026, 2, 'Salah satu aspek yang dinilai dalam Pemilihan Remaja Teladan adalah ...', 'Pelayanan Holistik', 'Kekayaan orang tua', 'Popularitas di media sosial', 'Jumlah teman', 'a', 'pilihan_ganda'),
(2026, 3, 'Kepanjangan dari P3SDM dalam struktur KPRS adalah ...', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a', 'pilihan_ganda'),
(2026, 4, 'Sakramen Baptisan Kudus dalam GMIM dilayankan ...', 'Sekali seumur hidup', 'Setiap tahun', 'Setiap kali bertobat', 'Sebelum menikah', 'a', 'pilihan_ganda'),
(2026, 5, 'Badan Pekerja Majelis Sinode (BPMS) dipilih setiap ...', '5 tahun sekali dalam Sidang Majelis Sinode', '4 tahun sekali', '3 tahun sekali', '6 tahun sekali', 'a', 'pilihan_ganda'),
(2026, 6, 'Tahapan seleksi Pemilihan Remaja Teladan yang berupa pengabdian kepada jemaat adalah ...', 'Pelayanan Holistik', 'Karantina', 'Kompetisi Potensi Diri', 'Tes Wawancara', 'a', 'pilihan_ganda'),
(2026, 7, 'Bobot penilaian untuk tahap Kompetisi Potensi Diri adalah ...', '25%', '35%', '20%', '15%', 'a', 'pilihan_ganda'),
(2026, 8, 'Semboyan Reformasi "Soli Deo Gloria" berarti ...', 'Segala kemuliaan hanya bagi Tuhan', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh kasih karunia', 'Hanya Alkitab sebagai otoritas', 'a', 'pilihan_ganda'),
(2026, 9, 'Apa yang dimaksud dengan "Indische Kerk"?', 'Gereja Hindia Belanda yang menjadi cikal bakal GMIM', 'Gereja pertama di Indonesia', 'Gereja yang didirikan oleh para misionaris', 'Gereja di tanah Minahasa', 'a', 'pilihan_ganda'),
(2026, 10, 'Siapakah Ketua BPMS GMIM periode 2018-2022?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'a', 'pilihan_ganda'),
(2026, 11, 'Siapakah yang menulis kitab Amsal?', 'Salomo', 'Daud', 'Musa', 'Yeremia', 'a', 'pilihan_ganda'),
(2026, 12, 'Berapa jumlah kitab dalam Perjanjian Lama?', '39', '27', '66', '40', 'a', 'pilihan_ganda'),
(2026, 13, 'Ayat terpendek dalam Alkitab adalah ...', 'Yohanes 11:35', '1 Tesalonika 5:16', 'Mazmur 117:1', 'Amsal 20:10', 'a', 'pilihan_ganda'),
(2026, 14, 'Dalam Peraturan tentang Jemaat, remaja adalah anggota GMIM berusia ...', '12-16 tahun 364 hari', '13-17 tahun', '12-17 tahun', '11-16 tahun', 'a', 'pilihan_ganda'),
(2026, 15, 'Tahun pelayanan BPMJ dimulai tanggal ...', '1 Januari', '1 Maret', '1 April', '1 Juli', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah Ketua Sinode GMIM yang dikenal dengan slogan "Tuhan mengangkat kita dari Samudera Raya"?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'a', 'pilihan_ganda'),
(2026, 17, 'Siapakah nama misionaris yang melayani di Tondano?', 'J.F. Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 18, 'Apa warna selempang untuk finalis Remaja Teladan tingkat Wilayah?', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 19, 'Tarian tradisional Minahasa yang menggambarkan sukacita panen adalah ...', 'Tari Maengket', 'Tari Kabasaran', 'Tari Cakalele', 'Tari Gantar', 'a', 'pilihan_ganda'),
(2026, 20, 'Kepanjangan dari PSR (dalam kegiatan remaja) adalah ...', 'Pesta Seni Remaja', 'Perkemahan Seni Remaja', 'Pekan Seni Remaja', 'Pentas Seni Remaja', 'a', 'pilihan_ganda'),
(2026, 21, 'Lagu Mars Remaja GMIM pertama kali diperkenalkan pada tahun ...', '1990', '1995', '2000', '2005', 'a', 'pilihan_ganda'),
(2026, 22, 'Siapakah Ketua KPRS periode 2014-2018?', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. dr. Michaela E. Paruntu', 'Pnt. Melky R. Pattiwael', 'Pnt. Edward Saragih', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah yang menulis surat kepada jemaat di Korintus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 24, 'Perikop terpendek dalam Mazmur adalah ...', 'Mazmur 117:1-2', 'Mazmur 23:1-6', 'Mazmur 1:1-6', 'Mazmur 150:1-6', 'a', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang menulis kitab Kisah Para Rasul?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa pesan utama dari perumpamaan tentang Talenta?', 'Kita harus mengembangkan karunia yang Tuhan berikan', 'Kita harus menyembunyikan talenta', 'Kita harus mencari talenta sebanyak-banyaknya', 'Kita harus membuang talenta yang tidak berguna', 'a', 'pilihan_ganda'),
(2026, 27, 'Dalam 1 Korintus 13, yang paling besar di antara iman, pengharapan, dan kasih adalah ...', 'Kasih', 'Iman', 'Pengharapan', 'Ketiganya sama besar', 'a', 'pilihan_ganda'),
(2026, 28, 'Siapakah yang dijual oleh saudara-saudaranya ke Mesir?', 'Yusuf', 'Daniel', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2026, 29, 'Sistem Informasi Kegiatan Terpadu (SIKAT) dikembangkan oleh bidang ...', 'TIK KPRS', 'APIM', 'P3SDM', 'PMB', 'a', 'pilihan_ganda'),
(2026, 30, 'Gelar atribut "Remaja Teladan Intelegensia" diukur dari ...', '50% nilai tes tertulis dan 50% nilai psikotes karantina', '100% nilai tes tertulis', '100% nilai wawancara', '50% nilai wawancara dan 50% nilai karantina', 'a', 'pilihan_ganda'),
(2026, 31, 'Gelar atribut "Remaja Teladan Persahabatan" diukur dari ...', 'Pilihan dari sesama peserta', 'Penilaian juri', 'Like di media sosial', 'Nilai psikotes', 'a', 'pilihan_ganda'),
(2026, 32, 'Siapakah nama ibu dari Yesus?', 'Maria', 'Marta', 'Salome', 'Elisabeth', 'a', 'pilihan_ganda'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Yesaya?', '66', '52', '50', '42', 'a', 'pilihan_ganda'),
(2026, 34, 'Di manakah Yesus dibaptis oleh Yohanes Pembaptis?', 'Sungai Yordan', 'Danau Galilea', 'Laut Mati', 'Bukit Zaitun', 'a', 'pilihan_ganda'),
(2026, 35, 'Siapakah yang menjadi raja pertama Israel?', 'Saul', 'Daud', 'Salomo', 'Yerobeam', 'a', 'pilihan_ganda'),
(2026, 36, 'Berapa lamakah bangsa Israel berjalan di padang gurun?', '40 tahun', '30 tahun', '20 tahun', '10 tahun', 'a', 'pilihan_ganda'),
(2026, 37, 'Apakah tema MTPJ yang berfokus pada "Kebangkitan Yesus mengubah manusia"?', 'Paskah', 'Adven', 'Natal', 'Pentakosta', 'a', 'pilihan_ganda'),
(2026, 38, 'Siapakah Wakil Sekretaris BPMS Bidang Pekerja GMIM dan Pelayan Khusus periode 2014-2018?', 'Pnt. Jhonly Th Wenur, SH, MH, MM', 'Pdt. Richard Mengko', 'Pdt. Altje Runtu-Lumi', 'Pdt. Janny Rende', 'a', 'pilihan_ganda'),
(2026, 39, 'Di manakah makam penginjil Ulfers berada?', 'Tomohon', 'Tondano', 'Kakas', 'Langowan', 'a', 'pilihan_ganda'),
(2026, 40, 'Dalam Tata Dasar Bab III Pasal 8, GMIM ditata dalam sistem ...', 'Presbiterial Sinodal', 'Episkopal', 'Kongregasional', 'Sinodal', 'a', 'pilihan_ganda'),
(2026, 41, 'Kata "hiperbola" dalam kalimat memiliki arti ...', 'Perbandingan yang berlebihan', 'Gambaran yang nyata', 'Makna yang tersembunyi', 'Simbolisme yang mendalam', 'a', 'pilihan_ganda'),
(2026, 42, 'Indonesia menjadi tuan rumah KTT ASEAN pada tahun ...', '2023', '2024', '2025', '2022', 'a', 'pilihan_ganda'),
(2026, 43, 'The word "meticulous" is closest in meaning to ...', 'Detail-oriented', 'Careless', 'Lazy', 'Impulsive', 'a', 'pilihan_ganda'),
(2026, 44, 'Contoh cryptocurrency yang dikenal luas adalah ...', 'Bitcoin', 'Facebook Coin', 'Google Pay', 'Apple Cash', 'a', 'pilihan_ganda'),
(2026, 45, 'Diketahui deret aritmatika 3, 7, 11, 15,... Suku ke-10 adalah ...', '39', '35', '43', '31', 'a', 'pilihan_ganda'),
(2026, 46, 'Proses fotosintesis menghasilkan ...', 'Oksigen dan glukosa', 'Karbon dioksida dan air', 'Energi panas', 'Protein dan lemak', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia U-20 tahun 2023 seharusnya diselenggarakan di ...', 'Indonesia', 'Argentina', 'Qatar', 'Afrika Selatan', 'a', 'pilihan_ganda'),
(2026, 48, 'Siapa yang dikenal sebagai "Bapak Komputer" (penemu komputer modern)?', 'Alan Turing', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'a', 'pilihan_ganda'),
(2026, 49, 'Lembaga yang bertugas menangani korupsi di Indonesia adalah ...', 'KPK (Komisi Pemberantasan Korupsi)', 'BPK', 'BPKP', 'Kejaksaan Agung', 'a', 'pilihan_ganda'),
(2026, 50, 'Program ketahanan pangan yang digalakkan pemerintah Indonesia disebut ...', 'Ketahanan pangan mandiri', 'Program beras murah', 'Dapur sehat', 'Makan gratis', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Remaja Teladan" menurut Pola Baku GMIM?', 'Remaja usia 12-16 tahun yang berprestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang menjadi pengurus komisi remaja', 'Remaja yang populer di lingkungan gereja', 'Remaja yang memiliki orang tua kaya', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab Mazmur sebagian besar?', 'Daud', 'Salomo', 'Musa', 'Yeremia', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari KPRS?', 'Komisi Pelayanan Remaja Sinode', 'Komisi Pembinaan Remaja Sinode', 'Kelompok Pelayanan Remaja Sinode', 'Komisi Pelayanan Remaja Sekunder', 'a', 'pilihan_ganda'),
(2026, 4, 'Di manakah Yesus lahir?', 'Betlehem', 'Nazaret', 'Yerusalem', 'Kapernaum', 'a', 'pilihan_ganda'),
(2026, 5, 'Apa warna selempang untuk finalis Remaja Teladan tingkat Jemaat?', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 6, 'Siapakah yang disebut sebagai "Bapak Reformasi Gereja"?', 'Martin Luther', 'Yohanes Calvin', 'John Knox', 'Ulrich Zwingli', 'a', 'pilihan_ganda'),
(2026, 7, 'Apa singkatan dari LTPR?', 'Latihan Tenaga Pembina Remaja', 'Latihan Teknis Pembina Remaja', 'Latihan Terpadu Pembina Remaja', 'Latihan Tugas Pembina Remaja', 'a', 'pilihan_ganda'),
(2026, 8, 'Siapakah yang menulis surat kepada jemaat di Galatia?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 9, 'Berapa jumlah rayon pelayanan KPRS GMIM?', '12 Rayon', '10 Rayon', '11 Rayon', '13 Rayon', 'a', 'pilihan_ganda'),
(2026, 10, 'Apa inti dari Hukum Taurat yang terutama?', 'Kasih kepada Tuhan dan sesama', 'Jangan membunuh', 'Hormati orang tua', 'Jangan mencuri', 'a', 'pilihan_ganda'),
(2026, 11, 'Siapakah Ketua KPRS GMIM periode pertama?', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Drs. Jantje Sajow', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. Drs. Jimmy Mamahit', 'a', 'pilihan_ganda'),
(2026, 12, 'Apa arti kata "Injil"?', 'Kabar Baik', 'Kabar Keselamatan', 'Firman Tuhan', 'Ajaran Yesus', 'a', 'pilihan_ganda'),
(2026, 13, 'Program KB3 dalam KPRS adalah singkatan dari ...', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kelompok Belajar Bersama', 'Kegiatan Bina Bakat Berkah', 'Komisi Bina Berkat Bersama', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang menggantikan Yudas Iskariot sebagai rasul?', 'Matias', 'Barnabas', 'Stefanus', 'Filipus', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa kepanjangan dari BPMS?', 'Badan Pekerja Majelis Sinode', 'Badan Pelayanan Majelis Sinode', 'Badan Pengurus Majelis Sinode', 'Badan Pengawas Majelis Sinode', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang menulis kitab Wahyu?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa tema pelayanan GMIM periode 2018-2022?', 'Tuhan mengangkat kita dari Samudera Raya', 'Remaja Bagi Kristus', 'Berakar, Bertumbuh, Berbuah', 'Gereja Global', 'a', 'pilihan_ganda'),
(2026, 18, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja?', 'Daniel', 'Yusuf', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2026, 19, 'Apa kepanjangan dari PKRS?', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa isi dari Pengakuan Iman Rasuli?', 'Aku percaya kepada Allah Bapa, Yesus Kristus, dan Roh Kudus', 'Aku percaya kepada Yesus saja', 'Aku percaya kepada Allah saja', 'Aku percaya kepada para nabi', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah Ketua KPRS periode 2022-2027?', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. Melky R. Pattiwael', 'Pnt. Edward Saragih', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa nama sungai yang ada di taman Eden?', 'Pison, Gihon, Tigris, Efrat', 'Nil, Tigris, Efrat, Yordan', 'Efrat, Tigris, Nil, Gangga', 'Amazon, Tigris, Efrat, Nil', 'a', 'pilihan_ganda'),
(2026, 23, 'Apa makna warna ungu pada selempang finalis?', 'Nuansa kerendahan hati dan kesetiaan', 'Kekuasaan dan kehormatan', 'Kemurnian dan kesucian', 'Kegembiraan dan sukacita', 'a', 'pilihan_ganda'),
(2026, 24, 'Siapakah yang menjadi raja pertama Israel?', 'Saul', 'Daud', 'Salomo', 'Yerobeam', 'a', 'pilihan_ganda'),
(2026, 25, 'Apa kepanjangan dari SIKAT?', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Komunikasi Terpadu', 'Sistem Informasi Kegiatan Terkini', 'Sistem Informasi Keuangan Terpadu', 'a', 'pilihan_ganda'),
(2026, 26, 'Siapakah yang menulis kitab Amsal?', 'Salomo', 'Daud', 'Musa', 'Yeremia', 'a', 'pilihan_ganda'),
(2026, 27, 'Berapa jumlah pasal dalam kitab Mazmur?', '150', '100', '120', '66', 'a', 'pilihan_ganda'),
(2026, 28, 'Apa arti "Sitou Timou Tumou Tou"?', 'Manusia hidup untuk memanusiakan manusia lain', 'Hidup adalah perjuangan', 'Bekerja keras untuk sukses', 'Hormati orang tua', 'a', 'pilihan_ganda'),
(2026, 29, 'Siapakah nama misionaris yang melayani di Tondano?', 'J.F. Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 30, 'Apa yang dimaksud dengan "Sakramen"?', 'Tanda dan meterai kasih karunia Allah yang kelihatan', 'Upacara adat gereja', 'Ritual keagamaan', 'Perayaan hari raya', 'a', 'pilihan_ganda'),
(2026, 31, 'Siapakah yang dijual oleh saudara-saudaranya ke Mesir?', 'Yusuf', 'Daniel', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2026, 32, 'Apa tema HPRG (Hari Persatuan Remaja GMIM)?', 'Remaja Bagi Kristus', 'Remaja Berprestasi', 'Remaja Kreatif', 'Remaja Cinta Damai', 'a', 'pilihan_ganda'),
(2026, 33, 'Siapakah yang menulis surat kepada jemaat di Efesus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 34, 'Berapa usia minimal peserta Pemilihan Remaja Teladan?', '12 tahun', '13 tahun', '14 tahun', '15 tahun', 'a', 'pilihan_ganda'),
(2026, 35, 'Apa nama gunung tempat Yesus berdoa sebelum ditangkap?', 'Bukit Zaitun', 'Gunung Sinai', 'Gunung Tabor', 'Gunung Hermon', 'a', 'pilihan_ganda'),
(2026, 36, 'Siapakah yang menjadi Ketua Sinode GMIM pertama dari Minahasa?', 'Ds. A.Z.R. Wenas', 'Ds. E.A.A. de Vreede', 'Pdt. R.M. Luntungan', 'Pdt. M. Sondakh', 'a', 'pilihan_ganda'),
(2026, 37, 'Apa arti kata "Eli, Eli, lama sabakhtani"?', 'Allah-Ku, Allah-Ku, mengapa Engkau meninggalkan Aku?', 'Ya Tuhan, ampunilah mereka', 'Ya Bapa, ke dalam tangan-Mu', 'Aku haus', 'a', 'pilihan_ganda'),
(2026, 38, 'Berapa jumlah bidang dalam KPRS GMIM periode 2022-2027?', '7 bidang', '8 bidang', '9 bidang', '10 bidang', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah yang disebut sebagai "Gembala yang Baik"?', 'Yesus Kristus', 'Petrus', 'Paulus', 'Daud', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa kepanjangan dari MTPJ?', 'Materi Pembacaan dan Tanggung Jawab Pelayanan Jemaat', 'Materi Tugas Pelayanan Jemaat', 'Minggu Tanggung Jawab Pelayanan Jemaat', 'Materi Tanggung Jawab Pelayanan Jemaat', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Indonesia adalah negara kepulauan terbesar di dunia" merupakan kalimat ...', 'Fakta', 'Opini', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa Presiden Indonesia periode 2014-2024?', 'Joko Widodo', 'Prabowo Subianto', 'Susilo Bambang Yudhoyono', 'Megawati Sukarnoputri', 'a', 'pilihan_ganda'),
(2026, 43, 'The word "success" is antonym of ...', 'Failure', 'Victory', 'Achievement', 'Triumph', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah KTT G20 pada tahun ...', '2022', '2023', '2024', '2021', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 15 × 6 - 30 ÷ 5 adalah ...', '84', '90', '80', '78', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama gunung tertinggi di Sulawesi Utara?', 'Gunung Klabat', 'Gunung Lokon', 'Gunung Soputan', 'Gunung Ruang', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia 2022 diselenggarakan di negara ...', 'Qatar', 'Rusia', 'Brasil', 'Jerman', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari CPU dalam komputer adalah ...', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit', 'Computer Program Unit', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara ASEAN yang tidak memiliki laut adalah ...', 'Laos', 'Kamboja', 'Thailand', 'Myanmar', 'a', 'pilihan_ganda'),
(2026, 50, 'Program vaksinasi nasional COVID-19 di Indonesia dimulai pada tahun ...', '2021', '2020', '2022', '2019', 'a', 'pilihan_ganda'),
(2026, 1, 'Siapakah yang disebut sebagai "Rasul Maluku" yang datang ke Minahasa?', 'J.F. Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 2, 'Apa yang dimaksud dengan "Presbiterial Sinodal"?', 'Kepemimpinan kolektif para penatua dengan musyawarah', 'Kepemimpinan satu uskup', 'Kepemimpinan kongregasi independen', 'Kepemimpinan karismatik', 'a', 'pilihan_ganda'),
(2026, 3, 'Berapa jumlah kitab dalam Perjanjian Baru?', '27', '39', '66', '24', 'a', 'pilihan_ganda'),
(2026, 4, 'Apa kepanjangan dari NZG?', 'Nederlands Zending Genootschap', 'Nederlands Zendeling Genootschap', 'Nederland Zending Genootschap', 'Nederland Zendeling Genootschap', 'a', 'pilihan_ganda'),
(2026, 5, 'Siapakah yang menulis kitab Kisah Para Rasul?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa tema Misi Remaja GMIM?', 'Berakar, bertumbuh, dan berbuah bagi Kristus', 'Remaja Bagi Kristus', 'Menjadi Teladan', 'Remaja Kreatif dan Inovatif', 'a', 'pilihan_ganda'),
(2026, 7, 'Siapakah yang menjadi raja Israel setelah Daud?', 'Salomo', 'Saul', 'Yerobeam', 'Rehabeam', 'a', 'pilihan_ganda'),
(2026, 8, 'Apa kepanjangan dari GEMAR?', 'Gerakan Membaca Alkitab Remaja', 'Gerakan Memasyarakatkan Alkitab Remaja', 'Gereja Membaca Alkitab Remaja', 'Gerakan Muda Alkitab Remaja', 'a', 'pilihan_ganda'),
(2026, 9, 'Apa arti "Sola Fide"?', 'Hanya oleh iman', 'Hanya oleh kasih karunia', 'Hanya Alkitab', 'Hanya bagi kemuliaan Tuhan', 'a', 'pilihan_ganda'),
(2026, 10, 'Siapakah yang menulis surat kepada jemaat di Filipi?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa usia maksimal peserta Pemilihan Remaja Teladan?', '16 tahun 364 hari', '16 tahun', '17 tahun', '15 tahun 364 hari', 'a', 'pilihan_ganda'),
(2026, 12, 'Siapakah nama ibu dari Samuel?', 'Hana', 'Elkana', 'Sara', 'Ribka', 'a', 'pilihan_ganda'),
(2026, 13, 'Apa warna dasar selempang finalis tingkat Sinode?', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan emas', 'Ungu dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang menulis kitab Keluaran?', 'Musa', 'Daud', 'Salomo', 'Yeremia', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa singkatan dari KB3?', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kelompok Belajar Bersama', 'Kegiatan Bina Bakat Berkah', 'Komisi Bina Berkat Bersama', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang disebut sebagai "Bapa Orang Percaya"?', 'Abraham', 'Musa', 'Daud', 'Adam', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa kepanjangan dari P3SDM?', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a', 'pilihan_ganda'),
(2026, 18, 'Berapa jumlah tulah yang Tuhan datangkan ke Mesir?', '10 tulah', '7 tulah', '12 tulah', '5 tulah', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menjadi Ketua Sinode GMIM pertama?', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa arti "Sola Gratia"?', 'Hanya oleh kasih karunia', 'Hanya oleh iman', 'Hanya Alkitab', 'Hanya bagi kemuliaan Tuhan', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menulis kitab Yohanes?', 'Rasul Yohanes', 'Petrus', 'Yakobus', 'Matius', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa yang dimaksud dengan "Karunia Roh"?', 'Kemampuan khusus yang diberikan Roh Kudus untuk melayani', 'Bakat alami sejak lahir', 'Kekayaan materi', 'Popularitas di gereja', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah Ketua KPRS periode 2018-2022?', 'Pnt. dr. Michaela E. Paruntu', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. Melky R. Pattiwael', 'Pnt. Edward Saragih', 'a', 'pilihan_ganda'),
(2026, 24, 'Apa nama gunung tempat Musa menerima 10 Hukum Allah?', 'Gunung Sinai', 'Gunung Tabor', 'Gunung Hermon', 'Bukit Zaitun', 'a', 'pilihan_ganda'),
(2026, 25, 'Apa kepanjangan dari APIM?', 'Ajaran, Persekutuan, Ibadah, dan Misi', 'Ajaran, Pelayanan, Ibadah, dan Misi', 'Alkitab, Persekutuan, Ibadah, dan Misi', 'Ajaran, Persekutuan, Ibadah, dan Musik', 'a', 'pilihan_ganda'),
(2026, 26, 'Siapakah yang menjadi raja Israel yang paling bijaksana?', 'Salomo', 'Daud', 'Saul', 'Yosia', 'a', 'pilihan_ganda'),
(2026, 27, 'Berapa jumlah pasal dalam kitab Kejadian?', '50', '40', '45', '55', 'a', 'pilihan_ganda'),
(2026, 28, 'Apa arti "Buah Roh" dalam Galatia 5?', 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri', 'Iman, pengharapan, kasih', 'Hikmat, pengertian, nasihat', 'Kemuliaan, hormat, kuasa', 'a', 'pilihan_ganda'),
(2026, 29, 'Siapakah nama misionaris yang melayani di Langowan dan Kakas?', 'J.G. Schwarz', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2026, 30, 'Apa yang dimaksud dengan "Ekaristi"?', 'Perjamuan Kudus', 'Baptisan', 'Katekisasi', 'Peneguhan Sidi', 'a', 'pilihan_ganda'),
(2026, 31, 'Siapakah yang dibuang ke gua singa karena setia berdoa?', 'Daniel', 'Yusuf', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2026, 32, 'Apa tema MTPJ bulan April biasanya?', 'Kebangkitan Yesus', 'Kelahiran Yesus', 'Kenaikan Yesus', 'Pencurahan Roh Kudus', 'a', 'pilihan_ganda'),
(2026, 33, 'Siapakah yang menulis surat kepada jemaat di Tesalonika?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 34, 'Berapa bobot nilai tes tertulis dalam Pemilihan Remaja Teladan?', '5%', '15%', '25%', '35%', 'a', 'pilihan_ganda'),
(2026, 35, 'Apa nama sungai tempat Yesus dibaptis?', 'Sungai Yordan', 'Sungai Nil', 'Sungai Efrat', 'Sungai Tigris', 'a', 'pilihan_ganda'),
(2026, 36, 'Siapakah yang menjadi Ketua Sinode GMIM terlama?', 'Pdt. Dr. W.A. Roeroe', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. Hein Arina', 'Ds. E.A.A. de Vreede', 'a', 'pilihan_ganda'),
(2026, 37, 'Apa arti kata "Manna" dalam Perjanjian Lama?', 'Roti dari sorga', 'Air dari batu', 'Daging burung puyuh', 'Buah dari tanah perjanjian', 'a', 'pilihan_ganda'),
(2026, 38, 'Berapa jumlah rayon pelayanan KPRS?', '12', '10', '11', '13', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah yang disebut sebagai "Pokok Anggur yang benar"?', 'Yesus Kristus', 'Petrus', 'Paulus', 'Daud', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa kepanjangan dari HPRG?', 'Hari Persatuan Remaja GMIM', 'Hari Pelayanan Remaja GMIM', 'Hari Pertemuan Remaja GMIM', 'Hari Paskah Remaja GMIM', 'a', 'pilihan_ganda'),
(2026, 41, 'Kalimat "Menurut saya, kopi lebih enak daripada teh" adalah contoh ...', 'Opini', 'Fakta', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa Wakil Presiden Indonesia periode 2019-2024?', 'Ma''ruf Amin', 'Jusuf Kalla', 'Boediono', 'Try Sutrisno', 'a', 'pilihan_ganda'),
(2026, 43, 'The antonym of "brave" is ...', 'Coward', 'Strong', 'Fearless', 'Bold', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi anggota BRICS pada tahun ...', '2024', '2023', '2025', '2022', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 120 ÷ 5 × 3 - 10 adalah ...', '62', '70', '58', '66', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama danau terluas di Sulawesi Utara?', 'Danau Tondano', 'Danau Linow', 'Danau Moat', 'Danau Toba', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia Wanita 2023 diselenggarakan di negara ...', 'Australia dan Selandia Baru', 'Prancis', 'Amerika Serikat', 'Kanada', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari RAM dalam komputer adalah ...', 'Random Access Memory', 'Read Access Memory', 'Random Available Memory', 'Read Available Memory', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara terbaru yang bergabung dengan ASEAN adalah ...', 'Timor Leste', 'Papua Nugini', 'Sri Lanka', 'Bangladesh', 'a', 'pilihan_ganda'),
(2026, 50, 'Program "Makan Bergizi Gratis" digagas oleh presiden terpilih ...', 'Prabowo Subianto', 'Joko Widodo', 'Anies Baswedan', 'Ganjar Pranowo', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Imamat yang Rajani" (1 Petrus 2:9)?', 'Setiap orang percaya adalah imam yang melayani Tuhan', 'Hanya pendeta yang bisa melayani', 'Hamba Tuhan yang khusus', 'Imam dalam gereja katolik', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab Roma?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari PKRS?', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'a', 'pilihan_ganda'),
(2026, 4, 'Apa arti "Soli Deo Gloria"?', 'Kemuliaan hanya bagi Tuhan', 'Hanya oleh iman', 'Hanya oleh kasih karunia', 'Hanya Alkitab', 'a', 'pilihan_ganda'),
(2026, 5, 'Siapakah yang menjadi raja Israel yang membangun Bait Suci?', 'Salomo', 'Daud', 'Saul', 'Yosia', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa singkatan dari LKRG?', 'Latihan Kader Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'a', 'pilihan_ganda'),
(2026, 7, 'Berapa jumlah pasal dalam kitab Yeremia?', '52', '50', '48', '55', 'a', 'pilihan_ganda'),
(2026, 8, 'Siapakah nama isteri Yusuf dalam Perjanjian Lama?', 'Asnat', 'Dina', 'Abisag', 'Potifera', 'a', 'pilihan_ganda'),
(2026, 9, 'Apa tema Misi Remaja GMIM?', 'Berakar, Bertumbuh, Berbuah bagi Kristus', 'Remaja Bagi Kristus', 'Menjadi Teladan', 'Remaja Kreatif', 'a', 'pilihan_ganda'),
(2026, 10, 'Siapakah yang disebut sebagai "Rasul kepada bangsa-bangsa bukan Yahudi"?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa bobot nilai wawancara dalam Pemilihan Remaja Teladan?', '15%', '5%', '25%', '35%', 'a', 'pilihan_ganda'),
(2026, 12, 'Apa arti "Teens for Christ"?', 'Remaja Bagi Kristus', 'Remaja Untuk Kristus', 'Remaja Dalam Kristus', 'Remaja Bersama Kristus', 'a', 'pilihan_ganda'),
(2026, 13, 'Siapakah yang menulis kitab 1 Timotius?', 'Paulus', 'Petrus', 'Yohanes', 'Lukas', 'a', 'pilihan_ganda'),
(2026, 14, 'Apa yang dimaksud dengan "Pelayanan Holistik"?', 'Pelayanan yang menyentuh seluruh aspek kehidupan', 'Pelayanan yang hanya rohani', 'Pelayanan jasmani saja', 'Pelayanan yang melelahkan', 'a', 'pilihan_ganda'),
(2026, 15, 'Siapakah nama ibu dari Yohanes Pembaptis?', 'Elisabeth', 'Maria', 'Hana', 'Sara', 'a', 'pilihan_ganda'),
(2026, 16, 'Apa warna dasar selempang finalis tingkat Wilayah?', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 17, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2014-2018?', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. Hein Arina', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2026, 18, 'Apa arti kata "Ekklesia"?', 'Gereja - persekutuan orang yang dipanggil keluar', 'Jemaat', 'Rumah doa', 'Tempat ibadah', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menulis kitab Yakobus?', 'Yakobus saudara Yesus', 'Yakobus anak Zebedeus', 'Paulus', 'Petrus', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa kepanjangan dari PSR?', 'Pesta Seni Remaja', 'Perkemahan Seni Remaja', 'Pekan Seni Remaja', 'Pentas Seni Remaja', 'a', 'pilihan_ganda'),
(2026, 21, 'Berapa lama bangsa Israel berjalan di padang gurun?', '40 tahun', '30 tahun', '20 tahun', '10 tahun', 'a', 'pilihan_ganda'),
(2026, 22, 'Siapakah yang disebut sebagai "Nabi yang naik ke sorga dengan kereta api"?', 'Elia', 'Elisa', 'Musa', 'Henokh', 'a', 'pilihan_ganda'),
(2026, 23, 'Apa yang dimaksud dengan "Karantina" dalam seleksi Retel?', 'Tahap pembinaan intensif selama 3 hari', 'Tahap tes tertulis', 'Tahap wawancara', 'Tahap final', 'a', 'pilihan_ganda'),
(2026, 24, 'Siapakah yang menulis kitab 1 Petrus?', 'Petrus', 'Paulus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 25, 'Apa arti "Sola Scriptura"?', 'Hanya Alkitab sebagai otoritas tertinggi', 'Hanya oleh iman', 'Hanya oleh kasih karunia', 'Hanya bagi kemuliaan Tuhan', 'a', 'pilihan_ganda'),
(2026, 26, 'Siapakah nama misionaris yang melayani di Minahasa pada abad ke-19?', 'J.F. Riedel dan J.G. Schwarz', 'Ds. de Vreede dan Ds. Buenk', 'Pdt. Wenas dan Pdt. Roeroe', 'Pdt. Tampi dan Pdt. Sumakul', 'a', 'pilihan_ganda'),
(2026, 27, 'Berapa jumlah perintah dalam Dekalog?', '10', '12', '7', '5', 'a', 'pilihan_ganda'),
(2026, 28, 'Apa yang dimaksud dengan "Grand Final"?', 'Puncak acara Pemilihan Remaja Teladan', 'Tahap awal seleksi', 'Tahap karantina', 'Tahap wawancara', 'a', 'pilihan_ganda'),
(2026, 29, 'Siapakah yang menjadi raja Israel yang paling rendah hati?', 'Daud', 'Salomo', 'Saul', 'Yosia', 'a', 'pilihan_ganda'),
(2026, 30, 'Apa tema MTPJ minggu Paskah?', 'Kebangkitan Yesus', 'Kematian Yesus', 'Kenaikan Yesus', 'Pencurahan Roh Kudus', 'a', 'pilihan_ganda'),
(2026, 31, 'Siapakah yang menulis kitab 2 Timotius?', 'Paulus', 'Petrus', 'Yohanes', 'Lukas', 'a', 'pilihan_ganda'),
(2026, 32, 'Berapa bobot nilai Grand Final?', '20%', '25%', '15%', '5%', 'a', 'pilihan_ganda'),
(2026, 33, 'Apa arti "Pelayanan Marturia"?', 'Pelayanan kesaksian', 'Pelayanan kasih', 'Pelayanan ibadah', 'Pelayanan persekutuan', 'a', 'pilihan_ganda'),
(2026, 34, 'Siapakah yang disebut sebagai "Garam dan Terang dunia"?', 'Setiap orang percaya', 'Hanya pendeta', 'Hanya rasul', 'Hanya nabi', 'a', 'pilihan_ganda'),
(2026, 35, 'Apa warna dasar selempang finalis tingkat Jemaat?', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 36, 'Siapakah yang menulis kitab Filipi?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 37, 'Apa arti "Pelayanan Diakonia"?', 'Pelayanan kasih kepada yang membutuhkan', 'Pelayanan kesaksian', 'Pelayanan ibadah', 'Pelayanan persekutuan', 'a', 'pilihan_ganda'),
(2026, 38, 'Siapakah nama ayah dari Yosua?', 'Nun', 'Musa', 'Kaleb', 'Harun', 'a', 'pilihan_ganda'),
(2026, 39, 'Berapa jumlah tulah kesepuluh di Mesir?', 'Kematian anak sulung', 'Belalang', 'Gelap gulita', 'Katak', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa kepanjangan dari BPMJ?', 'Badan Pekerja Majelis Jemaat', 'Badan Pelayanan Majelis Jemaat', 'Badan Pengurus Majelis Jemaat', 'Badan Pengawas Majelis Jemaat', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Harga BBM naik menjadi 3 dampak negatif bagi masyarakat" adalah contoh ...', 'Fakta', 'Opini', 'Asumsi', 'Prediksi', 'a', 'pilihan_ganda'),
(2026, 42, 'Ibu Kota Negara Indonesia yang baru bernama ...', 'Nusantara', 'Palangkaraya', 'Balikpapan', 'Samarinda', 'a', 'pilihan_ganda'),
(2026, 43, 'The synonym of "difficult" is ...', 'Hard', 'Easy', 'Simple', 'Light', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah Piala Dunia U-20 pada tahun ...', '2023 (batal)', '2024', '2025', '2026', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 100 - 5 × 6 + 15 ÷ 3 adalah ...', '75', '85', '70', '80', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama taman laut terkenal di Sulawesi Utara?', 'Bunaken', 'Raja Ampat', 'Wakatobi', 'Derawan', 'a', 'pilihan_ganda'),
(2026, 47, 'Presiden terpilih Amerika Serikat untuk periode 2025-2029 adalah ...', 'Donald Trump', 'Joe Biden', 'Kamala Harris', 'Barack Obama', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari AI dalam teknologi adalah ...', 'Artificial Intelligence', 'Automated Intelligence', 'Artificial Integration', 'Automated Integration', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara dengan penduduk Muslim terbanyak di dunia adalah ...', 'Indonesia', 'India', 'Pakistan', 'Bangladesh', 'a', 'pilihan_ganda'),
(2026, 50, 'Program ketahanan pangan "PIP" singkatan dari ...', 'Pangan Inovatif dan Produktif', 'Program Intensifikasi Pangan', 'Pangan Indonesia Prima', 'Program Inovasi Pangan', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Pelayanan Koinonia"?', 'Pelayanan persekutuan', 'Pelayanan kasih', 'Pelayanan kesaksian', 'Pelayanan ibadah', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab 1 Korintus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari BPMW?', 'Badan Pekerja Majelis Wilayah', 'Badan Pelayanan Majelis Wilayah', 'Badan Pengurus Majelis Wilayah', 'Badan Pengawas Majelis Wilayah', 'a', 'pilihan_ganda'),
(2026, 4, 'Siapakah yang disebut sebagai "Perjanjian Baru dalam darah-Ku"?', 'Yesus Kristus', 'Musa', 'Abraham', 'Daud', 'a', 'pilihan_ganda'),
(2026, 5, 'Berapa jumlah pasal dalam kitab Kejadian?', '50', '40', '45', '55', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa arti "Gelar Atribut" dalam Pemilihan Remaja Teladan?', 'Gelar khusus selain juara utama', 'Gelar juara utama', 'Penghargaan peserta', 'Sertifikat partisipasi', 'a', 'pilihan_ganda'),
(2026, 7, 'Siapakah yang menjadi raja Israel yang paling kaya?', 'Salomo', 'Daud', 'Saul', 'Yosia', 'a', 'pilihan_ganda'),
(2026, 8, 'Apa tema Visi Remaja GMIM?', 'Remaja Bagi Kristus', 'Berakar, Bertumbuh, Berbuah', 'Menjadi Teladan', 'Remaja Kreatif', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapakah yang menulis kitab Kolose?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 10, 'Apa yang dimaksud dengan "Pelayanan Leiturgia"?', 'Pelayanan ibadah dan penyembahan', 'Pelayanan kasih', 'Pelayanan kesaksian', 'Pelayanan persekutuan', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa bobot nilai Kompetisi Potensi Diri?', '25%', '35%', '20%', '15%', 'a', 'pilihan_ganda'),
(2026, 12, 'Siapakah nama ayah dari Yesus menurut silsilah Matius?', 'Yusuf', 'Daud', 'Abraham', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 13, 'Apa warna dasar selempang finalis tingkat Rayon?', 'Hitam dengan tulisan perak', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'Ungu dengan tulisan perak', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang disebut sebagai "Pahlawan Iman" dalam Ibrani 11?', 'Abraham, Musa, Daud, dll', 'Hanya Yesus', 'Hanya Paulus', 'Hanya Petrus', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa arti "Katekisasi"?', 'Pengajaran iman Kristen secara sistematis', 'Ibadah minggu', 'Doa bersama', 'Puasa', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang menulis kitab Titus?', 'Paulus', 'Petrus', 'Yohanes', 'Lukas', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa kepanjangan dari Retel?', 'Remaja Teladan', 'Remaja Teladan GMIM', 'Remaja Teladan Sinode', 'Remaja Teladan Jemaat', 'a', 'pilihan_ganda'),
(2026, 18, 'Berapa jumlah kitab dalam Alkitab?', '66', '39', '27', '73', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2010-2014?', 'Pdt. Piet M. Tampi', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa yang dimaksud dengan "Sakramen Baptisan Kudus"?', 'Tanda perjanjian Allah dengan umat-Nya', 'Upacara adat', 'Ritual pembersihan', 'Perayaan tahunan', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menulis kitab Filemon?', 'Paulus', 'Petrus', 'Yohanes', 'Lukas', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa arti "Pelayanan Penggembalaan"?', 'Pelayanan membimbing dan mengarahkan jemaat', 'Pelayanan kasih', 'Pelayanan kesaksian', 'Pelayanan ibadah', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah nama istri dari Abraham?', 'Sara', 'Hagar', 'Ribka', 'Rahel', 'a', 'pilihan_ganda'),
(2026, 24, 'Berapa jumlah bidang KPRS?', '7 bidang', '8 bidang', '9 bidang', '10 bidang', 'a', 'pilihan_ganda'),
(2026, 25, 'Apa tema MTPJ bulan Desember?', 'Natal dan Kedatangan Yesus', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'Pencurahan Roh Kudus', 'a', 'pilihan_ganda'),
(2026, 26, 'Siapakah yang menulis kitab 2 Petrus?', 'Petrus', 'Paulus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 27, 'Apa yang dimaksud dengan "Peneguhan Sidi Jemaat"?', 'Pengakuan iman secara dewasa', 'Baptisan anak', 'Pernikahan', 'Katekisasi', 'a', 'pilihan_ganda'),
(2026, 28, 'Siapakah nama anak dari Abraham dan Sara?', 'Ishak', 'Ismail', 'Yakub', 'Esau', 'a', 'pilihan_ganda'),
(2026, 29, 'Apa arti "Semboyan Reformasi"?', 'Sola Fide, Sola Gratia, Sola Scriptura, Soli Deo Gloria', 'Iman, Pengharapan, Kasih', 'Bersekutu, Bersaksi, Melayani', 'Doa, Puasa, Sedekah', 'a', 'pilihan_ganda'),
(2026, 30, 'Siapakah yang menulis kitab Yudas?', 'Yudas saudara Yesus', 'Yudas Iskariot', 'Paulus', 'Petrus', 'a', 'pilihan_ganda'),
(2026, 31, 'Berapa usia minimal menjadi Sidi Jemaat?', '17 tahun', '16 tahun', '18 tahun', '15 tahun', 'a', 'pilihan_ganda'),
(2026, 32, 'Apa yang dimaksud dengan "Tahun Gerejawi"?', 'Siklus tahunan perayaan iman Kristen', 'Tahun pelayanan gereja', 'Tahun anggaran gereja', 'Tahun ajaran sekolah minggu', 'a', 'pilihan_ganda'),
(2026, 33, 'Siapakah yang menulis kitab 3 Yohanes?', 'Yohanes', 'Paulus', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 34, 'Apa arti "Pelayanan Kategorial"?', 'Pelayanan berdasarkan kategori usia dan status', 'Pelayanan umum', 'Pelayanan khusus', 'Pelayanan harian', 'a', 'pilihan_ganda'),
(2026, 35, 'Siapakah nama anak dari Ishak dan Ribka?', 'Yakub dan Esau', 'Ismail', 'Yusuf', 'Benyamin', 'a', 'pilihan_ganda'),
(2026, 36, 'Apa tema Misi GMIM?', 'Bersekutu, Bersaksi, Melayani', 'Remaja Bagi Kristus', 'Gereja Global', 'Berakar, Bertumbuh, Berbuah', 'a', 'pilihan_ganda'),
(2026, 37, 'Siapakah yang menulis kitab Wahyu?', 'Yohanes di Patmos', 'Paulus', 'Petrus', 'Lukas', 'a', 'pilihan_ganda'),
(2026, 38, 'Berapa bobot nilai karantina dan pelayanan holistik?', '35%', '25%', '20%', '15%', 'a', 'pilihan_ganda'),
(2026, 39, 'Apa arti "Perjamuan Kudus"?', 'Sakramen peringatan kematian dan kebangkitan Yesus', 'Makan bersama', 'Ibadah malam', 'Doa bersama', 'a', 'pilihan_ganda'),
(2026, 40, 'Siapakah yang menjadi Ketua KPRS periode 2000-2005?', 'Pnt. Drs. Jantje W. Sajow', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'a', 'pilihan_ganda'),
(2026, 41, 'Kalimat "Bencana alam terjadi karena ulah manusia" adalah contoh ...', 'Opini', 'Fakta', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa nama presiden terpilih Indonesia 2024-2029?', 'Prabowo Subianto', 'Joko Widodo', 'Anies Baswedan', 'Ganjar Pranowo', 'a', 'pilihan_ganda'),
(2026, 43, 'The synonym of "happy" is ...', 'Joyful', 'Sad', 'Angry', 'Tired', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah ajang MotoGP di sirkuit ...', 'Mandalika', 'Sentul', 'Jakarta', 'Surabaya', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 4² + 3² - 2³ adalah ...', '17', '15', '19', '13', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama pulau terbesar di Sulawesi Utara?', 'Pulau Lembeh', 'Pulau Bunaken', 'Pulau Manado Tua', 'Pulau Sangihe', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia 2026 akan diselenggarakan di negara ...', 'Amerika Serikat, Kanada, Meksiko', 'Amerika Serikat', 'Kanada', 'Meksiko', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari URL adalah ...', 'Uniform Resource Locator', 'Universal Resource Locator', 'Uniform Resource Link', 'Universal Resource Link', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara di Asia Tenggara yang berbentuk kerajaan adalah ...', 'Thailand', 'Indonesia', 'Malaysia', 'Vietnam', 'a', 'pilihan_ganda'),
(2026, 50, 'Program "Indonesia Emas 2045" adalah visi ...', 'Indonesia menjadi negara maju pada 100 tahun kemerdekaan', 'Indonesia menjadi negara adidaya', 'Indonesia menjadi pusat ekonomi dunia', 'Indonesia menjadi negara termakmur', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Pola Baku Pemilihan Remaja Teladan"?', 'Standar prosedur seleksi yang harus dilaksanakan semua aras', 'Aturan khusus untuk sinode', 'Pedoman untuk juri', 'Buku panduan peserta', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab Efesus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari KPRJ?', 'Komisi Pelayanan Remaja Jemaat', 'Komisi Pelayanan Remaja Wilayah', 'Komisi Pelayanan Remaja Sinode', 'Komisi Pelayanan Remaja Rayon', 'a', 'pilihan_ganda'),
(2026, 4, 'Siapakah yang disebut sebagai "Rasul bangsa-bangsa bukan Yahudi"?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 5, 'Berapa jumlah perintah dalam 10 Hukum Allah?', '10', '12', '7', '5', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa arti "Gelar Remaja Teladan Intelegensia"?', 'Gelar untuk peserta dengan nilai tes tertulis dan psikotes terbaik', 'Gelar juara utama', 'Gelar favorit', 'Gelar persahabatan', 'a', 'pilihan_ganda'),
(2026, 7, 'Siapakah yang menjadi raja Israel yang pertama?', 'Saul', 'Daud', 'Salomo', 'Yerobeam', 'a', 'pilihan_ganda'),
(2026, 8, 'Apa tema MTPJ Minggu Sangsara?', 'Penderitaan dan kematian Yesus', 'Kebangkitan Yesus', 'Kelahiran Yesus', 'Kenaikan Yesus', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapakah yang menulis kitab 2 Korintus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 10, 'Apa yang dimaksud dengan "Kata Kunci Final"?', '3 kata yang diambil acak peserta final untuk dijelaskan', 'Soal tes tertulis', 'Materi wawancara', 'Topik karantina', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa bobot nilai tes tertulis?', '5%', '15%', '25%', '35%', 'a', 'pilihan_ganda'),
(2026, 12, 'Siapakah nama anak dari Daud yang menjadi raja?', 'Salomo', 'Absalom', 'Amnon', 'Adonia', 'a', 'pilihan_ganda'),
(2026, 13, 'Apa warna dasar selempang pelayanan finalis?', 'Ungu', 'Hitam', 'Merah', 'Putih', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang disebut sebagai "Bapa Para Nabi"?', 'Abraham', 'Musa', 'Daud', 'Isaac', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa arti "Katekisasi Sidi"?', 'Pengajaran bagi calon anggota sidi jemaat', 'Pengajaran baptisan', 'Pengajaran pernikahan', 'Pengajaran umum', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang menulis kitab 1 Yohanes?', 'Yohanes', 'Paulus', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa kepanjangan dari KPRW?', 'Komisi Pelayanan Remaja Wilayah', 'Komisi Pelayanan Remaja Jemaat', 'Komisi Pelayanan Remaja Sinode', 'Komisi Pelayanan Remaja Rayon', 'a', 'pilihan_ganda'),
(2026, 18, 'Berapa jumlah pasal dalam kitab Mazmur yang paling pendek?', '2 pasal (Mazmur 117)', '1 pasal', '3 pasal', '5 pasal', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2005-2010?', 'Pdt. Dr. A.O. Supit', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'Pdt. Dr. Henny Sumakul', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa yang dimaksud dengan "Sakramen Perjamuan Kudus"?', 'Perjamuan peringatan kematian Yesus', 'Makan bersama jemaat', 'Ibadah malam', 'Doa bersama', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menulis kitab 2 Yohanes?', 'Yohanes', 'Paulus', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa arti "Pelayanan Siswa" dalam KPRS?', 'Pelayanan yang fokus pada siswa dan pelajar', 'Pelayanan sekolah minggu', 'Pelayanan kampus', 'Pelayanan anak-anak', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah nama ibu dari Daud?', 'Tidak disebutkan dalam Alkitab', 'Sara', 'Hana', 'Ribka', 'a', 'pilihan_ganda'),
(2026, 24, 'Apa tema MTPJ bulan November?', 'Syukur dan Pemeliharaan Tuhan', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'a', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang menulis kitab 1 Tesalonika?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa yang dimaksud dengan "Akumulasi nilai"?', 'Penjumlahan nilai dari berbagai tahapan seleksi', 'Nilai tertinggi', 'Nilai terendah', 'Nilai rata-rata', 'a', 'pilihan_ganda'),
(2026, 27, 'Siapakah nama anak dari Yakub dari Rahel?', 'Yusuf dan Benyamin', 'Ruben', 'Simeon', 'Lewi', 'a', 'pilihan_ganda'),
(2026, 28, 'Berapa jumlah pasal dalam kitab Yesaya?', '66', '52', '50', '60', 'a', 'pilihan_ganda'),
(2026, 29, 'Apa arti "Emiritat" bagi pendeta GMIM?', 'Status kehormatan setelah pensiun', 'Jabatan baru', 'Gelar akademik', 'Penghargaan khusus', 'a', 'pilihan_ganda'),
(2026, 30, 'Siapakah yang menjadi Ketua KPRS periode 2010-2014?', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pnt. Melky Pattiwael', 'Pnt. Edward Saragih', 'a', 'pilihan_ganda'),
(2026, 31, 'Apa yang dimaksud dengan "Parousia"?', 'Kedatangan Tuhan kedua kali', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'Kelahiran Yesus', 'a', 'pilihan_ganda'),
(2026, 32, 'Siapakah yang menulis kitab 2 Tesalonika?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 33, 'Apa arti "Kompetisi Potensi Diri"?', 'Lomba debat, pidato Inggris, dan karya tulis', 'Tes tertulis', 'Wawancara', 'Karantina', 'a', 'pilihan_ganda'),
(2026, 34, 'Siapakah nama istri dari Ishak?', 'Ribka', 'Sara', 'Rahel', 'Lea', 'a', 'pilihan_ganda'),
(2026, 35, 'Berapa jumlah pasal dalam kitab Yohanes?', '21', '24', '28', '16', 'a', 'pilihan_ganda'),
(2026, 36, 'Apa tema Misi GMIM secara umum?', 'Bersekutu, Bersaksi, Melayani', 'Remaja Bagi Kristus', 'Gereja Global', 'Berakar, Bertumbuh, Berbuah', 'a', 'pilihan_ganda'),
(2026, 37, 'Siapakah yang menulis kitab Markus?', 'Markus', 'Matius', 'Lukas', 'Yohanes', 'a', 'pilihan_ganda'),
(2026, 38, 'Apa yang dimaksud dengan "Regenerasi" dalam organisasi?', 'Proses kaderisasi untuk pemimpin penerus', 'Pergantian pengurus', 'Pemilihan baru', 'Evaluasi program', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah nama ibu dari Musa?', 'Yokhebed', 'Miriam', 'Sara', 'Hana', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa arti "Pelayanan Pemuda" dalam struktur GMIM?', 'Pelayanan untuk usia 17-30 tahun', 'Pelayanan remaja', 'Pelayanan anak', 'Pelayanan lansia', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Indonesia memiliki 17.000 pulau" adalah contoh ...', 'Fakta', 'Opini', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa Wakil Presiden Indonesia periode 2024-2029?', 'Gibran Rakabuming Raka', 'Ma''ruf Amin', 'Jusuf Kalla', 'Boediono', 'a', 'pilihan_ganda'),
(2026, 43, 'The antonym of "expensive" is ...', 'Cheap', 'Costly', 'Pricey', 'Valuable', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah KTT ASEAN pada tahun 2023 di kota ...', 'Labuan Bajo', 'Jakarta', 'Bali', 'Bandung', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 8 × 7 - 12 + 6 ÷ 2 adalah ...', '47', '50', '44', '53', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama air terjun terkenal di Minahasa?', 'Air Terjun Tunan', 'Air Terjun Sekar', 'Air Terjun Sipiso-piso', 'Air Terjun Madakaripura', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia Wanita 2027 akan diselenggarakan di negara ...', 'Brasil', 'Amerika Serikat', 'Australia', 'Prancis', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari HTML adalah ...', 'HyperText Markup Language', 'HyperText Machine Language', 'HighText Markup Language', 'Hyper Transfer Markup Language', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara yang disebut sebagai "Macan Asia" adalah ...', 'Korea Selatan, Taiwan, Hong Kong, Singapura', 'Indonesia, Malaysia, Thailand', 'China, Jepang, India', 'Vietnam, Filipina, Myanmar', 'a', 'pilihan_ganda'),
(2026, 50, 'Program "Bansos" adalah singkatan dari ...', 'Bantuan Sosial', 'Bantuan Sosis', 'Bantuan Subsidi', 'Bantuan Sembako', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Tahapan Karantina" dalam seleksi Retel?', 'Tahap pembinaan intensif selama 3 hari', 'Tahap tes tertulis', 'Tahap wawancara', 'Tahap final', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab Matius?', 'Matius', 'Markus', 'Lukas', 'Yohanes', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari BIPRA?', 'Bidang Pelayanan dan Pembinaan', 'Bidang Informasi dan Pengembangan', 'Bidang Pengembangan dan Pelayanan', 'Bidang Pembinaan dan Pengembangan', 'a', 'pilihan_ganda'),
(2026, 4, 'Siapakah yang disebut sebagai "Juru Selamat dunia"?', 'Yesus Kristus', 'Musa', 'Nabi Muhammad', 'Buddha', 'a', 'pilihan_ganda'),
(2026, 5, 'Berapa jumlah rasul Yesus?', '12', '10', '11', '13', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa arti "Gelar Remaja Teladan Persahabatan"?', 'Gelar yang dipilih oleh sesama peserta', 'Gelar juara utama', 'Gelar favorit', 'Gelar intelegensia', 'a', 'pilihan_ganda'),
(2026, 7, 'Siapakah yang menjadi raja Israel yang membangun tembok Yerusalem?', 'Nehemia', 'Ezra', 'Zerubabel', 'Yosua', 'a', 'pilihan_ganda'),
(2026, 8, 'Apa tema MTPJ minggu Adven?', 'Penantian kelahiran Yesus', 'Kebangkitan Yesus', 'Penderitaan Yesus', 'Kenaikan Yesus', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapakah yang menulis kitab Lukas?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'a', 'pilihan_ganda'),
(2026, 10, 'Apa yang dimaksud dengan "Pelayanan Holistik" dalam Retel?', 'Pelayanan sosial kepada jemaat yang membutuhkan', 'Ibadah bersama', 'Doa bersama', 'Retret rohani', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa bobot nilai wawancara?', '15%', '5%', '25%', '35%', 'a', 'pilihan_ganda'),
(2026, 12, 'Siapakah nama anak dari Daud dengan Batsyeba yang menjadi raja?', 'Salomo', 'Absalom', 'Amnon', 'Adonia', 'a', 'pilihan_ganda'),
(2026, 13, 'Apa warna liturgi untuk masa Paskah?', 'Putih', 'Ungu', 'Merah', 'Hijau', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang disebut sebagai "Nabi terakhir Perjanjian Lama"?', 'Maleakhi', 'Zakharia', 'Hagai', 'Yoel', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa arti "Katekisasi Baptisan"?', 'Pengajaran bagi calon baptisan', 'Pengajaran sidi', 'Pengajaran pernikahan', 'Pengajaran umum', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang menulis kitab 1 Raja-raja?', 'Tidak diketahui (tradisi: Yeremia)', 'Daud', 'Salomo', 'Musa', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa kepanjangan dari BPMI?', 'Badan Pekerja Majelis Jemaat', 'Badan Pelayanan Majelis Jemaat', 'Badan Pengurus Majelis Jemaat', 'Badan Pengawas Majelis Jemaat', 'a', 'pilihan_ganda'),
(2026, 18, 'Berapa jumlah pasal dalam kitab Keluaran?', '40', '50', '30', '36', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2018-2022?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa yang dimaksud dengan "Penasihat BPMJ"?', 'Orang yang memberi nasihat kepada BPMJ', 'Ketua BPMJ', 'Sekretaris BPMJ', 'Bendahara BPMJ', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menulis kitab 2 Raja-raja?', 'Tidak diketahui (tradisi: Yeremia)', 'Daud', 'Salomo', 'Musa', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa arti "Bidang PMB" dalam KPRS?', 'Pengembangan Minat dan Bakat', 'Pelayanan dan Manajemen Bakat', 'Program Minat dan Bakat', 'Pengelolaan Minat dan Bakat', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah nama anak dari Abraham dari Hagar?', 'Ismail', 'Ishak', 'Yakub', 'Esau', 'a', 'pilihan_ganda'),
(2026, 24, 'Apa tema MTPJ bulan Oktober?', 'Misi dan Penginjilan', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Pencurahan Roh Kudus', 'a', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang menulis kitab 1 Tawarikh?', 'Ezra (tradisi)', 'Daud', 'Salomo', 'Musa', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa yang dimaksud dengan "Skala nilai B (Baik)" dalam wawancara?', '70-80', '81-90', '60-70', '50-60', 'a', 'pilihan_ganda'),
(2026, 27, 'Siapakah nama anak dari Yakub dari Lea?', 'Ruben, Simeon, Lewi, Yehuda', 'Yusuf', 'Benyamin', 'Dan', 'a', 'pilihan_ganda'),
(2026, 28, 'Berapa jumlah pasal dalam kitab Ulangan?', '34', '30', '40', '28', 'a', 'pilihan_ganda'),
(2026, 29, 'Apa arti "Kostor" dalam struktur jemaat GMIM?', 'Pelayan kebersihan dan kerapihan gereja', 'Penjaga gereja', 'Pengurus properti', 'Pemandu ibadah', 'a', 'pilihan_ganda'),
(2026, 30, 'Siapakah yang menjadi Ketua KPRS periode 2005-2010?', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Drs. Jantje Sajow', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'a', 'pilihan_ganda'),
(2026, 31, 'Apa yang dimaksud dengan "Koinonia"?', 'Persekutuan orang percaya', 'Kesaksian', 'Pelayanan kasih', 'Ibadah', 'a', 'pilihan_ganda'),
(2026, 32, 'Siapakah yang menulis kitab 2 Tawarikh?', 'Ezra (tradisi)', 'Daud', 'Salomo', 'Musa', 'a', 'pilihan_ganda'),
(2026, 33, 'Apa arti "Bidang Pelsis" dalam KPRS?', 'Pelayanan Siswa', 'Pelayanan Sidi', 'Pelayanan Sekolah', 'Pelayanan Sinode', 'a', 'pilihan_ganda'),
(2026, 34, 'Siapakah nama istri dari Yakub yang paling dikasihi?', 'Rahel', 'Lea', 'Bilha', 'Zilpa', 'a', 'pilihan_ganda'),
(2026, 35, 'Berapa jumlah pasal dalam kitab Imamat?', '27', '25', '30', '24', 'a', 'pilihan_ganda'),
(2026, 36, 'Apa tema MTPJ bulan September?', 'Pendidikan dan Pengajaran', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Misi', 'a', 'pilihan_ganda'),
(2026, 37, 'Siapakah yang menulis kitab Ezra?', 'Ezra', 'Nehemia', 'Zerubabel', 'Hagai', 'a', 'pilihan_ganda'),
(2026, 38, 'Apa yang dimaksud dengan "Martyria"?', 'Kesaksian', 'Persekutuan', 'Pelayanan kasih', 'Ibadah', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah nama ayah dari Yohanes Pembaptis?', 'Zakharia', 'Elkana', 'Imamat', 'Harun', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa arti "Pelayanan Anak" dalam struktur GMIM?', 'Pelayanan untuk usia 11 tahun ke bawah', 'Pelayanan remaja', 'Pelayanan pemuda', 'Pelayanan lansia', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Sebaiknya pemerintah menurunkan harga BBM" adalah contoh ...', 'Opini', 'Fakta', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa Menteri Pertahanan Indonesia periode 2024-2029?', 'Sjafrie Sjamsoeddin', 'Prabowo Subianto', 'Ryamizard Ryacudu', 'Juwono Sudarsono', 'a', 'pilihan_ganda'),
(2026, 43, 'The synonym of "fast" is ...', 'Quick', 'Slow', 'Lazy', 'Careful', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia resmi menjadi anggota BRICS pada KTT di ...', 'Kazan, Rusia', 'Johannesburg, Afrika Selatan', 'Brasilia, Brasil', 'New Delhi, India', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 12 × 5 - 30 + 45 ÷ 9 adalah ...', '35', '40', '30', '45', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama pulau yang terkenal dengan lumba-lumba di Sulut?', 'Pulau Lihaga', 'Pulau Bunaken', 'Pulau Lembeh', 'Pulau Manado Tua', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia 2030 akan diselenggarakan di negara ...', 'Spanyol, Portugal, Maroko', 'Uruguay, Argentina, Paraguay', 'Amerika Serikat', 'Inggris', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari SSD adalah ...', 'Solid State Drive', 'Solid System Drive', 'Solid State Disk', 'Solid System Disk', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara di Asia yang berbentuk kerajaan absolut adalah ...', 'Arab Saudi', 'Thailand', 'Malaysia', 'Brunei', 'a', 'pilihan_ganda'),
(2026, 50, 'Program "Makan Siang Gratis" adalah program unggulan presiden ...', 'Prabowo Subianto', 'Joko Widodo', 'Anies Baswedan', 'Ganjar Pranowo', 'a', 'pilihan_ganda'),
(2026, 1, 'Apa yang dimaksud dengan "Tahapan Final" dalam seleksi Retel?', 'Puncak acara penentuan juara', 'Tahap awal seleksi', 'Tahap karantina', 'Tahap wawancara', 'a', 'pilihan_ganda'),
(2026, 2, 'Siapakah yang menulis kitab Nehemia?', 'Nehemia', 'Ezra', 'Zerubabel', 'Hagai', 'a', 'pilihan_ganda'),
(2026, 3, 'Apa kepanjangan dari UPK?', 'Urusan Pelayanan Kategorial', 'Unit Pelayanan Kategorial', 'Unsur Pelayanan Kategorial', 'Utusan Pelayanan Kategorial', 'a', 'pilihan_ganda'),
(2026, 4, 'Siapakah yang disebut sebagai "Pembawa damai" dalam Khotbah di Bukit?', 'Setiap orang percaya', 'Hanya pendeta', 'Hanya rasul', 'Hanya nabi', 'a', 'pilihan_ganda'),
(2026, 5, 'Berapa jumlah murid Yesus yang terpilih menjadi rasul?', '12', '10', '11', '13', 'a', 'pilihan_ganda'),
(2026, 6, 'Apa arti "Gelar Remaja Teladan Berbakat"?', '40% nilai talent show karantina dan 60% kompetisi potensi diri', '100% nilai tes tertulis', '100% nilai wawancara', '50% nilai karantina', 'a', 'pilihan_ganda'),
(2026, 7, 'Siapakah yang menjadi raja Israel yang membaca kembali kitab Taurat?', 'Yosia', 'Hizkia', 'Salomo', 'Daud', 'a', 'pilihan_ganda'),
(2026, 8, 'Apa tema MTPJ minggu Pentakosta?', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'Kelahiran Yesus', 'a', 'pilihan_ganda'),
(2026, 9, 'Siapakah yang menulis kitab Ester?', 'Tidak diketahui (mungkin Mordekhai)', 'Ester', 'Ezra', 'Nehemia', 'a', 'pilihan_ganda'),
(2026, 10, 'Apa yang dimaksud dengan "Tahapan Kompetisi Potensi Diri"?', 'Lomba debat, pidato Inggris, dan karya tulis', 'Tes tertulis', 'Wawancara', 'Karantina', 'a', 'pilihan_ganda'),
(2026, 11, 'Berapa bobot nilai Grand Final?', '20%', '25%', '15%', '5%', 'a', 'pilihan_ganda'),
(2026, 12, 'Siapakah nama anak dari Rahel yang bungsu?', 'Benyamin', 'Yusuf', 'Dan', 'Naftali', 'a', 'pilihan_ganda'),
(2026, 13, 'Apa warna liturgi untuk masa Adven?', 'Ungu', 'Putih', 'Merah', 'Hijau', 'a', 'pilihan_ganda'),
(2026, 14, 'Siapakah yang disebut sebagai "Pemungut cukai yang menjadi murid Yesus"?', 'Matius', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2026, 15, 'Apa arti "Katekisasi Pernikahan"?', 'Pengajaran bagi calon pengantin', 'Pengajaran baptisan', 'Pengajaran sidi', 'Pengajaran umum', 'a', 'pilihan_ganda'),
(2026, 16, 'Siapakah yang menulis kitab Ayub?', 'Tidak diketahui (mungkin Ayub)', 'Musa', 'Daud', 'Salomo', 'a', 'pilihan_ganda'),
(2026, 17, 'Apa kepanjangan dari UPK Kolom?', 'Urusan Pelayanan Kategorial', 'Unit Pelayanan Kolom', 'Unsur Pelayanan Kolom', 'Utusan Pelayanan Kolom', 'a', 'pilihan_ganda'),
(2026, 18, 'Berapa jumlah pasal dalam kitab Bilangan?', '36', '40', '30', '34', 'a', 'pilihan_ganda'),
(2026, 19, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2000-2005?', 'Pdt. Dr. A.F. Parengkuan', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. A.O. Supit', 'Pdt. Dr. Hein Arina', 'a', 'pilihan_ganda'),
(2026, 20, 'Apa yang dimaksud dengan "Pekerja GMIM"?', 'Pendeta, guru agama, dan pegawai yang menerima biaya hidup dari GMIM', 'Semua anggota jemaat', 'Hanya pendeta', 'Hanya guru agama', 'a', 'pilihan_ganda'),
(2026, 21, 'Siapakah yang menulis kitab Mazmur 23?', 'Daud', 'Salomo', 'Musa', 'Asaf', 'a', 'pilihan_ganda'),
(2026, 22, 'Apa arti "Bidang TIK" dalam KPRS?', 'Teknologi Informasi dan Komunikasi', 'Tim Informasi dan Komunikasi', 'Tenaga Informasi dan Komunikasi', 'Tugas Informasi dan Komunikasi', 'a', 'pilihan_ganda'),
(2026, 23, 'Siapakah nama anak dari Yusuf di Mesir?', 'Manasye dan Efraim', 'Ruben', 'Simeon', 'Lewi', 'a', 'pilihan_ganda'),
(2026, 24, 'Apa tema MTPJ bulan Agustus?', 'Kemerdekaan dan Syukur', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Pencurahan Roh Kudus', 'a', 'pilihan_ganda'),
(2026, 25, 'Siapakah yang menulis kitab Amsal 31 tentang istri yang cakap?', 'Salomo (tradisi)', 'Daud', 'Musa', 'Yeremia', 'a', 'pilihan_ganda'),
(2026, 26, 'Apa yang dimaksud dengan "Skala nilai A (Amat Baik)" dalam wawancara?', '81-90', '70-80', '60-70', '50-60', 'a', 'pilihan_ganda'),
(2026, 27, 'Siapakah nama anak dari Yusuf dari Mesir yang menjadi suku terbesar?', 'Efraim', 'Manasye', 'Ruben', 'Yehuda', 'a', 'pilihan_ganda'),
(2026, 28, 'Berapa jumlah pasal dalam kitab Yosua?', '24', '20', '30', '22', 'a', 'pilihan_ganda'),
(2026, 29, 'Apa arti "Jemaat" dalam struktur GMIM?', 'Persekutuan orang percaya di suatu tempat', 'Bangunan gereja', 'Organisasi gereja', 'Majelis gereja', 'a', 'pilihan_ganda'),
(2026, 30, 'Siapakah yang menjadi Ketua KPRS periode 1990-1995?', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Drs. Jantje Sajow', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'a', 'pilihan_ganda'),
(2026, 31, 'Apa yang dimaksud dengan "Diakonia"?', 'Pelayanan kasih', 'Kesaksian', 'Persekutuan', 'Ibadah', 'a', 'pilihan_ganda'),
(2026, 32, 'Siapakah yang menulis kitab Ratapan?', 'Yeremia', 'Yesaya', 'Yehezkiel', 'Daniel', 'a', 'pilihan_ganda'),
(2026, 33, 'Apa arti "Bidang P3SDM" dalam KPRS?', 'Pembinaan, Pengkaderan, Pengembangan SDM', 'Pelayanan, Pengembangan, Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pendidikan, Pelatihan, Pengembangan SDM', 'a', 'pilihan_ganda'),
(2026, 34, 'Siapakah nama istri dari Abraham yang melahirkan Ishak?', 'Sara', 'Hagar', 'Ribka', 'Rahel', 'a', 'pilihan_ganda'),
(2026, 35, 'Berapa jumlah pasal dalam kitab Hakim-hakim?', '21', '20', '22', '24', 'a', 'pilihan_ganda'),
(2026, 36, 'Apa tema MTPJ bulan Januari?', 'Tahun baru dan pengharapan', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Misi', 'a', 'pilihan_ganda'),
(2026, 37, 'Siapakah yang menulis kitab Rut?', 'Tidak diketahui (mungkin Samuel)', 'Rut', 'Naomi', 'Boas', 'a', 'pilihan_ganda'),
(2026, 38, 'Apa yang dimaksud dengan "Leiturgia"?', 'Ibadah dan penyembahan', 'Kesaksian', 'Persekutuan', 'Pelayanan kasih', 'a', 'pilihan_ganda'),
(2026, 39, 'Siapakah nama ayah dari Daud?', 'Isai', 'Obet', 'Boas', 'Salmon', 'a', 'pilihan_ganda'),
(2026, 40, 'Apa arti "Pelayanan Lansia" dalam struktur GMIM?', 'Pelayanan untuk usia 60 tahun ke atas', 'Pelayanan remaja', 'Pelayanan pemuda', 'Pelayanan anak', 'a', 'pilihan_ganda'),
(2026, 41, 'Teks "Kopi lebih baik diminum pagi hari daripada malam" adalah contoh ...', 'Opini', 'Fakta', 'Asumsi', 'Hipotesis', 'a', 'pilihan_ganda'),
(2026, 42, 'Siapa Menteri Koordinator Kemaritiman dan Investasi periode 2024-2029?', 'Luhut Binsar Pandjaitan', 'Prabowo Subianto', 'Joko Widodo', 'Ma''ruf Amin', 'a', 'pilihan_ganda'),
(2026, 43, 'The antonym of "strong" is ...', 'Weak', 'Powerful', 'Mighty', 'Tough', 'a', 'pilihan_ganda'),
(2026, 44, 'Indonesia menjadi tuan rumah Pertemuan IMF-World Bank pada tahun ...', '2022 di Bali', '2023 di Labuan Bajo', '2024 di Jakarta', '2025 di Surabaya', 'a', 'pilihan_ganda'),
(2026, 45, 'Hasil dari 14 × 3 - 18 + 24 ÷ 4 adalah ...', '30', '32', '28', '34', 'a', 'pilihan_ganda'),
(2026, 46, 'Apa nama pantai terkenal di Likupang?', 'Pantai Paal', 'Pantai Kima Bajo', 'Pantai Malalayang', 'Pantai Tongkaina', 'a', 'pilihan_ganda'),
(2026, 47, 'Piala Dunia Futsal 2024 diselenggarakan di negara ...', 'Uzbekistan', 'Indonesia', 'Thailand', 'Vietnam', 'a', 'pilihan_ganda'),
(2026, 48, 'Kepanjangan dari VPN adalah ...', 'Virtual Private Network', 'Virtual Public Network', 'Virtual Protected Network', 'Virtual Personal Network', 'a', 'pilihan_ganda'),
(2026, 49, 'Negara yang disebut sebagai "Negeri Sakura" adalah ...', 'Jepang', 'Korea Selatan', 'China', 'Taiwan', 'a', 'pilihan_ganda'),
(2026, 50, 'Program "Ibu Kota Nusantara (IKN)" dipindahkan dari ...', 'Jakarta ke Kalimantan Timur', 'Jakarta ke Kalimantan Selatan', 'Jakarta ke Kalimantan Tengah', 'Jakarta ke Kalimantan Barat', 'a', 'pilihan_ganda');
