-- TAHUN 2023 - Soal 1 s.d 50
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2023, 1, 'Terdapat Dimanakah Judul Perikop "Yesus diolok-olokan"', 'Matius 27:27-44', 'Matius 27:32-44', 'Matius 27:27-31', 'Matius 27:45-55', 'c'),
(2023, 2, 'Apakah judul perikop Markus 16:1-8 yang merupakan pembacaan Alkitab warga GMIM pada tanggal 9-15 April 2023', 'Kematian Yesus', 'Kebangkitan Yesus', 'Yesus Dikuburkan', 'Yesus Menampakkan Diri', 'b'),
(2023, 3, 'Dibawah ini adalah nama-nama perempuan yang membawa rempah-rempah ke kubur Yesus, kecuali?', 'Maria Magdalena', 'Maria Ibu Yakobus', 'Salome', 'Maria Ibu Yesus', 'd'),
(2023, 4, 'Kepada siapakah Yesus menampakkan diri pertama kali?', 'Maria Magdalena', 'Maria Ibu Yakobus', 'Salome', 'Maria Ibu Yesus', 'a'),
(2023, 5, 'Lengkapilah Yohanes 20:13b: "Tuhanku telah diambil ........ dan aku tidak tahu dimana la ........"', 'Orang dan di bawah', 'Malaikat dan dibawah', 'Orang dan diletakkan', 'Malaikat dan diletakkan', 'c'),
(2023, 6, 'Apakah yang Maria Magdalena katakan kepada murid-murid berdasarkan Yohanes 20:18?', 'Aku telah bertemu Tuhan', 'Aku telah berbicara dengan Tuhan', 'Aku telah melihat Dia', 'Aku telah melihat Tuhan', 'd'),
(2023, 7, 'Berapakah jumlah perikop Yohanes 20:19-29?', '3', '2', '1', '4', 'b'),
(2023, 8, 'Ibu menghendaki 5 buah jeruk dan 5 buah salak yang baik, peluangnya adalah', '16/273', '26/273', '42/273', '48/273', 'a'),
(2023, 9, 'Apakah tema mingguan Pembacaan Alkitab tanggal 23-29 April 2023?', 'Berbahagialah mereka yang tidak melihat namun percaya', 'Aku telah melihat Tuhan', 'Yesus sudah bangkit percayalah', 'Tersalib diantara dua penyamun', 'a'),
(2023, 10, 'Misal kita mempunyai 10 kartu yang bernomor 1 sampai 10. Peluang terambil kartu bernomor bilangan prima adalah', '4/5', '3/5', '1/2', '3/10', 'c'),
(2023, 11, 'Pernyataan berikut yang benar tentang kandang ayam Pak Eko seluas 324 m² adalah', 'Jika lebar kandang 9 meter, biaya pemasangan kawat akan minimum', 'Jika lebar kandang 22 meter, biaya pemasangan kawat akan minimum', 'Jika panjang kandang 36 meter, biaya pemasangan kawat akan minimum', 'Biaya pemasangan kawat minimum adalah Rp864.000,00', 'd'),
(2023, 12, 'Lengkapilah Yohanes 20:27: "Kemudian ia berkata kepada Tomas: ........ jarimu disini dan lihatlah tanganku, ulurkanlah tanganmu dan cucukkanlah kedalam ........"', 'Letakkan dan lambungku', 'Taruhlah dan tubuhku', 'Letakkan dan tubuhku', 'Taruhlah dan lambungku', 'd'),
(2023, 13, 'Ekosistem dengan ciri tumbuhan dominan berdaun jarum, hewan beruang hitam dan rusa adalah', 'Taiga', 'Tundra', 'Gurun', 'Sabana', 'a'),
(2023, 14, 'Berikut ini adalah pembacaan Alkitab sesuai MTPJ GMIM selama bulan April 2023, kecuali?', 'Yohanes 20:11-20', 'Yohanes 20:19-29', 'I Korintus 3:10-23', 'Yohanes 19:38-42', 'c'),
(2023, 15, 'Frekuensi yang didengar oleh pendengar jika sumber bunyi menjauh adalah', '680 Hz', '720 Hz', '50 Hz', '800 Hz', 'a'),
(2023, 16, 'Tuan rumah pelaksanaan Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2023 adalah?', 'Wilayah Amurang 4', 'Wilayah Tengah', 'Wilayah Amurang 3', 'Wilayah Amurang 1', 'd'),
(2023, 17, 'Siapakah nama ketua komisi pelayanan remaja wilayah Manado Sentrum?', 'Pnt. Melky Rocky Pattiwael', 'Pnt. Michaela E Paruntu', 'Pnt. Stevie Kaligis', 'Pnt. Rizky Tombeng', 'a'),
(2023, 18, 'Apa kepanjangan bidang P3SDM KPRS GMIM 2022-2027?', 'Bidang Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Bidang Pengkaderan, Pembinaan dan Pengembangan Sumber Daya Manusia', 'Bidang Pengembangan, Pembinaan dan Pengkaderan Sumber Daya Manusia', 'Bidang Pembinaan, Pengembangan dan Pengkaderan Sumber Daya Manusia', 'a'),
(2023, 19, 'Yang bukan menjadikan remaja GMIM yang bertumbuh adalah?', 'Bertumbuh melalui kegiatan pemahaman Alkitab (PA)', 'Bertumbuh melalui ketekunan berdoa', 'Bertumbuh melalui pengenalan akan keselamatan dari Allah', 'Bertumbuh melalui kegiatan selebrasi', 'd'),
(2023, 20, 'Pola dan strategi pelayanan remaja GMIM adalah?', 'Penginjilan, Pembinaan, pelatihan, pelipatgandaan', 'Penginjilan, pembinaan, pelipatgandaan, pemuridan', 'Penginjilan, pembinaan, pelipatgandaan, pengutusan', 'Penginjilan, pelatihan, pelipatgandaan, pemuridan', 'c'),
(2023, 21, 'Berapakah jumlah Komisi Pelayanan Remaja Sinode Periode 2022-2027?', '13 orang', '7 orang', '15 orang', '11 orang', 'a'),
(2023, 22, 'Misi Komisi pelayanan remaja sinode GMIM periode 2014-2018 adalah?', 'Menjadikan remaja GMIM yang berakar, bertumbuh dan berbuah', 'Remaja GMIM yang berakar dan bertumbuh serta berbuah bagi Kristus', 'Menjadikan remaja yang berakar bertumbuh dan berbuah', 'Menjadikan Remaja GMIM yang berakar bertumbuh dan berbuah bagi Kristus', 'd'),
(2023, 23, 'Program pelatihan KPRS dalam bidang P3SDM bagi Remaja adalah?', 'LTPR dan LTPR Lanjutan', 'LKRG Madya dan LKRG Taruna', 'TOT', 'LKRG, LTPR, dan TOT', 'b'),
(2023, 24, 'Perbedaan jumlah Komisi Pelayanan Remaja Sinode Periode 2018-2022 dan 2022-2027 adalah:', '15 dan 12', '13 dan 15', '15 dan 13', '15 dan 15', 'c'),
(2023, 25, 'Perbandingan genotip F2 dari persilangan dihibrid kacang ercis adalah', '1:3:3:1', '9:3:3:1', '12:3:1', '1:2:1', 'b'),
(2023, 26, 'What does the text tell us about? (Independence day festival)', 'Independence day festival', 'Gathering in school', 'Parade with the principal', 'School contest', 'a'),
(2023, 27, 'The antonym of the word "fail" is ...', 'escape', 'reach', 'predict', 'success', 'd'),
(2023, 28, 'Dalam pengajaran GMIM tentang baptisan kudus, baptisan adalah ...', 'Tanda perjanjian antara Allah dengan orang-orang yang dipanggil-Nya, serta keturunannya.', 'Pengganti sunat sebagai tanda perjanjian', 'Dilakukan dalam nama Allah Bapa, Anak, dan Roh Kudus.', 'Semuanya benar', 'd'),
(2023, 29, 'Rahmat ..... all of his friends to the celebration next week.', 'Will invite', 'Invites', 'Invited', 'Invitation', 'a'),
(2023, 30, 'Iman Kristen memahami Allah Tritunggal sebagai ...', 'Satu Pribadi, Tiga Cara Berada', 'Satu Hakikat, Satu Pribadi', 'Satu Hakikat, Tiga Pribadi', 'Tiga Pribadi, Tiga Cara Berada', 'c'),
(2023, 31, 'Dalam Peraturan tentang Jemaat Bab IX Pasal 31 Ayat 4d, Remaja yang adalah anggota GMIM berusia ...', '12 tahun sampai dengan 16 tahun 364 hari', '12 tahun sampai dengan 16 tahun 365 hari', '12 tahun sampai dengan 17 tahun', '12 tahun sampai dengan 17 tahun satu hari', 'a'),
(2023, 32, 'What does the letter tell us about? (Reny''s letter to Nadine)', 'Asking for a friend to teach Mathematic', 'Preparing for the national examination', 'Asking for a friend''s suggestion to solve a problem', 'Giving a solution to a friend', 'c'),
(2023, 33, 'Kalimat tanya yang sesuai dengan isi paragraf tentang penelitian IPB adalah...', 'Kapan para mahasiswa IPB mengadakan penelitian daging ayam?', 'Berapa orang mahasiswa yang melakukan penelitian?', 'Apa tindak lanjut hasil penelitian mahasiswa IPB?', 'Apa hasil penelitian mahasiswa IPB terhadap daging ayam yang dijual di pasar tersebut?', 'd'),
(2023, 34, 'GMIM terpanggil untuk memperlengkapi anggota-anggotanya melalui ...', 'Ibadah-ibadah', 'Katekisasi-katekisasi', 'Pembinaan Warga Gereja', 'Sakramen', 'c'),
(2023, 35, 'Kata "di" dalam nama GMIM menunjukkan pada organisasi gereja yang berada di ...', 'Seluruh dunia', 'Seluruh Indonesia', 'Sulawesi Utara dan sekitarnya', 'Tanah Minahasa saja', 'a'),
(2023, 36, 'Penyair dalam puisi Taufik Ismail bermaksud mengungkapkan...', 'tuntutan perbaikan kesejahteraan rakyat', 'penderitaan sebagai besar rakyat', 'republik ini milik yang menderita', 'keadaan bencana alam yang menimpa rakyat', 'b'),
(2023, 37, 'GMIM sebagai Gereja Bagian Mandiri dari Gereja Protestan di Indonesia sejak ...', '17 September 1934', '30 September 1934', '12 Juni 1831', '28 Oktober 1928', 'b'),
(2023, 38, 'Orang-orang yang karena kemampuan dan keteladannya dipercayakan untuk memberikan nasihat kepada BPMJ disebut ...', 'Penasihat jemaat', 'Tua-tua jemaat', 'Penasihat BPMI', 'Ketua Lansia', 'c'),
(2023, 39, 'Kata penghubung yang tepat untuk melengkapi paragraf rumpang tersebut adalah...', 'Tentu saja, kalau, begitu, barangkali', 'Tentunya, bahwa, ketika, kalau', 'Namun, bahwa, begitu, barangkali', 'Namun, ketika, begitu, barangkali', 'b'),
(2023, 40, 'Fila memotong rambutnya dan mengecat pirang seperti penyanyi idolanya. Fila melakukan proses ...', 'Kasih sayang', 'Empati', 'Imitasi', 'Sosial', 'c'),
(2023, 41, 'Pasar sepeda motor di Indonesia menunjukkan bentuk pasar ...', 'Oligopoli', 'Monopsoni', 'Oligopsoni', 'Persaingan sempurna', 'a'),
(2023, 42, 'Siapakah seorang Farisi sekaligus pemimpin agama Yahudi yang datang pada waktu malam kepada Yesus?', 'Yusuf dari Arimatea', 'Kayafas', 'Nikodemus', 'Hanas', 'c'),
(2023, 43, 'Siapakah nama perempuan Moab yang menikah dengan Boas?', 'Tamar', 'Naomi', 'Rut', 'Hana', 'c'),
(2023, 44, '"Teofilus yang mulia," adalah kalimat pembukaan dari Injil ...', 'Matius', 'Markus', 'Lukas', 'Yohanes', 'c'),
(2023, 45, 'Berikut ini adalah contoh-contoh realitas sosial, kecuali ....', 'Keluarga', 'Organisasi', 'Lingkungan', 'Komunitas', 'c'),
(2023, 46, 'Siapa penyelenggara event G20 tahun 2023?', 'Argentina', 'Jerman', 'Indonesia', 'India', 'd'),
(2023, 47, 'Pada tanggal 14 Februari 2024, Indonesia akan menyelenggarakan event apa?', 'Valentine Se Indonesia', 'Tuan Rumah G20', 'Pemilihan umum', 'Pemilihan umum dan Presiden', 'd'),
(2023, 48, 'Dimana potensi panas bumi di Sulawesi Utara yang saat ini dikelola oleh PT. Pertamina Geothermal Energy?', 'Lahendong, Tompaso dan Kotamobagu', 'Amurang, Motoling dan Tondano', 'Airmadidi dan Likupang', 'Bitung, Kema dan Ranowangko', 'a'),
(2023, 49, 'Di mana penyelenggaraan Piala Dunia FIFA U-20 Tahun 2023?', 'Indonesia', 'Qatar', 'Afrika Selatan', 'Argentina', 'a'),
(2023, 50, 'Siapakah Pencipta Lagu Mars Remaja GMIM?', 'Ir. Moody Rondonuwu', 'Jantje Wowiling Sajow', 'Ronald Pohan', 'Yaris Banua', 'b');
