-- TAHUN 2022 - Soal 1 s.d 50
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2022, 1, 'Gagasan pokok teks tentang pencabutan subsidi BBM adalah ....', 'Kenaikan harga BBM disebabkan kesalahan pemerintah', 'Kenaikan harga BBM berdampak negatif terhadap masyarakat', 'Pengangguran disebabkan kenaikan harga BBM', 'Dampak kenaikan harga BBM saat ini', 'b'),
(2022, 2, 'Kesimpulan isi paragraf tentang krisis moneter adalah ....', 'Banyak anak putus sekolah karena orang tuanya kehilangan pekerjaan', 'Krisis moneter berdampak buruk bagi sektor industri dan pendidikan', 'Dengan adanya krisis moneter banyak karyawan yang di PHK', 'Krisis moneter menimbulkan permasalahan yang kompleks', 'b'),
(2022, 3, 'Lengkapilah Lukas 12:51. "Kamu menyangka, bahwa Aku datang untuk membawa damai di atas bumi? Bukan, kata-Ku kepadamu, bukan damai, melainkan ...”', 'Keselamatan', 'Berkat', 'Pertentangan', 'Perubahan', 'c'),
(2022, 4, 'GMIM sebagai Gereja Bagian Mandiri dari Gereja Protestan di Indonesia sejak ...', '17 September 1934', '30 September 1934', '12 Juni 1831', '28 Oktober 1928', 'b'),
(2022, 5, 'Apakah judul perikop Efesus 4:17-24 yang merupakan pembacaan Alkitab warga GMIM pada tanggal 19-25 Juni 2022 ?', 'Kesatuan jemaat dan karunia yang berbeda-beda', 'Manusia baru', 'Hidup sebagai anak-anak terang', 'Taat dan kasih', 'b'),
(2022, 6, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 1, penyelenggaraan panggilan GMIM bersumber dari …', 'Tata Gereja GMIM', 'Kesaksian Alkitab: Perjanjian Lama dan Perjanjian Baru', 'Pola pelayanan dan pemerintahan Kristus', 'Yesus Kristus', 'c'),
(2022, 7, 'Berdasarkan Keluaran 31:2, dari suku manakah Bezaleel bin Uri bin Hur yang ditunjuk Allah itu ?', 'Lewi', 'Yehuda', 'Naftali', 'Gad', 'b'),
(2022, 8, 'Siapakah juga yang ditetapkan Allah di samping Bezaleel bin Uri bin Hur, berdasarkan Keluaran 31:6 ?', 'Yosua bin Nun', 'Bileam bin Beor', 'Aholiab bin Ahisamakh', 'Harun dan Hur', 'c'),
(2022, 9, 'Dalam Peraturan tentang Jemaat Bab IX Pasal 31 Ayat 4d, Remaja yang adalah anggota GMIM berusia …', '12 tahun sampai dengan 16 tahun 364 hari', '12 tahun sampai dengan 16 tahun 365 hari', '12 tahun sampai dengan 17 tahun', '12 tahun sampai dengan 17 tahun satu hari', 'a'),
(2022, 10, 'Berdasarkan Tata Gereja GMIM Tahun 2021, satu periode pelayanan GMIM adalah …', 'Tiga tahun', 'Empat tahun', 'Lima tahun', 'Enam tahun', 'c'),
(2022, 11, 'Makna istilah produktif dan konsumtif dalam paragraf tentang budaya tulisan dan lisan adalah ....', 'Mampu menghasilkan – mampu memakai', 'Mampu memakai – mampu menghasilkan', 'Mampu menghasilkan – tidak memakai', 'Mampu menghasilkan – memakai tanpa menghasilkan', 'd'),
(2022, 12, 'GMIM sebagai gereja mandiri ditata dalam sistem …', 'Episkopal', 'Kongregasional', 'Presbiterial Sinodal', 'Sinodal', 'c'),
(2022, 13, 'Terdapat di manakah pembacaan Alkitab pada tanggal 12-18 Juni 2022 dalam perayaan HUT Pekabaran Injil dan Pendidikan Kristen ke 191 ?', 'Matius 10:16-33', 'Efesus 4:17-24', 'Lukas 12:49-59', 'Keluaran 31:1-11', 'a'),
(2022, 14, 'Sebelum menggunakan Tata Gereja GMIM Tahun 2021, GMIM menggunakan Tata Gereja Tahun …', '2007', '2012', '2016', '2020', 'c'),
(2022, 15, 'Lengkapilah Matius 10:22. "Dan kamu akan dibenci semua orang oleh karena …; tetapi orang yang bertahan sampai pada kesudahannya akan selamat."', 'Yesus', 'Bapa-Ku', 'Injil', 'Nama-Ku', 'd'),
(2022, 16, 'Apakah bunyi dari Injil Matius 10:16 ?', '"Aku datang untuk melemparkan api ke bumi dan betapakah Aku harapkan, api itu telah menyala!"', '"Tetapi kamu bukan demikian. Kamu telah belajar mengenal Kristus."', '"Lihat, Aku mengutus kamu seperti domba ke tengah-tengah serigala, sebab itu hendaklah kamu cerdik seperti ular dan tulus seperti merpati."', '"Karena bukan kamu yang berkata-kata, melainkan Roh Bapamu; Dia yang akan berkata-kata di dalam kamu."', 'c'),
(2022, 17, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 3, penyelenggaraan panggilan GMIM berada di …', 'Tanah Minahasa', 'Sulawesi Utara dan sekitarnya', 'Tanah Minahasa dan di luar tanah Minahasa', 'Indonesia dan luar negeri', 'c'),
(2022, 18, 'Kalimat penjelas yang sumbang dalam paragraf tentang SKB empat menteri ditandai dengan nomor ....', '(1)', '(2)', '(3)', '(5)', 'd'),
(2022, 19, 'Siapakah yang mencetuskan Reformasi Gereja pada tahun 1517 ?', 'Yohanes Calvin', 'John Hus', 'Martin Luther', 'John Knox', 'c'),
(2022, 20, 'Dalam pengajaran GMIM tentang baptisan kudus, baptisan adalah ...', 'Tanda perjanjian antara Allah dengan orang-orang yang dipanggil-Nya, serta keturunannya.', 'Pengganti sunat sebagai tanda perjanjian.', 'Dilakukan dalam nama Allah Bapa, Anak, dan Roh Kudus.', 'Semuanya benar.', 'd'),
(2022, 21, 'Pelayanan kategorial remaja GMIM menjadi terpisah dari komisi pelayanan pemuda yang secara resmi menjadi Komisi Pelayanan Remaja Sinode GMIM terhitung sejak tanggal?', '28 Januari 1993', '28 Januari 1992', '28 Januari 1991', '28 Januari 1990', 'd'),
(2022, 22, 'Terdapat di manakah perintah Tuhan Yesus untuk melaksanakan baptisan kudus ?', 'Matius 28:17', 'Matius 28:18', 'Matius 28:19', 'Matius 28:20', 'c'),
(2022, 23, 'Baptisan Kudus dan Perjamuan Kudus adalah bentuk pelayanan gereja yang disebut sebagai ...', 'Katekisasi', 'Ibadah', 'Sakramen', 'Penginjilan', 'c'),
(2022, 24, 'Kepanjangan yang benar dari APIM adalah:', 'Ajaran, Peribadatan dan Misi', 'Ajaran, Persekutuan Ibadat dan Misi', 'Ajaran, Persekutuan Ibadat dan Melayani', 'Alkitab, Persekutuan Ibadat dan Misi', 'b'),
(2022, 25, 'Seseorang dapat menerima sakramen Perjamuan Kudus bila ...', 'Sudah berusia 17 tahun ke atas.', 'Sudah menikah', 'Sudah diteguhkan sebagai anggota sidi jemaat.', 'Sudah mendapat izin dari orang tua.', 'c'),
(2022, 26, 'Diketahui panjang rusuk kubus ABCD.EFGH adalah 6 cm. Tentukan jarak Titik A ke titik C', '3 cm', '6 cm', '12 cm', '6√2', 'd'),
(2022, 27, 'Semboyan Reformasi Gereja "Sola Fide" mengandung maksud ...', 'Keselamatan hanya oleh iman.', 'Keselamatan hanya oleh anugerah.', 'Keselamatan oleh iman dan perbuatan baik.', 'Keselamatan oleh perbuatan baik.', 'a'),
(2022, 28, 'Program strategis KPRS melalui Bidang P3SDM dalam upaya mempersiapkan remaja GMIM menjadi kader remaja yang militan adalah:', 'LKRG', 'LTPR', 'KB3', 'Pemilihan Remaja Teladan', 'a'),
(2022, 29, 'Sebagai gereja Reformasi, GMIM mendasarkan panggilan dan kesaksiannya pada ...', 'Alkitab sebagai Firman Allah', 'Tradisi Gereja', 'Tata Gereja', 'Alkitab, Tradisi Gereja, dan Tata Gereja', 'a'),
(2022, 30, 'Dibawah ini adalah gambaran tantangan yang dihadapi remaja, kecuali:', 'Berpacaran', 'Seks bebas', 'Kemalasan', 'Rajin Beribadah', 'd'),
(2022, 31, 'Dalam Pengakuan Iman Rasuli disebutkan tentang sifat-sifat gereja, yaitu ...', 'Bersaksi, bersekutu, dan melayani', 'Kudus, am, dan rasuli', 'Tubuh Kristus', 'Jujur, adil, dan makmur', 'b'),
(2022, 32, 'Bendahara Komisi Pelayanan Remaja Sinode GMIM 2022-2027 adalah:', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Ester Lambey, SH, MH', 'Pnt. Michelle Rompis, SE, MM', 'Pnt. Okstesi Prisillia Runtu, SH, M.Si', 'a'),
(2022, 33, 'They avoided...... the place because it is dangerous.', 'Visit', 'Visited', 'Visiting', 'to visit', 'c'),
(2022, 34, 'Fungsi kuadrat yang menyinggung sumbu x di titik (3,0) dan melalui titik (0,-9) adalah . . .', 'y = x² + 2x - 5', 'y = -x² + 6x - 9', 'y = x² + 2x - 7', 'y = -x² + 4x - 8', 'b'),
(2022, 35, 'Sekretaris Komisi Pelayanan Remaja Sinode GMIM periode pelayanan 2018-2022 adalah:', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Marthen Riedel Tombeg, M.Teol, MM', 'Pnt. Melky Roky Pattiwael, S.IK, M.S', 'Pnt. Okstesi Prisillia Runtu, SH, M.Si', 'c'),
(2022, 36, 'Did you manage…….. such a difficult project ?', 'to finish', 'finish', 'finishing', 'finished', 'a'),
(2022, 37, 'He was made ….. come here early in the morning.', 'come', 'to come', 'coming', 'came', 'b'),
(2022, 38, 'Perkemahan Kreatif Remaja Sinode GMIM Tahun 2022 akan dilaksanakan di mana?', 'Bumi Perkemahan Senayan, Wilayah Tombatu Timur', 'Bumi Perkemahan Senayan, Wilayah Tombatu Utara', 'Bumi Perkemahan Senayan, Wilayah Tombatu Barat', 'Bumi Perkemahan Senayan, Wilayah Tombatu', 'd'),
(2022, 39, 'Di manakah Ibadah Agung Paskah Tahun 2022 dilaksanakan?', 'Wilayah Likupang 1', 'Wilayah Likupang 2', 'Wilayah Likupang 3', 'Wilayah Likupang 4', 'b'),
(2022, 40, 'Ciri utama Demokrasi Liberal adalah kabinet-kabinet yang terbentuk bertanggungjawab kepada ....', 'wakil presiden', 'presiden', 'partai pendukung', 'perdana menteri', 'd'),
(2022, 41, 'Pada masa kabinet Burhanuddin Harahap pemerintah Indonesia berhasil menyelenggarakan ....', 'Konferensi Inter Indonesia', 'pemilihan umum', 'politik konfrontasi dengan Malaysia', 'sidang konstituante', 'b'),
(2022, 42, 'Tuntutan mahasiswa yang tergabung dalam KAMI terkenal dengan sebutan ....', 'Trikora', 'Tritura', 'Dwikora', 'Tridharma', 'b'),
(2022, 43, 'Munculnya negara-negara adikuasa disebabkan oleh...', 'faktor kekuatan militer dari suatu negara', 'faktor kekuasaan dari suatu negara', 'faktor keberhasilan suatu negara mempengaruhi negara lain', 'faktor keberhasilan suatu negara menguasai negara lain', 'a'),
(2022, 44, 'Yang bukan merupakan sifat gelombang elektromagnetik adalah....', 'memerlukan medium', 'tidak menyimpang dalam medan listrik', 'arah getarannya tegak lurus arah rambatan', 'dapat dipantulkan dan dibiaskan', 'a'),
(2022, 45, 'Tinggi rendahnya nada ditentukan oleh ...', 'panjang gelombang', 'frekuensi', 'lebar sempitnya mulut', 'cepat rambat', 'b'),
(2022, 46, 'Siapakah Menteri Perdagangan Republik Indonesia saat ini ?', 'Muhammad Lutfi', 'Zulkifli Hasan', 'Enggartiasto Lukita', 'Agus Suparmanto', 'b'),
(2022, 47, 'Pada tahun berapakah Pemilihan Umum serentak dilaksanakan ?', '2023', '2025', '2026', '2024', 'd'),
(2022, 48, 'Apabila kita hendak menaikkan tinggi nada suatu dawai maka dapat dilakukan dengan cara....', 'panjang dawai diperbesar', 'panjang dawai diperkecil', 'penampang dawai diperbesar', 'tegangan dawai diperkecil', 'b'),
(2022, 49, 'Ada berapakah jumlah Kabupaten dan Kota di Provinsi Sulawesi Utara ?', '12 Kabupaten 3 Kota', '9 Kabupaten 4 Kota', '11 Kabupaten 4 Kota', '10 Kabupaten 5 Kota', 'c'),
(2022, 50, 'Panjang rusuk kubus ABCD.EFGH adalah 4 cm. Tentukan jarak titik F ke garis AC!', '36√6 cm', '63√3 cm', '12 cm', '62√2', 'd');
