-- TAHUN 2015 - Soal 1 s.d 150 (Data lengkap dari file Soal 2015.pdf)
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2015, 1, 'Berakhirnya pemerintahan Orde Baru ditandai dengan adanya...', 'Mundurnya Presiden Soeharto', 'Demonstrasi besar-besaran Mei 1998', 'Kerusuhan yang terjadi di Jakarta', 'Adanya pahlawan reformasi', 'a'),
(2015, 2, 'Isi dekrit presiden 5 Juli 1959, antara lain...', 'Pembubaran DPR', 'Berlakunya kembali UUD 1945', 'Dibentuknya front nasional', 'Diberlakukannya sistem ekonomi terpimpin', 'b'),
(2015, 3, 'Selain Indonesia, Negara anggota ASEAN yang berbentuk kepuluan adalah...', 'Laos', 'Vietnam', 'Kamboja', 'Filipina', 'd'),
(2015, 4, 'Organisasi yang berusaha untuk mewujudkan perdagangan bebas dunia adalah...', 'WTO', 'OPEC', 'ILO', 'IBRD', 'a'),
(2015, 5, 'Negara - Negara yang termasuk ke dalam kawasan Asia Barat adalah...', 'Suriyah, Israel, Irak', 'India, Pakistan, Nepal', 'Cina, Armenia, Kazakhstan', 'Korea, Jepang, Taiwan', 'a'),
(2015, 6, 'Samudera yang paling luas adalah samudera...', 'Samudra Hindia', 'Samudra Atlantik', 'Samudra Pasifik', 'Samudra Artika', 'c'),
(2015, 7, 'Peristiwa Rengasdengklok terjadi pada tanggal...', '16 Agustus 1945', '15 Agustus 1945', '14 Agustus 1945', '13 Agustus 1945', 'a'),
(2015, 8, 'Organisasi - organisasi bentukan Jepang yang dimanfaatkan pejuang untuk mewujudkan kemerdekaan Indonesia antara lain, kecuali...', 'PUTERA', 'Jawa Hokokai', 'Hizbullah', 'BPUPKI', 'b'),
(2015, 9, 'Perubahan social budaya dari segi ekonomi dapat mengakibatkan kesenjangan antara yang kaya dan yang miskin...', 'Keserasian sosial', 'Penyimpangan sosial', 'Kecemburuan sosial', 'Kesetaraan sosial', 'c'),
(2015, 10, 'Suatu perilaku yang hanya ingin dilihat atau ingin gaya membeli barang - barang atau kebutuhan secara berlebihan disebut...', 'Westernisasi', 'Agen Perubahan', 'Modernisasi', 'Konsumerisme', 'd'),
(2015, 11, 'Dilihat dari letak astronomis menyebabkan Indonesia mempunyai iklim...', 'Tropis', 'Sub Tropis', 'Panas', 'Sejuk', 'a'),
(2015, 12, 'Fungsi keluarga sebagai media hubungan sosial yang utama, yaitu ...', 'Reproduksi', 'Pengaturan pernikahan', 'Kontrol sosial', 'Sosialisasi anggota keluarga', 'd'),
(2015, 13, 'Faktor pendorong adanya perubahan social budaya masyarakat, kecuali...', 'Perubahan jumlah penduduk', 'Sikap masyarakat yang masih sangat tradisional', 'Sistem pendidikan formal yang sangat maju', 'Sikap menghargai hasil karya orang lain', 'b'),
(2015, 14, 'Panitia kecil yang dibentuk pada siding BPUPKI diketuai oleh...', 'Moh. Hatta', 'Ir. Soekarno', 'Moh. Yamin', 'Mr. Ahmad Subarja', 'b'),
(2015, 15, 'Kerjasama internasional merupakan bentuk kerja sama yang tidak mementingkan kepentingan Negara atau wilayah tertentu...', 'ASEAN', 'GATT', 'SEATO', 'Pakta Warsawa', 'b'),
(2015, 16, 'Ciri - ciri drama adalah ...', 'Memiliki alur', 'Mengandung konflik', 'Terdiri atas dialog - dialog', 'Bertema sosial', 'c'),
(2015, 17, 'Fitnah itu lebih kejam dari pada pembunuhan. Kalimat di atas mengandung kata tingkat perbandingan...', 'Superlatif', 'Komparatif', 'Ekuatif', 'Distributif', 'b'),
(2015, 18, 'Dina merupakan buah hati kedua orang tuanya. Kata buah hati merupakan contoh kata ...', 'Konatif', 'Denotatif', 'Reduplikasi', 'Deduksi', 'b'),
(2015, 19, 'Perbaikan kalimat tidak efektif yang tepat adalah...', 'Kami selalu sarapan pagi agar tidak sakit perut ketika berolahraga', 'Kami selalu sarapan pagi supaya tidak sakit perut ketika berolahraga', 'Ketika berolahraga kami selalu sarapan agar tidak sakit perut', 'Kami selalu sarapan agar tidak sakit perut ketika berolahraga', 'd'),
(2015, 20, 'Pernyataan dibawah ini yang termasuk ciri - ciri surat resmi adalah...', 'Bahasa resmi, bernomor, berkepala surat', 'Bahasa resmi, tidak bernomor, berkepala surat', 'Bahasa santai, tidak bernomor, tidak berkepala surat', 'Bahasa santai, bernomor, tidak berkepala surat', 'a'),
(2015, 21, 'Slogan yang tepat sesuai dengan ilustrasi kepala sekolah...', 'Sampah musuh kita, bersih sahabat kita', 'Kebersihan sekolah merupakan kewajiban semua siswa', 'Jagalah kebersihan kelas dan lingkungan kelas masing-masing', 'Setiap hari kita harus menjaga kebersihan lingkungan sekolah kita', 'a'),
(2015, 22, 'Rumusan masalah yang tepat sesuai tema "Meningkatkan prestasi belajar siswa dengan membaca bersama" adalah...', 'Siapa sajakah yang prestasi belajarnya meningkat?', 'Kapan kita dapat meningkatkan prestasi belajar?', 'Bagaimanakah upaya peningkatan prestasi belajar dengan membaca bersama?', 'Apakah dengan belajar dapat meningkatkan prestasi belajar bersama?', 'c'),
(2015, 23, 'Berkat usahanya yang gigih, orang tua asuh itu mampu mengantarkan kedua putranya menjadi cendekiawan...', 'Berkat', 'Usahanya', 'Putranya', 'Cendekiawan', 'd'),
(2015, 24, 'Permasalahan yang tidak tepat berdasarkan topic "Perpustakaan Multimedia dan Fungsinya bagi Pelajar" adalah...', 'Apa fungsi perpustakaan multimedia bagi pelajar?', 'Siapakah penggagas ide perpustakaan multimedia?', 'Apa yang dimaksud dengan perpustakaan multimedia?', 'Apa tujuan perpustakaan multimedia?', 'b'),
(2015, 25, 'Lidya pergi ke sekolah dengan pakaiannya yang terlalu mencolok. Kritikan yang tepat...', 'Pakaian kamu itu hanya cocok untuk pergi ke pasar.', 'Jangan dulu masuk kelas, kamu harus berganti pakaian dulu.', 'Kamu jangan terlalu menonjolkan diri, nanti teman-temanmu cemburu.', 'Lidya, pakaianmu terlalu mencolok, terutama bahannya sangat mahal.', 'd'),
(2015, 26, 'What is the text about? (Congratulations on your graduation)', 'A letter from a student', 'A student report', 'A greeting card', 'An email', 'c'),
(2015, 27, 'What is the Jeremy''s purpose to send the card?', 'inform Brynetta about graduation day', 'tell Brynetta about graduation ceremony', 'describe the process of graduation', 'congratulate Brynetta for her graduation', 'd'),
(2015, 28, 'What is the short message about? (Plan to join school choir postponed)', 'delaying the plan', 'informing the new schedule', 'agreeing to join the activity', 'joining school choir', 'a'),
(2015, 29, 'Possibly, Irene is one of Christo''s...', 'soulmate', 'playmate', 'schoolmate', 'roommate', 'c'),
(2015, 30, 'What is the purpose of the text? (Missing wallet)', 'To announce a missing wallet', 'To describe a wallet', 'To give a reward', 'To advertise a wallet', 'a'),
(2015, 31, 'What does the text tell about?', 'a missing wallet', 'a driving license', 'a reward', 'a telephone number', 'a'),
(2015, 32, 'You can find these things in the wallet, except...', 'driving license', 'ATM card', 'Some money', 'A reward', 'd'),
(2015, 33, 'What does the text mainly tell about? (Persian cat)', 'Nursing a pet', 'A Persian cat', 'Taking care a pet', 'A Persian pet cat', 'b'),
(2015, 34, 'What is the main idea of paragraph 3?', 'Grace massaged Ryan''s back', 'Grace knew who really care her', 'Grace showed a surprising attitude', 'Grace was brought to Ryan''s family', 'c'),
(2015, 35, 'Where did Grace do the massage?', 'On the window', 'On the bed', 'In her cage', 'In the bed', 'b'),
(2015, 36, 'Why didn''t Grace move from her cage to welcome Ryan''s mother and sister?', 'She was sleepy', 'One of her legs is broken', 'The cage was locked by Ryan', 'She thought they were not her master', 'd'),
(2015, 37, 'He runs ...to catch. He leaves me far behind him', 'Too fast', 'Fast enough', 'Too slow', 'Slow enough', 'a'),
(2015, 38, 'What is the purpose of this notice? (Aviation safety)', 'To give the message to the all readers', 'To ban the use of hand phone at the airport', 'To warn people not to carry hand phone', 'To remind passengers not to carry hand phone on the plane', 'd'),
(2015, 39, 'Who does give the notice?', 'The pilot', 'Air crew', 'Stewardess', 'Airport authority', 'd'),
(2015, 40, 'Hana : Dad, would you mind if I borrow your recorder? Mr Christo : Ok, no problem. The expression expresses...', 'Certainty', 'Doubt', 'Uncertainty', 'Permission', 'd'),
(2015, 41, '(-20) + 8 × 5 - 18 ÷ (-3) adalah...', '-26', '-14', '14', '26', 'd'),
(2015, 42, 'Hasil dari 2 1/5 + 1 1/5 - 1 1/4 adalah ...', '1 5/7', '1 1/30', '7/12', '5/12', 'b'),
(2015, 43, 'Hasil dari 3√6 × √2 adalah', '6√2', '6√3', '6√6', '18√2', 'b'),
(2015, 44, 'Yosua membeli 10 pasang sepatu... Persentase keuntungan yang diperoleh Yosua adalah...', '7 1/2%', '15%', '22 1/2%', '30%', 'a'),
(2015, 45, 'Tiga keeping uang logam dilempar bersama - sama. Peluang muncul dua gambar dan satu angka adalah ...', '1/8', '1/3', '3/8', '2/3', 'c'),
(2015, 46, 'Pak Fiano mempunyai persediaan makanan ternak... persediaan makanan ternak Pak Fiano akan habis dalam waktu ... hari', '6', '11', '14', '15', 'a'),
(2015, 47, 'Hasil dari 27^(2/3) + 100^0 + 64^(1/6) - 64^(1/3) adalah', '16', '12', '10', '8', 'b'),
(2015, 48, 'Selesaikan 2^(x+1) = 4√2', '1/2', '1/3', '2/3', '3/2', 'a'),
(2015, 49, 'Perbandingan kelereng Yosua dan Aldo 2:3. Jumlah kelereng mereka 70 buah. Selisih kelereng keduanya adalah...', '14 buah', '24 buah', '26 buah', '42 buah', 'a'),
(2015, 50, 'Dua suku berikutnya dari barisan bilangan 100, 95, 89, 82, 74,...', '64, 65', '64, 56', '65, 55', '65, 56', 'c'),
(2015, 51, 'Dari 50 siswa, 23 siswa menggemari Matematika, 31 Bahasa Inggris, dan 9 keduanya...', '4', '5', '13', '23', 'b'),
(2015, 52, 'Sebuah mobil menempuh jarak dari kota A ke B dalam waktu 1,2 jam dengan kecepatan 80 km/jam...', '96 km/jam', '72 km/jam', '66 km/jam', '62 km/jam', 'a'),
(2015, 53, 'Dalam waktu 7 menit Maria mampu membaca buku cerita sebanyak 140 kata...', '20 menit', '25 menit', '35 menit', '70 menit', 'c'),
(2015, 54, 'Bila X1 dan X2 adalah akar - akar persamaan kuadrat x² - 6x - 5 = 0, maka x1² + x2² adalah ...', '41', '46', '31', '37', 'b'),
(2015, 55, 'Banyaknya digit pada bilangan hasil dari 2^2014 . 5^2015 adalah....', '2014', '2015', '2016', '2017', 'b'),
(2015, 56, 'Asteroid merupakan planet kecil yang mengorbit di antara orbit planet yang bernomor....', '(1) dan (2)', '(2) dan (3)', '(3) dan (4)', '(4) dan (5)', 'c'),
(2015, 57, 'Air laut terjadi pasang minimum dan pasang maksimum, ketika bulan berturut-turut harus berada pada titik....', '(1),(3) dan (2),(4)', '(1),(4) dan (2),(3)', '(2),(4) dan (1),(3)', '(2),(3) dan (1),(4)', 'b'),
(2015, 58, 'Keluarga Ardy memiliki 4 buah kipas listrik, masing-masing berdaya 50 W...', '50 kWh', '60 kWh', '70 kWh', '80 kWh', 'b'),
(2015, 59, 'Berikut ini yang dapat menjadi indikasi terjadinya gejala pemanasan global adalah .', 'sering terjadinya gempa', 'sering terjadi asap kabut', 'sering terjadi banjir', 'penderita gangguan pernapasan meningkat', 'c'),
(2015, 60, 'Ciri-ciri makhluk hidup terdapat pada nomor ....', '1,2,3,4,5', '1,2,3,4,6', '1,2,4,5,6', '1,2,3,4,5,6', 'a'),
(2015, 61, 'Berdasarkan gambar tersebut menunjukkan bahwa makhluk hidup memiliki ciri ....', 'bernafas', 'berkembangbiak', 'tumbuh', 'peka terhadap rangsang', 'b'),
(2015, 62, 'Gambar yang menunjukkan ciri makhluk hidup membutuhkan makan dan menanggapi rangsang adalah ....', '1 dan 2', '1 dan 3', '2 dan 3', '2 dan 4', 'b'),
(2015, 63, 'Usaha untuk menyelamatkan populasi komodo yang semakin terancam kelestariannya...', 'melindungi habitat aslinya', 'melakukan penangkaran di luar habitat', 'menegakkan UU anti perburuan', 'menjadikan habitat aslinya cagar alam', 'a'),
(2015, 64, 'Bila lengan bawah digerakkan... maka otot-otot pada lengan atas akan bekerja secara ....', 'sinergis', 'antagonis', 'supinasi', 'pronasi', 'b'),
(2015, 65, 'Enzim yang dihasilkan oleh pankreas dan berfungsi merombak protein menjadi asam amino adalah....', 'amilopsin', 'pepsin', 'rennin', 'tripsin', 'd'),
(2015, 66, 'Bagian yang berfungsi menyaring darah adalah....', 'a', 'b', 'c', 'd', 'c'),
(2015, 67, 'Bagian yang berfungsi mengangkut garam mineral dan air dari dalam tanah ditunjukkan oleh ....', '1', '2', '3', '4', '2'),
(2015, 68, 'Tanaman yang sengaja disimpan terbalik, arah tumbuhnya tetap akan ke atas. Gerak ini disebut....', 'fototropisme positif', 'fototropisme negatif', 'geotropisme positif', 'geotropisme negatif', 'c'),
(2015, 69, 'Dari hasil percobaan di atas, proses fotosintesis akan menghasilkan ....', 'Karbohidrat', 'Protein', 'Oksigen', 'Karbondioksida', 'c'),
(2015, 70, 'Lumba-lumba dan paus merupakan hewan mamalia yang hidup di air... perilaku adaptasi adalah ..', 'banyak minum air', 'banyak mengeluarkan urine', 'sedikit mengeluarkan urine', 'sering kali muncul ke permukaan', 'd'),
(2015, 71, 'Teknologi reproduksi yang dapat membantu pasangan suami-istri yang lama belum mendapatkan keturunan adalah ....', 'kloning', 'bayi tabung', 'rekombinasi ADN', 'fusi protoplasma', 'b'),
(2015, 72, 'Jika boraks termakan dalam kadar tertentu, dapat menimbulkan efek samping bagi kesehatan...', 'gangguan pada sistem saraf, ginjal, hati, dan kulit', 'gejala pendarahan di usus halus dan ginjal', 'terjadinya komplikasi pada jantung dan hati', 'menyebabkan kematian jika mengandung 6-10 gram', 'a'),
(2015, 73, 'Berikut ini yang merupakan dampak dari minuman keras adalah ....', 'meningkatkan tindak kejahatan', 'menimbulkan kanker saluran pernapasan', 'menyebabkan penyempitan pembuluh darah', 'timbulnya halusinasi', 'a'),
(2015, 74, 'Panjang suatu benda yang diukur dengan jangka sorong diperlihatkan gambar... panjang benda adalah ....', '5,04 cm', '5,47 cm', '5,70 cm', '5,74 cm', 'b'),
(2015, 75, 'Gelas ukur berisi air dimasukkan benda... massa benda 54 g, maka massa jenis benda adalah ....', '1 g/cm³', '1,4 g/cm³', '2,5 g/cm³', '2,7 g/cm³', 'd'),
(2015, 76, 'Pernyataan yang tidak tepat dari gambar bimetal itu yaitu ....', 'koefisien muai panjang logam A lebih kecil dari B', 'koefisien muai panjang logam B lebih kecil dari A', 'bimetal akan melengkung ke arah logam B bila didinginkan', 'koefisien muai volume logam B lebih kecil dari A', 'b'),
(2015, 77, 'Siapakah Ketua MPR RI Sekarang ini :', 'Zulkifli Husain', 'Zulkifli Hasan', 'Zulkifli Husein', 'Zulkifli Husein', 'b'),
(2015, 78, 'Siapakah Menteri Luar Negeri RI sekarang ini :', 'Retno Marsudirini', 'Retno Wulandari', 'Retno Marsudi', 'Retno Marsudin', 'c'),
(2015, 79, 'Siapakah Gubernur Propinsi Jawa Tengah Sekarang ini :', 'Ganjar Pranowo', 'Banjar Pranowo', 'Ganjar Prabuwono', 'Ganjar Prabukusomo', 'a'),
(2015, 80, 'Kedutaan Besar Republik Indonesia (KBRI) manakah yang hancur pada bulan April 2015 :', 'KBRI Yaman', 'KBRI Oman', 'KBRI Irak', 'KBRI Syria', 'a'),
(2015, 81, 'Kapankah Konperensi Asia Afrika itu dilaksanakan di Bandung :', 'Tahun 2015', 'Tahun 1955', 'Tahun 2000', 'Tahun 1950', 'b'),
(2015, 82, 'Siapakah yang pertama kali memelopori emansipasi wanita di Indonesia', 'Raden A. Kartini', 'Walanda Maramis', 'Cut Nyak Dien', 'Semua benar', 'a'),
(2015, 83, 'Di Indonesia ada hewan purba yang masih hidup yaitu :', 'Ikan Raja Laut', 'Komodo', 'Gorilla', 'a dan b benar', 'b'),
(2015, 84, 'Presiden Keenam Republik Indonesia adalah', 'Joko Widodo', 'Megawati Sukarnoputri', 'B. J. Habibie', 'Susilo B. Yudhoyono', 'd'),
(2015, 85, 'Menteri Pemuda dan olahraga republik indonesia sekarang ini adalah :', 'Imam Nahrawi', 'Iman Nahrowi', 'Maruar Sirait', 'Imas Nahrowi', 'a'),
(2015, 86, 'Ibadah & Pawai Paskah Nasional Pertama kali dilaksanakan di :', 'Kupang', 'Manado', 'Ambon', 'Jakarta', 'b'),
(2015, 87, 'Siapakah Gubernur di Indonesia yang pernah menjabat sebagai Gubernur atau Pejabat Gubernur di tiga propinsi :', 'Sinyo H Sarundajang', 'Joko Widodo', 'Ganjar Pranowo', 'Fadel Muhamad', 'a'),
(2015, 88, 'Kepala Kepolisian Republik Indonesia adalah :', 'Badrodin Haiti', 'Badarudin Haiti', 'Badridon Haiti', 'Budi Gunawan', 'a'),
(2015, 89, 'Singkatan dalam bahasa Inggris untuk organisasi kesehatan dunia adalah :', 'ILO', 'WHO', 'IHO', 'AHO', 'b'),
(2015, 90, 'Berikut adalah organisasi dunia dimana Indonesia menjadi anggotanya kecuali :', 'OKI', 'APEC', 'OPEC', 'Semua Salah', 'c'),
(2015, 91, 'Dimanakah letak KM 0 dari negara republik Indonesia :', 'Sabang', 'Banda Aceh', 'Sibolga', 'Jakarta', 'b'),
(2015, 92, 'Kapankah secara resmi Komisi Pelayanan Remaja Sinode GMIM Berdiri sendiri:', '27 Januari 1990', '28 Januari 1990', '27 Januari 1960', '28 Januari 1960', 'b'),
(2015, 93, 'Ketua Komisi Pelayanan Remaja Sinode GMIM periode kedua adalah :', 'Pnt. Drs. Jemmy Mamahit', 'Pnt. Drs. J. W. Sajow, M.Si', 'Pnt. Jacobus Wowor', 'Pnt. Ir. Dwight Moody Rondonuwu', 'b'),
(2015, 94, 'Siapakah Asisten Bendahara Komisi Pelayanan Remaja Sinode GMIM yang tidak bisa menyelesaikan tugasnya hingga periode berakhir :', 'dr. Arthur Cahya', 'Sym. Davy Awondatu, SPd', 'Anita Enoch, SE', 'Pnt. Santy G. Luntungan, ST', 'b'),
(2015, 95, 'Pada Pemilihan Komisi Remaja periode manakah yang hasilnya di anulir oleh Sidang Sinode :', '1990 - 1995', '1995 - 2000', '2000 - 2005', '2005 - 2010', 'c'),
(2015, 96, 'Berikut ini adalah anggota Komisi Pelayanan Remaja Sinode GMIM periode 2014-2018 yang baru pertama kali kecuali :', 'Pnt. Selfran Wungow, SE', 'Pnt. Melky Pattiwael, SIK. MSi', 'Pnt. Mariana Sibi', 'Pnt. dr. Fiona Seilatuw', 'c'),
(2015, 97, 'Berikut ini adalah jabatan lain Ketua Komisi Pelayanan Remaja Sinode GMIM 2014-2018 sekarang, kecuali :', 'Dosen Fakultas Teknik Universitas Sam Ratulangi', 'Ketua Komisi Pelayanan Remaja Jemaat Yobel Winangun', 'Ketua Komisi Pelayanan Remaja Wilayah Manado Winangun', 'Anggota Badan Pekerja Majelis Sinode GMIM', 'b'),
(2015, 98, 'Berapakah jumlah Kelompok Kerja Bidang pada KPRS GMIM Periode sekarang ini :', '7 Bidang', '8 Bidang', '9 Bidang', '10 Bidang', 'b'),
(2015, 99, 'Melaksanakan kegiatan Festival Kreativitas Remaja & Siswa GMIM adalah tugas dari Kelompok Kerja Bidang :', 'PMB', 'P3SDM', 'Pelsis', 'OM', 'c'),
(2015, 100, 'Di wilayah manakah akan dilaksanakan kegiatan Festival Kreativitas Remaja & Siswa GMIM tahun 2015 :', 'Tondano', 'Tondano I', 'Tondano II', 'Tondano Raya', 'c');
-- TAHUN 2015 Lanjutan (101 - 150)
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2015, 101, 'Berikut ini adalah jabatan lain Ketua Komisi Pelayanan Remaja Sinode GMIM 2014-2018 sekarang, kecuali :', 'Dosen Fakultas Teknik Universitas Sam Ratulangi Manado', 'Ketua Komisi Pelayanan Remaja Jemaat Yobel Winangun', 'Ketua Komisi Pelayanan Remaja Wilayah Manado Winangun', 'Anggota Badan Pekerja Majelis Sinode GMIM', 'b'),
(2015, 102, 'Berapakah jumlah Kelompok Kerja Bidang pada KPRS GMIM Periode sekarang ini :', '7 Bidang', '8 Bidang', '9 Bidang', '10 Bidang', 'b'),
(2015, 103, 'Melaksanakan kegiatan Festival Kreativitas Remaja & Siswa GMIM adalah tugas dari Kelompok Kerja Bidang :', 'PMB', 'P3SDM', 'Pelsis', 'OM', 'c'),
(2015, 104, 'Di wilayah manakah akan dilaksanakan kegiatan Festival Kreativitas Remaja & Siswa GMIM tahun 2015 :', 'Tondano', 'Tondano I', 'Tondano II', 'Tondano Raya', 'c'),
(2015, 105, 'Kegiatan Pesta Seni Remaja GMIM tahun 2014 dilaksanakan pada :', '5-6 September 2014 di Wilayah Pineleng', '5-6 September 2014 di Wilayah Pinaesaan', '5-6 September 2014 di Wilayah Pakolor Indah', 'Semua jawaban salah', 'a'),
(2015, 106, 'Dimanakah Pemilihan KPRS GMIM Periode 2014 - 2018 dilaksanakan :', 'GMIM Dame Tosuraya Wilayah Ratahan', 'GMIM Elim Pangu Wilayah Ratahan', 'GMIM Wioy Wilayah Ratahan', 'GMIM Imanuel Rasi Wilayah Ratahan', 'b'),
(2015, 107, 'Syarat menjadi Ketua Komisi Pelayanan Kategorial Jemaat, kecuali :', 'Berusia diatas 25 Tahun', 'anggota Sidi Jemaat', 'Memiliki sertifikat pelatihan', 'memiliki pengalaman pelayanan', 'a'),
(2015, 108, 'Tata Gereja GMIM 2007 terdiri dari :', '1 Tata Dasar, 8 Peraturan', '1 Tata Dasar, 9 Peraturan', '1 Tata Dasar, 7 Peraturan', '1 Tata Dasar, 10 Peraturan', 'b'),
(2015, 109, 'Sesuai Adendum Tata Gereja GMIM maka Remaja yang adalah anggota GMIM adalah :', 'Berusia 12 tahun sampai dengan 16 tahun', 'Berusia 12 tahun sampai dengan 16 tahun, 364 hari', 'Berusia 12 tahun sampai dengan 17 tahun', 'Berusia 12 tahun sampai dengan 17 tahun, 364 hari', 'b'),
(2015, 110, 'Alkitab terdiri dari :', '39 Kitab Perjanjian Lama & 27 Kitab Perjanjian baru', '27 Kitab Perjanjian Lama & 39 Kitab Perjanjian Baru', '39 Kitab Perjanjian Lama & Perjanjian Baru', '27 Kitab Perjanjian Lama & Baru', 'a'),
(2015, 111, 'Bahasa yang dipakai dalam Kitab Perjanjian Lama adalah :', 'Aram', 'Ibrani', 'Arab', 'Yunani', 'b'),
(2015, 112, 'Berikut ini adalah Kitab Nabi-Nabi Besar Kecuali :', 'Yeheskiel', 'Yeremia', 'Amos', 'Yesaya', 'c'),
(2015, 113, 'Berikut ini adalah Kitab-Kitab Sastra, Kecuali :', 'Ayub', 'Mazmur', 'Kidung Agung', 'Ratapan', 'd'),
(2015, 114, 'Berikut adalah Kitab-Kitab Nabi Besar :', 'Yesaya', 'Yeremia', 'Ratapan', 'Semua benar', 'd'),
(2015, 115, 'Berikut ini adalah Kitab-Kitab Nabi Kecil, Kecuali :', 'Ezra', 'Hosea', 'Yoel', 'Hagai', 'a'),
(2015, 116, 'Nats : "Lalu aku mendengar suara Tuhan berkata : Siapakah yang akan Kuutus..." terdapat dalam kitab :', 'Yeheskiel', 'Yesaya', 'Yeremia', 'Daniel', 'b'),
(2015, 117, '"Maka inilah tulisan yang tertulis itu : Mene, mene, tekel ufarsin." Nats ini terdapat dalam Kitab :', 'Yeheskiel', 'Yesaya', 'Yeremia', 'Daniel', 'd'),
(2015, 118, 'Kitab Hosea terletak antara Kitab - Kitab apakah :', 'Daniel - Yoel', 'Yoel - Amos', 'Nahum - Habakuk', 'Zefanya - Hagai', 'b'),
(2015, 119, 'Bacaan Yang dipakai dalam Hari Paskah II/Hari Pemuda/Remaja GMIM tahun ini dalam buku MTPJ adalah :', 'Markus 16 : 1-8', 'Roma 4 : 18-25', 'Keluaran 15 : 19-21', 'Lukas 24 : 50-53', 'a'),
(2015, 120, '"Bersorak-sorailah, hai puteri Sion, bertempik-soraklah, hai Israel!..." Nats ini terdapat dalam Kitab :', 'Zefanya', 'Roma', 'Hosea', 'Ibrani', 'a'),
(2015, 121, '"Siapakah yang akan memisahkan kita dari kasih Kristus?..." Nats ini terdapat dalam kitab :', 'Zefanya', 'Roma', 'Hosea', 'Ibrani', 'b'),
(2015, 122, 'Lengkapi nats : "Dan Yesus makin bertambah besar dan bertambah ... dan ... dan makin dikasihi oleh Allah dan Manusia."', 'Hikmat - besarnya', 'hikmatnya - besarnya', 'Hikmatnya - besar', 'hikmat - besar', 'a'),
(2015, 123, 'Kitab dalam Alkitab yang tidak memuat satupun kata TUHAN atau Allah adalah :', 'Amsal', 'Pengkhotbah', 'Ratapan', 'Ester', 'd'),
(2015, 124, 'Kitab Roma terletak antara kitab :', 'Lukas - Yohanes', 'Yohanes - Kisah para rasul', 'Kisah Para Rasul - I Korintus', 'II Korintus - Galatia', 'c'),
(2015, 125, 'Berasal dari Negara manakah Riedel-Schwarz itu :', 'Belanda', 'Jerman', 'Polandia', 'Amerika', 'b'),
(2015, 126, 'Ketua Sinode GMIM periode 2010 - 2014 adalah :', 'Pdtr. DR. H. W. B. Sumakul', 'Pdtr. Piet Marthin Tampi, STh, MSi', 'Pdtr. Prof. DR. W. A. Roeroe', 'Pdtr. DR. A. O. Supit', 'b'),
(2015, 127, 'Ketua Majelis Pertimbangan Sinode GMIM Periode 2010-2014 adalah :', 'Pdtr. DR. Johan Nicolaas Gara, MA', 'Pdtr. A. W. Tampemawa, Sm.Th', 'Pdtr. Ketty Supit-Ticoalu, STh', 'Semua Salah', 'a'),
(2015, 128, 'Kepala Daerah yang menjadi anggota Majelis Pertimbangan Sinode GMIM periode 2014-2018 adalah :', 'Pnt. Drs. Jantje W. Sajow, MSi', 'James Sumendap, SH', 'Pnt. DR. Ir. G. S. V. Lumentut, SH, DEA', 'Pnt. DR. Jouhary Kansil, MPd', 'c'),
(2015, 129, 'Ketua BPMS GMIM Periode 2014-2018 pada periode sebelumnya menjabat sebagai?', 'Sekretaris BPMS', 'Wakil Ketua BPMS', 'Wakil Sekretaris BPMS', 'Bendahara BPMS', 'b'),
(2015, 130, 'Berikut adalah anggota Badan Pengawas Perbendaharaan Sinode GMIM Periode 2010-2014, kecuali :', 'Drs. J. W. A. Mengko', 'Max V. Kewas, SH', 'Drs. Alex Wariki', 'Ferdinand O. P. Tanos', 'd'),
(2015, 131, 'Wakil Sekretaris BPMS GMIM Bidang Data dan Informasi periode 2014-2018 adalah', 'Pdt. Altje Runtu-Lumi, MTh', 'Pdt. Richard J. H. Mengko, MTh', 'Pdt. Janny Ch. Rende, MTh', 'Pnt. Jhonly Th Wenur, SH, MH, MM', 'b'),
(2015, 132, 'Ketua Badan Pengawas Perbendaharaan Sinode GMIM Periode 2014 – 2018 adalah :', 'Prof. DR. Stanss L. H. V. J. Lapian, SE, M.Ec', 'Alwin Ch. Rondonuwu, SE, MBA, CPHR', 'DR. Tommy Parengkuan, SE, MS', 'Brian Janni Waleleling, SH', 'a'),
(2015, 133, 'Bendahara BPMS GMIM Periode 2014-2018 adalah :', 'Sym. Ricky Montong, STh', 'Sym. Eddy Sepang', 'Pnt. Michaela Paruntu', 'Pnt. Ester Lambey', 'a'),
(2015, 134, 'Jika pada periode 2014 - 2018 jumlah BPMS GMIM adalah 15 orang, berapa orangkah pada periode sebelumnya (2010-2014) :', '21 orang', '15 orang', '14 orang', '10 orang', 'c'),
(2015, 135, 'GMIM adalah gereja yang di mandirikan dari gereja apakah :', 'Gereja Protestan Indonesia bagian Barat', 'Gereja Kristen Indonesia', 'Gereja Belanda', 'Gereja Protestan di Indonesia', 'd'),
(2015, 136, 'Sejak berdirinya hingga sekarang, GMIM telah dipimpin oleh berapa Ketua Sinode :', '12', '13', '14', '15', 'b'),
(2015, 137, 'Sejak berdirinya hingga sekarang, GMIM telah dipimpin oleh berapa orang sebagai Ketua Sinode :', '12 orang', '13 orang', '14 orang', '15 orang', 'b'),
(2015, 138, 'Ketua Sinode GMIM yang pertama adalah :', 'Ds. E. A. A. D. de Vreede', 'Ds. H. H. van Herwerden', 'Ds. C. D. Buunck', 'Ds. G. P. H. Locker', 'a'),
(2015, 139, 'Ketua Sinode GMIM yang pertama yang adalah orang pribumi adalah :', 'Ds. A. Z. R. Wenas', 'Ds. R. M. Luntungan', 'Ds. M. Sondakh', 'Pdt. DR. W. A. Roeroe', 'a'),
(2015, 140, 'BONUS - Siapakah yang menulis surat kepada jemaat di Filipi?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a')
