-- TAHUN 2016 - Soal 1 s.d 150
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2016, 1, 'Ide pokok paragraf tentang peran seni teater tersebut adalah….', 'manfaat peran seni teater', 'pengajaran dalam teater', 'pengenalan karakter orang', 'runtuhnya karakter bangsa', 'a'),
(2016, 2, 'Kalimat yang merupakan fakta dalam paragraf tersebut adalah nomor….', '(1)', '(3)', '(2)', '(4)', 'b'),
(2016, 3, 'Kalimat yang menggunakan kata tidak baku adalah nomor …. (paragraf teater)', '(1)', '(3)', '(2)', '(4)', 'b'),
(2016, 4, 'Kalimat utama paragraf tentang radikal bebas dan DNA terdapat pada nomor ….', '(4)', '(2)', '(3)', '(1)', 'd'),
(2016, 5, 'Pernyataan yang sesuai dengan isi paragraf tentang DNA adalah….', 'DNA yang sangat penting bagi tubuh dapat dirusak oleh beberapa jenis virus, tetapi dapat dihambat dengan fitokimia', 'Beberapa bahan fitokimia mampu menghambat proses perusakan DNA', 'Sel kanker disebabkan oleh radikal bebas, virus, bahan kimia, dan radiasi', 'DNA adalah bagian penting dari sel tubuh karena berfungsi mengatur kinerja sel', 'a'),
(2016, 6, 'Simpulan makna simbol pakaian serba hitam pada kutipan cerpen tersebut adalah ….', 'kegembiraan', 'berduka cita', 'pemakaman', 'bersuka ria', 'b'),
(2016, 7, 'Isi tersirat pada kutipan cerpen tersebut adalah …', 'Shinta memberi kado terakhir kepada sahabatnya Fira', 'Persahabatan yang sejati akan terbawa sampai akhir hayat', 'Lila menenangkan Fira yang bersedih karena kehilangan', 'Fira dan Lila menghadiri acara pemakaman sahabat sejatinya', 'b'),
(2016, 8, 'Sebab terjadinya konflik pada kutipan cerpen tersebut adalah …', 'Shinta menderita sakit', 'Lila menyakiti Fira', 'Ibu memaksa Lila', 'Fira salah paham', 'a'),
(2016, 9, 'Akibat konflik pada kutipan cerpen tersebut adalah …', 'Shinta meninggal saat dioperasi penyakitnya', 'Ibu membawa Shinta berobat ke rumah sakit', 'Fira menyesal karena telah salah menilai Lila', 'Shinta menemani Lila meminta maaf pada Fira', 'a'),
(2016, 10, 'Isi dari pengumuman tentang kerja bakti di atas adalah ?', 'Menjaga kesehatan', 'Mengadakan kegiatan', 'Mengadakan kerja bakti', 'Menjaga kebersihan', 'c'),
(2016, 11, 'Kepada siapakah memo tersebut ditujukan ?', 'Manager keuangan', 'Karyawan', 'Dewan direksi', 'HRD', 'a'),
(2016, 12, 'Kalimat yang mengandung majas hiperbola adalah ?', 'Hutang Budi telah menumpuk hingga menjadi gunung', 'Waktu terus berjalan tanpa henti', 'Silahkan diterima pemberian kecil ini', 'Indonesia meraih juara umum di kejuaraan bulu tangkis', 'a'),
(2016, 13, 'Kalimat di bawah ini yang merupakan kalimat majemuk rapatan adalah ?', 'Ibu memarahi adik karena berbuat kenakalan', 'Paman datang dari kampung dengan membawa buah duku, rambutan, dan pisang', 'Budi rajin belajar sehingga dia menjadi anak yang pintar', 'Jeni memberikan adiknya uang supaya dia tidak menceritakan masalahnya', 'b'),
(2016, 14, 'Pidato impromptu adalah pidato yang disampaikan dengan cara ?', 'Tanpa menggunakan teks', 'Menghafal teks', 'Membaca teks', 'Formal', 'a'),
(2016, 15, 'Kata lemari merupakan kata serapan dari bahasa ?', 'Belanda', 'Arab', 'Inggris', 'Spanyol', 'a'),
(2016, 16, 'The story mainly tells us about …. (Rabbit and crocodile)', 'twenty crocodile', 'the boss of the crocodile', 'a rabbit and twenty crocodile', 'a rabbit and the boss of crocodile', 'c'),
(2016, 17, 'We know from the first paragraph that the rabbit actually wanted ....', 'to cross the river', 'to swim across the river', 'to meet the boss of crocodile', 'to know where the crocodile are', 'a'),
(2016, 18, 'All of you are good, nice, gentle, and kind.... The underlined word is synonymous with ....', 'mild', 'cheerful', 'diligent', 'easygoing', 'a'),
(2016, 19, 'What are the speakers going to do? (Bruno Mars show)', 'To stay at home', 'to see Bruno Mars show', 'to arrange their free time', 'to watch Bruno Mars at home', 'b'),
(2016, 20, 'What is the most possible place where Zaki is talking to her father?', 'A hall', 'Her home', 'The office', 'Her school', 'd'),
(2016, 21, 'In which section would you likely read the ad? (Company Accountant)', 'Company for sale', 'Office Equipment', 'Job Vacancy', 'Stationary and office', 'c'),
(2016, 22, 'What position is offered in the advertisement?', 'Salesman', 'Wholesaler', 'Accountant', 'Office staff', 'c'),
(2016, 23, 'What information should the applicant include in it? (Curriculum vitae)', 'Experience in managing a company', 'A statement of salary wanted', 'A prove of knowing about stationary', 'A statement of education and work experience', 'd'),
(2016, 24, 'The whole paragraph promotes that .... (University of Australia)', 'the university of Australia offers excellent educational program', 'the university of Australia is the largest university in the country', 'the university of Australia has a specialized technology campus', 'the university places particular importance on technology', 'a'),
(2016, 25, 'Which information is NOT TRUE about the University of Australia?', 'it has an international educational reputation', 'it also has a specialized technology campus', 'it has six technology campuses', 'it is Australia''s largest university', 'c'),
(2016, 26, 'It is stated that the university has good relationship with ....', 'educational professionals', 'other campuses', 'specialized technology', 'industry', 'd'),
(2016, 27, 'The underlined word "reputation" means ....', 'knowledge', 'attitude', 'prestige', 'characters', 'c'),
(2016, 28, 'What happened to the students'' room on Sunday afternoon?', 'the police broke it', 'the police ruined it', 'burglars broke into it', 'two burglars broke it', 'c'),
(2016, 29, 'The burglars broke into the room when the students ....', 'were at a party', 'were taking a rest', 'were playing football', 'were at a football game', 'd'),
(2016, 30, 'The underlined phrase "broke into" means ....', 'broke forcefully', 'put into pieces', 'entered by force', 'came into', 'c'),
(2016, 31, 'The students seem to think that ....', 'they had locked their room', 'their boarding house was not safe', 'their boarding house was in a safe area', 'there would be a robbery', 'c'),
(2016, 32, 'The third paragraph is mainly about the fact that .... (Elephant)', 'elephants are strong', 'elephants can lift logs', 'elephants are servants', 'elephants are very useful', 'd'),
(2016, 33, 'Which of the following is NOT part of the elephant described in the first paragraph ?', 'it looks strange', 'it is heavy', 'it is wild', 'it has a trunk', 'c'),
(2016, 34, 'It is stated in the text that the elephant uses the trunk to do the following, EXCEPT ....', 'to eat', 'to drink', 'to push', 'to carry things', 'c'),
(2016, 35, 'The underlined word "peculiar" is close in meaning to ....', 'large', 'tough', 'strange', 'smooth', 'c'),
(2016, 36, 'Pernyataan berikut yang benar adalah ....', '17 - (-13) - 4 = 0', '-18 + (-2) + 13 = 7', '-25 - (-8) - 17 = -34', '12 + (-7) - 6 = 1', 'c'),
(2016, 37, 'Nilai dari 35 + 14 - 34 : 17 adalah....', '145', '246', '245', '345', 'c'),
(2016, 38, '(2⁴ × 2)³ : 2⁵ =', '2⁵', '2⁸', '2¹⁰', '2¹²', 'c'),
(2016, 39, '(5³ × 5⁴)² : 5⁶ =', '5⁶', '5⁸', '5¹⁶', '5¹⁸', 'b'),
(2016, 40, 'Hasil dari 11½ + 1⅓ - 2¼ =', '11 9/12', '10 9/12', '10 7/12', '11 7/12', 'c'),
(2016, 41, 'Dari himpunan di atas yang merupakan himpunan kosong adalah…', 'Himpunan A dan B', 'Himpunan B dan C', 'Himpunan A dan C', 'Himpunan A, B, dan C', 'c'),
(2016, 42, 'Banyaknya siswa yang tidak mengikuti ekstrakurikuler Pramuka dan PMR adalah .....', '3 orang', '5 orang', '4 orang', '6 orang', 'a'),
(2016, 43, 'Jarak sebenarnya dengan skala 1:40000 dan jarak peta 30 cm adalah....', '12 km', '1,2 km', '7,5 km', '0,75 km', 'a'),
(2016, 44, 'Sebuah peta pulau jawa dibuat dengan skala 1:1000000. Jarak sebenarnya jika jarak peta 18 cm adalah ....', '18 km', '180 km', '10 km', '100 km', 'b'),
(2016, 45, 'Pedagang membeli 25 bungkus roti Rp45.000, dijual Rp2.000/bungkus. Pedagang tersebut akan mengalami .....', 'Untung Rp200 per bungkus', 'Rugi Rp200 per bungkus', 'Untung Rp250 per bungkus', 'Rugi Rp200 per bungkus', 'a'),
(2016, 46, 'Dari gambar, diketahui perbandingan x : y adalah 2 : 7. Besar sudut x adalah........', '10°', '90°', '80°', '40°', 'd'),
(2016, 47, 'Dari gambar di samping, maka panjang AC adalah', '20 cm', '36 cm', '10 cm', '12 cm', 'a'),
(2016, 48, 'Trapesium ABCD sebangun dengan Trapesium EFGH, Berapa panjang EH?', '8 cm', '9 cm', '10 cm', '12 cm', 'b'),
(2016, 49, 'Dari gambar di samping, berapa panjang BC...', '12 cm', '9 cm', '8 cm', '12,5 cm', 'c'),
(2016, 50, 'Diketahui luas selimut sebuah tabung 1.650 cm². Jika tinggi tabung 25 cm, maka jari-jari tabung tersebut adalah', '21 cm', '10,5 cm', '14 cm', '7 cm', 'b'),
(2016, 51, 'Proses masuknya udara melalui saluran pernafasan yang tepat adalah . . . .', 'trakea - pulmo - bronkus - bronkiolus', 'trakea - bronkus - bronkiolus - pulmo', 'trakea - pulmo - bronkiolus - bronkus', 'trakea - bronkiolus - bronkus - pulmo', 'b'),
(2016, 52, 'Proses pertukaran udara pada paru-paru terjadi pada', 'alveolus', 'bronkus', 'bronkiolus', 'trakea', 'a'),
(2016, 53, 'Bagian otak yang berfungsi menjaga keseimbangan adalah . . . .', 'otak kecil', 'otak tengah', 'otak besar', 'sumsum lanjutan', 'a'),
(2016, 54, 'Berdasarkan sensus penduduk, dampak pertambahan jumlah penduduk adalah . . . .', 'kandungan CO2 di udara menurun', 'tercukupinya kebutuhan perumahan', 'naiknya kandungan oksigen di udara', 'areal hutan semakin sempit', 'd'),
(2016, 55, 'Komponen darah yang berperan dalam peristiwa berhentinya darah adalah . . . .', 'keping darah dan eritrosit', 'fibrinogen dan keping darah', 'plasma darah dan serum', 'serum dan fibrinogen', 'b'),
(2016, 56, 'Sebongkah es yang volumenya 70 cm³ dimasukkan ke dalam gelas ukur, jika es tersebut mencair akan menjadi air dengan volume...', 'lebih dari 70 cm³', 'tidak menentu', 'kurang dari 70 cm³', '70 cm³', 'c'),
(2016, 57, 'Gaya sebesar 45 N bekerja pada benda bermassa 5 kg di atas lantai licin. Setelah 6 detik jarak yang ditempuh adalah...', '160 m', '166 m', '164 m', '162 m', 'd'),
(2016, 58, 'Diketahui nada d : nada a = 27 : 40. Jika frekuensi nada a = 440 Hz, maka frekuensi nada d adalah . . . .', '729 Hz', '792 Hz', '297 Hz', '927 Hz', 'c'),
(2016, 59, 'Dua buah benda masing-masing 2 C dan 5 C menimbulkan gaya tolak sebesar 15 N. Besar medan listrik pada benda yang bermuatan 2 C adalah . . . .', '4,5 N/C', '3 N/C', '7,5 N/C', '30 N/C', 'c'),
(2016, 60, 'Untuk memindahkan muatan 75 Coulomb dengan potensial listrik 12 volt maka energi listrik yang dibutuhkan adalah . . . .', '6,25 Joule', '9000 joule', '900 Joule', '90 Joule', 'c'),
(2016, 61, 'Bahan yang sering digunakan dalam pembuatan pemutih pakaian adalah . . . .', 'Insektisida', 'natrium hipoklorit', 'natrium klorida', 'natrium klorida', 'b'),
(2016, 62, 'Pasangan unsur di bawah ini yang memiliki elektron valensi sama adalah….', '³Li dan ¹³Al', '¹¹Na dan ¹⁹K', '¹²Mg dan ³⁰Zn', '⁵B dan ²¹Sc', 'b'),
(2016, 63, 'Jika atom X yang mempunyai nomor atom 19 dituliskan konfigurasi elektronnya, maka atom X memiliki ciri ….', 'Elektron valensi 9, valensi 1', 'Elektron valensi 1, valensi 1', 'Elektron valensi 7, valensi 1', 'Elektron valensi 2, valensi 2', 'b'),
(2016, 64, 'Kegunaan protein dalam makanan terdapat pada nomor …. (makanan)', '1 dan 2', '3 dan 4', '2 dan 3', '2 dan 4', 'b'),
(2016, 65, 'Harga keempat bilangan kuantum elektron terakhir dari atom ³⁹S₁₆ adalah….', 'n=2; l=0; m=0; s=-½', 'n=3; l=1; m=-1; s=-½', 'n=3; l=1; m=0; s=-½', 'n=3; l=1; m=0; s=+½', 'c'),
(2016, 66, 'Yang termasuk kategori sebagai negara berkembang adalah …. (IPS)', 'Amerika Serikat, Perancis, Inggris', 'Jepang, Uni Soviet, Cekoslovakia', 'Selandia Baru, Kanada, Australia', 'Arab Saudi, Kuwait, Thailand', 'd'),
(2016, 67, 'Kerjasama ekonomi yang dilakukan oleh dua negara merupakan kerjasama …..', 'multilateral', 'bilateral', 'antar regional', 'Regional', 'b'),
(2016, 68, 'Organisasi regional yang didirikan pada 8 Agustus 1967 oleh Indonesia dan ke-4 negara lainnya adalah…', 'OPEC', 'APEC', 'ASEAN', 'MEE', 'c'),
(2016, 69, 'Salah satu dampak kerja sama ekonomi Internasional bagi Indonesia adalah meningkatkan produktivitas negara. Peningkatan produktivitas ini dapat mengurangi ...', 'pengangguran', 'pinjaman', 'devisa', 'pendapatan negara', 'a'),
(2016, 70, 'Organisasi negara-negara yang tidak berada di dalam naungan PBB adalah …….', 'WTO', 'UNDP', 'APEC', 'ILO', 'c'),
(2016, 71, 'Yang bukan merupakan kepentingan Indonesia untuk ikut serta dalam keanggotaan pada OPEC adalah untuk …', 'saling menguntungkan dalam memenuhi kebutuhan minyak dunia', 'menentukan jumlah produksi minyak', 'menghindari perang harga dalam pemasaran minyak', 'menciptakan kawasan regional yang stabil', 'd'),
(2016, 72, 'IGGI sebagai organisasi kelompok negara pemberi bantuan bagi Indonesia kemudian dibubarkan dan digantikan oleh Jepang berganti nama …. (CGI)', 'CGI', 'IMF', 'EEC', 'WTO', 'a'),
(2016, 73, 'Berikut ini yang bukan termasuk alasan bahwa Singapura termasuk kelompok negara maju adalah', 'memiliki tingkat pendapatan perkapita tinggi', 'komoditas ekspor berupa barang industri & jasa', '>80% penduduknya tinggal di daerah perkotaan', 'luas negaranya relatif kecil', 'd'),
(2016, 74, 'Yang disebut benua hitam adalah….', 'Benua Asia', 'Benua Afrika', 'Benua Eropa', 'Benua Amerika', 'b'),
(2016, 75, 'Negara di kawasan Asia Tenggara yang memiliki garis pantai terpanjang adalah …', 'Malaysia', 'Vietnam', 'Thailand', 'Indonesia', 'd'),
(2016, 76, 'Ada 2 negara yang tidak menanggapi aksi-aksi yang dilakukan rakyat Indonesia yang menuntut untuk kembali ke Negara Kesatuan. Dua negara tersebut adalah …', 'Negara Indonesia Timur dan Kalimantan', 'Negara Jawa Timur dan Negara Pasundan', 'Negara Sumatera Timur dan Negara Indonesia Timur', 'Negara Madura dan Negara Jawa Timur', 'c'),
(2016, 77, 'Dampak Serangan Umum 1 Maret 1949 yang menunjang perjuangan diplomasi adalah …', 'meningkatkan semangat juang TNI dalam pertempuran', 'menunjukkan bahwa TNI masih ada dan terorganisasi', 'menjadi landasan dibawanya masalah Indonesia dalam forum PBB', 'dapat dikuasai Yogyakarta selama 6 jam', 'b'),
(2016, 78, 'Mayoritas negara-negara maju berada di belahan bumi bagian …. (Utara)', 'Selatan', 'Utara', 'Timur', 'Tengah', 'b'),
(2016, 79, 'Sebagian besar penduduk di kawasan Asia Tenggara bermata pencaharian sebagai …', 'pedagang', 'petani', 'nelayan', 'pekerja tambang', 'b'),
(2016, 80, 'Dampak positif dari perubahan sosial budaya adalah', 'penemuan ilmu pengetahuan dan teknologi', 'sikap individualistik', 'gaya hidup yang meniru Barat', 'kesenjangan sosial', 'a'),
(2016, 81, 'Dalam taman Eden terdapat satu sungai yang terbagi menjadi 4 cabang, yaitu ...', 'Pison, Tigris, Efrat, Nil', 'Pison, Gihon, Tigris, Efrat', 'Gihon, Tigris, Galilea, Efrat', 'Tigris, Efrat, Gihon, Galilea', 'b'),
(2016, 82, 'Siapakah Isteri Ishak?', 'Rachel Anak Laban', 'Ribka Anak Nahor', 'Ribka anak Betuel', 'Sarah Anak Laban', 'c'),
(2016, 83, 'Siapakah anak – anak Yakub dari istrinya Lea?', 'Ruben, Simeon, Lewi, Yehuda, Dan, Naftali', 'Ruben, Simeon, Gad, Asyer, Isakhar, Zebulon', 'Ruben, Simeon, Lewi, Yehuda, Isakhar, Zebulon, Dina', 'Ruben, Simeon, Gad, Isakhar, Zebulon, Dina', 'c'),
(2016, 84, 'Tuhan mendatangkan 10 tulah kepada orang Mesir. Apakah tulah ke 4?', 'Katak', 'Nyamuk', 'Lalat Pikat', 'Penyakit Sampar pada ternak', 'c'),
(2016, 85, 'Dari keturunan siapakah Daud dan siapakah ayahnya?', 'Keturunan Benyamin, ayahnya Kish', 'Keturunan Yehuda, ayahnya Isai', 'Keturunan Yehuda, ayahnya Kish', 'Keturunan Benyamin, ayahnya Isai', 'b'),
(2016, 86, 'Siapakah orang yang sangat kaya di Maon dan siapakah isterinya yang dijadikan Isteri oleh Daud setelah ia mati?', 'Ahab, isterinya Isebel', 'Nabal, Isterinya Abigail', 'Uria, isterinya Batsyeba', 'Ahab, isterinya Abigail', 'b'),
(2016, 87, 'Siapakah yang dijuluki Nabi yang naik ke Sorga dengan kereta dan kuda yang berapi?', 'Nabi Nuh', 'Nabi Elia', 'Nabi Henokh', 'Nabi Elisa', 'b'),
(2016, 88, 'Berapa Jumlah kitab Perjanjian Lama dan Perjanjian Baru?', 'PL 39 dan PB 27', 'PL 40 dan PB 26', 'PL 37 dan PB 29', 'Tidak ada yang benar', 'a'),
(2016, 89, 'Siapakah murid Yesus yang pertama?', 'Yakobus anak Zebedeus dan Yohanes', 'Simon yang disebut Petrus dan Yakobus anak Zebedeus', 'Simon yang disebut Petrus dan Andreas saudaranya', 'Yakobus anak Zebedeus dan Yudas Iskariot', 'c'),
(2016, 90, 'Kitab Habakuk berada di urutan ke... dalam perjanjian lama.', '33', '35', '34', '36', 'b'),
(2016, 91, 'Terdapat dimanakah perikop, "Hari TUHAN"?', 'Maleakhi 3:1-6', 'Maleakhi 4:1-6', 'Maleakhi 2:1-7', 'Maleakhi 1:1-7', 'b'),
(2016, 92, 'Siapakah tokoh di Alkitab yang mencapai usia terlama?', 'Adam mencapai usia 969 tahun', 'Yared mencapai usia 996 tahun', 'Metusalah mencapai usia 969 tahun', 'Enos mencapai usia 996 tahun', 'c'),
(2016, 93, 'Di jaman siapakah orang mulai memanggil nama Tuhan?', 'Adam dan Hawa', 'Enos anak Set', 'Henokh anak Enos', 'Henokh anak Yared', 'b'),
(2016, 94, 'Menurut Kejadian 10:8-9, siapakah seorang pemburu gagah perkasa yang mula-mula berkuasa di bumi?', 'Yared anak Mahalaleel', 'Nimrod anak Yared', 'Kain anak Adam', 'Nimrod anak Kush', 'd'),
(2016, 95, 'Dalam kitab manakah yang menceritakan tentang adanya orang-orang raksasa di bumi?', 'Kejadian 6:4', 'Kejadian 6:14', 'Kejadian 4:6', 'Kejadian 14:6', 'a'),
(2016, 96, 'Siapakah Menteri Desa, Pembangunan, Daerah Tertinggal dan Transmigrasi?', 'Marwan Jafar', 'Jafar Marwan', 'Mulawarman Jafar', 'Munawar Jafar', 'a'),
(2016, 97, 'Yang diusulkan untuk mengganti Fahri Hamzah sebagai Wakil Ketua DPR RI adalah :', 'Ledia Hanifah', 'Mustafa Kamal', 'Lydia Hanifah', 'Hanifah Ledia', 'a'),
(2016, 98, 'Sesuai data terbaru dari Kementerian Agama RI, Propinsi Sulawesi Utara berada pada peringkat keberapa sebagai daerah indeks kerukunan tertinggi di Indonesia :', 'Kedua', 'Ketiga', 'Keempat', 'Pertama', 'd'),
(2016, 99, 'Peringkat Kedua daerah dengan indeks kerukunan tertinggi di Indonesia ditempati oleh propinsi', 'Nusa Tenggara Timur', 'DI Yogyakarta', 'Sulawesi Utara', 'Bali', 'a'),
(2016, 100, 'Wakil Ketua Komisi Pemberantasan Korupsi (KPK) adalah :', 'Saut Sumampouw', 'Saut Simatupang', 'Saut Situmorang', 'Saut Simorangkir', 'a'),
(2016, 101, 'Jabatan Perwira yang barusan tertangkap tangan berpesta narkoba adalah :', 'Dandim 1408 Makasar', 'Dandim 1408 Manado', 'Dandim 1408 Minahasa', 'Dandim 1408 Merauke', 'b'),
(2016, 102, 'Bandara yang anjungan keberangkatannya dihancurkan oleh bom bunuh diri ISIS :', 'Brussels, Belgia', 'Brussels, Bolivia', 'Changi, Singapura', 'Brussels, Belanda', 'a'),
(2016, 103, 'Presiden Ketujuh Republik Indonesia adalah', 'Susilo Bambang Yudhoyono', 'B. J. Habibie', 'Megawati Sukarnoputri', 'Joko Widodo', 'd'),
(2016, 104, 'Tempat kediamanan kepresidenan Korea Selatan dikenal dengan :', 'Orange House', 'Red House', 'Blue House', 'White House', 'c'),
(2016, 105, 'Menteri Pendidikan dan Kebudayaan Republik Indonesia :', 'Anes Baswedan', 'Aris Baswedan', 'Anis Baswedan', 'Anies Baswedan', 'd'),
(2016, 106, 'Apa nama skandal baru di dunia yang berkaitan dengan penghindaran pajak', 'Panama Gate', 'Panama affair', 'Panama Papers', 'Panama Tax Affair', 'c'),
(2016, 107, 'Siapakah Mantan Kapolda Metro Jaya yang dilantik menjadi Kepala Badan Nasional Penanggulangan Terorisme (BNPT) :', 'Irjen Tito Karnavian', 'AKBP Tito Karnavian', 'Irjen Tito Karni', 'Brigjen Tito Karnavian', 'a'),
(2016, 108, 'Propinsi terbaru di Indonesia adalah :', 'Banten', 'Maluku Utara', 'Bangka Belitung', 'Kalimantan Utara', 'd'),
(2016, 109, 'Berikut adalah organisasi dunia dimana Indonesia menjadi anggotanya kecuali :', 'OKI', 'OPEC', 'APEC', 'Semua Salah', 'b'),
(2016, 110, 'Presiden Baru Myanmar adalah', 'Aung San Suu Kyi', 'Myint Swe', 'Htin Kyaw', 'Henry Van Thio', 'c'),
(2016, 111, 'Jika J. P. Riedel melaksanakan tugas pelayanan di Tondano dari Tahun 1829-1860, maka J. G. Schwarz melaksanakan tugas pelayan di Kakas dan Langowan pada tahun berapa :', '1829 - 1860', '1830 – 1850', '1831-1850', '1830-1860', 'c'),
(2016, 112, 'Ketua Sinode GMIM yang kedua adalah :', 'Ds. E. A. A. De Vreede', 'Ds. H. H. van Herwerden', 'Ds. E. A. A. De Veerde', 'Ds. C. D. Buenk', 'b'),
(2016, 113, 'Ketua Majelis Pertimbangan Sinode GMIM Periode 2014-2018 adalah :', 'Pdt. DR. A. O. Supit', 'Tidak Ada Yang Benar', 'Pdt. P. M. Tampi, STh, MSi', 'Pnt. DR. Ir. G. S. V. Lumentut, SH, DEA', 'd'),
(2016, 114, 'Berikut ini adalah anggota Badan Pengawas Perbendaharaan Sinode periode 2014-2018, KECUALI :', 'Prof. DR. Stans L.H.V.J. Lapian, SE, MEc', 'DR. Ficke Ranti-Rawung, MSc', 'DR. Tommy Parengkuan, SE, MS', 'Alwin Ch. Rondonuwu, SE, MBA, CPHR', 'b'),
(2016, 115, 'Sekretaris BPMS GMIM Periode 2014 – 2018 pada periode sebelumnya menjabat sebagai :', 'Sekretaris Departemen BPMS', 'Anggota BPMS', 'Wakil Sekretaris BPMS', 'Ketua Wilayah', 'c'),
(2016, 116, 'Berapakah jumlah keanggotaan Komisi Pelayanan Remaja Sinode GMIM periode 2010-2014', '8 orang', '15 orang', '14 Orang', '9 orang', 'c'),
(2016, 117, 'Wakil Ketua BPMS GMIM Bidang Pengembangan Sumber Daya periode 2014-2018 adalah :', 'Pdt. Dr. Hein Arina', 'Pdt. DR. Arthur R. Rumengan, MTh, MPdK', 'Pdt. Petra J. Rembang, MTh', 'Pdt. J. J. Plangiten, STh', 'a'),
(2016, 118, 'Toga adalah pakaian jabatan Pendeta. Toga apakah yang melambangkan persekutuan dengan kematian dan kebangkitan Kristus :', 'Toga ungu', 'a dan d benar', 'Toga Putih', 'Toga Hitam', 'c'),
(2016, 119, 'Jika anggota Sidi Jemaat melayani ibadah/firman maka ia menggunakan stola :', 'Stola sesuai tahun gerejawi', 'Stola putih', 'Stola warna merah dengan salib warna kuning', 'a dan c benar', 'a'),
(2016, 120, 'Jika pada periode 2010 – 2014 jumlah BPMS GMIM adalah 14 orang, berapa orangkah pada periode sekarang ini :', '21 orang', '15 orang', '14 orang', '12 orang', 'b'),
(2016, 121, 'Yang pernah menjabat Ketua Sinode dua periode adalah :', 'Ds. A. Z. R. Wenas', 'Ds. E. A. A. De Vreede', 'Ds. M. Sondakh', 'Semua salah', 'a'),
(2016, 122, 'Ketua Sinode GMIM Periode 1990-1995 adalah :', 'Pdt. DR. W. A. Roeroe', 'Pdt. DR. A. F. Parengkuan', 'Pdt. DR. A. O. Supit', 'Pdt. K. H. Rondo, MTh', 'd'),
(2016, 123, 'Anggota BPMS GMIM Periode 2000-2005 yang adalah Ketua Komisi Remaja Sinode GMIM adalah :', 'Pnt. Drs. Jemmy Ch. Mamahit', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. Drs. Jantje W. Sajow, M.Si', 'Pnt. Drs. Jacobus Wowor', 'c'),
(2016, 124, 'Dari 5 lambang Komisi Pelayanan Kategorial, Lambang Komisi Apakah yang memiliki ayat Alkitab :', 'Komisi Pelayanan Pria Kaum Bapa', 'Komisi Pelayanan Remaja', 'Komisi Pelayanan Wanita Kaum Ibu', 'Komisi Pelayanan Anak', 'd'),
(2016, 125, 'Tema Bulanan sesuai MTPJ Bulan April 2016 adalah :', 'Berjalan Bersama Yesus Yang telah bangkit', 'Diutus untuk membebaskan', 'Kebangkitan Yesus Mengubah Manusia', 'Pemulihan Dunia', 'a'),
(2016, 126, 'Kapankah secara resmi Komisi Pelayanan Remaja Sinode GMIM Berdiri sendiri :', 'Sabtu, 28 Januari 1990', 'Minggu, 28 Januari 1990', 'Jumat, 28 Januari 1990', 'Senin, 28 Januari 1990', 'a'),
(2016, 127, 'Orang Kedua yang menjadi Ketua Komisi Pelayanan Remaja Sinode GMIM adalah :', 'Pnt. Drs. Jemmy Mamahit', 'Pnt. Jacobus Wowor', 'Pnt. Drs. J. W. Sajow, M.Si', 'Pnt. Ir. Dwight Moody Rondonuwu', 'c'),
(2016, 128, 'Serah terima Pelayanan Komisi Pelayanan Remaja Sinode GMIM dari Periode 2000-2004 kepada Periode 2005-2010 dilaksanakan di :', 'Imanuel Bahu Wil. Manado Barat Daya', 'Imanuel Maumbi Wil. Kalawat I', 'Imanuel Aertembaga Wil. Bitung II', 'Imanuel Kawangkoan Bawah Wil. Amurang II', 'b'),
(2016, 129, 'Dimana dilaksanakan Pemilihan Komisi Remaja yang hasilnya di anulir oleh Sidang Sinode :', 'Winuri, Wilayah Likupang I', 'Winuri, Wilayah Likupang 2', 'Winuri, Wilayah Likupang', 'Getsemani, Sea Wilayah Pineleng', 'a'),
(2016, 130, 'Berikut ini adalah anggota Komisi Pelayanan Remaja Sinode GMIM periode 2014-2018 yang baru pertama kali kecuali :', 'Pnt. Melky R. Pattiwael, SIK. MSI', 'Pnt. Santi G. Luntungan, ST', 'Pnt. Cerry Lumangkan', 'Pnt. Charles Mamelas', 'c'),
(2016, 131, 'Kepanjangan yang benar dari Bidang P3SDM adalah :', 'Pembinaan, Pengkaderan dan Pengembangan Sumber Daya Manusia', 'Pemberdayaan, Pembinaan dan Pengembangan Sumber Daya Manusia', 'Pengkaderan, Pemberdayaan dan Pengembangan Sumber Daya Manusia', 'Pengembangan, Pembinaan dan Pengkaderan Sumber Daya Manusia', 'a'),
(2016, 132, 'Tahun Berapakah Perkembangan Karya Remaja Sinode GMIM Pertama Kali digelar, walau Komisinya masih bersama dengan Komisi Pelayanan Pemuda :', '1980', '1983', '1990', '1981', 'b'),
(2016, 133, 'Melaksanakan kegiatan Pelatihan & Workshop Kelompok Kecil Penelaan Alkitab (PA) adalah program dari Kelompok Kerja Bidang :', 'OM', 'P3SDM', 'Pelsis', 'API MISI', 'a'),
(2016, 134, 'Di wilayah manakah dilaksanakan kegiatan Hari Persatuan Remaja GMIM tahun 2016 :', 'Kalawat I', 'Kalawat Raya', 'Kalawat II', 'Minawerot', 'c'),
(2016, 135, 'Kegiatan Pesta Seni Remaja GMIM tahun 2015 dilaksanakan pada :', 'September 2015 di Wilayah Manado Malalayang', 'September 2015 di Wilayah Mandolang', 'September 2015 di Wilayah Manado Malalayang Barat', 'Semua jawaban salah', 'b'),
(2016, 136, 'Dimanakah Pemilihan KPRS GMIM Periode 2010 – 2014 dilaksanakan :', 'GMIM Getsemani Sea Wil. Pineleng', 'GMIM Getsemani Senduk Wilayah Tanahwangko I', 'GMIM Elim Pangu Wilayah Ratahan', 'GMIM Getsemani Senduk Wilayah Tanahwangko II', 'd'),
(2016, 137, 'Di Wilayah manakah Hari Persatuan Remaja GMIM tahun 2017 akan dilaksanakan :', 'Wilayah Tombatu', 'Wilayah Tombatu Barat', 'Wilayah Tombatu Selatan', 'Wilayah Tombatu Timur', 'a'),
(2016, 138, 'Yang terpilih sebagai Remaja Teladan Putri tahun 2015 adalah :', 'Wulan Pusung', 'Elizabet Kainde', 'Vanessa Monintja', 'Hana Imbar', 'b'),
(2016, 139, 'Grand Final Pemilihan Remaja Teladan Sinode GMIM tahun 2013 di gelar di :', 'Ballroom Peninsula Hotel Manado', 'Auditorium Kantor Gubernur Manado', 'Auditorium Bukit Inspirasi Tomohon', 'Wale Ne Tou Tondano', 'c'),
(2016, 140, 'Pada Periode 2005-2010 dalam keanggotaan Komisi Pelayanan Remaja Sinode GMIM ada seorang Pendeta yaitu :', 'Pdt. Helena Palit-Aspan, STh', 'Pdt. Ferdinand Sasuwuk, STh', 'Pdt. Edward Timbuleng, STh', 'Pdt. Robby Kawengan, STh, SPd', 'a'),
(2016, 141, 'Berikut adalah tempat Lokakarya Penyusunan Konsep Tata Gereja 2007, Kecuali', 'GMIM Sion Pinasungkulan Wil. Modoinding', 'House Of Blessing Koka Wil. Kembes', 'GMIM Sentrum Wil. Manado Sentrum', 'GMIM Sentrum Tatelu, Wil. Tatelu', 'c'),
(2016, 142, 'Tata Dasar pada Tata Gereja GMIM Tahun 2007 terdiri dari :', '12 BAB', '13 BAB', '14 BAB', '15 BAB', 'd'),
(2016, 143, 'Sesuai Tata Dasar pada Tata Gereja tahun 2007 GMIM dimandirikan dari Gereja :', 'Gereja Belanda', 'Gereja Kristen Indonesia', 'Gereja Protestan Indonesia', 'Gereja Protestan di Indonesia', 'd'),
(2016, 144, 'Peraturan Tentang Jemaat BAB VIII Pelayanan Kategorial dalam Tata Gereja 2007 yang diadendum hanyalah pada ayat manakah :', 'Ayat 2', 'Ayat 3', 'Ayat 4', 'Ayat 5', 'c'),
(2016, 145, 'Hal apakah yang diperbaiki pada Peraturan tentang Jemaat BAB VIII Pelayanan Kategorial Pasal 27 ayat 1 – 5 sesuai Adendum Tata Gereja Tahun 2012', 'Kata usia 364 hari dihapus', 'Pengurus Komisi Pelayanan Kategorial harus memiliki sertifikat', 'Semua Benar', 'Semua Salah', 'c'),
(2016, 146, 'Sesuai Adendum Tata Gereja 2012 (Peraturan Tentang Jemaat Pasal 37 ayat 2), Pengisian lowong Komisi Pelayanan Kategorial Jemaat dilaksanakan oleh :', 'BPMJ', 'Panitia Pemilihan', 'Komisi yang bersangkutan', 'a, b dan c benar', 'd'),
(2016, 147, 'Pelaksanaan Tugas Pelayanan Kategorial Wilayah :', 'Peraturan Tentang Wilayah, Bab VII Pasal 16', 'Peraturan Tentang Wilayah, Bab VII Pasal 17', 'Peraturan Tentang Wilayah, Bab VII Pasal 18', 'Peraturan Tentang Wilayah, Bab VII Pasal 19', 'a'),
(2016, 148, 'Berikut adalah syarat menjadi ketua Komisi Pelayanan Kategorial Jemaat, kecuali :', 'Berusia diatas 25 Tahun', 'anggota Sidi Jemaat', 'Memiliki sertifikat pelatihan', 'memiliki pengalaman pelayanan', 'a'),
(2016, 149, 'Tata Gereja GMIM 2007 terdiri dari :', '1 Tata Dasar, 8 Peraturan', '1 Tata Dasar, 7 Peraturan', '1 Tata Dasar, 9 Peraturan', '1 Tata Dasar, 10 Peraturan', 'a'),
(2016, 150, 'Pemilihan Komisi Pelayanan Kategorial pada Wilayah Pemekaran, sesuai Adendum Tata Gereja 2012 dilaksanakan pada :', 'Pada Saat ditetapkan oleh BPMS', 'Pada Saat menjelang Peresmian oleh BPMS', 'Pada Saat setelah peresmian oleh BPMS', 'Terserah kemauan wilayah pemekaran', 'c');
