-- TAHUN 2019 - Soal 1 s.d 50
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2019, 1, 'Judul Perikop Kepercayaan Abraham diuji terdapat dalam kitab dan ayat mana dalam Alkitab :', 'Kejadian 22:1-24', 'Kejadian 22:1-19', 'Kejadian 22:19-24', 'Kejadian 21:1-19', 'b'),
(2019, 2, 'Lengkapi Nats: "Karena semua orang telah berdosa dan telah kehilangan ... Allah" (Roma 3:23)', 'Kuasa', 'Kemuliaan', 'Kasih', 'Berkat', 'b'),
(2019, 3, 'Lengkapi Nats: "Dan Yesus semakin bertambah ..., dan bertambah hikmatnya dan besarnya dan makin dikasihi ... dan ..."', 'Besar, Tuhan, dan Allah', 'Kuat, Tuhan, dan Dunia', 'Besar, Tuhan, dan Manusia', 'Kuat, Manusia, dan Tuhan', 'c'),
(2019, 4, 'Terdapat dimanakah pembacaan Doa Bapa Kami ?', 'Matius 6:9-11', 'Matius 6:9-13', 'Matius 9:6-10', 'Matius 9:6-13', 'b'),
(2019, 5, 'Sebutkan nama-nama sungai yang terdapat dalam taman Eden', 'Pison, tigeris, efrat, gihon', 'Pison, tigris, efrata, gihon', 'Pison, tigris, efrat, gihon', 'Pison, tigris, eferat, gihon', 'c'),
(2019, 6, 'Apakah arti "Eli, Eli, lama sabakhtani"?', 'Allah, mengapa kau meninggalkan aku', 'Bapa-Ku, Bapa-Ku, mengapa Engkau meninggalkan aku', 'Allah-Ku, Allah-Ku, mengapa Kau meninggalkanKu', 'Bapa-Ku, mengapa Engkau meninggalkan aku', 'c'),
(2019, 7, 'Terdapat dimanakah Hukum Kasih ?', 'Matius 23:37-40', 'Matius 22:37-40', 'Matius 21:37-40', 'Matius 20:37-40', 'b'),
(2019, 8, 'Tema bulan Maret dan Tema Mingguan 17-23 Maret 2019 adalah?', 'Akulah yang awal dan yang akhir, dan ketaatan paripurna', 'Ketaatan paripurna, dan Akulah yang awal dan yang akhir', 'Tuhan adalah Alfa dan Omega, dan Ketaatan Paripurna', 'Dialah Tuhan yang awal dan yang akhir, dan kesetiaan', 'a'),
(2019, 9, 'Dibawah adalah tugas Gereja kecuali :', 'Bersaksi', 'Bersekutu', 'Memberitakan Injil', 'Melayani', 'b'),
(2019, 10, 'Riedel dan Schwarz adalah Misionaris yang diutus oleh?', 'NSG', 'NZG', 'NGZ', 'NGS', 'b'),
(2019, 11, 'Pengertian & kualifikasi Remaja yang adalah anggota GMIM, menurut Tata Gereja GMIM 2016 terdapat pada :', 'BAB VIII. Pasal 26 ayat 4a', 'BAB VIII. Pasal 26 ayat 4b', 'BAB VIII. Pasal 26 ayat 4c', 'BAB VIII. Pasal 26 ayat 4d', 'd'),
(2019, 12, 'Menurut Tata Gereja GMIM 2016, yang dimaksud remaja yang adalah anggota GMIM adalah :', 'Berusia 12-16 tahun', 'Belum mengikuti kegiatan pemuda dan tidak lagi mengikuti kegiatan anak-anak', 'Duduk di SLTP dan awal SLTA', 'Jawaban a,b,c benar', 'd'),
(2019, 13, 'Visi remaja GMIM adalah :', 'Remaja bagi Kristus', 'Remaja teladan GMIM', 'Remaja yang kreatif & inovatif', 'Remaja yang berintegritas', 'a'),
(2019, 14, 'Misi remaja GMIM adalah :', 'Remaja yang berakar dalam Kristus', 'Remaja yang bertumbuh dalam Kristus', 'Remaja yang berbuah dalam Kristus', 'Remaja yang berakar, bertumbuh dan berbuah dalam Kristus', 'd'),
(2019, 15, 'Model remaja GMIM yang diharapkan adalah menjadi remaja seperti Yesus (remaja Kristus) seperti yang terdapat pada :', 'Lukas 2:50', 'Lukas 2:51', 'Lukas 2:52', 'Lukas 2:53', 'c'),
(2019, 16, 'Makna visi "Teens for Christ" adalah :', 'Remaja yang telah mengalami dan menghayati hidup baru dalam Kristus', 'Remaja yang hidupnya hanya berpusatkan pada Kristus', 'Remaja yang berkomitmen hidup dalam karakter & keteladanan Kristus', 'Jawaban a,b,c benar', 'd'),
(2019, 17, 'Program pemuridan KPRS dikenal dengan istilah KB3 yaitu :', 'Kelompok Berakar, Bertumbuh, Berbuah', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kesatuan Berakar, Bertumbuh, Berbuah', 'Kerjasama Berakar, Bertumbuh, Berbuah', 'b'),
(2019, 18, 'Setiap tahun dilaksanakan program LKRG, apa kepanjangannya ?', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kader Remaja Gereja', 'Latihan Komunikasi Remaja Gereja', 'Latihan Kapasitas Remaja Gereja', 'b'),
(2019, 19, 'Lagu "Menjadi Teladan" (Cipt. Kak Moody Rondonuwu), dinyanyikan pertama kali pada pemilihan Remaja Teladan Sinode GMIM tahun :', '2014', '2015', '2016', '2017', 'b'),
(2019, 20, 'Kepemimpinan Gereja Masehi Injili di Minahasa menganut sistem :', 'Presbiterial sinodal', 'Episkopal', 'Kongregasional', 'Jawaban a,b,c benar', 'a'),
(2019, 21, 'Struktur GMIM menurut tata gereja GMIM 2016, ditata dalam aras :', 'Kolom, Jemaat, Wilayah dan Sinode', 'Jemaat, Wilayah dan Sinode', 'Jemaat, Wilayah, Rayon dan Sinode', 'Sinode, Wilayah dan Jemaat', 'b'),
(2019, 22, 'Remaja GMIM saat ini sedang berada pada era milenial/post-milenial dalam pusaran generasi Revolusi Industri ke :', '1.0', '2.0', '3.0', '4.0', 'd'),
(2019, 23, 'Berikut adalah nama-nama Bidang KPRS GMIM Periode 2018-2022, KECUALI?', 'Bidang Pengembangan Minat dan Bakat (PMB)', 'Bidang Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia (P3SDM)', 'Bidang Pelayanan Siswa, Pengembangan, Pengendalian Keuangan (PSPPK)', 'Bidang Penelitian dan Pengembangan (LITBANG)', 'c'),
(2019, 24, 'Berapakah jumlah bidang pada KPRS GMIM Periode ini?', '7', '10', '9', '11', 'c'),
(2019, 25, 'Berikut ini adalah beberapa model Remaja sesuai Lukas 2:52, kecuali:', 'Aspek Fisik', 'Aspek Biologis', 'Aspek Sosial', 'Aspek Intelektual', 'b'),
(2019, 26, 'Gagasan pokok teks tentang pencabutan subsidi BBM adalah ....', 'Kenaikan harga BBM disebabkan kesalahan pemerintah', 'Kenaikan harga BBM berdampak negatif terhadap masyarakat', 'Pengangguran disebabkan kenaikan harga BBM', 'Dampak kenaikan harga BBM saat ini', 'b'),
(2019, 27, 'Paragraf tentang Taufik Ismail menggambarkan bahwa ia adalah ...', 'penyair dengan puisi-puisi sosial yang tajam', 'penyair yang tidak peduli pada capaian estetika', 'penyair yang peduli pada perang dan masalah ideologi pendidikan', 'Semua jawaban benar', 'd'),
(2019, 28, 'Kata yang tepat untuk melengkapi kalimat rumpang "Dari tahun ke tahun (.....) koperasi sekolah kami mengalami peningkatan" adalah ....', 'agunan', 'asuransi', 'pajak', 'omzet', 'd'),
(2019, 29, 'Manakah di antara deretan kalimat perintah berikut yang sopan?', 'Ia membantu membawakan tas adiknya', 'Dik, mengapa kamu menangis?', 'Mengapa engkau datang ke sini?', 'Ia mempersilakan tamu itu untuk duduk', 'd'),
(2019, 30, 'Karen ...... to go to the cinema with us because she''d already seen the movie.', 'didn''t wanted', 'wanted', 'didn''t want', 'doesn''t want', 'c'),
(2019, 31, 'Who is that woman? ...... her before, but I can''t remember where.', 'I''ve see', 'I saw', 'I see', 'I''ve seen', 'd'),
(2019, 32, 'We weren''t hungry. ......', 'We''d just had lunch.', 'We''ve just had lunch.', 'We just have lunch.', 'We just had lunch.', 'a'),
(2019, 33, 'Emily: Have you .... Tom? Stevy: Yes, I have.', 'See', 'Saw', 'Seen', 'Sees', 'c'),
(2019, 34, 'Pekerjaan membangun sebuah warung dapat diselesaikan oleh Pak Zulkifli dalam 30 hari, sementara Pak Sahlan dalam 20 hari. Jika mereka bekerja bersama, waktu yang diperlukan adalah ....', '50 hari', '25 hari', '12 hari', '10 hari', 'c'),
(2019, 35, 'Harga pembelian 1,5 lusin buku Rp72.000,00. Buku tersebut dijual eceran dengan harga Rp5.000,00 tiap buah. Persentase untung atau ruginya adalah ....', 'untung 20%', 'rugi 20%', 'untung 25%', 'rugi 25%', 'c'),
(2019, 36, 'Berapa banyak rusuk yang dimiliki kubus?', '12 buah', '16 buah', '32 buah', '10 buah', 'a'),
(2019, 37, '2 4 6 8 10 ...', '12', '22', '44', '55', 'a'),
(2019, 38, 'Interaksi yang dikategorikan simbiosis mutualisme ditunjukkan oleh...', '1 dan 2', '1 dan 3', '3 dan 4', '2 dan 4', 'c'),
(2019, 39, 'Jika musang diburu sehingga populasinya berkurang, dampak yang akan terjadi adalah...', 'Populasi rumput dan marmot akan meningkat', 'Populasi harimau dan marmot akan meningkat', 'Populasi rumput, marmot dan harimau akan meningkat', 'Populasi rumput dan harimau akan menurun', 'd'),
(2019, 40, 'Salah satu penyebab global warming adalah efek rumah kaca yang ditimbulkan oleh...', 'Penggunaan gas CFC untuk AC dan kulkas', 'Penggunaan kaca sebagai bahan bangunan', 'Pembangunan gedung pencakar langit', 'Polusi udara oleh gas CO2 dari pembakaran minyak', 'd'),
(2019, 41, 'Persamaan dan perbedaan antara belalang dan laba-laba dalam tabel berikut yang benar adalah....', 'Kaki berbuku-buku : Belalang berkaki 6, Laba-laba berkaki 8', 'Tubuh dibedakan kepala-dada dan perut : Belalang mempunyai kaki di kepala-dada, laba-laba mempunyai kaki di bagian perut', 'Tubuh simetris bilateral : Belalang tidak punya rongga tubuh, laba-laba punya rongga tubuh', 'Respirasi dengan sistem trakea : Belalang sistem peredaran darah terbuka, laba-laba tertutup', 'a'),
(2019, 42, 'Tulisan tangan naskah teks proklamasi merupakan konsep yang ditulis di atas secarik kertas oleh....', 'Drs Moh Hatta', 'Ahmad Subardjo', 'Sukarni', 'Ir. Soekarno', 'd'),
(2019, 43, 'Naskah teks proklamasi yang telah mengalami perubahan oleh karena berbagai pertimbangan selanjutnya diketahui oleh....', 'Sayuti Melik', 'Ahmad Subarjo', 'Mr. Muh Yamin', 'Sukarni', 'a'),
(2019, 44, 'Munculnya negara-negara adikuasa disebabkan oleh...', 'faktor kekuatan militer dari suatu negara', 'faktor kekuasaan dari suatu negara', 'faktor keberhasilan suatu negara mempengaruhi negara lain', 'faktor keberhasilan suatu negara menguasai negara lain', 'a'),
(2019, 45, 'Makna proklamasi 17 Agustus 1945 bagi bangsa Indonesia adalah.....', 'dunia mengakui kemerdekaan Indonesia', 'seluruh rakyat Indonesia menyambutnya dengan gembira', 'keinginan Belanda untuk kembali menjajah bangsa Indonesia', 'adanya tekanan dari pemerintah pendudukan Jepang', 'b'),
(2019, 46, 'Berapakah jumlah Kabupaten/Kota yang ada di Provinsi Sulawesi Utara?', '14', '15', '16', '17', 'b'),
(2019, 47, 'Pada Pemilihan Umum 17 April 2019, Rakyat Indonesia akan memilih dibawah ini, Kecuali :', 'Presiden dan Wakil Presiden', 'Gubernur dan Wakil Gubernur', 'Anggota DPR RI dan DPD RI', 'Anggota DPRD Provinsi dan DPRD Kabupaten/Kota', 'b'),
(2019, 48, 'Dimanakah kota tempat kejadian penembakan dua Masjid di Selandia Baru pada tanggal 15 Maret 2019:', 'Auckland', 'Wellington', 'Christchurch', 'Queenstown', 'c'),
(2019, 49, 'Semboyan "Si Tou Timou Tumou Tou" dicetuskan oleh:', 'S.H Sarundajang', 'A.J Sondakh', 'G.S.S.J Ratulangi', 'Olly Dondokambey', 'c'),
(2019, 50, 'Hari Ulang Tahun ke-55 Provinsi Sulawesi Utara jatuh pada tanggal?', '22 September 2019', '23 September 2019', '24 September 2019', '25 September 2019', 'b');
