-- TAHUN 2014 - Soal 1 s.d 150
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2014, 1, 'Siapa Sekertaris Jenderal Perserikatan Bangsa-bangsa sekarang ini?', 'Barack Obama', 'Ban Ki-moon', 'Javier Peres de Cuellar', 'Boutros Boutros Ghali', 'b'),
(2014, 2, 'Siapa Perdana Menteri Israel sekarang ini?', 'Silvio Berlusconi', 'Simon Peres', 'Benyamin Natanyahu', 'Havier Peres de Cueler', 'c'),
(2014, 3, 'Siapa wakil presiden Amerika Serikat Sekarang ini?', 'Jimmy Carter', 'Joe Biden', 'Barak Obama', 'John Kerry', 'b'),
(2014, 4, 'Apa artinya Apartheid?', 'Salah satu jenis mobil Toyota', 'Persamaan Hak dan warna kulit', 'Sistem pemisahan Ras dan perbedaan warna kulit', 'Hak asasi manusia', 'c'),
(2014, 5, 'Siapa tokoh Anti Apartheid di Afrika Selatan yang pernah di penjara tetapi pada akhirnya menjadi presiden di negaranya?', 'Moammar Kadafi', 'Barack Obama', 'Ayathollah Khomeini', 'Nelson Mandela', 'd'),
(2014, 6, 'Apa artinya Rasialisme?', 'Penganut aliran perbedaan ras', 'Penganut aliran antikris', 'Anti Perbedaan Agama', 'Semua salah', 'a'),
(2014, 7, 'Turki termasuk benua apa?', 'Eropa', 'Amerika', 'Asia', 'Australia', 'c'),
(2014, 8, 'Lee Kwan Yew adalah ahli ekonomi yang pernah menjadi Pemimpin di Negara Mana?', 'Malaysia', 'Singapura', 'Korea Selatan', 'Hongkong', 'b'),
(2014, 9, 'Politik Luar Negeri Indonesia ialah apa?', 'Bebas Aktif', 'Bebas Rahasia', 'Ekslusif', 'Inklusif', 'a'),
(2014, 10, '2 Pebulutangkis Indonesia yang sekarang ini adalah pasangan suami - isteri Peraih Medali Emas Olimpiade ialah:', 'Icku Sugiarto dan Imelda', 'Yayuk Basuki dan Sugiono', 'Liem Swe King dan Susi Susanti', 'Allan Budikusuma dan Susi Susanti', 'd'),
(2014, 11, 'Siapakah Menteri Koordinator Ekonomi dan Keuangan Indonesia sekarang ini?', 'Dahlan Iskan', 'Chatib Basri', 'Hatta Radjasa', 'Cairul Tanjung', 'b'),
(2014, 12, 'Siapa Menteri Luar Negeri Indonesia sekarang ini?', 'Alwi Shihab', 'Martty Natalegawa', 'Dahlan Iskan', 'Muhammad Nuh', 'b'),
(2014, 13, 'Bagaimana cara mengurangi jumlah penduduk di daerah yang padat penduduknya?', 'Urbanisasi', 'Transmigrasi', 'Pembuatan Rumah Susun', 'Pembangunan Perumahan Murah', 'b'),
(2014, 14, 'Siapa ketua Komisi Pemberantasan Korupsi tahun 2010 - 2011?', 'Abraham Samad', 'Busro Muqodas', 'Taufiqrachman Ruki', 'Antasari', 'a'),
(2014, 15, '“Kita hidup untuk menghidupkan orang lain” adalah semboyan dari siapa dan bahasa daerahnya apa:', 'E E Mangindaan dengan bahasa daerah Sitou Timou Tumou Tou', 'A J Sondakh dengan bahasa daerah Gotong Royong', 'Sam Ratulangie dengan bahasa daerah Sitou Timou Tumou Tou', 'S H Sarundajang dengan bahasa daerah I Yayat U Santi', 'c'),
(2014, 16, 'Tuhan mendatangkan 10 tulah kepada orang Mesir. Apakah tulah ke 4?', 'Katak', 'Nyamuk', 'Lalat Pikat', 'Penyakit Sampar pada ternak', 'c'),
(2014, 17, 'Dari keturunan siapakah Daud dan siapakah ayahnya?', 'Keturunan Benyamin, ayahnya Kish', 'Keturunan Yehuda, ayahnya Isai', 'Keturunan Yehuda, ayahnya Kish', 'Keturunan Benyamin, ayahnya Isai', 'b'),
(2014, 18, 'Siapakah orang yang sangat kaya di Maon dan siapakah isterinya yang dijadikan Isteri oleh Daud setelah ia mati?', 'Ahab, isterinya Isebel', 'Nabal, Isterinya Abigail', 'Uria, isterinya Batsyeba', 'Ahab, isterinya Abigail', 'b'),
(2014, 19, 'Siapakah murid Yesus yang pertama?', 'Yakobus anak Zebedeus dan Yohanes', 'Simon yang di sebut Petrus dan Yakobus anak Zebedeus', 'Simon yang di sebut Petrus dan Andreas saudaranya', 'Yakobus anak Zebedeus dan Yudas Iskariot', 'c'),
(2014, 20, 'Kitab Habakuk berada di urutan ke... dalam perjanjian lama.', '33', '34', '35', '36', 'c'),
(2014, 21, 'Terdapat dimanakah firman Tuhan yang berbunyi, “Diberkatilah orang yang mengandalkan Tuhan, yang menaruh harapannya pada Tuhan.”?', 'Yeheskiel 7 : 17', 'Yeremia 17 : 7', 'Yeheskiel 17 : 7', 'Yeremia 7 : 17', 'b'),
(2014, 22, 'Apa perikop Matius 1 : 18 – 25?', 'Kelahiran Yesus Kristus', 'Silsilah Yesus Kristus', 'Orang-orang majus dari Timur', 'Semua pilihan salah', 'a'),
(2014, 23, 'Siapakah ayah dan ibu dari Yohanes Pembaptis?', 'Elkana dan Hanna', 'Zakharia dan Hanna', 'Zakharia dan Elisabeth', 'Elkana dan Elisabeth', 'c'),
(2014, 24, 'Siapakah Murid Tuhan Yesus yang adalah Pemungut cukai dan seorang dokter?', 'Pemungut cukai Andreas dan dokter adalah Lukas', 'Pemungut cukai Lewi dan dokter adalah Lukas', 'Pemungut cukai Lewi dan dokter adalah Yakobus', 'Pemungut cukai Yakobus dan dokter adalah Lukas', 'b'),
(2014, 25, 'Terdapat di manakah firman Tuhan, "Jangan seorangpun menganggap engkau rendah karena kau muda. Jadilah teladan bagi orang-orang percaya..."?', 'II Timotius 4 : 12', 'II Timotius 12 : 4', 'I Timotius 4 : 12', 'I Timotius 12 : 4', 'c'),
(2014, 26, 'Siapakah Yang menulis Surat kepada jemaat Korintus dan Efesus?', 'Paulus kepada Jemaat Korintus dan Petrus kepada Jemaat Efesus', 'Petrus kepada Jemaat Korintus dan Jemaat Efesus', 'Petrus kepada Jemaat Korintus dan Paulus kepada Jemaat Efesus', 'Paulus kepada Jemaat Korintus dan Jemaat Efesus', 'd'),
(2014, 27, 'Apa Nama Kitab dalam perjanjian baru yg tersedikit jumlah pasalnya dan berapa jumlah pasalnya?', 'Titus dan Yudas dengan jumlah 2 pasal', 'Filemon dan Yudas dengan jumlah 1 Pasal', 'Titus dan Filemon dengan jumlah 2 pasal', 'Filemon dan Titus dengan jumlah 1 Pasal', 'b'),
(2014, 28, 'Siapakah Kepala Gereja Masehi Injili di Minahasa periode 2010 - 2014?', 'Pdt. Dr. Albet O Supit, M.Th', 'Pdt. Piet M Tampi, S.Th. M.Si', 'Pdt. Prof. Dr. W A Roeroe, M.Th', 'Tuhan Yesus Kristus', 'd'),
(2014, 29, 'Menurut Trilogi pembangunan Jemaat, apa Bahan Alkitab tanggal 15 - 21 Juni 2014?', 'Kelurahan 20 : 8 - 11 dan Roma 8 : 26 - 28', 'Amsal 31 : 10 - 31 dan 2 Tesalonika 3 : 10 - 12', 'Kelurahan 20 : 8 - 11 dan 2 Tesalonika 3 : 10 - 12', 'Amsal 31 : 10 - 31 dan Roma 8 : 26 - 28', 'c'),
(2014, 30, 'Menurut Trilogi pembangunan Jemaat, apa Tema tanggal 15 - 21 Juni 2014?', 'Berdemokrasi Dalam Kemenangan Kristus', 'Kemenangan Kristus Mengatasi Segala Kuasa', 'Peranan Roh Kudus Dalam Pendidikan Keluarga', 'Etos Kerja', 'd'),
(2014, 31, 'Tata Gereja yang dipakai oleh gereja kita sekarang ini adalah :', 'Tata Gereja 2007 & Adendum 2012', 'Tata Gereja 1999', 'Tata Gereja 2007', 'Tata Gereja 1990', 'a'),
(2014, 32, 'Tata Dasar dalam Tata Gereja 2007 terdiri dari .... Bab dan..... pasal', '15 Bab; 33 Pasal', '15 Bab : 34 Pasal', '16 Bab ; 33 Pasal', '16 Bab : 34 Pasal', 'b'),
(2014, 33, 'Sesuai Tata Gereja 2007 Bab II Pasal 3, GMIM mengakui dan melaksanakan 2 Sakramen yaitu :', 'Baptisan Kudus & Perkawinan Kudus', 'Baptisan Kudus & Sidi Jemaat', 'Baptisan Kudus & Perjamuan Kudus', 'Perjamuan Kudus & Perkawinan Kudus', 'c'),
(2014, 34, 'Kata Presbiterial Sinodal berasal dari Bahasa :', 'Yunani', 'Latin', 'Ibrani', 'Persia', 'a'),
(2014, 35, 'Sesuai Tata Dasar Bab XI pasal 28 : GMIM secara hukum, kedalam dan keluar diwakili oleh :', 'Ketua Badan Pekerja Majelis Sinode', 'Sekretaris Departemen Hukum & HAM', 'Sekretaris Badan Pekerja Majelis Sinode', 'a dan c benar', 'd'),
(2014, 36, 'Sesuai Tata Dasar Bab XII Pasal 30 : Tahun Pelayanan dan tahun anggaran dimulai tanggal :', '1 Januari sampai dengan 31 Desember', '1 Februari sampai dengan 31 Januari', '1 April sampai dengan 31 Maret', '1 Maret sampai dengan 28 Februari', 'a'),
(2014, 37, 'Orang-orang yang karena kemampuan dan keteladannnya dipercayakan untuk memberikan nasihat kepada Majelis Jemaat adalah :', 'Penasehat Majelis Jemaat', 'Penasehat Jemaat', 'Penasihat Majelis Jemaat', 'Penasihat Jemaat', 'd'),
(2014, 38, 'Jumlah keanggotaan Badan Pekerja Majelis Jemaat berdasarkan :', 'Jumlah Kolom dalam Jemaat', 'Jumlah Keluarga dalam Jemaat', 'Jumlah Pelayan Khusus dalam Jemaat', 'Jumlah anggota dalam jemaat', 'b'),
(2014, 39, 'Rapat Komisi Pelayanan Kategorial dipimpin oleh :', 'Ketua & Sekretaris Komisi', 'Dipilih dari antara anggota Komisi', 'Pimpinan Komisi', 'Ketua Komisi', 'c'),
(2014, 40, 'Manakah pernyataan yang benar sesuai Peraturan Tentang Jemaat Bab VIII Pasal 31', 'Anggota Komisi bertugas menjadi Ketua Bidang Pelayanan', 'Anggota Komisi bertugas sesuai kesepakatan masing-masing Komisi', 'Anggota Komisi bertugas jika dibutuhkan dan diperlukan', 'Anggota Komisi bertugas sesuai selera masing-masing', 'b'),
(2014, 41, 'Dalam Peraturan tentang Wilayah, Pelayanan Kategorial Wilayah terdapat dalam Bab mana :', 'Bab VIII', 'Bab IX', 'Bab VII', 'Bab VI', 'c'),
(2014, 42, 'Sesuai Tata Gereja , Manakah pernyataan yang benar :', 'Komisi Pelayanan Kategorial Remaja', 'a dan c benar', 'Komisi Pelayanan Remaja', 'a dan c salah', 'b'),
(2014, 43, 'Keanggotaan Majelis Sinode dari utusan jemaat didasarkan pada :', 'Jumlah Pelayan Khusus', 'Jumlah kolom', 'Jumlah anggota Jemaat', 'Keputusan Badan Pekerja Majelis Sinode', 'b'),
(2014, 44, 'Pelaksana Pemilihan BPMS dilaksanakan oleh Panitia pemilihan. Kapankah Panitia Pemilihan harus ditetapkan dan dilantik sebelum Sidang Majelis Sinode :', '1 bulan', '3 bulan', '2 bulan', '4 bulan', 'c'),
(2014, 45, 'Pendeta yang diangkat sebagai pekerja GMIM harus berusia minimal.....tahun and maksimal....tahun.', '25 dan 39', '25 and 40', '23 and 35', '23 and 39', 'a'),
(2014, 46, 'Ketua BPMS GMIM Periode 2014-2018 adalah :', 'Pdtr. DR. H. W. B. Sumakul', 'Pdtr. Dr. H. W. B. Sumakul, PhD', 'Pdtr. Dr. H. W. B. Sumakul, STh, PhD', 'Pdtr. Dr. H. W. B. Sumakul, PhD', 'd'),
(2014, 47, 'Ketua Komisi Pelayanan Remaja Sinode Periode 2014-2018 adalah :', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. Drs. Jantje W. Sajow, MSi', 'Pnt. Meksi Joseph Sahensolar, SPi', 'Pnt. Iwan Mahardika Frederik, SE', 'a'),
(2014, 48, 'Ketua Komisi Pelayanan Remaja Sinode yang pertama adalah :', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Drs. Jimmy Mamahit', 'Pnt. Drs. Jantje W. Sajow, MSi', 'Pnt. Ir. Dwight Moody Rondonuwu', 'a'),
(2014, 49, 'Kapan dan dimanakah Komisi Pelayanan Remaja Sinode resmi berdiri sendiri :', '28 Oktober 1990 di Palelon Modoinding', '28 Oktober 1990 di Palelon Modoinding', '28 Januari 1990 di Palelon Modoinding', '28 Januari 1990 di Palelon Modoinding', 'd'),
(2014, 50, 'Kapan dan dimanakah Komisi Pelayanan Remaja Sinode GMIM periode 2014 - 2018 di lantik :', '13 April 2014 di Paulus Wasian Kakas', '13 April 2014 di Wilayah Bitung 9', '20 April 2014 di Wilayah Bitung 9', '20 April 2014 di Paulus Wasian Kakas', 'b'),
(2014, 51, 'Mengapa kita menggunakan symbol burung Manguni pada Lambang GMIM :', 'Karena Burung yang hidup dan banyak di tanah Minahasa', 'Karena telah dikenal secara universal sebagai symbol hikmat', 'Karena Burung ini beraktivitas pada malam hari, symbol terang di tengah kegelapan', 'Semua benar', 'd'),
(2014, 52, 'Jumlah keseluruhan sayap manguni pada lambang GMIM melambangkan apa :', 'Jumlah Jemaat pada waktu berdiri', 'Jumlah Klasis pada waktu berdiri', 'Tahun 1934', 'Bulan September', 'c'),
(2014, 53, 'Yang melambangkan remaja yang sedang mekar, bertumbuh dan berkembang pada lambang Remaja GMIM adalah :', 'Lingkaran berwarna merah', 'Dua kelapa', 'Bunga Cengkih yang sedang mekar', 'Sayap burung manguni', 'c'),
(2014, 54, 'Bangunan Gereja berwarna merah dan berbentuk waruga melambangkan apa dalam lambang remaja GMIM :', 'Gereja sebagai wadah pelayanan remaja', 'Remaja sebagai Gereja Masa Depan', 'Ciri khas', 'Semua benar', 'd'),
(2014, 55, 'Bidang apakah dalam KPRS yang menangani Pemilihan Remaja Teladan :', 'Bidang Pengembangan Minat Bakat', 'Bidang Pelayanan Siswa', 'Bidang Data Base dan Umum', 'Bidang P3SDM', 'a'),
(2014, 56, 'Siapakah Ketua Bidang Pengembangan Minat dan Bakat KPRS GMIM Periode 2014-2018 :', 'Pnt. Melky Pattiwael, SIK, MSi', 'Pnt. Gino Laguyu, S.Sos', 'Pnt. Yerry Makarawung', 'Pnt. Mariana Siby', 'a'),
(2014, 57, 'Dimanakah pelaksanaan Pesta Seni Remaja Sinode GMIM Tahun 2014 :', 'Wilayah Mapanget I', 'Wilayah Ratahan', 'Wilayah Manado Timur III', 'Wilayah Pasan', 'b'),
(2014, 58, 'Wilayah Pineleng pada tahun 2014 adalah tuan dan nyonya rumah untuk kegiatan apa :', 'Perkemahan Kreatif Remaja', 'Hari Persatuan Remaja', 'Pesta Seni Remaja', 'Pekan Olahraga Remaja', 'c'),
(2014, 59, 'Ketua Komisi Pelayanan Remaja Sinode GMIM periode 2000-2005 adalah :', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Drs. Jantje Wowiling Sajow,MSi', 'Pnt. Drs. Jimmy Mamahit', 'Pnt. Ir. Wenny Pantouw', 'b'),
(2014, 60, 'Siapakah Sekretaris BPMG MIM Periode 2010-2014 :', 'Pdt. Hendry Runtuween, STh, MSi', 'Pdt. Djerfy Saisab, STh', 'Pdt. Arthur R. Rumengan, M. Teol', 'Pdt. DR. Nico Gara, STh, MA', 'c'),
(2014, 61, 'Lidya pergi ke sekolah dengan pakaiannya yang terlalu mencolok. Kritikan yang tepat untuk penampilan Lidya adalah ....', 'Pakaian kamu itu hanya cocok untuk pergi ke pasar.', 'Jangan dulu masuk kelas, kamu harus berganti pakaian dulu.', 'Kamu jangan terlalu menonjolkan diri, nanti teman-temanmu cemburu.', 'Lidya, pakaianmu terlalu mencolok, terutama bahannya sangat mahal.', 'd'),
(2014, 62, 'Daftar kata-kata penting yang terdapat dalam buku ilmiah dan disusun secara abjad disebut ....', 'Kamus', 'Ensiklopedi', 'Indeks', 'Daftar Pustaka', 'c'),
(2014, 63, 'Akibat semua daerah ingin menang sendiri, bermunculanlah perkumpulan pemuda yang bersifat kedaerahan. Dari hasil kongres perkumpulan pemuda-pemuda itu lahirlah sumpah pemuda...', 'Sumpah Pemuda', 'Sumpah Palapa', 'Semangat Pemuda', 'Sumpah Setia', 'a'),
(2014, 64, 'Contoh kalimat majemuk bertingkat adalah ....', 'Mereka bertukar pikiran dengan teman kelompoknya.', 'Mereka bersalam-salaman setelah menyadari kesalahannya.', 'Ketua rombongan itu sedang tukar menukar vandel dengan senyum.', 'Kedua kelompok itu menyalahkan satu lain.', 'b'),
(2014, 65, 'Ibunda, Andre sudah dapat menyesuaikan diri dengan lingkungan sekolah yang baru... Surat pribadi di atas adalah ....', 'Keadaan sekolah Andre', 'Teman-teman Andre', 'Lingkungan sekolah Andre', 'Penyesuaian diri Andre', 'd'),
(2014, 66, 'Kalimat penutup surat undangan resmi yang tepat adalah ....', 'Mohon kehadiran Bapak/Ibu tepat waktu.', 'Kehadiran Bapak/Ibu merupakan kehormatan bagi kami.', 'Kehadiran Bapak/Ibu tepat waktu merupakan disiplin waktu rapat.', 'Atas perhatian Bapak/Ibu, kami mengucapkan terima kasih.', 'd'),
(2014, 67, 'Dalam berdagang, Pak Petrus memperoleh keuntungan besar. Peribahasa yang tepat untuk pernyataan di atas adalah ....', 'Seperti kejatuhan bulan', 'Bagai bulan berpagar bintang', 'Siang bagai hari, tenang bagai bulan', 'Bulan jatuh dalam ribaan', 'd'),
(2014, 68, 'Penulisan judul karangan yang tepat sesuai dengan EYD adalah ....', 'Tampil Menawan Di Setiap Kesempatan', 'Tampil Menawan di Setiap Kesempatan', 'Tampil menawan di setiap kesempatan', 'TAMPIL MENAWAN di setiap KESEMPATAN', 'b'),
(2014, 69, 'Di antara kalimat-kalimat berikut ini yang mengandung kata bermakna konotasi adalah ....', 'Akhirnya ia mati ditembak polisi.', 'Air teh itu terlalu manis.', 'Hanya dialah bunga idamanku seorang.', 'Pada malam yang gelap kami berjalan menuju bukit itu.', 'c'),
(2014, 70, '96 - 4 x 9 + 20 ÷ 5 = ....', '60', '64', '70', '74', 'b'),
(2014, 71, '0,75 + 1 2 ÷ 0,6 - 2 3 × 0,125 = ....', '1,50', '1,25', '0,50', '0,25', 'c'),
(2014, 72, 'Banyaknya digit pada bilangan hasil dari 2^2014 . 5^2015 adalah', '2014', '2015', '2016', '2017', 'b'),
(2014, 73, 'Dalam kompetisi Matematika, setiap jawaban benar diberi skor 3, jawaban salah diberi skor -1...', '81', '84', '87', '93', 'a'),
(2014, 74, 'Lima ekor sapi menghabiskan rumput seluas 5 kali ukuran lapangan sepak bola dalam waktu 5 hari...', '1 hari', '3 hari', '5 hari', '7 hari', 'c'),
(2014, 75, 'Dalam waktu 7 menit Maria mampu membaca buku cerita sebanyak 140 kata...', '20 menit', '25 menit', '35 menit', '70 menit', 'c'),
(2014, 76, 'Dengan kecepatan rata-rata 90 km/jam, sebuah kendaraan memerlukan waktu 3 jam 20 menit...', '3 jam 15 menit', '3 jam 45 menit', '3 jam 40 menit', '3 jam 50 menit', 'b'),
(2014, 77, 'Dari Manado ke Tomohon dilayani oleh 5 bus dan dari Tomohon ke Tondano dilayani oleh 4 bus...', '200', '240', '400', '440', 'b'),
(2014, 78, 'Rata-rata sembilan bilangan adalah 6. Satu di antara ke sembilan bilangan dibuang...', '1', '2', '3', '5', 'b'),
(2014, 79, 'Penghasilan Joshua setiap bulan adalah Rp3.600.000,00...', 'Rp. 800.000,00', 'Rp. 600.000,00', 'Rp. 400.000,00', 'Rp. 200.000,00', 'd'),
(2014, 80, 'Seorang pedagang membeli 30 kg beras dengan harga Rp150.000,00...', 'Untung 10%', 'Untung 15%', 'Rugi 10%', 'Rugi 15%', 'a'),
(2014, 81, 'Besar sudut-sudut suatu segitiga adalah 3x, 5x dan 7x. Nilai x adalah ....', '90', '120', '150', '180', 'b'),
(2014, 82, 'Beni membuat model bola dengan diameter 14 cm. Luas permukaan model bola tersebut adalah .... cm²', '610', '160', '616', '660', 'c'),
(2014, 83, 'Jumlah semua bilangan asli dari 1 sampai 100 adalah ....', '5050', '5005', '5500', '5000', 'a'),
(2014, 84, 'Perang Dunia II diawali dengan peristiwa....', 'Serbuan Bala Tentara Jepang ke pangkalan militer AS di Pearl Harbour', 'Serbuan tentara Jepang ke Filipina', 'Serbuan Bala tentara Italia ke Indonesia', 'Serbuan Bala Tentara Jerman ke Uni Soviet', 'a'),
(2014, 85, 'Dalam Perang Dunia II, Blok Sekutu adalah...', 'Italia, Inggris, Perancis', 'Amerika Serikat, Australia, Afrika', 'Jerman, Amerika Serikat, Rusia', 'Jepang, Cina, Australia', 'b'),
(2014, 86, 'Kerjasama internasional merupakan bentuk kerja sama yang tidak mementingkan kepentingan negara atau wilayah tertentu, misalnya...', 'ASEAN', 'GATT', 'SEATO', 'Pakta Warsawa', 'b'),
(2014, 87, 'Kerjasama regional dan internasional di dunia banyak tumbuh dan berkembang. Contoh kerja sama regional adalah...', 'Negara-negara Non Blok', 'World Bank', 'NATO', 'PBB', 'c'),
(2014, 88, 'Organisasi internasional yang bergerak dalam bidang makanan dan produksi agrarian ialah...', 'ILO', 'FAO', 'ECOSOC', 'UNICEF', 'b'),
(2014, 89, 'Faktor – faktor yang mendorong terjadinya kerja sama internasional terutama disebabkan oleh....', 'Persamaan Sistem Sosial', 'Persamaan Kultur', 'Persamaan Teknologi', 'Persamaan kehidupan hidup', 'a'),
(2014, 90, 'Tindakan yang dilakukan mahasiswa, pelajar, dan pemuda untuk memperkokoh kesatuan aksi pada tahun 1966 adalah...', 'Meminta dukungan ABRI', 'Meminta bantuan Presiden', 'Membentuk Fron Nasional', 'Membentuk Fron Pancasila', 'd'),
(2014, 91, 'Tujuan Mahasiswa, pemuda, dan pelajar mencetuskan TRITURA adalah...', 'Mengukuhkan Supersemar', 'Menyelenggarakan aksi Demonstrasi', 'Merebut basis kekuatan PKI', 'Membersihkan cabinet', 'd'),
(2014, 92, 'Berikut merupakan kebutuhan manusia... Yang merupakan kebutuhan rohani manusia adalah....', '1 dan 2', '1 dan 3', '1 dan 4', '2 dan 4', 'c'),
(2014, 93, 'Christy mencoba memenuhi beberapa kebutuhannya... Jika ditinjau dari sifatnya yang termasuk kebutuhan jasmani adalah ....', '1 dan 2', '1 dan 3', '1 dan 4', '2 dan 4', 'b'),
(2014, 94, 'Faktor-faktor produksi terdiri atas... Yang merupakan faktor produksi asli adalah....', '1 dan 2', '2 dan 3', '1 dan 4', '1 dan 3', 'a'),
(2014, 95, 'Berikut merupakan kelebihan sistem ekonomi komando dan sistem ekonomi pasar... Yang merupakan kelebihan sistem ekonomi pasar adalah ....', '1,2 dan 3', '1,2 dan 4', '2,3 dan 4', '2,3 dan 5', 'd'),
(2014, 96, 'Kebijakan bank sentral dibidang moneter yang menaikkan dan menurunkan suku bunga bank umum... disebut ....', 'Kebijakan Diskon', 'Kebijakan cadangan kas', 'Kebijakan operasi kas', 'Kebijakan operasi pasar terbuka', 'd'),
(2014, 97, 'Uang terdiri atas uang kartal dan uang giral merupakan perbedaan jenis uang berdasarkan ....', 'Nilai uang', 'Bahan uang', 'Pihak yang mengeluarkan', 'Negara yang mengeluarkan', 'c'),
(2014, 98, 'Berikut ini yang bukan merupakan tugas bank umum adalah ....', 'Menghimpun dana dari masyarakat', 'Menempatkan dan meminjamkan dana ke bank lain', 'Menyediakan tempat untuk menyimpan barang dan surat berharga', 'Menjaga kelancaran sistem pembayaran', 'd'),
(2014, 99, 'Giro, tabungan berjangka, sertifikat deposito, tabungan, deposito on call merupakan produk perbankan ....', 'Kredit pasif', 'Kredit aktif', 'Kredit macet', 'Macam-macam kredit', 'a'),
(2014, 100, 'Suatu keadaan dimana angkatan kerja yang bersedia bekerja mendapat pekerjaan disebut ....', 'Kesempatan kerja', 'Keinginan kerja', 'Pengangguran', 'Kemauan kerja', 'a'),
(2014, 101, 'Perbandingan nilai suatu mata uang dengan mata uang negatif disebut ....', 'Kurs valuta asing', 'Kurs tetap', 'Kurs melebihi uang', 'Kurs bebas', 'a'),
(2014, 102, 'Bidang kajian ilmu Geografi yang mempelajari segala bentuk tubuh dan pola aliran air adalah...', 'Hidrografi', 'Morfologi', 'Fisiografi', 'Topografi', 'a'),
(2014, 103, 'Garis kontur yang menghubungkan tempat - tempat yang memiliki kedalaman sama dinamakan...', 'Garis Isobath', 'Garis Isoterm', 'Garis Isohyet', 'Garis Isholin', 'a'),
(2014, 104, 'Propinsi terdiri dari gabungan dari kabupaten/kota . Jumlah Kabupaten/Kota di Sulawesi Utara adalah...', '12', '13', '14', '15', 'd'),
(2014, 105, 'Negara di Asia Tenggara yang tidak berbatasan dengan laut adalah...', 'Laos', 'Kamboja', 'Thailand', 'Vietnam', 'a'),
(2014, 106, 'Di antara Negara - Negara Asia Tenggara berikut yang tidak memiliki gunung berapi adalah...', 'Indonesia', 'Filipina', 'Malaysia', 'Myanmar', 'c'),
(2014, 107, 'Pulau yang paling luas di bumi adalah...', 'Greenland', 'Papua', 'Kalimantan', 'Madagaskar', 'a'),
(2014, 108, 'Makhluk hidup menunjukkan perubahan tubuh manusia yang sejalan dengan pertambahan usianya...', 'berkembang biak dan memerlukan nutrisi', 'memerlukan nutrisi dan bereproduksi', 'peka terhadap rangsang dan bereproduksi', 'mengalami pertumbuhan dan perkembangan', 'd'),
(2014, 109, 'Berikut ini beberapa tanaman yang ditemukan dikebun sekolah... Tanaman yang dapat dikelompokkan dalam kelompok dikotil adalah ....', '1,2,3', '1,3,4', '2,3,4', '2,4,5', 'b'),
(2014, 110, 'Perhatikan tumbuhan-tumbuhan berikut ini! Kelompok tumbuhan tak berpembuluh ditunjukkan oleh ....', '1,2,3', '2,3,6', '2,4,5', '3,5,6', 'c'),
(2014, 111, 'Contoh yang menunjukkan simbiosis komensalisme adalah ....', 'cacing pita dan sapi', 'benalu dengan tanaman inang', 'bakteri usus dengan manusia', 'anggrek dengan tanaman inang', 'd'),
(2014, 112, 'Usaha yang dapat dilakukan untuk mengurangi pencemaran udara di daerah perkotaan adalah ....', 'membuat taman kota', 'mendirikan pabrik di perkotaan', 'menambahkan jumlah angkutan kota', 'membakar sampah rumah tangga', 'a'),
(2014, 113, 'Cara yang dapat dilakukan untuk mengatasi pencemaran yang terjadi di daerah perkotaan adalah ....', 'mengurangi produksi kendaraan', 'melarang pengusaha mendirikan pabrik', 'menghentikan penggunaan bahan bakar minyak', 'melakukan reboisasi di sepanjang jalan kota', 'd'),
(2014, 114, 'Peningkatan jumlah penduduk berakibat pada pemanfaatan hutan menjadi pemukiman dan lahan pertanian. Hal ini dapat menyebabkan ....', 'ketersediaan air bersih mencukupi', 'meningkatnya udara bersih lingkungan', 'hilangnya flora dan fauna tertentu', 'semakin luasnya paru-paru bumi', 'c'),
(2014, 115, 'Berdasarkan sensus penduduk, jumlah penduduk di Indonesia semakin bertambah... dampak pertambahan jumlah penduduk tersebut adalah ....', 'naiknya kandungan oksigen di udara', 'kandungan CO2 di udara menurun', 'areal hutan semakin sempit', 'tercukupinya kebutuhan perumahan', 'c'),
(2014, 116, 'Sebuah gelas ukur berisi air... kemudian ke dalam gelas tersebut dimasukkan sebuah benda. Volume benda yang dicelupkan adalah....', '20 ml', '50 ml', '70 ml', '120 ml', 'c'),
(2014, 117, 'Sebongkah es yang volumenya 70 cm³ dimasukkan kedalam gelas ukur, jika es tersebut mencair akan menjadi air dengan volume ....', '70 cm³', 'kurang dari 70 cm³', 'lebih dari 70 cm³', 'tidak menentu', 'b'),
(2014, 118, 'Perhatikan pemasangan kabel listrik pada transmisi jarak jauh dibuat agak kendur. hal ini dilakukan...', 'Memberi toleransi pemuaian saat arus listrik mengalir', 'kawat tidak putus karena menyusut ketika udara dingin', 'kawat tidak putus karena memuai ketika udara panas', 'kawat tidak memuai saat terkena sinar matahari', 'a'),
(2014, 119, 'Perhatikan perilaku berikut ini! Yang bertujuan untuk mengatasi dampak negatif dari pemuaian dan penyusutan ditujukan nomor...', '1 dan 2', '2 dan 4', '1 dan 4', '2 dan 3', 'c'),
(2014, 120, 'Perhatikan peristiwa berikut ! contoh gerak lurus berubah beraturan dipercepat yang benar adalah...', '1 dan 2', '1 dan 3', '2 dan 3', '2 dan 4', 'b'),
(2014, 121, 'Gaya sebesar 45 N bekerja pada benda bermassa 5 kg diatas lantai licin... Setelah 6 detik jarak yang ditempuh adalah...', '160 m', '162 m', '164 m', '166 m', 'b'),
(2014, 122, 'Sebuah rumah menggunakan peralatan listrik... biaya energi listrik yang harus dibayar dalam 1 bulan (30 hari) adalah . . . .', 'Rp. 54.890', 'Rp. 64.890', 'Rp. 68.420', 'Rp. 74.280', 'b'),
(2014, 123, 'Bahan kimia yang berguna untuk memberantas gulma adalah . . . .', 'Insektisida', 'Fungisida', 'Herbisida', 'Larvasida', 'c'),
(2014, 124, 'Bahan yang sering digunakan dalam pembuatan pemutih pakaian adalah . . . .', 'Natrium hipoklorit', 'Natrium alkil benzena sulfonat', 'Natrium klorida', 'Natrium klorida', 'a'),
(2014, 125, 'Berikut ini yang merupakan sifat kimia adalah . . . .', 'wujud', 'kelarutan', 'warna', 'membusuk', 'd'),
(2014, 126, 'Dampak fisiologis yang ditimbulkan oleh narkoba terhadap penggunanya adalah...', 'tingkat emosi yang sangat labil', 'perubahan perilaku yang negatif', 'menurunnya fungsi sistem kerja tubuh', 'kecemasan berlebih', 'c'),
(2014, 127, 'Perhatikan ciri-ciri pemakai NAPZA berikut ini!', '1,2,3', '1,3,4', '2,4,5', '3,4,5', 'b'),
(2014, 128, '"I like many ..., if you want to exchange music information or songs, e- mail me". The underlined word means ....', 'Change thing in a different way', 'Need thing for him/her self', 'Give/receive thing of each other', 'Take thing in a formal situation', 'c'),
(2014, 129, 'Arrange these words into a good caution! Before - the unit - the main switch - cleaning - turn off', '4-2-5-1-3', '5-3-1-4-2', '5-2-1-4-3', '4-2-1-5-3', 'a'),
(2014, 130, 'Arrange the following sentences into a good paragraph about National Monument.', '3-5-2-4-1', '3-4-5-2-1', '3-5-4-1-2', '3-4-2-5-1', 'a'),
(2014, 131, 'What is the purpose of this notice? ATTENTION DUE TO AVIATION SAFETY...', 'To give the message to the all readers', 'To ban the use of hand phone at the airport', 'To warn people not to carry hand phone', 'To remind passengers not to carry hand phone on the plane', 'd'),
(2014, 132, 'Who does give the notice?', 'The pilot', 'Air crew', 'Stewardess', 'Airport authority', 'd'),
(2014, 133, 'Leo : Mom, I have won the chess competition. Mother : ...', 'Of course', 'Sure', 'Congratulations', 'I''m sorry', 'c'),
(2014, 134, 'You can find this below notice in the hospital. ICU (INTENSIVE CARE UNIT) What does the notice mean?', 'It is a place for doctor and nurse', 'The place is very special', 'Only the doctor can enter the room', 'The room is only for critical patient', 'd'),
(2014, 135, 'The notice below can be found aboard the plane. LIFE VEST UNDER YOUR SEAT What does the notice mean?', 'In case of emergency you can get the life vest under your seat', 'There is a life vest under your seat', 'If you like the vest you can take it under your seat', 'You have to wear the life vest anytime', 'a'),
(2014, 136, 'He runs ... to catch. He leaves me far behind him.', 'Too fast', 'Fast enough', 'Too slow', 'Slow enough', 'a'),
(2014, 137, 'I didn''t buy the t-shirt, because it was ...', 'Too cheap', 'Too expensive', 'Expensive enough', 'Cheap enough', 'b'),
(2014, 138, 'Dave : Swimming in a river is more enjoyable than swimming in a pool. Tri : I don''t think so. The underlined word means that ...', 'Agree', 'Certain', 'Disagree', 'Uncertain', 'c'),
(2014, 139, 'What sickness did Kristen suffer at that time?', 'Migraine', 'Toothache', 'Influenza', 'Cough', 'a'),
(2014, 140, 'What is the letter about?', 'Asking for advice', 'Preparing the test', 'Taking medicines', 'Having the problem', 'a'),
(2014, 141, '"I take an aspirin and the pain is gone" The underlined word nearly means ...', 'Medicine', 'Capsule', 'Pill', 'Sickness', 'a'),
(2014, 142, 'Kristen wrote a letter to a doctor because she will ...', 'Continue her study', 'Have a face to face advice', 'Have a final test at school', 'Get confused to choose medicine', 'c'),
(2014, 143, 'BONUS SOAL - Dampak positif dari perubahan sosial budaya adalah', 'penemuan ilmu pengetahuan dan teknologi', 'sikap individualistik', 'gaya hidup yang meniru Barat', 'kesenjangan sosial', 'a'),
(2014, 144, 'Siapa Ketua MPR RI Sekarang ini :', 'Zulkifli Husain', 'Zulkifli Hasan', 'Zulkifli Husein', 'Zulkifli Husein', 'b'),
(2014, 145, 'Siapa Menteri Luar Negeri RI sekarang ini :', 'Retno Marsudirini', 'Retno Wulandari', 'Retno Marsudi', 'Retno Marsudin', 'c'),
(2014, 146, 'Siapa Gubernur Propinsi Jawa Tengah Sekarang ini :', 'Ganjar Pranowo', 'Banjar Pranowo', 'Ganjar Prabuwono', 'Ganjar Prabukusomo', 'a'),
(2014, 147, 'Kedutaan Besar Republik Indonesia (KBRI) manakah yang hancur pada bulan April 2015 :', 'KBRI Yaman', 'KBRI Oman', 'KBRI Irak', 'KBRI Syria', 'a'),
(2014, 148, 'Kapankah Konperensi Asia Afrika itu dilaksanakan di Bandung :', 'Tahun 2015', 'Tahun 1955', 'Tahun 2000', 'Tahun 1950', 'b'),
(2014, 149, 'Siapakah yang pertama kali memelopori emansipasi wanita di Indonesia', 'Raden A. Kartini', 'Walanda Maramis', 'Cut Nyak Dien', 'Semua benar', 'a'),
(2014, 150, 'Di Indonesia ada hewan purba yang masih hidup yaitu :', 'Ikan Raja Laut', 'Komodo', 'Gorilla', 'a dan b benar', 'b');
