-- TAHUN 2017 - Soal 1 s.d 76
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2017, 1, 'Nats : "Tetapi aku dan seisi rumahku, kami akan beribadah kepada Tuhan!" Nats ini terdapat dalam kitab :', 'Yosua', 'Yeremia', 'Yesaya', 'Daniel', 'a'),
(2017, 2, '"Dengan telanjang aku keluar dari kandungan ibuku, dengan telanjang juga aku akan kembali ke dalamnya." Nats ini terdapat dalam Kitab :', 'Yehezkiel', 'Yeremia', 'Yesaya', 'Ayub', 'd'),
(2017, 3, 'Kitab Ayub terletak antara :', 'Ester - Amsal', 'Ester - Pengkhotbah', 'Ester - Mazmur', 'Ester - Kidung Agung', 'a'),
(2017, 4, 'Bacaan Yang dipakai dalam Hari Paskah II/Hari Pemuda/Remaja GMIM tahun ini dalam buku MTPJ adalah :', 'Yohanes 20 : 20-24', 'Matius 20 : 24-29', 'Yohanes 20 : 24-29', 'Lukas 20 : 20-24', 'c'),
(2017, 5, 'Tema Mingguan pada Minggu Sangsara III 19-25 Maret 2017 adalah', 'Bekerja Dalam Ketaatan', 'Pembentukan Iman', 'Bertekun Dalam Penderitaan', 'Kemurnian Iman di uji', 'd'),
(2017, 6, 'Judul Perikop dari Lukas 22 : 54-62 adalah :', 'Yesus di hadapan Mahkamah Agama', 'Percakapan waktu Perjamuan Malam', 'di Taman Getsemani', 'Petrus menyangkal Yesus', 'd'),
(2017, 7, 'Lengkapi nats : "Dan Yesus makin bertambah besar dan bertambah ... dan ... dan makin dikasihi oleh Allah dan Manusia."', 'Hikmat - besarnya', 'Hikmatnya - besar', 'hikmatnya - besarnya', 'hikmat - besar', 'a'),
(2017, 8, '"Bukan, aku tidak tahu apa yang engkau katakan." Ini adalah ucapan dari :', 'Paulus', 'Petrus', 'Lewi', 'Andreas', 'b'),
(2017, 9, '"Celakalah gembala-gembala Israel, yang menggembalakan dirinya sendiri." Nats ini terdapat dalam kitab', 'Yesaya', 'Yeremia', 'Yehezkiel', 'Daniel', 'c'),
(2017, 10, 'Tetapi Tuhan berfirman kepadaku : "Janganlah katakan : Aku ini masih muda..." Nats ini terdapat dalam Kitab :', 'Yesaya', 'Yeremia', 'Yehezkiel', 'Daniel', 'b'),
(2017, 11, 'Nats : "Didiklah orang muda menurut jalan yang patut baginya, maka pada masa tuanya pun ia tidak akan menyimpang dari jalan itu."', 'Amsal 6 : 22', 'Amsal 2 : 26', 'Amsal 22 : 6', 'Amsal 6 : 2', 'c'),
(2017, 12, 'Nats "Bangsamulah bangsaku dan Allahmulah Allahku." Nats ini terdapat dalam Kitab :', 'Ayub', 'Yosua', 'Lukas', 'Rut', 'd'),
(2017, 13, 'Bagi Isai, Boas adalah :', 'Ayahnya', 'Pamannya', 'Opanya', 'Kakaknya', 'c'),
(2017, 14, 'Judul perikop Mazmur 23 : 1-6 adalah :', 'Syukur dan Doa', 'Gembala yang Baik', 'Tuhan, gembalaku yang baik', 'Haleluyah', 'c'),
(2017, 15, '"Tetapi buah Roh ialah : kasih, sukacita, damai sejahtera..." Nats ini terdapat dalam :', 'Galatia 5 : 22', 'Galatia 5 : 22-23', 'Galatia 5 : 23', 'Galatia 5 : 16-26', 'b'),
(2017, 16, 'Sidang Majelis Sinode Istimewa (SMSI) ke 78 dimana pada hari pertama membahas perubahan (Revisi) Tata Gereja 2007 dilaksanakan pada :', '17-18 Mei 2016', '18-19 Mei 2016', '15-17 Mei 2016', '15-18 Mei 2016', 'b'),
(2017, 17, 'Dalam Tata Gereja 2016 Pada Bab keberapakah dalam Peraturan Tentang Sinode yang mengatur Pelayanan Kategorial Sinode :', 'BAB V', 'BAB VII', 'BAB VI', 'BAB VIII', 'c'),
(2017, 18, 'Sesuai Peraturan Tentang Wilayah Bab VII Pasal 16 ayat 2, kepada siapa Komisi pelayanan kategorial wilayah bertanggung jawab :', 'Badan Pekerja Majelis Wilayah', 'Konsultasi Tahunan Komisi Wilayah', 'Sidang Majelis Wilayah Bulanan', 'a dan b benar', 'd'),
(2017, 19, 'Pengakuan dan Panggilan Gereja terdapat dalam Bab berapa Tata Dasar, Tata Gereja GMIM 2016:', 'Bab I', 'Bab III', 'Bab II', 'Bab IV', 'c'),
(2017, 20, 'Dari pernyataan yang berikut manakah yang benar :', 'Komisi Pelayanan Remaja Jemaat Petra Sawangan Wilayah Kembes', 'Komisi Pelayanan Kategorial Remaja Jemaat Nafiri Malalayang Satu', 'Komisi Pelayanan Kategorial Remaja Wilayah Tondano II', 'Semua Benar', 'd'),
(2017, 21, 'Konsultasi Komisi Pelayanan Kategorial Jemaat diselenggarakan sekurang-kurangnya sekali dalam', 'Sebulan', 'Setahun', 'enam bulan', 'tiga bulan', 'b'),
(2017, 22, 'Peserta Sidang Majelis Wilayah dengan hak suara memutuskan, yaitu :', 'Badan Pekerja Majelis Jemaat', 'Seluruh Pelayan Khusus di Wilayah', 'Badan Pekerja Majelis Wilayah', 'a dan b benar', 'd'),
(2017, 23, 'Sesuai Tata Gereja 2016, Sakramen Perjamuan Kudus dilaksanakan pada perayaan, Kecuali :', 'Jumat Agung', 'Hari Pekabaran Injil', 'Perjamuan Kudus se-Dunia', 'Malam Akhir Tahun', 'd'),
(2017, 24, 'Tata Gereja GMIM 2016 terdiri dari :', '1 Tata Dasar, 8 Peraturan', '1 Tata Dasar, 9 Peraturan', '1 Tata Dasar, 7 Peraturan', '1 Tata Dasar, 10 Peraturan', 'a'),
(2017, 25, 'Sebelum Tata Gereja 2016, Yang diberlakukan adalah :', 'Tata Gereja 2007', 'Tata Gereja 1990', 'Tata Gereja 2007 dan Adendum 2012', 'Tata Gereja 1981', 'c'),
(2017, 26, 'Ketua Majelis Pertimbangan Sinode GMIM Periode 2014-2018 adalah :', 'Pnt. DR. Ir. G. S. V. Lumentut, SH, DEA', 'Pdt. DR. A. O. Supit', 'Pdt. Piet Marthin Tampi, STh, MSi', 'Semua Salah', 'a'),
(2017, 27, 'Wakil Sekretaris BPMS GMIM Bidang Pekerja GMIM dan Pelayan Khusus periode 2014-2018 adalah:', 'Pdt. Altje Runtu-Lumi, MTh', 'Pdt. Richard J. H. Mengko, MTh', 'Pdt. Janny Ch. Rende, MTh', 'Pnt. Jhonly Th Wenur, SH, MH, MM', 'd'),
(2017, 28, 'Sidang Majelis Sinode Tahunan (SMST) GMIM ke-28 dilaksanakan pada tahun dan dimana ?', '2016 di Wilayah Bunaken', '2015 di Wilayah Kawangkoan', '2016 di Wilayah Manado Titiwungen', '2015 di Wilayah Manado Titiwungen', 'a'),
(2017, 29, 'Keenam distrik yang ada di Minahasa pada saat GMIM Berdiri sendiri', 'Tonsea, Manado, Toulour, Kawangkoan, Amurang, Tonsawang', 'Tonsea, Manado, Toulour, Kawangkoan, Tareran, Amurang', 'Tonsea, Airmadidi, Manado, Kawangkoan, Tareran, Amurang', 'Tonsea, Manado, Toulour, Kawangkoan, Amurang, Ratahan', 'd'),
(2017, 30, 'Dalam kegiatan apakah Komisi Pelayanan Remaja Sinode GMIM Berdiri sendiri pada 28 Januari 1990 :', 'Rapat Pemilihan', 'Konsultasi Komisi Pelayanan Remaja Sinode', 'Pertemuan Raya Remaja GMIM', 'Pertemuan Raya Pembina Remaja GMIM', 'b'),
(2017, 31, 'Melaksanakan kegiatan Perkemahan Kreatif Remaja (PKR) tugas dari Kelompok Kerja Bidang :', 'Pelayanan Siswa', 'Semua Salah', 'Organisasi dan Manajemen', 'Ajaran Persekutuan Ibadah dan Misi', 'a'),
(2017, 32, 'Dimanakah Perayaan Hari Persatuan Remaja Gereja (HPRG) tahun 2017 dilaksanakan :', 'Wilayah Tombatu', 'Wilayah Tombatu Timur', 'Wilayah Tombatu Barat', 'Wilayah Tombatu Selatan', 'a'),
(2017, 33, 'Ketua Umum Panitia Pemilihan Remaja Teladan Sinode tahun 2017 adalah :', 'Ir. Marhany V. P. Pua, MA', 'Ester Lambey, SH, MSI', 'Syeny A. Sompotan', 'Pnt. Agustivo Tumundo, SE., MSI', 'a'),
(2017, 34, 'Berikut adalah tempat pemilihan Komisi Pelayanan Remaja Sinode GMIM, Kecuali', 'Zaitun Paleon Wilayah Modoinding', 'Getsemani Senduk Wilayah Tanawangko II', 'Imanuel Tolok Wilayah Kawangkoan', 'Getsemani Wineru Wilayah Likupang 2', 'c'),
(2017, 35, 'Tuan dan Nyonya Rumah pelaksanaan Pesta Seni dan Kreatifitas Remaja Sinode GMIM Tahun 2017 adalah :', 'Winangun', 'Pineleng', 'Manado Winangun', 'Minawerot', 'b'),
(2017, 36, 'Kapankah Selebrasi Paskah Remaja Sinode GMIM Tahun 2017 dilaksanakan :', '16 April 2017', '23 April 2017', '17 April 2017', '24 April 2017', 'a'),
(2017, 37, 'Sebelum menjadi Ketua KPRS pada periode saat ini, Pnt. Ir. D.Moody Rondonuwu MT pada periode sebelumnya menjadi KPRS pada jabatan apa ?', 'Ketua Bidang Minat dan Bakat', 'Ketua Bidang Data dan Umum', 'Ketua Bidang Pelayanan Siswa', 'Semua salah', 'b'),
(2017, 38, 'Pemilihan Remaja Teladan adalah salah satu kegiatan dari Kelompok Kerja Bidang :', 'Organisasi dan Manajemen', 'Data dan Umum', 'Pelayanan Siswa', 'Semua salah', 'b'),
(2017, 39, 'Cermati penulisan kalimat! Kata yang huruf pertamanya harus ditulis dengan huruf kapital ditandai dengan nomor...', '1 dan 3', '2 dan 4', '2 dan 3', '1 dan 4', 'b'),
(2017, 40, 'Kata yang tepat untuk melengkapi kutipan puisi tersebut agar menjadi padu adalah...', 'tubuh, gembira', 'hati, lestari', 'janji, bahagia', 'batin, cerah', 'c'),
(2017, 41, 'Penulisan daftar pustaka yang tepat berdasarkan data buku tersebut adalah...', 'Tohari, Ahmad. Jakarta: Gramedia.2001. Belantik.', 'Ahmad Tohari, Jakarta: Gramedia.2001. Belantik.', 'Tohari, Ahmad. Belantik. Jakarta: Gramedia, 2001.', 'Ahmad Tohari. Belantik. Gramedia: Jakarta, 2001.', 'c'),
(2017, 42, 'Perbaikan kalimat "Selain dari pada itu, masih ada satu truk bantuan sembako" yang tepat adalah...', 'Daripada selain itu, masih ada satu truk bantuan sembako', 'Selain dari itu, masih ada satu truk bantuan sembako', 'Daripada itu, masih ada satu truk bantuan sembako', 'Selain itu, masih ada satu truk bantuan sembako', 'd'),
(2017, 43, 'Rumusan masalah karya ilmiah sesuai tema "Peran Pelajar dalam menciptakan lingkungan yang bersih" adalah ...', 'Di mana pelajar berperan dalam menjaga kebersihan lingkungan?', 'Bagaimana peran pelajar dalam menciptakan lingkungan yang bersih?', 'Berapa pelajar yang dapat berperan dalam menjaga kebersihan?', 'Mengapa pelajar harus ikut berperan dalam menciptakan kebersihan?', 'b'),
(2017, 44, 'Larik yang tepat untuk melengkapi kutipan pantun tersebut adalah ....', 'Setelah tiga bilangan empat, Bila berusaha pasti didapat', 'Ketika berjabat hendaknya erat, Kamu harus selalu sehat', 'Kalau kamu suka makan jamur, Jangan lupa dimasak semur', 'Ketupat dibungkus dengan janur, Junjungan sikap yang jujur', 'd'),
(2017, 45, 'What is the main function of the Exclusive Facial Cotton?', 'To soften baby''s skin', 'To comfort the face', 'To absorb cosmetic', 'To clean make up', 'd'),
(2017, 46, 'From the text above, we know that Exclusive Facial Cotton is ....', 'hygienic in certain items', 'pure white dengan chemical process', 'white with certain addition substances', 'natural because of no chemical process', 'd'),
(2017, 47, 'Complete the text with suitable word: A lion is very strong and here are some facts about ...', 'it', 'he', 'her', 'them', 'a'),
(2017, 48, 'Complete: The lion''s fur ... to the widest part of their body', 'grew', 'grows', 'grown', 'growing', 'b'),
(2017, 49, 'What is Fiola''s mother doing now?', 'working at the office', 'picking up Fiola''s sister', 'waiting for Fiola at home', 'joining the English course', 'a'),
(2017, 50, 'What is Fiola''s mother''s purpose to write the message above?', 'ask Fiola to be home soon', 'help Fiola to remember the job', 'tell Fiola that she is in the course', 'remind Fiola to pick up her sister', 'b'),
(2017, 51, 'Hasil dari 2 1/5 : 1 1/5 - 1 1/4 adalah ...', '1 5/7', '1 1/30', '7/12', '5/12', 'd'),
(2017, 52, 'Hasil dari √300 : √6 =', '5√2', '5√3', '6√2', '6√3', 'a'),
(2017, 53, 'Hasil dari (2x² + 10x - 29)/(4x² - 16) adalah ....', '(x-7)/(2x-4)', '(x-7)/(2x+4)', '(x+7)/(2x-4)', '(x-7)/(2x+4)', 'a'),
(2017, 54, 'Uang Jeheskiel berbanding uang Cesar 1:3. Jika selisih uang mereka Rp120.000,00. Jumlah uang mereka adalah ...', 'Rp160.000,00', 'Rp180.000,00', 'Rp240.000,00', 'Rp360.000,00', 'c'),
(2017, 55, 'Dua suku berikutnya dari barisan 3, 4, 6, 9, ... adalah ....', '13, 18', '13, 17', '12, 26', '12, 15', 'a'),
(2017, 56, 'Urutan pecahan terkecil ke pecahan terbesar dari 0,45; 0,85; 7/8 dan 78% adalah ...', '0,45; 78%; 7/8; 0,85', '0,45; 78%; 0,85; 7/8', '0,85; 7/8; 78%; 0,45', '7/8; 0,85; 78%; 0,45', 'b'),
(2017, 57, 'Berdasarkan data yang termasuk perubahan kimia adalah pasangan nomor ...', '(1) dan (2)', '(1) dan (3)', '(2) dan (3)', '(3) dan (4)', 'd'),
(2017, 58, 'Rumus kimia yang benar untuk magnesium hidroksida dan natrium sulfat masing-masing adalah nomor ...', '(1) dan (2)', '(1) dan (3)', '(2) dan (4)', '(3) dan (4)', 'c'),
(2017, 59, 'Hewan dengan ciri tubuh lunak berlendir, bergerak dengan otot perut, memiliki cangkang keras termasuk dalam kelompok ...', 'Porifera', 'Coelenterata', 'Arthropoda', 'Mollusca', 'd'),
(2017, 60, 'Langkah ketiga dari percobaan fotosintesis dilakukan untuk ...', 'Melunakkan daun', 'Melarutkan klorofil', 'Mematikan sel-sel daun', 'Melarutkan amilum', 'b'),
(2017, 61, 'Berapakah besar energi listrik (W) selama 1 bulan (30 hari)?', '80 kWh', '78 kWh', '52 kWh', '26 kWh', 'b'),
(2017, 62, 'Interaksi di antara makhluk hidup yang saling menguntungkan ditunjukkan kepada peristiwa ...', 'benalu yang hidup pada pohon rambutan', 'bunga anggrek yang hidup di pohon mangga', 'Rhizobium yang hidup di akar tanaman kacang-kacangan', 'tali putri yang hidup pada tanaman beluntas', 'c'),
(2017, 63, 'Panitia kecil yang dibentuk pada sidang BPUPKI 1 diketuai oleh ...', 'Moh. Hatta', 'Ir. Soekarno', 'Moh. Yamin', 'Mr. Ahmad Subarja', 'b'),
(2017, 64, 'Daerah yang lebih jauh dari paparan benua dengan kedalaman 130-4.000 meter dinamakan ...', 'Lereng benua', 'Lubuk laut', 'Punggung laut', 'Palung laut', 'b'),
(2017, 65, 'Isi Dekrit Presiden 5 Juli 1959, antara lain ...', 'Pembubaran DPR', 'Berlakunya kembali UUD 1945', 'Dibentuknya front nasional', 'Diberlakukannya sistem ekonomi terpimpin', 'b'),
(2017, 66, 'Peta yang menggambarkan keadaan muka bumi dengan menggunakan garis-garis kontur dinamakan ...', 'Peta Relief', 'Peta Chorografi', 'Peta Topografi', 'Peta Dunia', 'c'),
(2017, 67, 'Titik-titik pengukuran ketinggian suatu tempat digunakan ...', 'Titik Trigulasi', 'Titik Kontur', 'Titik Proyeksi', 'Titik Ketinggian', 'a'),
(2017, 68, 'Tabungan yang pengambilannya harus ada pemberitahuan dulu dari penabungnya disebut ...', 'Giro', 'Deposan', 'Simpanan Deposito', 'Deposits on call', 'c'),
(2017, 69, 'Berapa jumlah benua dan apa nama-nama benua yang di permukaan bumi ?', '4 Benua: Asia, Afrika, Amerika dan Antartika', '6 Benua: Asia, Afrika, Amerika, Antartika, Australia dan Eropa', '5 Benua: Eropa, Asia, Amerika, Australia dan Afrika', '6 Benua: Eropa, Asia, Amerika, Australia, Antartika dan India', 'b'),
(2017, 70, 'Siapakah saudara tiri Pemimpin Korea Utara yang terbunuh di Malaysia pada tanggal 13 Februari 2017 ?', 'Kim Jong Un', 'Kim Jong Nam', 'Kim Jong III', 'Kim Dae Jung', 'b'),
(2017, 71, 'Di bawah ini adalah 5 Negara kerajaan yang benar, kecuali:', 'Inggris, Arab Saudi, Denmark, Swedia dan Kamboja', 'Inggris, Arab Saudi, Belanda, Denmark dan Maroko', 'Maroko, Kamboja, Yordania, Swedia dan Spanyol', 'Inggris, Arab Saudi, Australia, Thailand dan Belanda', 'd'),
(2017, 72, 'Siapa Menteri Pendidikan dan Kebudayaan Indonesia sekarang ini ?', 'Muhadjir Effendi', 'Muhammad Nasir', 'Muhammad Natsir', 'Rudiantara', 'a'),
(2017, 73, 'Sebutkan 4 orang Menteri Kabinet Kerja saat ini yang beragama Kristen.', 'Yohana Yembise, Yasonna Laoly, Ignasius Jonan dan Theo Sambuaga', 'E.E. Mangindaan, Yohana Yembise, Yasonna Laoly dan Enggartiasto Lukito', 'Enggartiasto Lukito, Tjahyo Kumolo, Ignasius Jonan dan Rudiantara', 'Ignasius Jonan, Yohana Yembise, Yasonna Laoly dan Luhut Binsar Panjaitan', 'd'),
(2017, 74, 'Siapakah Kepala Dinas Pendidikan Daerah Provinsi Sulawesi Utara sekarang ini ?', 'Steven Evans Liow', 'Gemmy Kawatu', 'Muhammad Nasir', 'Arody Arely Tangkere', 'a'),
(2017, 75, 'Siapakah Pasangan Calon Bupati Kabupaten Sangihe yang menang dalam PILKADA tanggal 15 Februari 2017 ?', 'Hironimus Makagansa-Yabes Gaghana', 'Yabes Gaghana-Helmud Hontong', 'Yasti Supredjo-Yanni Tuuk', 'Hironimus Makagansa-F.A. Silangen', 'a'),
(2017, 76, 'Dalam tari Maengket ada 3 babak utama, Sebutkan', 'Maengket, Marambak dan Manangkup', 'Maowey Kamberu, Marambak dan Lalayaan', 'Maweru Kamberu, Mahambak dan Manangkup', 'Semua salah', 'b');
