-- INSERT INTO soal_tes 2026 FINAL RANDOMIZED (1-500)
DELETE FROM soal_tes WHERE tahun = 2026;
INSERT INTO soal_tes (id, tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, tipe_soal) VALUES
(2001, 2026, 1, 'Berdasarkan Lukas 2:52, aspek pertumbuhan Yesus yang harus diteladani remaja GMIM adalah ...', 'Rohani, sosial, ekonomi, dan politik', 'Fisik, kekayaan, popularitas, dan kuasa', 'Hikmat, umur, kasih karunia, dan kuasa', 'Fisik, hikmat, rohani, dan sosial', 'd', 'pilihan_ganda'),
(2002, 2026, 2, 'Visi pelayanan Remaja GMIM adalah ...', 'Remaja yang berakar, bertumbuh, dan berbuah', 'Remaja Bagi Kristus (Teens for Christ)', 'Remaja Teladan GMIM', 'Remaja Kreatif dan Inovatif', 'b', 'pilihan_ganda'),
(2003, 2026, 3, 'Misi pelayanan Remaja GMIM adalah ...', 'Menjadikan remaja GMIM yang pintar dan berprestasi', 'Menjadikan remaja GMIM yang berakar, bertumbuh, dan berbuah bagi Kristus', 'Menjadikan remaja GMIM yang patuh pada orang tua', 'Menjadikan remaja GMIM yang kaya dan terkenal', 'b', 'pilihan_ganda'),
(2004, 2026, 4, 'Sistem pemerintahan GMIM adalah ...', 'Episkopal', 'Kharismatik', 'Presbiterial Sinodal', 'Kongregasional', 'c', 'pilihan_ganda'),
(2005, 2026, 5, 'GMIM berdiri sendiri sebagai gereja mandiri pada tanggal ...', '28 Januari 1990', '12 Juni 1831', '17 September 1934', '30 September 1934', 'd', 'pilihan_ganda'),
(2006, 2026, 6, 'Komisi Pelayanan Remaja Sinode GMIM (KPRS) berdiri sendiri pada tanggal ...', '30 September 1934', '28 Oktober 1928', '28 Januari 1990', '17 Agustus 1945', 'c', 'pilihan_ganda'),
(2007, 2026, 7, 'Hari Persatuan Remaja GMIM diperingati setiap tanggal ...', '28 Januari', '1 April', '17 Agustus', '30 September', 'a', 'pilihan_ganda'),
(2008, 2026, 8, 'Semboyan Reformasi Gereja "Sola Fide" berarti ...', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'Keselamatan hanya oleh iman', 'd', 'pilihan_ganda'),
(2009, 2026, 9, 'Siapakah penginjil yang dijuluki "Rasul Maluku" dan datang ke Minahasa pada tahun 1817?', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'J.G. Schwarz', 'J.F. Riedel', 'd', 'pilihan_ganda'),
(2010, 2026, 10, 'Apakah kepanjangan dari NZG?', 'Nederlands Zendeling Genootschap', 'Nederland Zending Genootschap', 'Nederlands Zending Genootschap', 'Nederland Zendeling Genootschap', 'c', 'pilihan_ganda'),
(2011, 2026, 11, 'Siapakah nama ayah dari Samuel dalam Perjanjian Lama?', 'Imamat', 'Saul', 'Hana', 'Elkana', 'd', 'pilihan_ganda'),
(2012, 2026, 12, 'Berapa jumlah orang yang dibaptis pada hari Pentakosta?', '120 orang', '12 orang', '5.000 orang', '3.000 orang', 'd', 'pilihan_ganda'),
(2013, 2026, 13, 'Kata "Imago Dei" berarti ...', 'Manusia adalah teman Allah', 'Manusia adalah ciptaan Allah', 'Manusia adalah gambar Allah', 'Manusia adalah hamba Allah', 'c', 'pilihan_ganda'),
(2014, 2026, 14, 'Dalam Tata Gereja GMIM 2021, remaja adalah anggota GMIM berusia ...', '12-17 tahun', '13-17 tahun', '12-16 tahun 364 hari', '12-18 tahun', 'c', 'pilihan_ganda'),
(2015, 2026, 15, 'Satu periode pelayanan BPMS GMIM adalah ...', '6 tahun', '5 tahun', '4 tahun', '3 tahun', 'b', 'pilihan_ganda'),
(2016, 2026, 16, 'Siapakah nama Ketua Sinode GMIM pertama?', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'Ds. E.A.A. de Vreede', 'd', 'pilihan_ganda'),
(2017, 2026, 17, 'Siapakah nama Ketua Sinode GMIM orang Minahasa pertama?', 'Ds. A.Z.R. Wenas', 'Pdt. R.M. Luntungan', 'Ds. E.A.A. de Vreede', 'Pdt. M. Sondakh', 'a', 'pilihan_ganda'),
(2018, 2026, 18, 'Lambang GMIM adalah burung ...', 'Rajawali', 'Merpati', 'Garuda', 'Manguni', 'd', 'pilihan_ganda'),
(2019, 2026, 19, 'Apa makna falsafah Minahasa "Sitou Timou Tumou Tou"?', 'Manusia hidup untuk bersenang-senang', 'Manusia hidup untuk memanusiakan manusia lain', 'Manusia hidup untuk beribadah', 'Manusia hidup untuk bekerja keras', 'b', 'pilihan_ganda'),
(2020, 2026, 20, 'Kepanjangan dari LKRG adalah ...', 'Latihan Kader Remaja Gereja', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'a', 'pilihan_ganda'),
(2021, 2026, 21, 'Program pemuridan KPRS yang disebut KB3 adalah singkatan dari ...', 'Kesatuan Berakar, Bertumbuh, Berbuah', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kelompok Berakar, Bertumbuh, Berbuah', 'Keluarga Berakar, Bertumbuh, Berbuah', 'b', 'pilihan_ganda'),
(2022, 2026, 22, 'Lagu "Menjadi Teladan" diciptakan oleh ...', 'Pnt. Jantje Wowiling Sajow', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. dr. Michaela E. Paruntu', 'Pdt. Dr. Hein Arina', 'b', 'pilihan_ganda'),
(2023, 2026, 23, 'Siapakah yang menulis surat kepada jemaat di Roma?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2024, 2026, 24, '"Aku percaya kepada satu Allah, Bapa yang mahakuasa, Pencipta langit dan bumi" adalah kalimat pembuka dari ...', 'Pengakuan Iman Athanasius', 'Pengakuan Iman Rasuli', 'Doa Bapa Kami', 'Pengakuan Iman Nicea-Konstantinopel', 'd', 'pilihan_ganda'),
(2025, 2026, 25, 'Siapakah yang disebut sebagai "Gembala yang Baik" dalam Yohanes 10?', 'Paulus', 'Daud', 'Yesus Kristus', 'Petrus', 'c', 'pilihan_ganda'),
(2026, 2026, 26, 'Apa inti dari Amanat Agung Yesus dalam Matius 28:19-20?', 'Berdoalah tanpa henti', 'Kasihilah sesamamu seperti dirimu sendiri', 'Pergi, jadikan semua bangsa murid, baptis, dan ajarkan', 'Jangan membunuh dan jangan mencuri', 'c', 'pilihan_ganda'),
(2027, 2026, 27, 'Buah Roh dalam Galatia 5:22-23 terdiri dari ...', 'Hikmat, pengertian, nasihat, keperkasaan', 'Iman, pengharapan, kasih', 'Kemuliaan, hormat, kuasa, kekuatan', 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri', 'd', 'pilihan_ganda'),
(2028, 2026, 28, 'Siapakah yang dilemparkan ke dalam gua singa karena setia berdoa kepada Tuhan?', 'Daud', 'Yusuf', 'Daniel', 'Musa', 'c', 'pilihan_ganda'),
(2029, 2026, 29, 'Program SIKAT yang dikembangkan KPRS adalah singkatan dari ...', 'Sistem Informasi Kegiatan Terkini', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Komunikasi Terpadu', 'Sistem Informasi Keuangan Terpadu', 'b', 'pilihan_ganda'),
(2030, 2026, 30, 'Tahun 2025, KPRS mengadakan program GEMAR yang dikelola bidang ...', 'Pembinaan dan Pengembangan SDM (P3SDM)', 'Pengembangan Minat dan Bakat (PMB)', 'Ajaran, Persekutuan, Ibadah dan Misi (APIM)', 'Teknologi Informasi dan Komunikasi (TIK)', 'c', 'pilihan_ganda'),
(2031, 2026, 31, 'Untuk membantu pelayanan KPRS, dibentuk Koordinatorium Rayon Pelayanan yang dibagi dalam ... rayon', '12', '13', '11', '10', 'a', 'pilihan_ganda'),
(2032, 2026, 32, 'Siapakah nama hamba Imam Besar yang telinga kanannya putus karena dipotong Simon Petrus?', 'Anas', 'Malkhus', 'Kayafas', 'Yudas', 'b', 'pilihan_ganda'),
(2033, 2026, 33, 'Berapakah jumlah pasal dalam kitab Yeremia?', '52', '42', '72', '62', 'a', 'pilihan_ganda'),
(2034, 2026, 34, 'Kota apakah yang disebut sebagai kota Daud?', 'Yerusalem', 'Hebron', 'Nazaret', 'Betlehem', 'd', 'pilihan_ganda'),
(2035, 2026, 35, 'Pada hari ke berapakah Allah menjadikan benda-benda penerang pada cakrawala?', 'Hari kelima', 'Hari ketiga', 'Hari keempat', 'Hari kedua', 'c', 'pilihan_ganda'),
(2036, 2026, 36, 'Berapakah jumlah ikan yang diperoleh para murid setelah Yesus menyuruh menebarkan jala di sebelah kanan perahu?', '153 ekor', '120 ekor', '200 ekor', '150 ekor', 'a', 'pilihan_ganda'),
(2037, 2026, 37, 'Apakah tema mingguan MTPJ pada tanggal 25-31 Mei 2025?', 'Tuhan Allah, Pahlawan yang Memberi Kemenangan', 'Berbahagia dan Kuduslah Mereka yang Mendapat Bagian dalam Kebangkitan', 'Percaya kepada Kristus yang Bangkit', 'Yesus Menampakkan Diri Setelah Bangkit', 'b', 'pilihan_ganda'),
(2038, 2026, 38, 'Siapakah Ketua BPMS GMIM yang memimpin saat GMIM mengubah eklesiologinya menjadi Gereja Global?', 'Pdt. Dr. A.O. Supit', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'd', 'pilihan_ganda'),
(2039, 2026, 39, 'Siapakah penginjil yang datang ke tanah Minahasa pada tahun 1817?', 'Pdt. A.Z.R. Wenas', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Johann Friedrich Riedel', 'd', 'pilihan_ganda'),
(2040, 2026, 40, 'Dalam Tata Dasar Bab II Pasal 7, anggota GMIM adalah ...', 'Semua orang yang tinggal di Minahasa', 'Orang-orang yang lahir di Minahasa', 'Orang-orang percaya kepada Yesus Kristus yang terdaftar di salah satu jemaat GMIM', 'Mereka yang dibaptis di GMIM', 'c', 'pilihan_ganda'),
(2041, 2026, 41, 'Teks "Matahari terbit di timur dan terbenam di barat" merupakan contoh kalimat ...', 'Hipotesis', 'Fakta', 'Asumsi', 'Opini', 'b', 'pilihan_ganda'),
(2042, 2026, 42, 'Pemerintah Indonesia resmi memindahkan Ibu Kota Negara ke ... pada tahun 2024', 'Samarinda', 'Palangkaraya', 'Balikpapan', 'Nusantara (Kalimantan Timur)', 'd', 'pilihan_ganda'),
(2043, 2026, 43, 'The antonym of the word "victory" is ...', 'Success', 'Win', 'Triumph', 'Defeat', 'd', 'pilihan_ganda'),
(2044, 2026, 44, 'Indonesia menjadi tuan rumah KTT G20 pada tahun ...', '2025', '2022', '2023', '2024', 'b', 'pilihan_ganda'),
(2045, 2026, 45, 'Hasil dari 25 × 4 - 100 ÷ 5 adalah ...', '120', '100', '90', '80', 'd', 'pilihan_ganda'),
(2046, 2026, 46, 'Apa nama gunung berapi di Sulawesi Utara yang meletus pada April 2024?', 'Gunung Lokon', 'Gunung Ruang', 'Gunung Karangetang', 'Gunung Soputan', 'b', 'pilihan_ganda'),
(2047, 2026, 47, 'KTT G20 tahun 2025 dilaksanakan di negara ...', 'India', 'Brasil', 'Indonesia', 'Afrika Selatan', 'd', 'pilihan_ganda'),
(2048, 2026, 48, 'Kepanjangan dari AI (kecerdasan buatan) dalam bahasa Inggris adalah ...', 'Automated Intelligence', 'Artificial Information', 'Advanced Integration', 'Artificial Intelligence', 'd', 'pilihan_ganda'),
(2049, 2026, 49, 'Negara yang tidak pernah mengalami penjajahan di Asia Tenggara adalah ...', 'Malaysia', 'Thailand', 'Vietnam', 'Indonesia', 'b', 'pilihan_ganda'),
(2050, 2026, 50, 'Ciri utama dari sistem ekonomi Pancasila adalah ...', 'Kekeluargaan dan gotong royong', 'Terpusat dan komando', 'Bebas dan liberal', 'Kapitalis dan individualis', 'a', 'pilihan_ganda'),
(2051, 2026, 51, 'Model remaja GMIM yang diharapkan berdasarkan Lukas 2:52 adalah remaja yang bertumbuh dalam ...', 'Fisik, ekonomi, politik, dan budaya', 'Fisik, hikmat, rohani, dan sosial', 'Rohani, intelektual, ekonomi, dan sosial', 'Hikmat, popularitas, kekayaan, dan kuasa', 'b', 'pilihan_ganda'),
(2052, 2026, 52, 'Visi "Remaja Bagi Kristus" mengandung makna bahwa ...', 'Remaja harus menjadi pendeta', 'Remaja hanya datang ke gereja pada hari Minggu', 'Seluruh hidup remaja dipersembahkan bagi Kristus', 'Remaja harus meninggalkan dunia', 'c', 'pilihan_ganda'),
(2053, 2026, 53, 'Tujuan program LKRG adalah ...', 'Mempersiapkan remaja menjadi atlet', 'Mengajarkan remaja keterampilan digital', 'Mempersiapkan kader remaja yang militan dan berkarakter Kristus', 'Melatih remaja menjadi pengusaha sukses', 'c', 'pilihan_ganda'),
(2054, 2026, 54, 'Sakramen yang dilayankan GMIM adalah ...', 'Baptisan, Krisma, dan Perjamuan Kudus', 'Baptisan Kudus dan Perjamuan Kudus', 'Perjamuan Kudus dan Pengakuan Dosa', 'Baptisan, Perjamuan Kudus, dan Pernikahan', 'b', 'pilihan_ganda'),
(2055, 2026, 55, 'Pembukaan Tata Gereja GMIM 2021 menyatakan bahwa GMIM adalah bagian dari ...', 'Gereja Katolik', 'Gereja Pentakosta', 'Gereja Protestan di Indonesia', 'Gereja Orthodox', 'c', 'pilihan_ganda'),
(2056, 2026, 56, 'Pemilihan Remaja Teladan GMIM memiliki tahapan akhir yang disebut ...', 'Pelayanan Holistik', 'Kompetisi Potensi Diri', 'Grand Final', 'Karantina', 'c', 'pilihan_ganda'),
(2057, 2026, 57, 'Bobot penilaian untuk tahap Karantina dan Pelayanan Holistik dalam Pemilihan Remaja Teladan adalah ...', '25%', '35%', '20%', '15%', 'b', 'pilihan_ganda'),
(2058, 2026, 58, 'Semboyan Reformasi "Sola Gratia" berarti ...', 'Keselamatan hanya oleh Alkitab', 'Keselamatan hanya oleh iman', 'Kemuliaan hanya bagi Tuhan', 'Keselamatan hanya oleh kasih karunia', 'd', 'pilihan_ganda'),
(2059, 2026, 59, 'Siapa yang mencetuskan Reformasi Gereja pada tahun 1517?', 'Ulrich Zwingli', 'Yohanes Calvin', 'Martin Luther', 'John Knox', 'c', 'pilihan_ganda'),
(2060, 2026, 60, 'Apakah yang dimaksud dengan "Presbiterial Sinodal"?', 'Sistem kepemimpinan yang terpusat', 'Sistem kepemimpinan yang demokratis', 'Sistem kepemimpinan kolektif para penatua dengan musyawarah', 'Sistem kepemimpinan satu uskup', 'c', 'pilihan_ganda'),
(2061, 2026, 61, 'Siapakah yang menggantikan Yudas Iskariot sebagai rasul?', 'Filipus', 'Stefanus', 'Barnabas', 'Matias', 'd', 'pilihan_ganda'),
(2062, 2026, 62, 'Berapa jumlah kitab dalam Perjanjian Baru?', '24', '27', '66', '39', 'b', 'pilihan_ganda'),
(2063, 2026, 63, 'Nats "Jangan seorang pun menganggap engkau rendah karena engkau muda" terdapat dalam ...', '1 Timotius 4:12', 'Efesus 4:12', 'Titus 4:12', '2 Timotius 4:12', 'a', 'pilihan_ganda'),
(2064, 2026, 64, 'Dalam Tata Gereja GMIM 2021, satu periode pelayanan GMIM adalah ...', '4 tahun', '6 tahun', '5 tahun', '3 tahun', 'c', 'pilihan_ganda'),
(2065, 2026, 65, 'Tahun pelayanan dan tahun anggaran GMIM dimulai tanggal ...', '1 Juli sampai 30 Juni', '1 April sampai 31 Maret', '1 Maret sampai 28 Februari', '1 Januari sampai 31 Desember', 'd', 'pilihan_ganda'),
(2066, 2026, 66, 'Siapakah Ketua Sinode GMIM yang menjabat dua periode?', 'Pdt. Piet M. Tampi', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas dan Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'c', 'pilihan_ganda'),
(2067, 2026, 67, 'Siapakah yang mengutus misionaris Schwarz dan Riedel ke Minahasa?', 'Zending Belanda', 'NZG (Nederlands Zending Genootschap)', 'Indische Kerk', 'Gereja Reformasi Belanda', 'b', 'pilihan_ganda'),
(2068, 2026, 68, 'Apa warna dasar selempang untuk finalis Remaja Teladan tingkat Sinode?', 'Ungu dengan tulisan perak', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'c', 'pilihan_ganda'),
(2069, 2026, 69, 'Apa makna burung Manguni dalam lambang GMIM?', 'Gereja yang kaya raya', 'Gereja sebagai terang di tengah kegelapan', 'Gereja yang kuat dan perkasa', 'Gereja yang modern', 'b', 'pilihan_ganda'),
(2070, 2026, 70, 'Kepanjangan dari PKRS adalah ...', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'a', 'pilihan_ganda'),
(2071, 2026, 71, 'Siapakah yang menciptakan Mars Remaja GMIM?', 'Pnt. Jantje Wowiling Sajow', 'Pnt. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pdt. Hein Arina', 'a', 'pilihan_ganda'),
(2072, 2026, 72, 'Program GEMAR (Gerakan Membaca Alkitab Remaja) bertujuan untuk ...', 'Mengadakan lomba cerdas cermat Alkitab', 'Melatih remaja menjadi pengkhotbah', 'Mengajarkan remaja bermain musik', 'Mendorong remaja membaca Alkitab secara terstruktur', 'd', 'pilihan_ganda'),
(2073, 2026, 73, 'Siapakah yang menulis kitab Wahyu?', 'Paulus', 'Petrus', 'Yakobus', 'Yohanes', 'd', 'pilihan_ganda'),
(2074, 2026, 74, '"Aku percaya kepada Allah, Bapa yang mahakuasa, Khalik langit dan bumi" adalah pengakuan iman ...', 'Pengakuan Iman Nicea-Konstantinopel', 'Pengakuan Iman Athanasius', 'Pengakuan Iman Rasuli', 'Doa Bapa Kami', 'c', 'pilihan_ganda'),
(2075, 2026, 75, 'Siapakah yang disebut sebagai "Bapa Orang Percaya"?', 'Musa', 'Adam', 'Abraham', 'Daud', 'c', 'pilihan_ganda'),
(2076, 2026, 76, 'Apa isi dari Sepuluh Perintah Allah (Dekalog)?', 'Perintah untuk beribadah setiap hari', 'Perintah untuk berpuasa', 'Perintah untuk mengasihi Tuhan dan sesama', 'Perintah untuk bersedekah', 'c', 'pilihan_ganda'),
(2077, 2026, 77, 'Karunia Roh Kudus dalam 1 Korintus 12 antara lain ...', 'Bernubuat, melayani, mengajar, menasihati', 'Bernyanyi, menari, bermusik, melukis', 'Semua jawaban benar', 'Berbicara dalam bahasa roh, menyembuhkan', 'a', 'pilihan_ganda'),
(2078, 2026, 78, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja Babel?', 'Yusuf', 'Musa', 'Daud', 'Daniel', 'd', 'pilihan_ganda'),
(2079, 2026, 79, 'Tuan rumah Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2025 adalah ...', 'Wilayah Tondano', 'Wilayah Tomohon', 'Wilayah Airmadidi', 'Wilayah Sinel', 'd', 'pilihan_ganda'),
(2080, 2026, 80, 'Bidang P3SDM dalam KPRS memiliki kepanjangan ...', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'Perencanaan, Pengorganisasian, dan Pengawasan SDM', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'd', 'pilihan_ganda'),
(2081, 2026, 81, 'Wakil Sekretaris Koordinasi Program antar Komisi Pelayanan Kategorial Sinode GMIM adalah ...', 'Pdt. DR. Joice Sondakh, M.Th', 'Pdt. Christian Luwuk, M.Th', 'Pdt. Jefry Saisab, S.Th, M.Si', 'Pdt. Hein Arina, Th.D', 'c', 'pilihan_ganda'),
(2082, 2026, 82, 'Siapakah nama isteri Yusuf dalam Kejadian pasal 41?', 'Abisag', 'Potifera', 'Asnat', 'Dina', 'c', 'pilihan_ganda'),
(2083, 2026, 83, 'Berapakah jumlah pasal dalam kitab Mazmur yang paling panjang?', '119', '150', '117', '100', 'a', 'pilihan_ganda'),
(2084, 2026, 84, 'Kota apakah yang menjadi tempat kelahiran Yesus?', 'Betlehem', 'Nazaret', 'Yerusalem', 'Kapernaum', 'a', 'pilihan_ganda'),
(2085, 2026, 85, 'Siapakah nama ibu dari Samuel?', 'Elkana', 'Sara', 'Hana', 'Ribka', 'c', 'pilihan_ganda'),
(2086, 2026, 86, 'Apakah nama lain yang diberikan kepada Daniel oleh pegawai istana Babel?', 'Beltsazar', 'Sadrakh', 'Mesakh', 'Abednego', 'a', 'pilihan_ganda'),
(2087, 2026, 87, 'Apakah judul perikop dari Roma 10:4-15?', 'Kebenaran karena iman', 'Keselamatan oleh kasih karunia', 'Pembenaran oleh iman', 'Ketaatan karena iman', 'a', 'pilihan_ganda'),
(2088, 2026, 88, 'Siapakah Ketua Komisi Pelayanan Remaja Sinode GMIM periode 2022-2027?', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Edward Saragih, SAP', 'Pnt. Melky R. Pattiwael, S.IK, M.S', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'a', 'pilihan_ganda'),
(2089, 2026, 89, 'Siapakah nama misionaris yang melayani di Langowan dan Kakas?', 'J.G. Schwarz', 'Pdt. A.Z.R. Wenas', 'Ds. E.A.A. de Vreede', 'J.F. Riedel', 'a', 'pilihan_ganda'),
(2090, 2026, 90, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 1, penyelenggaraan panggilan GMIM bersumber dari ...', 'Pola pelayanan dan pemerintahan Kristus', 'Kesaksian Alkitab', 'Yesus Kristus', 'Tata Gereja GMIM', 'a', 'pilihan_ganda'),
(2091, 2026, 91, 'Teks "Sayur itu akan terasa lebih sedap jika ditambah sedikit garam" merupakan contoh kalimat ...', 'Asumsi', 'Deskripsi', 'Fakta', 'Opini', 'a', 'pilihan_ganda'),
(2092, 2026, 92, 'Siapa presiden terpilih Indonesia pada Pemilu 2024?', 'Anies Baswedan', 'Prabowo Subianto', 'Ganjar Pranowo', 'Joko Widodo', 'b', 'pilihan_ganda'),
(2093, 2026, 93, 'Which sentence uses the correct conditional form?', 'If I study hard, I would pass the exam', 'If I study hard, I will pass the exam', 'If I studied hard, I will pass the exam', 'If I will study hard, I will pass the exam', 'b', 'pilihan_ganda'),
(2094, 2026, 94, 'Indonesia menjadi anggota BRICS pada tahun ...', '2022', '2023', '2025', '2024', 'd', 'pilihan_ganda'),
(2095, 2026, 95, 'Sebuah kubus memiliki panjang sisi 4 cm. Volume kubus tersebut adalah ...', '64 cm³', '16 cm³', '48 cm³', '32 cm³', 'a', 'pilihan_ganda'),
(2096, 2026, 96, 'Apa nama bendungan yang diresmikan Presiden Jokowi di Sulawesi Utara pada Februari 2024?', 'Bendungan Tondano', 'Bendungan Kuwi', 'Bendungan Kuwil', 'Bendungan Lolak', 'd', 'pilihan_ganda'),
(2097, 2026, 97, 'Piala Dunia FIFA 2026 akan diselenggarakan bersama oleh negara ...', 'Amerika Serikat, Kanada, Meksiko', 'Amerika Serikat, Inggris, Prancis', 'Kanada, Meksiko, Brasil', 'Spanyol, Portugal, Maroko', 'a', 'pilihan_ganda'),
(2098, 2026, 98, 'Kepanjangan dari API dalam bidang teknologi adalah ...', 'Automated Programming Integration', 'Application Programming Interface', 'Application Processing Interface', 'Advanced Programming Interface', 'b', 'pilihan_ganda'),
(2099, 2026, 99, 'Negara dengan jumlah penduduk terbanyak di dunia adalah ...', 'Indonesia', 'India', 'Amerika Serikat', 'China', 'b', 'pilihan_ganda'),
(2100, 2026, 100, 'Kebijakan pemerintah Indonesia untuk membatasi penggunaan media sosial bagi anak di bawah umur disebut ...', 'Internet filter', 'Social media ban', 'Digital restriction', 'Pembatasan usia pengguna medsos', 'd', 'pilihan_ganda'),
(2101, 2026, 101, 'Makna dari "Remaja Teladan" menurut Pola Baku GMIM adalah ...', 'Remaja yang populer di media sosial', 'Remaja yang menjadi ketua OSIS', 'Remaja yang memiliki prestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang kaya dan terkenal', 'c', 'pilihan_ganda'),
(2102, 2026, 102, 'Salah satu aspek yang dinilai dalam Pemilihan Remaja Teladan adalah ...', 'Kekayaan orang tua', 'Pelayanan Holistik', 'Popularitas di media sosial', 'Jumlah teman', 'b', 'pilihan_ganda'),
(2103, 2026, 103, 'Kepanjangan dari P3SDM dalam struktur KPRS adalah ...', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'c', 'pilihan_ganda'),
(2104, 2026, 104, 'Sakramen Baptisan Kudus dalam GMIM dilayankan ...', 'Sekali seumur hidup', 'Sebelum menikah', 'Setiap tahun', 'Setiap kali bertobat', 'a', 'pilihan_ganda'),
(2105, 2026, 105, 'Badan Pekerja Majelis Sinode (BPMS) dipilih setiap ...', '6 tahun sekali', '4 tahun sekali', '5 tahun sekali dalam Sidang Majelis Sinode', '3 tahun sekali', 'c', 'pilihan_ganda'),
(2106, 2026, 106, 'Tahapan seleksi Pemilihan Remaja Teladan yang berupa pengabdian kepada jemaat adalah ...', 'Tes Wawancara', 'Kompetisi Potensi Diri', 'Pelayanan Holistik', 'Karantina', 'c', 'pilihan_ganda'),
(2107, 2026, 107, 'Bobot penilaian untuk tahap Kompetisi Potensi Diri adalah ...', '20%', '15%', '35%', '25%', 'd', 'pilihan_ganda'),
(2108, 2026, 108, 'Semboyan Reformasi "Soli Deo Gloria" berarti ...', 'Keselamatan hanya oleh iman', 'Segala kemuliaan hanya bagi Tuhan', 'Hanya Alkitab sebagai otoritas', 'Keselamatan hanya oleh kasih karunia', 'b', 'pilihan_ganda'),
(2109, 2026, 109, 'Apa yang dimaksud dengan "Indische Kerk"?', 'Gereja yang didirikan oleh para misionaris', 'Gereja Hindia Belanda yang menjadi cikal bakal GMIM', 'Gereja di tanah Minahasa', 'Gereja pertama di Indonesia', 'b', 'pilihan_ganda'),
(2110, 2026, 110, 'Siapakah Ketua BPMS GMIM periode 2018-2022?', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. Hein Arina', 'd', 'pilihan_ganda'),
(2111, 2026, 111, 'Siapakah yang menulis kitab Amsal?', 'Daud', 'Musa', 'Yeremia', 'Salomo', 'd', 'pilihan_ganda'),
(2112, 2026, 112, 'Berapa jumlah kitab dalam Perjanjian Lama?', '27', '40', '66', '39', 'd', 'pilihan_ganda'),
(2113, 2026, 113, 'Ayat terpendek dalam Alkitab adalah ...', 'Yohanes 11:35', '1 Tesalonika 5:16', 'Amsal 20:10', 'Mazmur 117:1', 'a', 'pilihan_ganda'),
(2114, 2026, 114, 'Dalam Peraturan tentang Jemaat, remaja adalah anggota GMIM berusia ...', '12-17 tahun', '13-17 tahun', '11-16 tahun', '12-16 tahun 364 hari', 'd', 'pilihan_ganda'),
(2115, 2026, 115, 'Tahun pelayanan BPMJ dimulai tanggal ...', '1 Januari', '1 April', '1 Juli', '1 Maret', 'a', 'pilihan_ganda'),
(2116, 2026, 116, 'Siapakah Ketua Sinode GMIM yang dikenal dengan slogan "Tuhan mengangkat kita dari Samudera Raya"?', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. Hein Arina', 'd', 'pilihan_ganda'),
(2117, 2026, 117, 'Siapakah nama misionaris yang melayani di Tondano?', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'J.G. Schwarz', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2118, 2026, 118, 'Apa warna selempang untuk finalis Remaja Teladan tingkat Wilayah?', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan perak', 'b', 'pilihan_ganda'),
(2119, 2026, 119, 'Tarian tradisional Minahasa yang menggambarkan sukacita panen adalah ...', 'Tari Gantar', 'Tari Cakalele', 'Tari Maengket', 'Tari Kabasaran', 'c', 'pilihan_ganda'),
(2120, 2026, 120, 'Kepanjangan dari PSR (dalam kegiatan remaja) adalah ...', 'Pekan Seni Remaja', 'Perkemahan Seni Remaja', 'Pentas Seni Remaja', 'Pesta Seni Remaja', 'd', 'pilihan_ganda'),
(2121, 2026, 121, 'Lagu Mars Remaja GMIM pertama kali diperkenalkan pada tahun ...', '2005', '1990', '2000', '1995', 'b', 'pilihan_ganda'),
(2122, 2026, 122, 'Siapakah Ketua KPRS periode 2014-2018?', 'Pnt. Edward Saragih', 'Pnt. dr. Michaela E. Paruntu', 'Pnt. Melky R. Pattiwael', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'd', 'pilihan_ganda'),
(2123, 2026, 123, 'Siapakah yang menulis surat kepada jemaat di Korintus?', 'Petrus', 'Paulus', 'Yohanes', 'Yakobus', 'b', 'pilihan_ganda'),
(2124, 2026, 124, 'Perikop terpendek dalam Mazmur adalah ...', 'Mazmur 150:1-6', 'Mazmur 1:1-6', 'Mazmur 23:1-6', 'Mazmur 117:1-2', 'd', 'pilihan_ganda'),
(2125, 2026, 125, 'Siapakah yang menulis kitab Kisah Para Rasul?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'a', 'pilihan_ganda'),
(2126, 2026, 126, 'Apa pesan utama dari perumpamaan tentang Talenta?', 'Kita harus mengembangkan karunia yang Tuhan berikan', 'Kita harus menyembunyikan talenta', 'Kita harus mencari talenta sebanyak-banyaknya', 'Kita harus membuang talenta yang tidak berguna', 'a', 'pilihan_ganda'),
(2127, 2026, 127, 'Dalam 1 Korintus 13, yang paling besar di antara iman, pengharapan, dan kasih adalah ...', 'Ketiganya sama besar', 'Iman', 'Kasih', 'Pengharapan', 'c', 'pilihan_ganda'),
(2128, 2026, 128, 'Siapakah yang dijual oleh saudara-saudaranya ke Mesir?', 'Daud', 'Yusuf', 'Musa', 'Daniel', 'b', 'pilihan_ganda'),
(2129, 2026, 129, 'Sistem Informasi Kegiatan Terpadu (SIKAT) dikembangkan oleh bidang ...', 'P3SDM', 'APIM', 'PMB', 'TIK KPRS', 'd', 'pilihan_ganda'),
(2130, 2026, 130, 'Gelar atribut "Remaja Teladan Intelegensia" diukur dari ...', '100% nilai wawancara', '50% nilai wawancara dan 50% nilai karantina', '100% nilai tes tertulis', '50% nilai tes tertulis dan 50% nilai psikotes karantina', 'd', 'pilihan_ganda'),
(2131, 2026, 131, 'Gelar atribut "Remaja Teladan Persahabatan" diukur dari ...', 'Pilihan dari sesama peserta', 'Nilai psikotes', 'Penilaian juri', 'Like di media sosial', 'a', 'pilihan_ganda'),
(2132, 2026, 132, 'Siapakah nama ibu dari Yesus?', 'Salome', 'Maria', 'Marta', 'Elisabeth', 'b', 'pilihan_ganda'),
(2133, 2026, 133, 'Berapakah jumlah pasal dalam kitab Yesaya?', '66', '52', '50', '42', 'a', 'pilihan_ganda'),
(2134, 2026, 134, 'Di manakah Yesus dibaptis oleh Yohanes Pembaptis?', 'Danau Galilea', 'Bukit Zaitun', 'Laut Mati', 'Sungai Yordan', 'd', 'pilihan_ganda'),
(2135, 2026, 135, 'Siapakah yang menjadi raja pertama Israel?', 'Salomo', 'Yerobeam', 'Daud', 'Saul', 'd', 'pilihan_ganda'),
(2136, 2026, 136, 'Berapa lamakah bangsa Israel berjalan di padang gurun?', '10 tahun', '30 tahun', '40 tahun', '20 tahun', 'c', 'pilihan_ganda'),
(2137, 2026, 137, 'Apakah tema MTPJ yang berfokus pada "Kebangkitan Yesus mengubah manusia"?', 'Pentakosta', 'Natal', 'Adven', 'Paskah', 'd', 'pilihan_ganda'),
(2138, 2026, 138, 'Siapakah Wakil Sekretaris BPMS Bidang Pekerja GMIM dan Pelayan Khusus periode 2014-2018?', 'Pdt. Janny Rende', 'Pnt. Jhonly Th Wenur, SH, MH, MM', 'Pdt. Altje Runtu-Lumi', 'Pdt. Richard Mengko', 'b', 'pilihan_ganda'),
(2139, 2026, 139, 'Di manakah makam penginjil Ulfers berada?', 'Kakas', 'Tondano', 'Tomohon', 'Langowan', 'c', 'pilihan_ganda'),
(2140, 2026, 140, 'Dalam Tata Dasar Bab III Pasal 8, GMIM ditata dalam sistem ...', 'Episkopal', 'Kongregasional', 'Sinodal', 'Presbiterial Sinodal', 'd', 'pilihan_ganda'),
(2141, 2026, 141, 'Kata "hiperbola" dalam kalimat memiliki arti ...', 'Gambaran yang nyata', 'Simbolisme yang mendalam', 'Perbandingan yang berlebihan', 'Makna yang tersembunyi', 'c', 'pilihan_ganda'),
(2142, 2026, 142, 'Indonesia menjadi tuan rumah KTT ASEAN pada tahun ...', '2024', '2025', '2022', '2023', 'd', 'pilihan_ganda'),
(2143, 2026, 143, 'The word "meticulous" is closest in meaning to ...', 'Careless', 'Lazy', 'Impulsive', 'Detail-oriented', 'd', 'pilihan_ganda'),
(2144, 2026, 144, 'Contoh cryptocurrency yang dikenal luas adalah ...', 'Bitcoin', 'Apple Cash', 'Google Pay', 'Facebook Coin', 'a', 'pilihan_ganda'),
(2145, 2026, 145, 'Diketahui deret aritmatika 3, 7, 11, 15,... Suku ke-10 adalah ...', '35', '43', '31', '39', 'd', 'pilihan_ganda'),
(2146, 2026, 146, 'Proses fotosintesis menghasilkan ...', 'Energi panas', 'Protein dan lemak', 'Karbon dioksida dan air', 'Oksigen dan glukosa', 'd', 'pilihan_ganda'),
(2147, 2026, 147, 'Piala Dunia U-20 tahun 2023 seharusnya diselenggarakan di ...', 'Afrika Selatan', 'Argentina', 'Qatar', 'Indonesia', 'd', 'pilihan_ganda'),
(2148, 2026, 148, 'Siapa yang dikenal sebagai "Bapak Komputer" (penemu komputer modern)?', 'Alan Turing', 'Mark Zuckerberg', 'Steve Jobs', 'Bill Gates', 'a', 'pilihan_ganda'),
(2149, 2026, 149, 'Lembaga yang bertugas menangani korupsi di Indonesia adalah ...', 'BPK', 'KPK (Komisi Pemberantasan Korupsi)', 'BPKP', 'Kejaksaan Agung', 'b', 'pilihan_ganda'),
(2150, 2026, 150, 'Program ketahanan pangan yang digalakkan pemerintah Indonesia disebut ...', 'Dapur sehat', 'Makan gratis', 'Ketahanan pangan mandiri', 'Program beras murah', 'c', 'pilihan_ganda'),
(2151, 2026, 151, 'Apa yang dimaksud dengan "Remaja Teladan" menurut Pola Baku GMIM?', 'Remaja usia 12-16 tahun yang berprestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang memiliki orang tua kaya', 'Remaja yang populer di lingkungan gereja', 'Remaja yang menjadi pengurus komisi remaja', 'a', 'pilihan_ganda'),
(2152, 2026, 152, 'Siapakah yang menulis kitab Mazmur sebagian besar?', 'Salomo', 'Musa', 'Daud', 'Yeremia', 'c', 'pilihan_ganda'),
(2153, 2026, 153, 'Apa kepanjangan dari KPRS?', 'Komisi Pembinaan Remaja Sinode', 'Komisi Pelayanan Remaja Sekunder', 'Komisi Pelayanan Remaja Sinode', 'Kelompok Pelayanan Remaja Sinode', 'c', 'pilihan_ganda'),
(2154, 2026, 154, 'Di manakah Yesus lahir?', 'Yerusalem', 'Nazaret', 'Kapernaum', 'Betlehem', 'd', 'pilihan_ganda'),
(2155, 2026, 155, 'Apa warna selempang untuk finalis Remaja Teladan tingkat Jemaat?', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan perak', 'd', 'pilihan_ganda'),
(2156, 2026, 156, 'Siapakah yang disebut sebagai "Bapak Reformasi Gereja"?', 'Yohanes Calvin', 'Martin Luther', 'Ulrich Zwingli', 'John Knox', 'b', 'pilihan_ganda'),
(2157, 2026, 157, 'Apa singkatan dari LTPR?', 'Latihan Tenaga Pembina Remaja', 'Latihan Teknis Pembina Remaja', 'Latihan Tugas Pembina Remaja', 'Latihan Terpadu Pembina Remaja', 'a', 'pilihan_ganda'),
(2158, 2026, 158, 'Siapakah yang menulis surat kepada jemaat di Galatia?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2159, 2026, 159, 'Berapa jumlah rayon pelayanan KPRS GMIM?', '13 Rayon', '12 Rayon', '10 Rayon', '11 Rayon', 'b', 'pilihan_ganda'),
(2160, 2026, 160, 'Apa inti dari Hukum Taurat yang terutama?', 'Kasih kepada Tuhan dan sesama', 'Jangan mencuri', 'Hormati orang tua', 'Jangan membunuh', 'a', 'pilihan_ganda'),
(2161, 2026, 161, 'Siapakah Ketua KPRS GMIM periode pertama?', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. Drs. Jimmy Mamahit', 'Pnt. Drs. Jantje Sajow', 'Pnt. Drs. Jacobus Wowor', 'd', 'pilihan_ganda'),
(2162, 2026, 162, 'Apa arti kata "Injil"?', 'Kabar Keselamatan', 'Firman Tuhan', 'Kabar Baik', 'Ajaran Yesus', 'c', 'pilihan_ganda'),
(2163, 2026, 163, 'Program KB3 dalam KPRS adalah singkatan dari ...', 'Kelompok Belajar Bersama', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kegiatan Bina Bakat Berkah', 'Komisi Bina Berkat Bersama', 'b', 'pilihan_ganda'),
(2164, 2026, 164, 'Siapakah yang menggantikan Yudas Iskariot sebagai rasul?', 'Stefanus', 'Filipus', 'Matias', 'Barnabas', 'c', 'pilihan_ganda'),
(2165, 2026, 165, 'Apa kepanjangan dari BPMS?', 'Badan Pelayanan Majelis Sinode', 'Badan Pekerja Majelis Sinode', 'Badan Pengawas Majelis Sinode', 'Badan Pengurus Majelis Sinode', 'b', 'pilihan_ganda'),
(2166, 2026, 166, 'Siapakah yang menulis kitab Wahyu?', 'Yakobus', 'Paulus', 'Petrus', 'Yohanes', 'd', 'pilihan_ganda'),
(2167, 2026, 167, 'Apa tema pelayanan GMIM periode 2018-2022?', 'Berakar, Bertumbuh, Berbuah', 'Gereja Global', 'Remaja Bagi Kristus', 'Tuhan mengangkat kita dari Samudera Raya', 'd', 'pilihan_ganda'),
(2168, 2026, 168, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja?', 'Yusuf', 'Musa', 'Daud', 'Daniel', 'd', 'pilihan_ganda'),
(2169, 2026, 169, 'Apa kepanjangan dari PKRS?', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'a', 'pilihan_ganda'),
(2170, 2026, 170, 'Apa isi dari Pengakuan Iman Rasuli?', 'Aku percaya kepada Allah Bapa, Yesus Kristus, dan Roh Kudus', 'Aku percaya kepada Yesus saja', 'Aku percaya kepada Allah saja', 'Aku percaya kepada para nabi', 'a', 'pilihan_ganda'),
(2171, 2026, 171, 'Siapakah Ketua KPRS periode 2022-2027?', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Edward Saragih', 'Pnt. Melky R. Pattiwael', 'b', 'pilihan_ganda'),
(2172, 2026, 172, 'Apa nama sungai yang ada di taman Eden?', 'Nil, Tigris, Efrat, Yordan', 'Efrat, Tigris, Nil, Gangga', 'Amazon, Tigris, Efrat, Nil', 'Pison, Gihon, Tigris, Efrat', 'd', 'pilihan_ganda'),
(2173, 2026, 173, 'Apa makna warna ungu pada selempang finalis?', 'Kemurnian dan kesucian', 'Nuansa kerendahan hati dan kesetiaan', 'Kekuasaan dan kehormatan', 'Kegembiraan dan sukacita', 'b', 'pilihan_ganda'),
(2174, 2026, 174, 'Siapakah yang menjadi raja pertama Israel?', 'Daud', 'Salomo', 'Yerobeam', 'Saul', 'd', 'pilihan_ganda'),
(2175, 2026, 175, 'Apa kepanjangan dari SIKAT?', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Kegiatan Terkini', 'Sistem Informasi Keuangan Terpadu', 'Sistem Informasi Komunikasi Terpadu', 'a', 'pilihan_ganda'),
(2176, 2026, 176, 'Siapakah yang menulis kitab Amsal?', 'Musa', 'Yeremia', 'Salomo', 'Daud', 'c', 'pilihan_ganda'),
(2177, 2026, 177, 'Berapa jumlah pasal dalam kitab Mazmur?', '66', '150', '120', '100', 'b', 'pilihan_ganda'),
(2178, 2026, 178, 'Apa arti "Sitou Timou Tumou Tou"?', 'Bekerja keras untuk sukses', 'Manusia hidup untuk memanusiakan manusia lain', 'Hormati orang tua', 'Hidup adalah perjuangan', 'b', 'pilihan_ganda'),
(2179, 2026, 179, 'Siapakah nama misionaris yang melayani di Tondano?', 'Ds. E.A.A. de Vreede', 'J.G. Schwarz', 'J.F. Riedel', 'Pdt. A.Z.R. Wenas', 'c', 'pilihan_ganda'),
(2180, 2026, 180, 'Apa yang dimaksud dengan "Sakramen"?', 'Upacara adat gereja', 'Ritual keagamaan', 'Perayaan hari raya', 'Tanda dan meterai kasih karunia Allah yang kelihatan', 'd', 'pilihan_ganda'),
(2181, 2026, 181, 'Siapakah yang dijual oleh saudara-saudaranya ke Mesir?', 'Daniel', 'Daud', 'Musa', 'Yusuf', 'd', 'pilihan_ganda'),
(2182, 2026, 182, 'Apa tema HPRG (Hari Persatuan Remaja GMIM)?', 'Remaja Bagi Kristus', 'Remaja Kreatif', 'Remaja Cinta Damai', 'Remaja Berprestasi', 'a', 'pilihan_ganda'),
(2183, 2026, 183, 'Siapakah yang menulis surat kepada jemaat di Efesus?', 'Paulus', 'Yohanes', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2184, 2026, 184, 'Berapa usia minimal peserta Pemilihan Remaja Teladan?', '15 tahun', '12 tahun', '14 tahun', '13 tahun', 'b', 'pilihan_ganda'),
(2185, 2026, 185, 'Apa nama gunung tempat Yesus berdoa sebelum ditangkap?', 'Bukit Zaitun', 'Gunung Tabor', 'Gunung Sinai', 'Gunung Hermon', 'a', 'pilihan_ganda'),
(2186, 2026, 186, 'Siapakah yang menjadi Ketua Sinode GMIM pertama dari Minahasa?', 'Ds. A.Z.R. Wenas', 'Pdt. M. Sondakh', 'Ds. E.A.A. de Vreede', 'Pdt. R.M. Luntungan', 'a', 'pilihan_ganda'),
(2187, 2026, 187, 'Apa arti kata "Eli, Eli, lama sabakhtani"?', 'Aku haus', 'Ya Bapa, ke dalam tangan-Mu', 'Ya Tuhan, ampunilah mereka', 'Allah-Ku, Allah-Ku, mengapa Engkau meninggalkan Aku?', 'd', 'pilihan_ganda'),
(2188, 2026, 188, 'Berapa jumlah bidang dalam KPRS GMIM periode 2022-2027?', '7 bidang', '10 bidang', '8 bidang', '9 bidang', 'a', 'pilihan_ganda'),
(2189, 2026, 189, 'Siapakah yang disebut sebagai "Gembala yang Baik"?', 'Daud', 'Petrus', 'Paulus', 'Yesus Kristus', 'd', 'pilihan_ganda'),
(2190, 2026, 190, 'Apa kepanjangan dari MTPJ?', 'Minggu Tanggung Jawab Pelayanan Jemaat', 'Materi Tugas Pelayanan Jemaat', 'Materi Tanggung Jawab Pelayanan Jemaat', 'Materi Pembacaan dan Tanggung Jawab Pelayanan Jemaat', 'd', 'pilihan_ganda'),
(2191, 2026, 191, 'Teks "Indonesia adalah negara kepulauan terbesar di dunia" merupakan kalimat ...', 'Hipotesis', 'Opini', 'Asumsi', 'Fakta', 'd', 'pilihan_ganda'),
(2192, 2026, 192, 'Siapa Presiden Indonesia periode 2014-2024?', 'Prabowo Subianto', 'Joko Widodo', 'Susilo Bambang Yudhoyono', 'Megawati Sukarnoputri', 'b', 'pilihan_ganda'),
(2193, 2026, 193, 'The word "success" is antonym of ...', 'Triumph', 'Achievement', 'Failure', 'Victory', 'c', 'pilihan_ganda'),
(2194, 2026, 194, 'Indonesia menjadi tuan rumah KTT G20 pada tahun ...', '2022', '2023', '2024', '2021', 'a', 'pilihan_ganda'),
(2195, 2026, 195, 'Hasil dari 15 × 6 - 30 ÷ 5 adalah ...', '84', '78', '80', '90', 'a', 'pilihan_ganda'),
(2196, 2026, 196, 'Apa nama gunung tertinggi di Sulawesi Utara?', 'Gunung Ruang', 'Gunung Soputan', 'Gunung Klabat', 'Gunung Lokon', 'c', 'pilihan_ganda'),
(2197, 2026, 197, 'Piala Dunia 2022 diselenggarakan di negara ...', 'Brasil', 'Jerman', 'Rusia', 'Qatar', 'd', 'pilihan_ganda'),
(2198, 2026, 198, 'Kepanjangan dari CPU dalam komputer adalah ...', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit', 'Computer Program Unit', 'a', 'pilihan_ganda'),
(2199, 2026, 199, 'Negara ASEAN yang tidak memiliki laut adalah ...', 'Kamboja', 'Myanmar', 'Laos', 'Thailand', 'c', 'pilihan_ganda'),
(2200, 2026, 200, 'Program vaksinasi nasional COVID-19 di Indonesia dimulai pada tahun ...', '2019', '2020', '2021', '2022', 'c', 'pilihan_ganda'),
(2201, 2026, 201, 'Siapakah yang disebut sebagai "Rasul Maluku" yang datang ke Minahasa?', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'J.G. Schwarz', 'Pdt. A.Z.R. Wenas', 'a', 'pilihan_ganda'),
(2202, 2026, 202, 'Apa yang dimaksud dengan "Presbiterial Sinodal"?', 'Kepemimpinan kongregasi independen', 'Kepemimpinan karismatik', 'Kepemimpinan satu uskup', 'Kepemimpinan kolektif para penatua dengan musyawarah', 'd', 'pilihan_ganda'),
(2203, 2026, 203, 'Berapa jumlah kitab dalam Perjanjian Baru?', '27', '66', '24', '39', 'a', 'pilihan_ganda'),
(2204, 2026, 204, 'Apa kepanjangan dari NZG?', 'Nederlands Zendeling Genootschap', 'Nederland Zending Genootschap', 'Nederlands Zending Genootschap', 'Nederland Zendeling Genootschap', 'c', 'pilihan_ganda'),
(2205, 2026, 205, 'Siapakah yang menulis kitab Kisah Para Rasul?', 'Markus', 'Matius', 'Yohanes', 'Lukas', 'd', 'pilihan_ganda'),
(2206, 2026, 206, 'Apa tema Misi Remaja GMIM?', 'Remaja Kreatif dan Inovatif', 'Remaja Bagi Kristus', 'Menjadi Teladan', 'Berakar, bertumbuh, dan berbuah bagi Kristus', 'd', 'pilihan_ganda'),
(2207, 2026, 207, 'Siapakah yang menjadi raja Israel setelah Daud?', 'Saul', 'Rehabeam', 'Yerobeam', 'Salomo', 'd', 'pilihan_ganda'),
(2208, 2026, 208, 'Apa kepanjangan dari GEMAR?', 'Gereja Membaca Alkitab Remaja', 'Gerakan Memasyarakatkan Alkitab Remaja', 'Gerakan Muda Alkitab Remaja', 'Gerakan Membaca Alkitab Remaja', 'd', 'pilihan_ganda'),
(2209, 2026, 209, 'Apa arti "Sola Fide"?', 'Hanya oleh iman', 'Hanya oleh kasih karunia', 'Hanya bagi kemuliaan Tuhan', 'Hanya Alkitab', 'a', 'pilihan_ganda'),
(2210, 2026, 210, 'Siapakah yang menulis surat kepada jemaat di Filipi?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2211, 2026, 211, 'Berapa usia maksimal peserta Pemilihan Remaja Teladan?', '16 tahun', '17 tahun', '15 tahun 364 hari', '16 tahun 364 hari', 'd', 'pilihan_ganda'),
(2212, 2026, 212, 'Siapakah nama ibu dari Samuel?', 'Ribka', 'Hana', 'Elkana', 'Sara', 'b', 'pilihan_ganda'),
(2213, 2026, 213, 'Apa warna dasar selempang finalis tingkat Sinode?', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'Ungu dengan tulisan emas', 'a', 'pilihan_ganda'),
(2214, 2026, 214, 'Siapakah yang menulis kitab Keluaran?', 'Musa', 'Daud', 'Yeremia', 'Salomo', 'a', 'pilihan_ganda'),
(2215, 2026, 215, 'Apa singkatan dari KB3?', 'Kegiatan Bina Bakat Berkah', 'Komisi Bina Berkat Bersama', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Kelompok Belajar Bersama', 'c', 'pilihan_ganda'),
(2216, 2026, 216, 'Siapakah yang disebut sebagai "Bapa Orang Percaya"?', 'Adam', 'Abraham', 'Musa', 'Daud', 'b', 'pilihan_ganda'),
(2217, 2026, 217, 'Apa kepanjangan dari P3SDM?', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'a', 'pilihan_ganda'),
(2218, 2026, 218, 'Berapa jumlah tulah yang Tuhan datangkan ke Mesir?', '5 tulah', '7 tulah', '12 tulah', '10 tulah', 'd', 'pilihan_ganda'),
(2219, 2026, 219, 'Siapakah yang menjadi Ketua Sinode GMIM pertama?', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'Ds. A.Z.R. Wenas', 'Ds. E.A.A. de Vreede', 'd', 'pilihan_ganda'),
(2220, 2026, 220, 'Apa arti "Sola Gratia"?', 'Hanya Alkitab', 'Hanya oleh iman', 'Hanya oleh kasih karunia', 'Hanya bagi kemuliaan Tuhan', 'c', 'pilihan_ganda'),
(2221, 2026, 221, 'Siapakah yang menulis kitab Yohanes?', 'Yakobus', 'Rasul Yohanes', 'Petrus', 'Matius', 'b', 'pilihan_ganda'),
(2222, 2026, 222, 'Apa yang dimaksud dengan "Karunia Roh"?', 'Kekayaan materi', 'Bakat alami sejak lahir', 'Kemampuan khusus yang diberikan Roh Kudus untuk melayani', 'Popularitas di gereja', 'c', 'pilihan_ganda'),
(2223, 2026, 223, 'Siapakah Ketua KPRS periode 2018-2022?', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. Edward Saragih', 'Pnt. dr. Michaela E. Paruntu', 'Pnt. Melky R. Pattiwael', 'c', 'pilihan_ganda'),
(2224, 2026, 224, 'Apa nama gunung tempat Musa menerima 10 Hukum Allah?', 'Bukit Zaitun', 'Gunung Sinai', 'Gunung Hermon', 'Gunung Tabor', 'b', 'pilihan_ganda'),
(2225, 2026, 225, 'Apa kepanjangan dari APIM?', 'Ajaran, Persekutuan, Ibadah, dan Misi', 'Ajaran, Persekutuan, Ibadah, dan Musik', 'Ajaran, Pelayanan, Ibadah, dan Misi', 'Alkitab, Persekutuan, Ibadah, dan Misi', 'a', 'pilihan_ganda'),
(2226, 2026, 226, 'Siapakah yang menjadi raja Israel yang paling bijaksana?', 'Salomo', 'Saul', 'Yosia', 'Daud', 'a', 'pilihan_ganda'),
(2227, 2026, 227, 'Berapa jumlah pasal dalam kitab Kejadian?', '50', '40', '55', '45', 'a', 'pilihan_ganda'),
(2228, 2026, 228, 'Apa arti "Buah Roh" dalam Galatia 5?', 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri', 'Hikmat, pengertian, nasihat', 'Iman, pengharapan, kasih', 'Kemuliaan, hormat, kuasa', 'a', 'pilihan_ganda'),
(2229, 2026, 229, 'Siapakah nama misionaris yang melayani di Langowan dan Kakas?', 'Pdt. A.Z.R. Wenas', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'J.F. Riedel', 'b', 'pilihan_ganda'),
(2230, 2026, 230, 'Apa yang dimaksud dengan "Ekaristi"?', 'Katekisasi', 'Peneguhan Sidi', 'Perjamuan Kudus', 'Baptisan', 'c', 'pilihan_ganda'),
(2231, 2026, 231, 'Siapakah yang dibuang ke gua singa karena setia berdoa?', 'Yusuf', 'Daniel', 'Musa', 'Daud', 'b', 'pilihan_ganda'),
(2232, 2026, 232, 'Apa tema MTPJ bulan April biasanya?', 'Pencurahan Roh Kudus', 'Kenaikan Yesus', 'Kebangkitan Yesus', 'Kelahiran Yesus', 'c', 'pilihan_ganda'),
(2233, 2026, 233, 'Siapakah yang menulis surat kepada jemaat di Tesalonika?', 'Paulus', 'Yakobus', 'Yohanes', 'Petrus', 'a', 'pilihan_ganda'),
(2234, 2026, 234, 'Berapa bobot nilai tes tertulis dalam Pemilihan Remaja Teladan?', '25%', '15%', '5%', '35%', 'c', 'pilihan_ganda'),
(2235, 2026, 235, 'Apa nama sungai tempat Yesus dibaptis?', 'Sungai Yordan', 'Sungai Efrat', 'Sungai Tigris', 'Sungai Nil', 'a', 'pilihan_ganda'),
(2236, 2026, 236, 'Siapakah yang menjadi Ketua Sinode GMIM terlama?', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. W.A. Roeroe', 'd', 'pilihan_ganda'),
(2237, 2026, 237, 'Apa arti kata "Manna" dalam Perjanjian Lama?', 'Buah dari tanah perjanjian', 'Roti dari sorga', 'Daging burung puyuh', 'Air dari batu', 'b', 'pilihan_ganda'),
(2238, 2026, 238, 'Berapa jumlah rayon pelayanan KPRS?', '11', '10', '12', '13', 'c', 'pilihan_ganda'),
(2239, 2026, 239, 'Siapakah yang disebut sebagai "Pokok Anggur yang benar"?', 'Yesus Kristus', 'Daud', 'Paulus', 'Petrus', 'a', 'pilihan_ganda'),
(2240, 2026, 240, 'Apa kepanjangan dari HPRG?', 'Hari Pelayanan Remaja GMIM', 'Hari Paskah Remaja GMIM', 'Hari Pertemuan Remaja GMIM', 'Hari Persatuan Remaja GMIM', 'd', 'pilihan_ganda'),
(2241, 2026, 241, 'Kalimat "Menurut saya, kopi lebih enak daripada teh" adalah contoh ...', 'Opini', 'Hipotesis', 'Asumsi', 'Fakta', 'a', 'pilihan_ganda'),
(2242, 2026, 242, 'Siapa Wakil Presiden Indonesia periode 2019-2024?', 'Jusuf Kalla', 'Ma''ruf Amin', 'Try Sutrisno', 'Boediono', 'b', 'pilihan_ganda'),
(2243, 2026, 243, 'The antonym of "brave" is ...', 'Bold', 'Strong', 'Coward', 'Fearless', 'c', 'pilihan_ganda'),
(2244, 2026, 244, 'Indonesia menjadi anggota BRICS pada tahun ...', '2024', '2023', '2025', '2022', 'a', 'pilihan_ganda'),
(2245, 2026, 245, 'Hasil dari 120 ÷ 5 × 3 - 10 adalah ...', '66', '70', '58', '62', 'd', 'pilihan_ganda'),
(2246, 2026, 246, 'Apa nama danau terluas di Sulawesi Utara?', 'Danau Tondano', 'Danau Toba', 'Danau Moat', 'Danau Linow', 'a', 'pilihan_ganda'),
(2247, 2026, 247, 'Piala Dunia Wanita 2023 diselenggarakan di negara ...', 'Amerika Serikat', 'Australia dan Selandia Baru', 'Kanada', 'Prancis', 'b', 'pilihan_ganda'),
(2248, 2026, 248, 'Kepanjangan dari RAM dalam komputer adalah ...', 'Random Available Memory', 'Read Available Memory', 'Read Access Memory', 'Random Access Memory', 'd', 'pilihan_ganda'),
(2249, 2026, 249, 'Negara terbaru yang bergabung dengan ASEAN adalah ...', 'Bangladesh', 'Timor Leste', 'Papua Nugini', 'Sri Lanka', 'b', 'pilihan_ganda'),
(2250, 2026, 250, 'Program "Makan Bergizi Gratis" digagas oleh presiden terpilih ...', 'Joko Widodo', 'Prabowo Subianto', 'Anies Baswedan', 'Ganjar Pranowo', 'b', 'pilihan_ganda'),
(2251, 2026, 251, 'Apa yang dimaksud dengan "Imamat yang Rajani" (1 Petrus 2:9)?', 'Hamba Tuhan yang khusus', 'Imam dalam gereja katolik', 'Setiap orang percaya adalah imam yang melayani Tuhan', 'Hanya pendeta yang bisa melayani', 'c', 'pilihan_ganda'),
(2252, 2026, 252, 'Siapakah yang menulis kitab Roma?', 'Petrus', 'Yohanes', 'Yakobus', 'Paulus', 'd', 'pilihan_ganda'),
(2253, 2026, 253, 'Apa kepanjangan dari PKRS?', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'a', 'pilihan_ganda'),
(2254, 2026, 254, 'Apa arti "Soli Deo Gloria"?', 'Hanya Alkitab', 'Kemuliaan hanya bagi Tuhan', 'Hanya oleh kasih karunia', 'Hanya oleh iman', 'b', 'pilihan_ganda'),
(2255, 2026, 255, 'Siapakah yang menjadi raja Israel yang membangun Bait Suci?', 'Salomo', 'Daud', 'Yosia', 'Saul', 'a', 'pilihan_ganda'),
(2256, 2026, 256, 'Apa singkatan dari LKRG?', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kader Remaja Gereja', 'd', 'pilihan_ganda'),
(2257, 2026, 257, 'Berapa jumlah pasal dalam kitab Yeremia?', '48', '50', '55', '52', 'd', 'pilihan_ganda'),
(2258, 2026, 258, 'Siapakah nama isteri Yusuf dalam Perjanjian Lama?', 'Dina', 'Asnat', 'Abisag', 'Potifera', 'b', 'pilihan_ganda'),
(2259, 2026, 259, 'Apa tema Misi Remaja GMIM?', 'Remaja Kreatif', 'Remaja Bagi Kristus', 'Berakar, Bertumbuh, Berbuah bagi Kristus', 'Menjadi Teladan', 'c', 'pilihan_ganda'),
(2260, 2026, 260, 'Siapakah yang disebut sebagai "Rasul kepada bangsa-bangsa bukan Yahudi"?', 'Paulus', 'Yakobus', 'Petrus', 'Yohanes', 'a', 'pilihan_ganda'),
(2261, 2026, 261, 'Berapa bobot nilai wawancara dalam Pemilihan Remaja Teladan?', '35%', '5%', '15%', '25%', 'c', 'pilihan_ganda'),
(2262, 2026, 262, 'Apa arti "Teens for Christ"?', 'Remaja Dalam Kristus', 'Remaja Untuk Kristus', 'Remaja Bagi Kristus', 'Remaja Bersama Kristus', 'c', 'pilihan_ganda'),
(2263, 2026, 263, 'Siapakah yang menulis kitab 1 Timotius?', 'Yohanes', 'Lukas', 'Petrus', 'Paulus', 'd', 'pilihan_ganda'),
(2264, 2026, 264, 'Apa yang dimaksud dengan "Pelayanan Holistik"?', 'Pelayanan yang menyentuh seluruh aspek kehidupan', 'Pelayanan jasmani saja', 'Pelayanan yang melelahkan', 'Pelayanan yang hanya rohani', 'a', 'pilihan_ganda'),
(2265, 2026, 265, 'Siapakah nama ibu dari Yohanes Pembaptis?', 'Elisabeth', 'Sara', 'Maria', 'Hana', 'a', 'pilihan_ganda'),
(2266, 2026, 266, 'Apa warna dasar selempang finalis tingkat Wilayah?', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'b', 'pilihan_ganda'),
(2267, 2026, 267, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2014-2018?', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. Hein Arina', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2268, 2026, 268, 'Apa arti kata "Ekklesia"?', 'Tempat ibadah', 'Rumah doa', 'Jemaat', 'Gereja - persekutuan orang yang dipanggil keluar', 'd', 'pilihan_ganda'),
(2269, 2026, 269, 'Siapakah yang menulis kitab Yakobus?', 'Petrus', 'Paulus', 'Yakobus saudara Yesus', 'Yakobus anak Zebedeus', 'c', 'pilihan_ganda'),
(2270, 2026, 270, 'Apa kepanjangan dari PSR?', 'Pesta Seni Remaja', 'Pekan Seni Remaja', 'Pentas Seni Remaja', 'Perkemahan Seni Remaja', 'a', 'pilihan_ganda'),
(2271, 2026, 271, 'Berapa lama bangsa Israel berjalan di padang gurun?', '30 tahun', '20 tahun', '40 tahun', '10 tahun', 'c', 'pilihan_ganda'),
(2272, 2026, 272, 'Siapakah yang disebut sebagai "Nabi yang naik ke sorga dengan kereta api"?', 'Henokh', 'Elisa', 'Musa', 'Elia', 'd', 'pilihan_ganda'),
(2273, 2026, 273, 'Apa yang dimaksud dengan "Karantina" dalam seleksi Retel?', 'Tahap tes tertulis', 'Tahap final', 'Tahap wawancara', 'Tahap pembinaan intensif selama 3 hari', 'd', 'pilihan_ganda'),
(2274, 2026, 274, 'Siapakah yang menulis kitab 1 Petrus?', 'Paulus', 'Yakobus', 'Petrus', 'Yohanes', 'c', 'pilihan_ganda'),
(2275, 2026, 275, 'Apa arti "Sola Scriptura"?', 'Hanya oleh iman', 'Hanya Alkitab sebagai otoritas tertinggi', 'Hanya bagi kemuliaan Tuhan', 'Hanya oleh kasih karunia', 'b', 'pilihan_ganda'),
(2276, 2026, 276, 'Siapakah nama misionaris yang melayani di Minahasa pada abad ke-19?', 'Pdt. Wenas dan Pdt. Roeroe', 'J.F. Riedel dan J.G. Schwarz', 'Ds. de Vreede dan Ds. Buenk', 'Pdt. Tampi dan Pdt. Sumakul', 'b', 'pilihan_ganda'),
(2277, 2026, 277, 'Berapa jumlah perintah dalam Dekalog?', '5', '10', '12', '7', 'b', 'pilihan_ganda'),
(2278, 2026, 278, 'Apa yang dimaksud dengan "Grand Final"?', 'Tahap karantina', 'Tahap awal seleksi', 'Tahap wawancara', 'Puncak acara Pemilihan Remaja Teladan', 'd', 'pilihan_ganda'),
(2279, 2026, 279, 'Siapakah yang menjadi raja Israel yang paling rendah hati?', 'Saul', 'Yosia', 'Daud', 'Salomo', 'c', 'pilihan_ganda'),
(2280, 2026, 280, 'Apa tema MTPJ minggu Paskah?', 'Kematian Yesus', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'c', 'pilihan_ganda'),
(2281, 2026, 281, 'Siapakah yang menulis kitab 2 Timotius?', 'Lukas', 'Petrus', 'Yohanes', 'Paulus', 'd', 'pilihan_ganda'),
(2282, 2026, 282, 'Berapa bobot nilai Grand Final?', '20%', '15%', '25%', '5%', 'a', 'pilihan_ganda'),
(2283, 2026, 283, 'Apa arti "Pelayanan Marturia"?', 'Pelayanan ibadah', 'Pelayanan persekutuan', 'Pelayanan kasih', 'Pelayanan kesaksian', 'd', 'pilihan_ganda'),
(2284, 2026, 284, 'Siapakah yang disebut sebagai "Garam dan Terang dunia"?', 'Hanya pendeta', 'Setiap orang percaya', 'Hanya rasul', 'Hanya nabi', 'b', 'pilihan_ganda'),
(2285, 2026, 285, 'Apa warna dasar selempang finalis tingkat Jemaat?', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan emas', 'a', 'pilihan_ganda'),
(2286, 2026, 286, 'Siapakah yang menulis kitab Filipi?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'c', 'pilihan_ganda'),
(2287, 2026, 287, 'Apa arti "Pelayanan Diakonia"?', 'Pelayanan kasih kepada yang membutuhkan', 'Pelayanan kesaksian', 'Pelayanan ibadah', 'Pelayanan persekutuan', 'a', 'pilihan_ganda'),
(2288, 2026, 288, 'Siapakah nama ayah dari Yosua?', 'Nun', 'Musa', 'Harun', 'Kaleb', 'a', 'pilihan_ganda'),
(2289, 2026, 289, 'Berapa jumlah tulah kesepuluh di Mesir?', 'Katak', 'Gelap gulita', 'Kematian anak sulung', 'Belalang', 'c', 'pilihan_ganda'),
(2290, 2026, 290, 'Apa kepanjangan dari BPMJ?', 'Badan Pelayanan Majelis Jemaat', 'Badan Pengawas Majelis Jemaat', 'Badan Pekerja Majelis Jemaat', 'Badan Pengurus Majelis Jemaat', 'c', 'pilihan_ganda'),
(2291, 2026, 291, 'Teks "Harga BBM naik menjadi 3 dampak negatif bagi masyarakat" adalah contoh ...', 'Asumsi', 'Prediksi', 'Fakta', 'Opini', 'c', 'pilihan_ganda'),
(2292, 2026, 292, 'Ibu Kota Negara Indonesia yang baru bernama ...', 'Nusantara', 'Palangkaraya', 'Samarinda', 'Balikpapan', 'a', 'pilihan_ganda'),
(2293, 2026, 293, 'The synonym of "difficult" is ...', 'Easy', 'Hard', 'Simple', 'Light', 'b', 'pilihan_ganda'),
(2294, 2026, 294, 'Indonesia menjadi tuan rumah Piala Dunia U-20 pada tahun ...', '2025', '2026', '2023 (batal)', '2024', 'c', 'pilihan_ganda'),
(2295, 2026, 295, 'Hasil dari 100 - 5 × 6 + 15 ÷ 3 adalah ...', '70', '80', '75', '85', 'c', 'pilihan_ganda'),
(2296, 2026, 296, 'Apa nama taman laut terkenal di Sulawesi Utara?', 'Wakatobi', 'Derawan', 'Raja Ampat', 'Bunaken', 'd', 'pilihan_ganda'),
(2297, 2026, 297, 'Presiden terpilih Amerika Serikat untuk periode 2025-2029 adalah ...', 'Kamala Harris', 'Donald Trump', 'Joe Biden', 'Barack Obama', 'b', 'pilihan_ganda'),
(2298, 2026, 298, 'Kepanjangan dari AI dalam teknologi adalah ...', 'Artificial Intelligence', 'Artificial Integration', 'Automated Intelligence', 'Automated Integration', 'a', 'pilihan_ganda'),
(2299, 2026, 299, 'Negara dengan penduduk Muslim terbanyak di dunia adalah ...', 'Bangladesh', 'India', 'Indonesia', 'Pakistan', 'c', 'pilihan_ganda'),
(2300, 2026, 300, 'Program ketahanan pangan "PIP" singkatan dari ...', 'Pangan Inovatif dan Produktif', 'Program Intensifikasi Pangan', 'Program Inovasi Pangan', 'Pangan Indonesia Prima', 'a', 'pilihan_ganda'),
(2301, 2026, 301, 'Apa yang dimaksud dengan "Pelayanan Koinonia"?', 'Pelayanan kesaksian', 'Pelayanan persekutuan', 'Pelayanan kasih', 'Pelayanan ibadah', 'b', 'pilihan_ganda'),
(2302, 2026, 302, 'Siapakah yang menulis kitab 1 Korintus?', 'Paulus', 'Yohanes', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2303, 2026, 303, 'Apa kepanjangan dari BPMW?', 'Badan Pelayanan Majelis Wilayah', 'Badan Pengurus Majelis Wilayah', 'Badan Pekerja Majelis Wilayah', 'Badan Pengawas Majelis Wilayah', 'c', 'pilihan_ganda'),
(2304, 2026, 304, 'Siapakah yang disebut sebagai "Perjanjian Baru dalam darah-Ku"?', 'Abraham', 'Daud', 'Musa', 'Yesus Kristus', 'd', 'pilihan_ganda'),
(2305, 2026, 305, 'Berapa jumlah pasal dalam kitab Kejadian?', '55', '40', '45', '50', 'd', 'pilihan_ganda'),
(2306, 2026, 306, 'Apa arti "Gelar Atribut" dalam Pemilihan Remaja Teladan?', 'Sertifikat partisipasi', 'Gelar khusus selain juara utama', 'Gelar juara utama', 'Penghargaan peserta', 'b', 'pilihan_ganda'),
(2307, 2026, 307, 'Siapakah yang menjadi raja Israel yang paling kaya?', 'Salomo', 'Saul', 'Yosia', 'Daud', 'a', 'pilihan_ganda'),
(2308, 2026, 308, 'Apa tema Visi Remaja GMIM?', 'Remaja Bagi Kristus', 'Menjadi Teladan', 'Berakar, Bertumbuh, Berbuah', 'Remaja Kreatif', 'a', 'pilihan_ganda'),
(2309, 2026, 309, 'Siapakah yang menulis kitab Kolose?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a', 'pilihan_ganda'),
(2310, 2026, 310, 'Apa yang dimaksud dengan "Pelayanan Leiturgia"?', 'Pelayanan persekutuan', 'Pelayanan kasih', 'Pelayanan ibadah dan penyembahan', 'Pelayanan kesaksian', 'c', 'pilihan_ganda'),
(2311, 2026, 311, 'Berapa bobot nilai Kompetisi Potensi Diri?', '20%', '25%', '35%', '15%', 'b', 'pilihan_ganda'),
(2312, 2026, 312, 'Siapakah nama ayah dari Yesus menurut silsilah Matius?', 'Abraham', 'Yakobus', 'Daud', 'Yusuf', 'd', 'pilihan_ganda'),
(2313, 2026, 313, 'Apa warna dasar selempang finalis tingkat Rayon?', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'a', 'pilihan_ganda'),
(2314, 2026, 314, 'Siapakah yang disebut sebagai "Pahlawan Iman" dalam Ibrani 11?', 'Hanya Yesus', 'Abraham, Musa, Daud, dll', 'Hanya Paulus', 'Hanya Petrus', 'b', 'pilihan_ganda'),
(2315, 2026, 315, 'Apa arti "Katekisasi"?', 'Pengajaran iman Kristen secara sistematis', 'Doa bersama', 'Puasa', 'Ibadah minggu', 'a', 'pilihan_ganda'),
(2316, 2026, 316, 'Siapakah yang menulis kitab Titus?', 'Petrus', 'Paulus', 'Lukas', 'Yohanes', 'b', 'pilihan_ganda'),
(2317, 2026, 317, 'Apa kepanjangan dari Retel?', 'Remaja Teladan', 'Remaja Teladan Jemaat', 'Remaja Teladan Sinode', 'Remaja Teladan GMIM', 'a', 'pilihan_ganda'),
(2318, 2026, 318, 'Berapa jumlah kitab dalam Alkitab?', '73', '27', '66', '39', 'c', 'pilihan_ganda'),
(2319, 2026, 319, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2010-2014?', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'b', 'pilihan_ganda'),
(2320, 2026, 320, 'Apa yang dimaksud dengan "Sakramen Baptisan Kudus"?', 'Ritual pembersihan', 'Perayaan tahunan', 'Upacara adat', 'Tanda perjanjian Allah dengan umat-Nya', 'd', 'pilihan_ganda'),
(2321, 2026, 321, 'Siapakah yang menulis kitab Filemon?', 'Yohanes', 'Paulus', 'Petrus', 'Lukas', 'b', 'pilihan_ganda'),
(2322, 2026, 322, 'Apa arti "Pelayanan Penggembalaan"?', 'Pelayanan kesaksian', 'Pelayanan ibadah', 'Pelayanan membimbing dan mengarahkan jemaat', 'Pelayanan kasih', 'c', 'pilihan_ganda'),
(2323, 2026, 323, 'Siapakah nama istri dari Abraham?', 'Rahel', 'Hagar', 'Sara', 'Ribka', 'c', 'pilihan_ganda'),
(2324, 2026, 324, 'Berapa jumlah bidang KPRS?', '8 bidang', '9 bidang', '7 bidang', '10 bidang', 'c', 'pilihan_ganda'),
(2325, 2026, 325, 'Apa tema MTPJ bulan Desember?', 'Pencurahan Roh Kudus', 'Kenaikan Yesus', 'Natal dan Kedatangan Yesus', 'Kebangkitan Yesus', 'c', 'pilihan_ganda'),
(2326, 2026, 326, 'Siapakah yang menulis kitab 2 Petrus?', 'Yakobus', 'Petrus', 'Yohanes', 'Paulus', 'b', 'pilihan_ganda'),
(2327, 2026, 327, 'Apa yang dimaksud dengan "Peneguhan Sidi Jemaat"?', 'Katekisasi', 'Pengakuan iman secara dewasa', 'Baptisan anak', 'Pernikahan', 'b', 'pilihan_ganda'),
(2328, 2026, 328, 'Siapakah nama anak dari Abraham dan Sara?', 'Yakub', 'Ishak', 'Esau', 'Ismail', 'b', 'pilihan_ganda'),
(2329, 2026, 329, 'Apa arti "Semboyan Reformasi"?', 'Iman, Pengharapan, Kasih', 'Bersekutu, Bersaksi, Melayani', 'Sola Fide, Sola Gratia, Sola Scriptura, Soli Deo Gloria', 'Doa, Puasa, Sedekah', 'c', 'pilihan_ganda'),
(2330, 2026, 330, 'Siapakah yang menulis kitab Yudas?', 'Yudas Iskariot', 'Petrus', 'Yudas saudara Yesus', 'Paulus', 'c', 'pilihan_ganda'),
(2331, 2026, 331, 'Berapa usia minimal menjadi Sidi Jemaat?', '18 tahun', '16 tahun', '15 tahun', '17 tahun', 'd', 'pilihan_ganda'),
(2332, 2026, 332, 'Apa yang dimaksud dengan "Tahun Gerejawi"?', 'Siklus tahunan perayaan iman Kristen', 'Tahun pelayanan gereja', 'Tahun ajaran sekolah minggu', 'Tahun anggaran gereja', 'a', 'pilihan_ganda'),
(2333, 2026, 333, 'Siapakah yang menulis kitab 3 Yohanes?', 'Petrus', 'Paulus', 'Yohanes', 'Yakobus', 'c', 'pilihan_ganda'),
(2334, 2026, 334, 'Apa arti "Pelayanan Kategorial"?', 'Pelayanan berdasarkan kategori usia dan status', 'Pelayanan khusus', 'Pelayanan umum', 'Pelayanan harian', 'a', 'pilihan_ganda'),
(2335, 2026, 335, 'Siapakah nama anak dari Ishak dan Ribka?', 'Ismail', 'Yusuf', 'Benyamin', 'Yakub dan Esau', 'd', 'pilihan_ganda'),
(2336, 2026, 336, 'Apa tema Misi GMIM?', 'Gereja Global', 'Berakar, Bertumbuh, Berbuah', 'Remaja Bagi Kristus', 'Bersekutu, Bersaksi, Melayani', 'd', 'pilihan_ganda'),
(2337, 2026, 337, 'Siapakah yang menulis kitab Wahyu?', 'Yohanes di Patmos', 'Lukas', 'Paulus', 'Petrus', 'a', 'pilihan_ganda'),
(2338, 2026, 338, 'Berapa bobot nilai karantina dan pelayanan holistik?', '20%', '25%', '15%', '35%', 'd', 'pilihan_ganda'),
(2339, 2026, 339, 'Apa arti "Perjamuan Kudus"?', 'Ibadah malam', 'Makan bersama', 'Doa bersama', 'Sakramen peringatan kematian dan kebangkitan Yesus', 'd', 'pilihan_ganda'),
(2340, 2026, 340, 'Siapakah yang menjadi Ketua KPRS periode 2000-2005?', 'Pnt. Drs. Jantje W. Sajow', 'Pnt. dr. Michaela Paruntu', 'Pnt. Drs. Jacobus Wowor', 'Pnt. Ir. Dwight Rondonuwu', 'a', 'pilihan_ganda'),
(2341, 2026, 341, 'Kalimat "Bencana alam terjadi karena ulah manusia" adalah contoh ...', 'Asumsi', 'Opini', 'Hipotesis', 'Fakta', 'b', 'pilihan_ganda'),
(2342, 2026, 342, 'Siapa nama presiden terpilih Indonesia 2024-2029?', 'Prabowo Subianto', 'Ganjar Pranowo', 'Joko Widodo', 'Anies Baswedan', 'a', 'pilihan_ganda'),
(2343, 2026, 343, 'The synonym of "happy" is ...', 'Angry', 'Sad', 'Tired', 'Joyful', 'd', 'pilihan_ganda'),
(2344, 2026, 344, 'Indonesia menjadi tuan rumah ajang MotoGP di sirkuit ...', 'Jakarta', 'Surabaya', 'Mandalika', 'Sentul', 'c', 'pilihan_ganda'),
(2345, 2026, 345, 'Hasil dari 4² + 3² - 2³ adalah ...', '19', '17', '13', '15', 'b', 'pilihan_ganda'),
(2346, 2026, 346, 'Apa nama pulau terbesar di Sulawesi Utara?', 'Pulau Sangihe', 'Pulau Manado Tua', 'Pulau Lembeh', 'Pulau Bunaken', 'c', 'pilihan_ganda'),
(2347, 2026, 347, 'Piala Dunia 2026 akan diselenggarakan di negara ...', 'Amerika Serikat', 'Kanada', 'Amerika Serikat, Kanada, Meksiko', 'Meksiko', 'c', 'pilihan_ganda'),
(2348, 2026, 348, 'Kepanjangan dari URL adalah ...', 'Uniform Resource Link', 'Uniform Resource Locator', 'Universal Resource Locator', 'Universal Resource Link', 'b', 'pilihan_ganda'),
(2349, 2026, 349, 'Negara di Asia Tenggara yang berbentuk kerajaan adalah ...', 'Vietnam', 'Thailand', 'Indonesia', 'Malaysia', 'b', 'pilihan_ganda'),
(2350, 2026, 350, 'Program "Indonesia Emas 2045" adalah visi ...', 'Indonesia menjadi negara maju pada 100 tahun kemerdekaan', 'Indonesia menjadi pusat ekonomi dunia', 'Indonesia menjadi negara adidaya', 'Indonesia menjadi negara termakmur', 'a', 'pilihan_ganda'),
(2351, 2026, 351, 'Apa yang dimaksud dengan "Pola Baku Pemilihan Remaja Teladan"?', 'Pedoman untuk juri', 'Standar prosedur seleksi yang harus dilaksanakan semua aras', 'Aturan khusus untuk sinode', 'Buku panduan peserta', 'b', 'pilihan_ganda'),
(2352, 2026, 352, 'Siapakah yang menulis kitab Efesus?', 'Paulus', 'Yohanes', 'Petrus', 'Yakobus', 'a', 'pilihan_ganda'),
(2353, 2026, 353, 'Apa kepanjangan dari KPRJ?', 'Komisi Pelayanan Remaja Jemaat', 'Komisi Pelayanan Remaja Rayon', 'Komisi Pelayanan Remaja Sinode', 'Komisi Pelayanan Remaja Wilayah', 'a', 'pilihan_ganda'),
(2354, 2026, 354, 'Siapakah yang disebut sebagai "Rasul bangsa-bangsa bukan Yahudi"?', 'Yakobus', 'Paulus', 'Petrus', 'Yohanes', 'b', 'pilihan_ganda'),
(2355, 2026, 355, 'Berapa jumlah perintah dalam 10 Hukum Allah?', '12', '7', '10', '5', 'c', 'pilihan_ganda'),
(2356, 2026, 356, 'Apa arti "Gelar Remaja Teladan Intelegensia"?', 'Gelar persahabatan', 'Gelar untuk peserta dengan nilai tes tertulis dan psikotes terbaik', 'Gelar favorit', 'Gelar juara utama', 'b', 'pilihan_ganda'),
(2357, 2026, 357, 'Siapakah yang menjadi raja Israel yang pertama?', 'Daud', 'Yerobeam', 'Salomo', 'Saul', 'd', 'pilihan_ganda'),
(2358, 2026, 358, 'Apa tema MTPJ Minggu Sangsara?', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Penderitaan dan kematian Yesus', 'Kenaikan Yesus', 'c', 'pilihan_ganda'),
(2359, 2026, 359, 'Siapakah yang menulis kitab 2 Korintus?', 'Petrus', 'Paulus', 'Yakobus', 'Yohanes', 'b', 'pilihan_ganda'),
(2360, 2026, 360, 'Apa yang dimaksud dengan "Kata Kunci Final"?', 'Materi wawancara', 'Soal tes tertulis', '3 kata yang diambil acak peserta final untuk dijelaskan', 'Topik karantina', 'c', 'pilihan_ganda'),
(2361, 2026, 361, 'Berapa bobot nilai tes tertulis?', '35%', '5%', '25%', '15%', 'b', 'pilihan_ganda'),
(2362, 2026, 362, 'Siapakah nama anak dari Daud yang menjadi raja?', 'Absalom', 'Salomo', 'Adonia', 'Amnon', 'b', 'pilihan_ganda'),
(2363, 2026, 363, 'Apa warna dasar selempang pelayanan finalis?', 'Putih', 'Hitam', 'Merah', 'Ungu', 'd', 'pilihan_ganda'),
(2364, 2026, 364, 'Siapakah yang disebut sebagai "Bapa Para Nabi"?', 'Abraham', 'Daud', 'Musa', 'Isaac', 'a', 'pilihan_ganda'),
(2365, 2026, 365, 'Apa arti "Katekisasi Sidi"?', 'Pengajaran bagi calon anggota sidi jemaat', 'Pengajaran pernikahan', 'Pengajaran umum', 'Pengajaran baptisan', 'a', 'pilihan_ganda'),
(2366, 2026, 366, 'Siapakah yang menulis kitab 1 Yohanes?', 'Yohanes', 'Yakobus', 'Petrus', 'Paulus', 'a', 'pilihan_ganda'),
(2367, 2026, 367, 'Apa kepanjangan dari KPRW?', 'Komisi Pelayanan Remaja Jemaat', 'Komisi Pelayanan Remaja Rayon', 'Komisi Pelayanan Remaja Wilayah', 'Komisi Pelayanan Remaja Sinode', 'c', 'pilihan_ganda'),
(2368, 2026, 368, 'Berapa jumlah pasal dalam kitab Mazmur yang paling pendek?', '1 pasal', '5 pasal', '3 pasal', '2 pasal (Mazmur 117)', 'd', 'pilihan_ganda'),
(2369, 2026, 369, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2005-2010?', 'Pdt. Dr. A.O. Supit', 'Pdt. Dr. Henny Sumakul', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2370, 2026, 370, 'Apa yang dimaksud dengan "Sakramen Perjamuan Kudus"?', 'Perjamuan peringatan kematian Yesus', 'Ibadah malam', 'Doa bersama', 'Makan bersama jemaat', 'a', 'pilihan_ganda'),
(2371, 2026, 371, 'Siapakah yang menulis kitab 2 Yohanes?', 'Yakobus', 'Paulus', 'Yohanes', 'Petrus', 'c', 'pilihan_ganda'),
(2372, 2026, 372, 'Apa arti "Pelayanan Siswa" dalam KPRS?', 'Pelayanan kampus', 'Pelayanan anak-anak', 'Pelayanan sekolah minggu', 'Pelayanan yang fokus pada siswa dan pelajar', 'd', 'pilihan_ganda'),
(2373, 2026, 373, 'Siapakah nama ibu dari Daud?', 'Sara', 'Hana', 'Ribka', 'Tidak disebutkan dalam Alkitab', 'd', 'pilihan_ganda'),
(2374, 2026, 374, 'Apa tema MTPJ bulan November?', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'Kelahiran Yesus', 'Syukur dan Pemeliharaan Tuhan', 'd', 'pilihan_ganda'),
(2375, 2026, 375, 'Siapakah yang menulis kitab 1 Tesalonika?', 'Yakobus', 'Petrus', 'Paulus', 'Yohanes', 'c', 'pilihan_ganda'),
(2376, 2026, 376, 'Apa yang dimaksud dengan "Akumulasi nilai"?', 'Nilai rata-rata', 'Penjumlahan nilai dari berbagai tahapan seleksi', 'Nilai terendah', 'Nilai tertinggi', 'b', 'pilihan_ganda'),
(2377, 2026, 377, 'Siapakah nama anak dari Yakub dari Rahel?', 'Yusuf dan Benyamin', 'Ruben', 'Lewi', 'Simeon', 'a', 'pilihan_ganda'),
(2378, 2026, 378, 'Berapa jumlah pasal dalam kitab Yesaya?', '50', '60', '66', '52', 'c', 'pilihan_ganda'),
(2379, 2026, 379, 'Apa arti "Emiritat" bagi pendeta GMIM?', 'Gelar akademik', 'Status kehormatan setelah pensiun', 'Penghargaan khusus', 'Jabatan baru', 'b', 'pilihan_ganda'),
(2380, 2026, 380, 'Siapakah yang menjadi Ketua KPRS periode 2010-2014?', 'Pnt. dr. Michaela Paruntu', 'Pnt. Edward Saragih', 'Pnt. Melky Pattiwael', 'Pnt. Ir. Dwight Moody Rondonuwu', 'd', 'pilihan_ganda'),
(2381, 2026, 381, 'Apa yang dimaksud dengan "Parousia"?', 'Kedatangan Tuhan kedua kali', 'Kenaikan Yesus', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'a', 'pilihan_ganda'),
(2382, 2026, 382, 'Siapakah yang menulis kitab 2 Tesalonika?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'c', 'pilihan_ganda'),
(2383, 2026, 383, 'Apa arti "Kompetisi Potensi Diri"?', 'Karantina', 'Lomba debat, pidato Inggris, dan karya tulis', 'Wawancara', 'Tes tertulis', 'b', 'pilihan_ganda'),
(2384, 2026, 384, 'Siapakah nama istri dari Ishak?', 'Ribka', 'Lea', 'Rahel', 'Sara', 'a', 'pilihan_ganda'),
(2385, 2026, 385, 'Berapa jumlah pasal dalam kitab Yohanes?', '24', '16', '28', '21', 'd', 'pilihan_ganda'),
(2386, 2026, 386, 'Apa tema Misi GMIM secara umum?', 'Gereja Global', 'Remaja Bagi Kristus', 'Berakar, Bertumbuh, Berbuah', 'Bersekutu, Bersaksi, Melayani', 'd', 'pilihan_ganda'),
(2387, 2026, 387, 'Siapakah yang menulis kitab Markus?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'c', 'pilihan_ganda'),
(2388, 2026, 388, 'Apa yang dimaksud dengan "Regenerasi" dalam organisasi?', 'Proses kaderisasi untuk pemimpin penerus', 'Pemilihan baru', 'Pergantian pengurus', 'Evaluasi program', 'a', 'pilihan_ganda'),
(2389, 2026, 389, 'Siapakah nama ibu dari Musa?', 'Yokhebed', 'Miriam', 'Sara', 'Hana', 'a', 'pilihan_ganda'),
(2390, 2026, 390, 'Apa arti "Pelayanan Pemuda" dalam struktur GMIM?', 'Pelayanan anak', 'Pelayanan untuk usia 17-30 tahun', 'Pelayanan remaja', 'Pelayanan lansia', 'b', 'pilihan_ganda'),
(2391, 2026, 391, 'Teks "Indonesia memiliki 17.000 pulau" adalah contoh ...', 'Fakta', 'Opini', 'Hipotesis', 'Asumsi', 'a', 'pilihan_ganda'),
(2392, 2026, 392, 'Siapa Wakil Presiden Indonesia periode 2024-2029?', 'Gibran Rakabuming Raka', 'Boediono', 'Ma''ruf Amin', 'Jusuf Kalla', 'a', 'pilihan_ganda'),
(2393, 2026, 393, 'The antonym of "expensive" is ...', 'Valuable', 'Costly', 'Pricey', 'Cheap', 'd', 'pilihan_ganda'),
(2394, 2026, 394, 'Indonesia menjadi tuan rumah KTT ASEAN pada tahun 2023 di kota ...', 'Labuan Bajo', 'Jakarta', 'Bali', 'Bandung', 'a', 'pilihan_ganda'),
(2395, 2026, 395, 'Hasil dari 8 × 7 - 12 + 6 ÷ 2 adalah ...', '53', '50', '47', '44', 'c', 'pilihan_ganda'),
(2396, 2026, 396, 'Apa nama air terjun terkenal di Minahasa?', 'Air Terjun Madakaripura', 'Air Terjun Sekar', 'Air Terjun Sipiso-piso', 'Air Terjun Tunan', 'd', 'pilihan_ganda'),
(2397, 2026, 397, 'Piala Dunia Wanita 2027 akan diselenggarakan di negara ...', 'Prancis', 'Australia', 'Brasil', 'Amerika Serikat', 'c', 'pilihan_ganda'),
(2398, 2026, 398, 'Kepanjangan dari HTML adalah ...', 'Hyper Transfer Markup Language', 'HighText Markup Language', 'HyperText Machine Language', 'HyperText Markup Language', 'd', 'pilihan_ganda'),
(2399, 2026, 399, 'Negara yang disebut sebagai "Macan Asia" adalah ...', 'Indonesia, Malaysia, Thailand', 'Vietnam, Filipina, Myanmar', 'Korea Selatan, Taiwan, Hong Kong, Singapura', 'China, Jepang, India', 'c', 'pilihan_ganda'),
(2400, 2026, 400, 'Program "Bansos" adalah singkatan dari ...', 'Bantuan Subsidi', 'Bantuan Sosis', 'Bantuan Sosial', 'Bantuan Sembako', 'c', 'pilihan_ganda'),
(2401, 2026, 401, 'Apa yang dimaksud dengan "Tahapan Karantina" dalam seleksi Retel?', 'Tahap pembinaan intensif selama 3 hari', 'Tahap wawancara', 'Tahap final', 'Tahap tes tertulis', 'a', 'pilihan_ganda'),
(2402, 2026, 402, 'Siapakah yang menulis kitab Matius?', 'Yohanes', 'Lukas', 'Matius', 'Markus', 'c', 'pilihan_ganda'),
(2403, 2026, 403, 'Apa kepanjangan dari BIPRA?', 'Bidang Pembinaan dan Pengembangan', 'Bidang Informasi dan Pengembangan', 'Bidang Pelayanan dan Pembinaan', 'Bidang Pengembangan dan Pelayanan', 'c', 'pilihan_ganda'),
(2404, 2026, 404, 'Siapakah yang disebut sebagai "Juru Selamat dunia"?', 'Buddha', 'Musa', 'Yesus Kristus', 'Nabi Muhammad', 'c', 'pilihan_ganda'),
(2405, 2026, 405, 'Berapa jumlah rasul Yesus?', '12', '10', '11', '13', 'a', 'pilihan_ganda'),
(2406, 2026, 406, 'Apa arti "Gelar Remaja Teladan Persahabatan"?', 'Gelar intelegensia', 'Gelar juara utama', 'Gelar favorit', 'Gelar yang dipilih oleh sesama peserta', 'd', 'pilihan_ganda'),
(2407, 2026, 407, 'Siapakah yang menjadi raja Israel yang membangun tembok Yerusalem?', 'Nehemia', 'Zerubabel', 'Yosua', 'Ezra', 'a', 'pilihan_ganda'),
(2408, 2026, 408, 'Apa tema MTPJ minggu Adven?', 'Penderitaan Yesus', 'Kebangkitan Yesus', 'Penantian kelahiran Yesus', 'Kenaikan Yesus', 'c', 'pilihan_ganda'),
(2409, 2026, 409, 'Siapakah yang menulis kitab Lukas?', 'Matius', 'Yohanes', 'Lukas', 'Markus', 'c', 'pilihan_ganda'),
(2410, 2026, 410, 'Apa yang dimaksud dengan "Pelayanan Holistik" dalam Retel?', 'Ibadah bersama', 'Doa bersama', 'Pelayanan sosial kepada jemaat yang membutuhkan', 'Retret rohani', 'c', 'pilihan_ganda'),
(2411, 2026, 411, 'Berapa bobot nilai wawancara?', '5%', '35%', '25%', '15%', 'd', 'pilihan_ganda'),
(2412, 2026, 412, 'Siapakah nama anak dari Daud dengan Batsyeba yang menjadi raja?', 'Absalom', 'Adonia', 'Amnon', 'Salomo', 'd', 'pilihan_ganda'),
(2413, 2026, 413, 'Apa warna liturgi untuk masa Paskah?', 'Merah', 'Putih', 'Hijau', 'Ungu', 'b', 'pilihan_ganda'),
(2414, 2026, 414, 'Siapakah yang disebut sebagai "Nabi terakhir Perjanjian Lama"?', 'Zakharia', 'Hagai', 'Yoel', 'Maleakhi', 'd', 'pilihan_ganda'),
(2415, 2026, 415, 'Apa arti "Katekisasi Baptisan"?', 'Pengajaran bagi calon baptisan', 'Pengajaran sidi', 'Pengajaran pernikahan', 'Pengajaran umum', 'a', 'pilihan_ganda'),
(2416, 2026, 416, 'Siapakah yang menulis kitab 1 Raja-raja?', 'Musa', 'Tidak diketahui (tradisi: Yeremia)', 'Salomo', 'Daud', 'b', 'pilihan_ganda'),
(2417, 2026, 417, 'Apa kepanjangan dari BPMI?', 'Badan Pelayanan Majelis Jemaat', 'Badan Pengurus Majelis Jemaat', 'Badan Pekerja Majelis Jemaat', 'Badan Pengawas Majelis Jemaat', 'c', 'pilihan_ganda'),
(2418, 2026, 418, 'Berapa jumlah pasal dalam kitab Keluaran?', '40', '50', '30', '36', 'a', 'pilihan_ganda'),
(2419, 2026, 419, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2018-2022?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Piet M. Tampi', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2420, 2026, 420, 'Apa yang dimaksud dengan "Penasihat BPMJ"?', 'Bendahara BPMJ', 'Ketua BPMJ', 'Sekretaris BPMJ', 'Orang yang memberi nasihat kepada BPMJ', 'd', 'pilihan_ganda'),
(2421, 2026, 421, 'Siapakah yang menulis kitab 2 Raja-raja?', 'Daud', 'Salomo', 'Musa', 'Tidak diketahui (tradisi: Yeremia)', 'd', 'pilihan_ganda'),
(2422, 2026, 422, 'Apa arti "Bidang PMB" dalam KPRS?', 'Pengelolaan Minat dan Bakat', 'Program Minat dan Bakat', 'Pelayanan dan Manajemen Bakat', 'Pengembangan Minat dan Bakat', 'd', 'pilihan_ganda'),
(2423, 2026, 423, 'Siapakah nama anak dari Abraham dari Hagar?', 'Esau', 'Ishak', 'Ismail', 'Yakub', 'c', 'pilihan_ganda'),
(2424, 2026, 424, 'Apa tema MTPJ bulan Oktober?', 'Kelahiran Yesus', 'Misi dan Penginjilan', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'b', 'pilihan_ganda'),
(2425, 2026, 425, 'Siapakah yang menulis kitab 1 Tawarikh?', 'Salomo', 'Musa', 'Daud', 'Ezra (tradisi)', 'd', 'pilihan_ganda'),
(2426, 2026, 426, 'Apa yang dimaksud dengan "Skala nilai B (Baik)" dalam wawancara?', '70-80', '50-60', '60-70', '81-90', 'a', 'pilihan_ganda'),
(2427, 2026, 427, 'Siapakah nama anak dari Yakub dari Lea?', 'Dan', 'Benyamin', 'Ruben, Simeon, Lewi, Yehuda', 'Yusuf', 'c', 'pilihan_ganda'),
(2428, 2026, 428, 'Berapa jumlah pasal dalam kitab Ulangan?', '28', '34', '40', '30', 'b', 'pilihan_ganda'),
(2429, 2026, 429, 'Apa arti "Kostor" dalam struktur jemaat GMIM?', 'Pelayan kebersihan dan kerapihan gereja', 'Penjaga gereja', 'Pengurus properti', 'Pemandu ibadah', 'a', 'pilihan_ganda'),
(2430, 2026, 430, 'Siapakah yang menjadi Ketua KPRS periode 2005-2010?', 'Pnt. Drs. Jacobus Wowor', 'Pnt. dr. Michaela Paruntu', 'Pnt. Drs. Jantje Sajow', 'Pnt. Ir. Dwight Rondonuwu', 'a', 'pilihan_ganda'),
(2431, 2026, 431, 'Apa yang dimaksud dengan "Koinonia"?', 'Persekutuan orang percaya', 'Kesaksian', 'Pelayanan kasih', 'Ibadah', 'a', 'pilihan_ganda'),
(2432, 2026, 432, 'Siapakah yang menulis kitab 2 Tawarikh?', 'Ezra (tradisi)', 'Salomo', 'Musa', 'Daud', 'a', 'pilihan_ganda'),
(2433, 2026, 433, 'Apa arti "Bidang Pelsis" dalam KPRS?', 'Pelayanan Siswa', 'Pelayanan Sekolah', 'Pelayanan Sidi', 'Pelayanan Sinode', 'a', 'pilihan_ganda'),
(2434, 2026, 434, 'Siapakah nama istri dari Yakub yang paling dikasihi?', 'Rahel', 'Lea', 'Bilha', 'Zilpa', 'a', 'pilihan_ganda'),
(2435, 2026, 435, 'Berapa jumlah pasal dalam kitab Imamat?', '30', '27', '25', '24', 'b', 'pilihan_ganda'),
(2436, 2026, 436, 'Apa tema MTPJ bulan September?', 'Misi', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'Pendidikan dan Pengajaran', 'd', 'pilihan_ganda'),
(2437, 2026, 437, 'Siapakah yang menulis kitab Ezra?', 'Ezra', 'Hagai', 'Zerubabel', 'Nehemia', 'a', 'pilihan_ganda'),
(2438, 2026, 438, 'Apa yang dimaksud dengan "Martyria"?', 'Pelayanan kasih', 'Persekutuan', 'Ibadah', 'Kesaksian', 'd', 'pilihan_ganda'),
(2439, 2026, 439, 'Siapakah nama ayah dari Yohanes Pembaptis?', 'Harun', 'Imamat', 'Elkana', 'Zakharia', 'd', 'pilihan_ganda'),
(2440, 2026, 440, 'Apa arti "Pelayanan Anak" dalam struktur GMIM?', 'Pelayanan pemuda', 'Pelayanan untuk usia 11 tahun ke bawah', 'Pelayanan remaja', 'Pelayanan lansia', 'b', 'pilihan_ganda'),
(2441, 2026, 441, 'Teks "Sebaiknya pemerintah menurunkan harga BBM" adalah contoh ...', 'Opini', 'Hipotesis', 'Asumsi', 'Fakta', 'a', 'pilihan_ganda'),
(2442, 2026, 442, 'Siapa Menteri Pertahanan Indonesia periode 2024-2029?', 'Prabowo Subianto', 'Juwono Sudarsono', 'Ryamizard Ryacudu', 'Sjafrie Sjamsoeddin', 'd', 'pilihan_ganda'),
(2443, 2026, 443, 'The synonym of "fast" is ...', 'Lazy', 'Slow', 'Careful', 'Quick', 'd', 'pilihan_ganda'),
(2444, 2026, 444, 'Indonesia resmi menjadi anggota BRICS pada KTT di ...', 'Kazan, Rusia', 'Johannesburg, Afrika Selatan', 'New Delhi, India', 'Brasilia, Brasil', 'a', 'pilihan_ganda'),
(2445, 2026, 445, 'Hasil dari 12 × 5 - 30 + 45 ÷ 9 adalah ...', '40', '45', '30', '35', 'd', 'pilihan_ganda'),
(2446, 2026, 446, 'Apa nama pulau yang terkenal dengan lumba-lumba di Sulut?', 'Pulau Lihaga', 'Pulau Manado Tua', 'Pulau Lembeh', 'Pulau Bunaken', 'a', 'pilihan_ganda'),
(2447, 2026, 447, 'Piala Dunia 2030 akan diselenggarakan di negara ...', 'Amerika Serikat', 'Inggris', 'Spanyol, Portugal, Maroko', 'Uruguay, Argentina, Paraguay', 'c', 'pilihan_ganda'),
(2448, 2026, 448, 'Kepanjangan dari SSD adalah ...', 'Solid State Drive', 'Solid State Disk', 'Solid System Drive', 'Solid System Disk', 'a', 'pilihan_ganda'),
(2449, 2026, 449, 'Negara di Asia yang berbentuk kerajaan absolut adalah ...', 'Brunei', 'Malaysia', 'Arab Saudi', 'Thailand', 'c', 'pilihan_ganda'),
(2450, 2026, 450, 'Program "Makan Siang Gratis" adalah program unggulan presiden ...', 'Prabowo Subianto', 'Anies Baswedan', 'Ganjar Pranowo', 'Joko Widodo', 'a', 'pilihan_ganda'),
(2451, 2026, 451, 'Apa yang dimaksud dengan "Tahapan Final" dalam seleksi Retel?', 'Tahap wawancara', 'Tahap awal seleksi', 'Tahap karantina', 'Puncak acara penentuan juara', 'd', 'pilihan_ganda'),
(2452, 2026, 452, 'Siapakah yang menulis kitab Nehemia?', 'Ezra', 'Zerubabel', 'Hagai', 'Nehemia', 'd', 'pilihan_ganda'),
(2453, 2026, 453, 'Apa kepanjangan dari UPK?', 'Utusan Pelayanan Kategorial', 'Unsur Pelayanan Kategorial', 'Urusan Pelayanan Kategorial', 'Unit Pelayanan Kategorial', 'c', 'pilihan_ganda'),
(2454, 2026, 454, 'Siapakah yang disebut sebagai "Pembawa damai" dalam Khotbah di Bukit?', 'Setiap orang percaya', 'Hanya nabi', 'Hanya pendeta', 'Hanya rasul', 'a', 'pilihan_ganda'),
(2455, 2026, 455, 'Berapa jumlah murid Yesus yang terpilih menjadi rasul?', '10', '13', '11', '12', 'd', 'pilihan_ganda'),
(2456, 2026, 456, 'Apa arti "Gelar Remaja Teladan Berbakat"?', '100% nilai wawancara', '50% nilai karantina', '100% nilai tes tertulis', '40% nilai talent show karantina dan 60% kompetisi potensi diri', 'd', 'pilihan_ganda'),
(2457, 2026, 457, 'Siapakah yang menjadi raja Israel yang membaca kembali kitab Taurat?', 'Yosia', 'Daud', 'Salomo', 'Hizkia', 'a', 'pilihan_ganda'),
(2458, 2026, 458, 'Apa tema MTPJ minggu Pentakosta?', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'Kelahiran Yesus', 'Kenaikan Yesus', 'a', 'pilihan_ganda'),
(2459, 2026, 459, 'Siapakah yang menulis kitab Ester?', 'Nehemia', 'Ester', 'Ezra', 'Tidak diketahui (mungkin Mordekhai)', 'd', 'pilihan_ganda'),
(2460, 2026, 460, 'Apa yang dimaksud dengan "Tahapan Kompetisi Potensi Diri"?', 'Wawancara', 'Karantina', 'Tes tertulis', 'Lomba debat, pidato Inggris, dan karya tulis', 'd', 'pilihan_ganda'),
(2461, 2026, 461, 'Berapa bobot nilai Grand Final?', '5%', '15%', '20%', '25%', 'c', 'pilihan_ganda'),
(2462, 2026, 462, 'Siapakah nama anak dari Rahel yang bungsu?', 'Benyamin', 'Dan', 'Naftali', 'Yusuf', 'a', 'pilihan_ganda'),
(2463, 2026, 463, 'Apa warna liturgi untuk masa Adven?', 'Ungu', 'Merah', 'Hijau', 'Putih', 'a', 'pilihan_ganda'),
(2464, 2026, 464, 'Siapakah yang disebut sebagai "Pemungut cukai yang menjadi murid Yesus"?', 'Petrus', 'Yohanes', 'Yakobus', 'Matius', 'd', 'pilihan_ganda'),
(2465, 2026, 465, 'Apa arti "Katekisasi Pernikahan"?', 'Pengajaran umum', 'Pengajaran bagi calon pengantin', 'Pengajaran sidi', 'Pengajaran baptisan', 'b', 'pilihan_ganda'),
(2466, 2026, 466, 'Siapakah yang menulis kitab Ayub?', 'Salomo', 'Tidak diketahui (mungkin Ayub)', 'Daud', 'Musa', 'b', 'pilihan_ganda'),
(2467, 2026, 467, 'Apa kepanjangan dari UPK Kolom?', 'Unsur Pelayanan Kolom', 'Utusan Pelayanan Kolom', 'Urusan Pelayanan Kategorial', 'Unit Pelayanan Kolom', 'c', 'pilihan_ganda'),
(2468, 2026, 468, 'Berapa jumlah pasal dalam kitab Bilangan?', '40', '30', '34', '36', 'd', 'pilihan_ganda'),
(2469, 2026, 469, 'Siapakah yang menjadi Ketua Sinode GMIM periode 2000-2005?', 'Pdt. Dr. A.F. Parengkuan', 'Pdt. Dr. A.O. Supit', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. W.A. Roeroe', 'a', 'pilihan_ganda'),
(2470, 2026, 470, 'Apa yang dimaksud dengan "Pekerja GMIM"?', 'Hanya guru agama', 'Pendeta, guru agama, dan pegawai yang menerima biaya hidup dari GMIM', 'Hanya pendeta', 'Semua anggota jemaat', 'b', 'pilihan_ganda'),
(2471, 2026, 471, 'Siapakah yang menulis kitab Mazmur 23?', 'Asaf', 'Salomo', 'Musa', 'Daud', 'd', 'pilihan_ganda'),
(2472, 2026, 472, 'Apa arti "Bidang TIK" dalam KPRS?', 'Tugas Informasi dan Komunikasi', 'Tenaga Informasi dan Komunikasi', 'Teknologi Informasi dan Komunikasi', 'Tim Informasi dan Komunikasi', 'c', 'pilihan_ganda'),
(2473, 2026, 473, 'Siapakah nama anak dari Yusuf di Mesir?', 'Lewi', 'Manasye dan Efraim', 'Simeon', 'Ruben', 'b', 'pilihan_ganda'),
(2474, 2026, 474, 'Apa tema MTPJ bulan Agustus?', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'Kelahiran Yesus', 'Kemerdekaan dan Syukur', 'd', 'pilihan_ganda'),
(2475, 2026, 475, 'Siapakah yang menulis kitab Amsal 31 tentang istri yang cakap?', 'Yeremia', 'Musa', 'Salomo (tradisi)', 'Daud', 'c', 'pilihan_ganda'),
(2476, 2026, 476, 'Apa yang dimaksud dengan "Skala nilai A (Amat Baik)" dalam wawancara?', '50-60', '70-80', '81-90', '60-70', 'c', 'pilihan_ganda'),
(2477, 2026, 477, 'Siapakah nama anak dari Yusuf dari Mesir yang menjadi suku terbesar?', 'Ruben', 'Yehuda', 'Manasye', 'Efraim', 'd', 'pilihan_ganda'),
(2478, 2026, 478, 'Berapa jumlah pasal dalam kitab Yosua?', '22', '24', '20', '30', 'b', 'pilihan_ganda'),
(2479, 2026, 479, 'Apa arti "Jemaat" dalam struktur GMIM?', 'Persekutuan orang percaya di suatu tempat', 'Bangunan gereja', 'Majelis gereja', 'Organisasi gereja', 'a', 'pilihan_ganda'),
(2480, 2026, 480, 'Siapakah yang menjadi Ketua KPRS periode 1990-1995?', 'Pnt. Drs. Jantje Sajow', 'Pnt. Ir. Dwight Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pnt. Drs. Jacobus Wowor', 'd', 'pilihan_ganda'),
(2481, 2026, 481, 'Apa yang dimaksud dengan "Diakonia"?', 'Persekutuan', 'Ibadah', 'Kesaksian', 'Pelayanan kasih', 'd', 'pilihan_ganda'),
(2482, 2026, 482, 'Siapakah yang menulis kitab Ratapan?', 'Daniel', 'Yesaya', 'Yehezkiel', 'Yeremia', 'd', 'pilihan_ganda'),
(2483, 2026, 483, 'Apa arti "Bidang P3SDM" dalam KPRS?', 'Pendidikan, Pelatihan, Pengembangan SDM', 'Pembinaan, Pengkaderan, Pengembangan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pelayanan, Pengembangan, Pemberdayaan SDM', 'b', 'pilihan_ganda'),
(2484, 2026, 484, 'Siapakah nama istri dari Abraham yang melahirkan Ishak?', 'Hagar', 'Sara', 'Ribka', 'Rahel', 'b', 'pilihan_ganda'),
(2485, 2026, 485, 'Berapa jumlah pasal dalam kitab Hakim-hakim?', '21', '24', '20', '22', 'a', 'pilihan_ganda'),
(2486, 2026, 486, 'Apa tema MTPJ bulan Januari?', 'Kelahiran Yesus', 'Tahun baru dan pengharapan', 'Kebangkitan Yesus', 'Misi', 'b', 'pilihan_ganda'),
(2487, 2026, 487, 'Siapakah yang menulis kitab Rut?', 'Tidak diketahui (mungkin Samuel)', 'Boas', 'Naomi', 'Rut', 'a', 'pilihan_ganda'),
(2488, 2026, 488, 'Apa yang dimaksud dengan "Leiturgia"?', 'Kesaksian', 'Pelayanan kasih', 'Persekutuan', 'Ibadah dan penyembahan', 'd', 'pilihan_ganda'),
(2489, 2026, 489, 'Siapakah nama ayah dari Daud?', 'Boas', 'Salmon', 'Obet', 'Isai', 'd', 'pilihan_ganda'),
(2490, 2026, 490, 'Apa arti "Pelayanan Lansia" dalam struktur GMIM?', 'Pelayanan remaja', 'Pelayanan untuk usia 60 tahun ke atas', 'Pelayanan anak', 'Pelayanan pemuda', 'b', 'pilihan_ganda'),
(2491, 2026, 491, 'Teks "Kopi lebih baik diminum pagi hari daripada malam" adalah contoh ...', 'Asumsi', 'Fakta', 'Opini', 'Hipotesis', 'c', 'pilihan_ganda'),
(2492, 2026, 492, 'Siapa Menteri Koordinator Kemaritiman dan Investasi periode 2024-2029?', 'Joko Widodo', 'Ma''ruf Amin', 'Luhut Binsar Pandjaitan', 'Prabowo Subianto', 'c', 'pilihan_ganda'),
(2493, 2026, 493, 'The antonym of "strong" is ...', 'Tough', 'Weak', 'Mighty', 'Powerful', 'b', 'pilihan_ganda'),
(2494, 2026, 494, 'Indonesia menjadi tuan rumah Pertemuan IMF-World Bank pada tahun ...', '2024 di Jakarta', '2022 di Bali', '2025 di Surabaya', '2023 di Labuan Bajo', 'b', 'pilihan_ganda'),
(2495, 2026, 495, 'Hasil dari 14 × 3 - 18 + 24 ÷ 4 adalah ...', '28', '34', '30', '32', 'c', 'pilihan_ganda'),
(2496, 2026, 496, 'Apa nama pantai terkenal di Likupang?', 'Pantai Kima Bajo', 'Pantai Malalayang', 'Pantai Tongkaina', 'Pantai Paal', 'd', 'pilihan_ganda'),
(2497, 2026, 497, 'Piala Dunia Futsal 2024 diselenggarakan di negara ...', 'Indonesia', 'Vietnam', 'Thailand', 'Uzbekistan', 'd', 'pilihan_ganda'),
(2498, 2026, 498, 'Kepanjangan dari VPN adalah ...', 'Virtual Protected Network', 'Virtual Private Network', 'Virtual Personal Network', 'Virtual Public Network', 'b', 'pilihan_ganda'),
(2499, 2026, 499, 'Negara yang disebut sebagai "Negeri Sakura" adalah ...', 'Taiwan', 'China', 'Jepang', 'Korea Selatan', 'c', 'pilihan_ganda'),
(2500, 2026, 500, 'Program "Ibu Kota Nusantara (IKN)" dipindahkan dari ...', 'Jakarta ke Kalimantan Tengah', 'Jakarta ke Kalimantan Timur', 'Jakarta ke Kalimantan Barat', 'Jakarta ke Kalimantan Selatan', 'b', 'pilihan_ganda');
