-- PAKET A - 50 SOAL PREDIKSI RETEL GMIM 2026
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2026, 1, 'Berdasarkan Lukas 2:52, aspek pertumbuhan Yesus yang harus diteladani remaja GMIM adalah ...', 'Fisik, hikmat, rohani, dan sosial', 'Fisik, kekayaan, popularitas, dan kuasa', 'Hikmat, umur, kasih karunia, dan kuasa', 'Rohani, sosial, ekonomi, dan politik', 'a'),
(2026, 2, 'Visi pelayanan Remaja GMIM adalah ...', 'Remaja yang berakar, bertumbuh, dan berbuah', 'Remaja Bagi Kristus (Teens for Christ)', 'Remaja Teladan GMIM', 'Remaja Kreatif dan Inovatif', 'b'),
(2026, 3, 'Misi pelayanan Remaja GMIM adalah ...', 'Menjadikan remaja GMIM yang berakar, bertumbuh, dan berbuah bagi Kristus', 'Menjadikan remaja GMIM yang pintar dan berprestasi', 'Menjadikan remaja GMIM yang kaya dan terkenal', 'Menjadikan remaja GMIM yang patuh pada orang tua', 'a'),
(2026, 4, 'Sistem pemerintahan GMIM adalah ...', 'Episkopal', 'Kongregasional', 'Presbiterial Sinodal', 'Kharismatik', 'c'),
(2026, 5, 'GMIM berdiri sendiri sebagai gereja mandiri pada tanggal ...', '17 September 1934', '30 September 1934', '28 Januari 1990', '12 Juni 1831', 'b'),
(2026, 6, 'Komisi Pelayanan Remaja Sinode GMIM (KPRS) berdiri sendiri pada tanggal ...', '28 Januari 1990', '30 September 1934', '17 Agustus 1945', '28 Oktober 1928', 'a'),
(2026, 7, 'Hari Persatuan Remaja GMIM diperingati setiap tanggal ...', '28 Januari', '30 September', '17 Agustus', '1 April', 'a'),
(2026, 8, 'Semboyan Reformasi Gereja "Sola Fide" berarti ...', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'a'),
(2026, 9, 'Siapakah penginjil yang dijuluki "Rasul Maluku" dan datang ke Minahasa pada tahun 1817?', 'J.G. Schwarz', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'b'),
(2026, 10, 'Apakah kepanjangan dari NZG?', 'Nederlands Zendeling Genootschap', 'Nederlands Zending Genootschap', 'Nederland Zending Genootschap', 'Nederlands Zendeling Genootschap', 'b'),
(2026, 11, 'Siapakah nama ayah dari Samuel dalam Perjanjian Lama?', 'Elkana', 'Hana', 'Imamat', 'Saul', 'a'),
(2026, 12, 'Berapa jumlah orang yang dibaptis pada hari Pentakosta?', '120 orang', '3.000 orang', '5.000 orang', '12 orang', 'b'),
(2026, 13, 'Kata "Imago Dei" berarti ...', 'Manusia adalah gambar Allah', 'Manusia adalah ciptaan Allah', 'Manusia adalah hamba Allah', 'Manusia adalah teman Allah', 'a'),
(2026, 14, 'Dalam Tata Gereja GMIM 2021, remaja adalah anggota GMIM berusia ...', '12-16 tahun 364 hari', '12-17 tahun', '13-17 tahun', '12-18 tahun', 'a'),
(2026, 15, 'Satu periode pelayanan BPMS GMIM adalah ...', '3 tahun', '4 tahun', '5 tahun', '6 tahun', 'c'),
(2026, 16, 'Siapakah nama Ketua Sinode GMIM pertama?', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'a'),
(2026, 17, 'Siapakah nama Ketua Sinode GMIM orang Minahasa pertama?', 'Ds. A.Z.R. Wenas', 'Ds. E.A.A. de Vreede', 'Pdt. R.M. Luntungan', 'Pdt. M. Sondakh', 'a'),
(2026, 18, 'Lambang GMIM adalah burung ...', 'Manguni', 'Garuda', 'Rajawali', 'Merpati', 'a'),
(2026, 19, 'Apa makna falsafah Minahasa "Sitou Timou Tumou Tou"?', 'Manusia hidup untuk memanusiakan manusia lain', 'Manusia hidup untuk bekerja keras', 'Manusia hidup untuk beribadah', 'Manusia hidup untuk bersenang-senang', 'a'),
(2026, 20, 'Kepanjangan dari LKRG adalah ...', 'Latihan Kader Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'a'),
(2026, 21, 'Program pemuridan KPRS yang disebut KB3 adalah singkatan dari ...', 'Komunitas Berakar, Bertumbuh, Berbuah', 'Keluarga Berakar, Bertumbuh, Berbuah', 'Kelompok Berakar, Bertumbuh, Berbuah', 'Kesatuan Berakar, Bertumbuh, Berbuah', 'a'),
(2026, 22, 'Lagu "Menjadi Teladan" diciptakan oleh ...', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. Jantje Wowiling Sajow', 'Pnt. dr. Michaela E. Paruntu', 'Pdt. Dr. Hein Arina', 'a'),
(2026, 23, 'Siapakah yang menulis surat kepada jemaat di Roma?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a'),
(2026, 24, '"Aku percaya kepada satu Allah, Bapa yang mahakuasa, Pencipta langit dan bumi" adalah kalimat pembuka dari ...', 'Pengakuan Iman Rasuli', 'Pengakuan Iman Nicea-Konstantinopel', 'Pengakuan Iman Athanasius', 'Doa Bapa Kami', 'b'),
(2026, 25, 'Siapakah yang disebut sebagai "Gembala yang Baik" dalam Yohanes 10?', 'Yesus Kristus', 'Petrus', 'Paulus', 'Daud', 'a'),
(2026, 26, 'Apa inti dari Amanat Agung Yesus dalam Matius 28:19-20?', 'Pergi, jadikan semua bangsa murid, baptis, dan ajarkan', 'Kasihilah sesamamu seperti dirimu sendiri', 'Jangan membunuh dan jangan mencuri', 'Berdoalah tanpa henti', 'a'),
(2026, 27, 'Buah Roh dalam Galatia 5:22-23 terdiri dari ...', 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri', 'Iman, pengharapan, kasih', 'Hikmat, pengertian, nasihat, keperkasaan', 'Kemuliaan, hormat, kuasa, kekuatan', 'a'),
(2026, 28, 'Siapakah yang melempar Daud ke dalam gua singa?', 'Raja Darius', 'Raja Nebukadnezar', 'Raja Herodes', 'Raja Saul', 'a'),
(2026, 29, 'Program SIKAT yang dikembangkan KPRS adalah singkatan dari ...', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Komunikasi Terpadu', 'Sistem Informasi Kegiatan Terkini', 'Sistem Informasi Keuangan Terpadu', 'a'),
(2026, 30, 'Tahun 2025, KPRS mengadakan program GEMAR yang dikelola bidang ...', 'Ajaran, Persekutuan, Ibadah dan Misi (APIM)', 'Pengembangan Minat dan Bakat (PMB)', 'Pembinaan dan Pengembangan SDM (P3SDM)', 'Teknologi Informasi dan Komunikasi (TIK)', 'a'),
(2026, 31, 'Untuk membantu pelayanan KPRS, dibentuk Koordinatorium Rayon Pelayanan yang dibagi dalam ... rayon', '10', '11', '12', '13', 'c'),
(2026, 32, 'Siapakah nama hamba Imam Besar yang telinga kanannya putus karena dipotong Simon Petrus?', 'Malkhus', 'Yudas', 'Anas', 'Kayafas', 'a'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Yeremia?', '42', '52', '62', '72', 'b'),
(2026, 34, 'Kota apakah yang disebut sebagai kota Daud?', 'Betlehem', 'Yerusalem', 'Nazaret', 'Hebron', 'a'),
(2026, 35, 'Pada hari ke berapakah Allah menjadikan benda-benda penerang pada cakrawala?', 'Hari kedua', 'Hari ketiga', 'Hari keempat', 'Hari kelima', 'c'),
(2026, 36, 'Berapakah jumlah ikan yang diperoleh para murid setelah Yesus menyuruh menebarkan jala di sebelah kanan perahu?', '120 ekor', '150 ekor', '153 ekor', '200 ekor', 'c'),
(2026, 37, 'Apakah tema mingguan MTPJ pada tanggal 25-31 Mei 2025?', 'Berbahagia dan Kuduslah Mereka yang Mendapat Bagian dalam Kebangkitan', 'Yesus Menampakkan Diri Setelah Bangkit', 'Percaya kepada Kristus yang Bangkit', 'Tuhan Allah, Pahlawan yang Memberi Kemenangan', 'a'),
(2026, 38, 'Siapakah Ketua BPMS GMIM yang memimpin saat GMIM mengubah eklesiologinya menjadi Gereja Global?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. A.O. Supit', 'a'),
(2026, 39, 'Siapakah penginjil yang datang ke tanah Minahasa pada tahun 1817?', 'Johann Friedrich Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a'),
(2026, 40, 'Dalam Tata Dasar Bab II Pasal 7, anggota GMIM adalah ...', 'Orang-orang percaya kepada Yesus Kristus yang terdaftar di salah satu jemaat GMIM', 'Semua orang yang tinggal di Minahasa', 'Orang-orang yang lahir di Minahasa', 'Mereka yang dibaptis di GMIM', 'a'),
(2026, 41, 'Teks "Matahari terbit di timur dan terbenam di barat" merupakan contoh kalimat ...', 'Fakta', 'Opini', 'Asumsi', 'Hipotesis', 'a'),
(2026, 42, 'Pemerintah Indonesia resmi memindahkan Ibu Kota Negara ke ... pada tahun 2024', 'Nusantara (Kalimantan Timur)', 'Palangkaraya', 'Balikpapan', 'Samarinda', 'a'),
(2026, 43, 'The antonym of the word "victory" is ...', 'Defeat', 'Success', 'Triumph', 'Win', 'a'),
(2026, 44, 'Indonesia menjadi tuan rumah KTT G20 pada tahun ...', '2022', '2023', '2024', '2025', 'a'),
(2026, 45, 'Hasil dari 25 × 4 - 100 ÷ 5 adalah ...', '80', '100', '120', '90', 'a'),
(2026, 46, 'Apa nama gunung berapi di Sulawesi Utara yang meletus pada April 2024?', 'Gunung Ruang', 'Gunung Lokon', 'Gunung Soputan', 'Gunung Karangetang', 'a'),
(2026, 47, 'KTT G20 tahun 2025 dilaksanakan di negara ...', 'Afrika Selatan', 'Brasil', 'India', 'Indonesia', 'a'),
(2026, 48, 'Kepanjangan dari AI (kecerdasan buatan) dalam bahasa Inggris adalah ...', 'Artificial Intelligence', 'Artificial Information', 'Automated Intelligence', 'Advanced Integration', 'a'),
(2026, 49, 'Negara yang tidak pernah mengalami penjajahan di Asia Tenggara adalah ...', 'Thailand', 'Indonesia', 'Malaysia', 'Vietnam', 'a'),
(2026, 50, 'Ciri utama dari sistem ekonomi Pancasila adalah ...', 'Kekeluargaan dan gotong royong', 'Bebas dan liberal', 'Terpusat dan komando', 'Kapitalis dan individualis', 'a');

-- PAKET B - 50 SOAL PREDIKSI RETEL GMIM 2026
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2026, 1, 'Model remaja GMIM yang diharapkan berdasarkan Lukas 2:52 adalah remaja yang bertumbuh dalam ...', 'Fisik, hikmat, rohani, dan sosial', 'Fisik, ekonomi, politik, dan budaya', 'Rohani, intelektual, ekonomi, dan sosial', 'Hikmat, popularitas, kekayaan, dan kuasa', 'a'),
(2026, 2, 'Visi "Remaja Bagi Kristus" mengandung makna bahwa ...', 'Seluruh hidup remaja dipersembahkan bagi Kristus', 'Remaja hanya datang ke gereja pada hari Minggu', 'Remaja harus menjadi pendeta', 'Remaja harus meninggalkan dunia', 'a'),
(2026, 3, 'Tujuan program LKRG adalah ...', 'Mempersiapkan kader remaja yang militan dan berkarakter Kristus', 'Melatih remaja menjadi pengusaha sukses', 'Mempersiapkan remaja menjadi atlet', 'Mengajarkan remaja keterampilan digital', 'a'),
(2026, 4, 'Sakramen yang dilayankan GMIM adalah ...', 'Baptisan Kudus dan Perjamuan Kudus', 'Baptisan, Perjamuan Kudus, dan Pernikahan', 'Baptisan, Krisma, dan Perjamuan Kudus', 'Perjamuan Kudus dan Pengakuan Dosa', 'a'),
(2026, 5, 'Pembukaan Tata Gereja GMIM 2021 menyatakan bahwa GMIM adalah bagian dari ...', 'Gereja Protestan di Indonesia', 'Gereja Katolik', 'Gereja Pentakosta', 'Gereja Orthodox', 'a'),
(2026, 6, 'Pemilihan Remaja Teladan GMIM memiliki tahapan akhir yang disebut ...', 'Grand Final', 'Karantina', 'Pelayanan Holistik', 'Kompetisi Potensi Diri', 'a'),
(2026, 7, 'Bobot penilaian untuk tahap Karantina dan Pelayanan Holistik dalam Pemilihan Remaja Teladan adalah ...', '35%', '25%', '20%', '15%', 'a'),
(2026, 8, 'Semboyan Reformasi "Sola Gratia" berarti ...', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'a'),
(2026, 9, 'Siapa yang mencetuskan Reformasi Gereja pada tahun 1517?', 'Martin Luther', 'Yohanes Calvin', 'John Knox', 'Ulrich Zwingli', 'a'),
(2026, 10, 'Apakah yang dimaksud dengan "Presbiterial Sinodal"?', 'Sistem kepemimpinan kolektif para penatua dengan musyawarah', 'Sistem kepemimpinan satu uskup', 'Sistem kepemimpinan yang terpusat', 'Sistem kepemimpinan yang demokratis', 'a'),
(2026, 11, 'Siapakah yang menggantikan Yudas Iskariot sebagai rasul?', 'Matias', 'Barnabas', 'Stefanus', 'Filipus', 'a'),
(2026, 12, 'Berapa jumlah kitab dalam Perjanjian Baru?', '27', '39', '66', '24', 'a'),
(2026, 13, 'Nats "Jangan seorang pun menganggap engkau rendah karena engkau muda" terdapat dalam ...', '1 Timotius 4:12', '2 Timotius 4:12', 'Titus 4:12', 'Efesus 4:12', 'a'),
(2026, 14, 'Dalam Tata Gereja GMIM 2021, satu periode pelayanan GMIM adalah ...', '5 tahun', '4 tahun', '3 tahun', '6 tahun', 'a'),
(2026, 15, 'Tahun pelayanan dan tahun anggaran GMIM dimulai tanggal ...', '1 Januari sampai 31 Desember', '1 April sampai 31 Maret', '1 Maret sampai 28 Februari', '1 Juli sampai 30 Juni', 'a'),
(2026, 16, 'Siapakah Ketua Sinode GMIM yang menjabat dua periode?', 'Ds. A.Z.R. Wenas dan Pdt. Dr. W.A. Roeroe', 'Pdt. Dr. Hein Arina', 'Pdt. Piet M. Tampi', 'Ds. E.A.A. de Vreede', 'a'),
(2026, 17, 'Siapakah yang mengutus misionaris Schwarz dan Riedel ke Minahasa?', 'NZG (Nederlands Zending Genootschap)', 'Zending Belanda', 'Indische Kerk', 'Gereja Reformasi Belanda', 'a'),
(2026, 18, 'Apa warna dasar selempang untuk finalis Remaja Teladan tingkat Sinode?', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan emas', 'Ungu dengan tulisan perak', 'a'),
(2026, 19, 'Apa makna burung Manguni dalam lambang GMIM?', 'Gereja sebagai terang di tengah kegelapan', 'Gereja yang kuat dan perkasa', 'Gereja yang kaya raya', 'Gereja yang modern', 'a'),
(2026, 20, 'Kepanjangan dari PKRS adalah ...', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'a'),
(2026, 21, 'Siapakah yang menciptakan Mars Remaja GMIM?', 'Pnt. Jantje Wowiling Sajow', 'Pnt. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pdt. Hein Arina', 'a'),
(2026, 22, 'Program GEMAR (Gerakan Membaca Alkitab Remaja) bertujuan untuk ...', 'Mendorong remaja membaca Alkitab secara terstruktur', 'Mengajarkan remaja bermain musik', 'Melatih remaja menjadi pengkhotbah', 'Mengadakan lomba cerdas cermat Alkitab', 'a'),
(2026, 23, 'Siapakah yang menulis kitab Wahyu?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'a'),
(2026, 24, '"Aku percaya kepada Allah, Bapa yang mahakuasa, Khalik langit dan bumi" adalah pengakuan iman ...', 'Pengakuan Iman Rasuli', 'Pengakuan Iman Nicea-Konstantinopel', 'Pengakuan Iman Athanasius', 'Doa Bapa Kami', 'a'),
(2026, 25, 'Siapakah yang disebut sebagai "Bapa Orang Percaya"?', 'Abraham', 'Musa', 'Daud', 'Adam', 'a'),
(2026, 26, 'Apa isi dari Sepuluh Perintah Allah (Dekalog)?', 'Perintah untuk mengasihi Tuhan dan sesama', 'Perintah untuk beribadah setiap hari', 'Perintah untuk berpuasa', 'Perintah untuk bersedekah', 'a'),
(2026, 27, 'Karunia Roh Kudus dalam 1 Korintus 12 antara lain ...', 'Bernubuat, melayani, mengajar, menasihati', 'Bernyanyi, menari, bermusik, melukis', 'Berbicara dalam bahasa roh, menyembuhkan', 'Semua jawaban benar', 'a'),
(2026, 28, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja Babel?', 'Daniel', 'Yusuf', 'Musa', 'Daud', 'a'),
(2026, 29, 'Tuan rumah Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2025 adalah ...', 'Wilayah Sinel', 'Wilayah Airmadidi', 'Wilayah Tomohon', 'Wilayah Tondano', 'a'),
(2026, 30, 'Bidang P3SDM dalam KPRS memiliki kepanjangan ...', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, dan Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a'),
(2026, 31, 'Wakil Sekretaris Koordinasi Program antar Komisi Pelayanan Kategorial Sinode GMIM adalah ...', 'Pdt. Jefry Saisab, S.Th, M.Si', 'Pdt. Hein Arina, Th.D', 'Pdt. DR. Joice Sondakh, M.Th', 'Pdt. Christian Luwuk, M.Th', 'a'),
(2026, 32, 'Siapakah nama isteri Yusuf dalam Kejadian pasal 41?', 'Asnat', 'Dina', 'Abisag', 'Potifera', 'a'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Mazmur yang paling panjang?', '119', '117', '150', '100', 'a'),
(2026, 34, 'Kota apakah yang menjadi tempat kelahiran Yesus?', 'Betlehem', 'Nazaret', 'Yerusalem', 'Kapernaum', 'a'),
(2026, 35, 'Siapakah nama ibu dari Samuel?', 'Hana', 'Elkana', 'Sara', 'Ribka', 'a'),
(2026, 36, 'Apakah nama lain yang diberikan kepada Daniel oleh pegawai istana Babel?', 'Beltsazar', 'Sadrakh', 'Mesakh', 'Abednego', 'a'),
(2026, 37, 'Apakah judul perikop dari Roma 10:4-15?', 'Kebenaran karena iman', 'Keselamatan oleh kasih karunia', 'Pembenaran oleh iman', 'Ketaatan karena iman', 'a'),
(2026, 38, 'Siapakah Ketua Komisi Pelayanan Remaja Sinode GMIM periode 2022-2027?', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. Melky R. Pattiwael, S.IK, M.S', 'Pnt. Edward Saragih, SAP', 'a'),
(2026, 39, 'Siapakah nama misionaris yang melayani di Langowan dan Kakas?', 'J.G. Schwarz', 'J.F. Riedel', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a'),
(2026, 40, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 1, penyelenggaraan panggilan GMIM bersumber dari ...', 'Pola pelayanan dan pemerintahan Kristus', 'Tata Gereja GMIM', 'Kesaksian Alkitab', 'Yesus Kristus', 'a'),
(2026, 41, 'Teks "Sayur itu akan terasa lebih sedap jika ditambah sedikit garam" merupakan contoh kalimat ...', 'Asumsi', 'Fakta', 'Opini', 'Deskripsi', 'a'),
(2026, 42, 'Siapa presiden terpilih Indonesia pada Pemilu 2024?', 'Prabowo Subianto', 'Ganjar Pranowo', 'Anies Baswedan', 'Joko Widodo', 'a'),
(2026, 43, 'Which sentence uses the correct conditional form?', 'If I study hard, I will pass the exam', 'If I will study hard, I will pass the exam', 'If I studied hard, I will pass the exam', 'If I study hard, I would pass the exam', 'a'),
(2026, 44, 'Indonesia menjadi anggota BRICS pada tahun ...', '2024', '2023', '2025', '2022', 'a'),
(2026, 45, 'Sebuah kubus memiliki panjang sisi 4 cm. Volume kubus tersebut adalah ...', '64 cm³', '16 cm³', '48 cm³', '32 cm³', 'a'),
(2026, 46, 'Apa nama bendungan yang diresmikan Presiden Jokowi di Sulawesi Utara pada Februari 2024?', 'Bendungan Lolak', 'Bendungan Kuwi', 'Bendungan Kuwil', 'Bendungan Tondano', 'a'),
(2026, 47, 'Piala Dunia FIFA 2026 akan diselenggarakan bersama oleh negara ...', 'Amerika Serikat, Kanada, Meksiko', 'Amerika Serikat, Inggris, Prancis', 'Kanada, Meksiko, Brasil', 'Spanyol, Portugal, Maroko', 'a'),
(2026, 48, 'Kepanjangan dari API dalam bidang teknologi adalah ...', 'Application Programming Interface', 'Advanced Programming Interface', 'Automated Programming Integration', 'Application Processing Interface', 'a'),
(2026, 49, 'Negara dengan jumlah penduduk terbanyak di dunia adalah ...', 'India', 'China', 'Amerika Serikat', 'Indonesia', 'a'),
(2026, 50, 'Kebijakan pemerintah Indonesia untuk membatasi penggunaan media sosial bagi anak di bawah umur disebut ...', 'Pembatasan usia pengguna medsos', 'Digital restriction', 'Social media ban', 'Internet filter', 'a');

-- PAKET C - 50 SOAL PREDIKSI RETEL GMIM 2026
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2026, 1, 'Makna dari "Remaja Teladan" menurut Pola Baku GMIM adalah ...', 'Remaja yang memiliki prestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang kaya dan terkenal', 'Remaja yang populer di media sosial', 'Remaja yang menjadi ketua OSIS', 'a'),
(2026, 2, 'Salah satu aspek yang dinilai dalam Pemilihan Remaja Teladan adalah ...', 'Pelayanan Holistik', 'Kekayaan orang tua', 'Popularitas di media sosial', 'Jumlah teman', 'a'),
(2026, 3, 'Kepanjangan dari P3SDM dalam struktur KPRS adalah ...', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a'),
(2026, 4, 'Sakramen Baptisan Kudus dalam GMIM dilayankan ...', 'Sekali seumur hidup', 'Setiap tahun', 'Setiap kali bertobat', 'Sebelum menikah', 'a'),
(2026, 5, 'Badan Pekerja Majelis Sinode (BPMS) dipilih setiap ...', '5 tahun sekali dalam Sidang Majelis Sinode', '4 tahun sekali', '3 tahun sekali', '6 tahun sekali', 'a'),
(2026, 6, 'Tahapan seleksi Pemilihan Remaja Teladan yang berupa pengabdian kepada jemaat adalah ...', 'Pelayanan Holistik', 'Karantina', 'Kompetisi Potensi Diri', 'Tes Wawancara', 'a'),
(2026, 7, 'Bobot penilaian untuk tahap Kompetisi Potensi Diri adalah ...', '25%', '35%', '20%', '15%', 'a'),
(2026, 8, 'Semboyan Reformasi "Soli Deo Gloria" berarti ...', 'Segala kemuliaan hanya bagi Tuhan', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh kasih karunia', 'Hanya Alkitab sebagai otoritas', 'a'),
(2026, 9, 'Apa yang dimaksud dengan "Indische Kerk"?', 'Gereja Hindia Belanda yang menjadi cikal bakal GMIM', 'Gereja pertama di Indonesia', 'Gereja yang didirikan oleh para misionaris', 'Gereja di tanah Minahasa', 'a'),
(2026, 10, 'Siapakah Ketua BPMS GMIM periode 2018-2022?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'a'),
(2026, 11, 'Siapakah yang menulis kitab Amsal?', 'Salomo', 'Daud', 'Musa', 'Yeremia', 'a'),
(2026, 12, 'Berapa jumlah kitab dalam Perjanjian Lama?', '39', '27', '66', '40', 'a'),
(2026, 13, 'Ayat terpendek dalam Alkitab adalah ...', 'Yohanes 11:35', '1 Tesalonika 5:16', 'Mazmur 117:1', 'Amsal 20:10', 'a'),
(2026, 14, 'Dalam Peraturan tentang Jemaat, remaja adalah anggota GMIM berusia ...', '12-16 tahun 364 hari', '13-17 tahun', '12-17 tahun', '11-16 tahun', 'a'),
(2026, 15, 'Tahun pelayanan BPMJ dimulai tanggal ...', '1 Januari', '1 Maret', '1 April', '1 Juli', 'a'),
(2026, 16, 'Siapakah Ketua Sinode GMIM yang dikenal dengan slogan "Tuhan mengangkat kita dari Samudera Raya"?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Henny Sumakul', 'Pdt. Dr. W.A. Roeroe', 'Pdt. Piet M. Tampi', 'a'),
(2026, 17, 'Siapakah nama misionaris yang melayani di Tondano?', 'J.F. Riedel', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Pdt. A.Z.R. Wenas', 'a'),
(2026, 18, 'Apa warna selempang untuk finalis Remaja Teladan tingkat Wilayah?', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'a'),
(2026, 19, 'Tarian tradisional Minahasa yang menggambarkan sukacita panen adalah ...', 'Tari Maengket', 'Tari Kabasaran', 'Tari Cakalele', 'Tari Gantar', 'a'),
(2026, 20, 'Kepanjangan dari PSR (dalam kegiatan remaja) adalah ...', 'Pesta Seni Remaja', 'Perkemahan Seni Remaja', 'Pekan Seni Remaja', 'Pentas Seni Remaja', 'a'),
(2026, 21, 'Lagu Mars Remaja GMIM pertama kali diperkenalkan pada tahun ...', '1990', '1995', '2000', '2005', 'a'),
(2026, 22, 'Siapakah Ketua KPRS periode 2014-2018?', 'Pnt. Ir. Dwight Moody Rondonuwu, MT', 'Pnt. dr. Michaela E. Paruntu', 'Pnt. Melky R. Pattiwael', 'Pnt. Edward Saragih', 'a'),
(2026, 23, 'Siapakah yang menulis surat kepada jemaat di Korintus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a'),
(2026, 24, 'Perikop terpendek dalam Mazmur adalah ...', 'Mazmur 117:1-2', 'Mazmur 23:1-6', 'Mazmur 1:1-6', 'Mazmur 150:1-6', 'a'),
(2026, 25, 'Siapakah yang menulis kitab Kisah Para Rasul?', 'Lukas', 'Matius', 'Markus', 'Yohanes', 'a'),
(2026, 26, 'Apa pesan utama dari perumpamaan tentang Talenta?', 'Kita harus mengembangkan karunia yang Tuhan berikan', 'Kita harus menyembunyikan talenta', 'Kita harus mencari talenta sebanyak-banyaknya', 'Kita harus membuang talenta yang tidak berguna', 'a'),
(2026, 27, 'Dalam 1 Korintus 13, yang paling besar di antara iman, pengharapan, dan kasih adalah ...', 'Kasih', 'Iman', 'Pengharapan', 'Ketiganya sama besar', 'a'),
(2026, 28, 'Siapakah yang dijual oleh saudara-saudaranya ke Mesir?', 'Yusuf', 'Daniel', 'Musa', 'Daud', 'a'),
(2026, 29, 'Sistem Informasi Kegiatan Terpadu (SIKAT) dikembangkan oleh bidang ...', 'TIK KPRS', 'APIM', 'P3SDM', 'PMB', 'a'),
(2026, 30, 'Gelar atribut "Remaja Teladan Intelegensia" diukur dari ...', '50% nilai tes tertulis dan 50% nilai psikotes karantina', '100% nilai tes tertulis', '100% nilai wawancara', '50% nilai wawancara dan 50% nilai karantina', 'a'),
(2026, 31, 'Gelar atribut "Remaja Teladan Persahabatan" diukur dari ...', 'Pilihan dari sesama peserta', 'Penilaian juri', 'Like di media sosial', 'Nilai psikotes', 'a'),
(2026, 32, 'Siapakah nama ibu dari Yesus?', 'Maria', 'Marta', 'Salome', 'Elisabeth', 'a'),
(2026, 33, 'Berapakah jumlah pasal dalam kitab Yesaya?', '66', '52', '50', '42', 'a'),
(2026, 34, 'Di manakah Yesus dibaptis oleh Yohanes Pembaptis?', 'Sungai Yordan', 'Danau Galilea', 'Laut Mati', 'Bukit Zaitun', 'a'),
(2026, 35, 'Siapakah yang menjadi raja pertama Israel?', 'Saul', 'Daud', 'Salomo', 'Yerobeam', 'a'),
(2026, 36, 'Berapa lamakah bangsa Israel berjalan di padang gurun?', '40 tahun', '30 tahun', '20 tahun', '10 tahun', 'a'),
(2026, 37, 'Apakah tema MTPJ yang berfokus pada "Kebangkitan Yesus mengubah manusia"?', 'Paskah', 'Adven', 'Natal', 'Pentakosta', 'a'),
(2026, 38, 'Siapakah Wakil Sekretaris BPMS Bidang Pekerja GMIM dan Pelayan Khusus periode 2014-2018?', 'Pnt. Jhonly Th Wenur, SH, MH, MM', 'Pdt. Richard Mengko', 'Pdt. Altje Runtu-Lumi', 'Pdt. Janny Rende', 'a'),
(2026, 39, 'Di manakah makam penginjil Ulfers berada?', 'Tomohon', 'Tondano', 'Kakas', 'Langowan', 'a'),
(2026, 40, 'Dalam Tata Dasar Bab III Pasal 8, GMIM ditata dalam sistem ...', 'Presbiterial Sinodal', 'Episkopal', 'Kongregasional', 'Sinodal', 'a'),
(2026, 41, 'Kata "hiperbola" dalam kalimat memiliki arti ...', 'Perbandingan yang berlebihan', 'Gambaran yang nyata', 'Makna yang tersembunyi', 'Simbolisme yang mendalam', 'a'),
(2026, 42, 'Indonesia menjadi tuan rumah KTT ASEAN pada tahun ...', '2023', '2024', '2025', '2022', 'a'),
(2026, 43, 'The word "meticulous" is closest in meaning to ...', 'Detail-oriented', 'Careless', 'Lazy', 'Impulsive', 'a'),
(2026, 44, 'Contoh cryptocurrency yang dikenal luas adalah ...', 'Bitcoin', 'Facebook Coin', 'Google Pay', 'Apple Cash', 'a'),
(2026, 45, 'Diketahui deret aritmatika 3, 7, 11, 15,... Suku ke-10 adalah ...', '39', '35', '43', '31', 'a'),
(2026, 46, 'Proses fotosintesis menghasilkan ...', 'Oksigen dan glukosa', 'Karbon dioksida dan air', 'Energi panas', 'Protein dan lemak', 'a'),
(2026, 47, 'Piala Dunia U-20 tahun 2023 seharusnya diselenggarakan di ...', 'Indonesia', 'Argentina', 'Qatar', 'Afrika Selatan', 'a'),
(2026, 48, 'Siapa yang dikenal sebagai "Bapak Komputer" (penemu komputer modern)?', 'Alan Turing', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'a'),
(2026, 49, 'Lembaga yang bertugas menangani korupsi di Indonesia adalah ...', 'KPK (Komisi Pemberantasan Korupsi)', 'BPK', 'BPKP', 'Kejaksaan Agung', 'a'),
(2026, 50, 'Program ketahanan pangan yang digalakkan pemerintah Indonesia disebut ...', 'Ketahanan pangan mandiri', 'Program beras murah', 'Dapur sehat', 'Makan gratis', 'a');

-- PAKET D - 50 SOAL PREDIKSI RETEL GMIM 2026 (151-200)
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2026, 151, 'Berapakah jumlah kitab dalam Alkitab (TB)?', '66', '73', '60', '70', 'a'),
(2026, 152, 'Siapakah penulis kitab Kejadian?', 'Musa', 'Abraham', 'Daud', 'Salomo', 'a'),
(2026, 153, 'Apa warna liturgi untuk hari raya Natal?', 'Putih', 'Merah', 'Ungu', 'Hijau', 'a'),
(2026, 154, 'Siapakah Ketua Sinode GMIM saat ini?', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. Joice Sondakh', 'Pdt. Dr. Everett Tangel', 'Pdt. Dr. Adolf Wenas', 'a'),
(2026, 155, 'Di mana Yesus lahir?', 'Betlehem', 'Nazaret', 'Yerusalem', 'Kana', 'a'),
(2026, 156, 'Siapakah murid yang menyangkal Yesus 3 kali?', 'Petrus', 'Yudas', 'Yohanes', 'Tomas', 'a'),
(2026, 157, 'Apa kepanjangan dari GMIM?', 'Gereja Masehi Injili di Minahasa', 'Gerakan Masehi Injili di Minahasa', 'Gereja Masyarakat Injili di Minahasa', 'Gereja Masehi Indonesia di Minahasa', 'a'),
(2026, 158, 'GMIM berdiri sebagai gereja mandiri sejak tahun ...', '1934', '1945', '1930', '1950', 'a'),
(2026, 159, 'Siapakah Ketua KPRS GMIM periode 2022-2027?', 'Pnt. dr. Michaela Paruntu', 'Pnt. Melky Pattiwael', 'Pnt. Edward Saragih', 'Pnt. Stevie Kaligis', 'a'),
(2026, 160, 'Semboyan Remaja GMIM adalah ...', 'Teens for Christ', 'Remaja Berakar', 'Remaja Teladan', 'Remaja Cerdas', 'a'),
(2026, 161, 'The opposite of "generous" is ...', 'Stingy', 'Kind', 'Helpful', 'Polite', 'a'),
(2026, 162, 'What is the largest ocean on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'a'),
(2026, 163, 'Hasil dari 100 / 4 + 25 adalah ...', '50', '25', '75', '100', 'a'),
(2026, 164, 'Siapa penemu gravitasi?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 'a'),
(2026, 165, 'Ibukota Sulawesi Utara adalah ...', 'Manado', 'Bitung', 'Tomohon', 'Minahasa', 'a'),
(2026, 166, 'Gunung tertinggi di Indonesia adalah ...', 'Puncak Jaya', 'Gunung Kerinci', 'Gunung Rinjani', 'Gunung Semeru', 'a'),
(2026, 167, 'Lagu kebangsaan Indonesia adalah ...', 'Indonesia Raya', 'Tanah Airku', 'Bagimu Negeri', 'Garuda Pancasila', 'a'),
(2026, 168, 'Presiden pertama Indonesia adalah ...', 'Ir. Soekarno', 'Moh. Hatta', 'Soeharto', 'B.J. Habibie', 'a'),
(2026, 169, 'Which element has the symbol "O"?', 'Oxygen', 'Gold', 'Silver', 'Iron', 'a'),
(2026, 170, 'Berapa jumlah sila dalam Pancasila?', '5', '4', '6', '3', 'a'),
(2026, 171, 'Siapakah pahlawan emansipasi wanita di Indonesia?', 'R.A. Kartini', 'Cut Nyak Dien', 'Martha Christina Tiahahu', 'Dewi Sartika', 'a'),
(2026, 172, 'Planet terdekat dengan matahari adalah ...', 'Merkurius', 'Venus', 'Bumi', 'Mars', 'a'),
(2026, 173, 'Who is the author of "Romeo and Juliet"?', 'William Shakespeare', 'Mark Twain', 'Charles Dickens', 'J.K. Rowling', 'a'),
(2026, 174, 'Berapa derajat dalam satu lingkaran penuh?', '360', '180', '90', '270', 'a'),
(2026, 175, 'Hewan mamalia terbesar di laut adalah ...', 'Paus Biru', 'Hiu Putih', 'Lumba-lumba', 'Anjing Laut', 'a'),
(2026, 176, 'Ibukota Jawa Timur adalah ...', 'Surabaya', 'Malang', 'Kediri', 'Madiun', 'a'),
(2026, 177, 'Siapakah pencipta lagu Indonesia Raya?', 'W.R. Supratman', 'Ismail Marzuki', 'Kusbini', 'Cornel Simanjuntak', 'a'),
(2026, 178, 'Apa kepanjangan dari DPR?', 'Dewan Perwakilan Rakyat', 'Dewan Pembangunan Rakyat', 'Dewan Pemuda Rakyat', 'Dewan Pemerintah Rakyat', 'a'),
(2026, 179, 'Which mammal can fly?', 'Bat', 'Eagle', 'Ostrich', 'Penguin', 'a'),
(2026, 180, 'What is the sum of 15 and 27?', '42', '32', '52', '45', 'a'),
(2026, 181, 'Siapa penemu telepon?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi', 'a'),
(2026, 182, 'Indonesia merdeka pada tanggal ...', '17 Agustus 1945', '1 Juni 1945', '10 November 1945', '28 Oktober 1928', 'a'),
(2026, 183, 'The color for "Danger" is often ...', 'Red', 'Blue', 'Green', 'Yellow', 'a'),
(2026, 184, 'Which month has 28 or 29 days?', 'February', 'January', 'March', 'April', 'a'),
(2026, 185, 'Berapa hasil dari 5 pangkat 2?', '25', '10', '15', '20', 'a'),
(2026, 186, 'Ibukota negara Jepang adalah ...', 'Tokyo', 'Seoul', 'Beijing', 'Bangkok', 'a'),
(2026, 187, 'Siapa penulis novel "Harry Potter"?', 'J.K. Rowling', 'Stephen King', 'Agatha Christie', 'Enid Blyton', 'a'),
(2026, 188, 'Apa simbol kimia untuk emas?', 'Au', 'Ag', 'Fe', 'Cu', 'a'),
(2026, 189, 'Sila kedua Pancasila adalah ...', 'Kemanusiaan yang adil dan beradab', 'Ketuhanan Yang Maha Esa', 'Persatuan Indonesia', 'Keadilan sosial', 'a'),
(2026, 190, 'Hari Pahlawan diperingati setiap tanggal ...', '10 November', '28 Oktober', '1 Juni', '2 Mei', 'a'),
(2026, 191, 'What is 10 x 10?', '100', '10', '1000', '20', 'a'),
(2026, 192, 'Which is the fastest land animal?', 'Cheetah', 'Lion', 'Horse', 'Eagle', 'a'),
(2026, 193, 'What is the currency of the USA?', 'Dollar', 'Euro', 'Yen', 'Pound', 'a'),
(2026, 194, 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh', 'Michelangelo', 'a'),
(2026, 195, 'Berapa 25% dari 100?', '25', '50', '20', '75', 'a'),
(2026, 196, 'Siapa penemu listrik?', 'Benjamin Franklin', 'Michael Faraday', 'Thomas Edison', 'Nikola Tesla', 'b'),
(2026, 197, 'Ibukota Sulawesi Selatan adalah ...', 'Makassar', 'Kendari', 'Palu', 'Manado', 'a'),
(2026, 198, 'Siapa pahlawan dari Sulawesi Utara yang wajahnya ada di uang kertas 10rb?', 'Frans Kaisiepo', 'Sam Ratulangi', 'Moh. Hatta', 'Djuanda', 'b'),
(2026, 199, 'Danau terbesar di Indonesia adalah ...', 'Danau Toba', 'Danau Tempe', 'Danau Poso', 'Danau Towuti', 'a'),
(2026, 200, 'Tari tradisional asal Sulawesi Utara adalah ...', 'Tari Maengket', 'Tari Saman', 'Tari Kecak', 'Tari Jaipong', 'a');

-- PAKET E-J (DUMMY placeholder for the rest to reach 500)
-- (Users can replace these with actual questions as they wish)
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) 
SELECT 2026, generate_series(201, 500), 'Pertanyaan Simulasi Paket ' || CASE 
    WHEN generate_series <= 250 THEN 'E'
    WHEN generate_series <= 300 THEN 'F'
    WHEN generate_series <= 350 THEN 'G'
    WHEN generate_series <= 400 THEN 'H'
    WHEN generate_series <= 450 THEN 'I'
    ELSE 'J' END || ' nomor ' || generate_series, 'Opsi A', 'Opsi B', 'Opsi C', 'Opsi D', 'a';
