-- ============================================================
-- PORTAL RETEL GMIM - SEED SOAL RANGKUMAN (2019-2025)
-- Paket 1: 2091, Paket 2: 2092, Paket 3: 2093 (Tiap paket 50 soal)
-- Kolom: tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar
-- ============================================================

INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2091, 1, 'Siapakah yang menjadi raja Israel yang pertama?', 'Daud', 'Yerobeam', 'Salomo', 'Saul', 'd'),
(2091, 2, 'Kepala Kepolisian Republik Indonesia adalah :', 'Badrodin Haiti', 'Badarudin Haiti', 'Badridon Haiti', 'Budi Gunawan', 'a'),
(2091, 3, 'Perbandingan nilai suatu mata uang dengan mata uang negara lain disebut ....', 'Kurs valuta asing', 'Kurs tetap', 'Kurs melebihi uang', 'Kurs bebas', 'a'),
(2091, 4, 'Hukum I Newton menyatakan bahwa...', 'Benda akan selalu diam atau bergerak dengan kelajuan tetap jika tidak ada gaya yang bekerja padanya', 'Gaya yang bekerja pada suatu benda akan menghasilkan percepatan yang sebanding dengan gaya tersebut', 'Untuk setiap aksi, selalu ada reaksi yang sama besar dan berlawanan arah', 'Suatu benda akan terus bergerak dengan kelajuan konstan jika tidak ada gaya yang bekerja padanya', 'a'),
(2091, 5, 'Siapakah nama istri dari Abraham yang melahirkan Ishak?', 'Sara', 'Hagar', 'Ribka', 'Rahel', 'a'),
(2091, 6, 'Diketahui luas selimut sebuah tabung 1.650 cm². Jika tinggi tabung 25 cm, maka jari-jari tabung tersebut adalah', '21 cm', '10,5 cm', '14 cm', '7 cm', 'b'),
(2091, 7, 'Apa arti Semboyan Reformasi?', 'Iman, Pengharapan, Kasih', 'Bersekutu, Bersaksi, Melayani', 'Sola Fide, Sola Gratia, Sola Scriptura, Soli Deo Gloria', 'Doa, Puasa, Sedekah', 'c'),
(2091, 8, 'Tahun 1860, lebih dari 50% penduduk Minahasa sudah menjadi Kristen sehingga terbentuk 10 Pos Pekabaran Injil yaitu :', 'Tondano, Langoan, Amurang, Tomohon, Kema, Tanawangko, Kumelembuai, Sonder, Ratahan dan Talawaan', 'Tondano, Kawangkoan, Amurang, Tomohon, Kema, Tanawangko, Kumelembuai, Sonder, Ratahan dan Talawaan', 'Talawaan, Ratahan, Tondano, Tumpaan, Tanawangko, Tomohon, Amurang, Sonder, Kumelembuai, Kema', 'Amurang, Sonder, Kumelembuai, Kema, Talawaan, Ratahan, Tondano, Tanawangko, Tomohon, Motoling', 'b'),
(2091, 9, 'Apa yang dimaksud dengan Akumulasi nilai?', 'Nilai rata-rata', 'Penjumlahan nilai dari berbagai tahapan seleksi', 'Nilai terendah', 'Nilai tertinggi', 'b'),
(2091, 10, 'Apa kepanjangan dari NZG?', 'Nederlands Zending Genootschap', 'Nederlands Zendeling Genootschap', 'Nederland Zending Genootschap', 'Nederland Zendeling Genootschap', 'a'),
(2091, 11, 'Sekretaris BPMS GMIM Periode 2014 – 2018 pada periode sebelumnya menjabat sebagai :', 'Sekretaris Departemen BPMS', 'Anggota BPMS', 'Wakil Sekretaris BPMS', 'Ketua Wilayah', 'c'),
(2091, 12, 'Siapakah yang menulis kitab Ester?', 'Tidak diketahui (mungkin Mordekhai)', 'Ester', 'Ezra', 'Nehemia', 'a'),
(2091, 13, 'Hasil dari 25 × 4 - 100 ÷ 5 adalah ...', '120', '100', '90', '80', 'd'),
(2091, 14, 'Apa nama air terjun terkenal di Minahasa?', 'Air Terjun Tunan', 'Air Terjun Sekar', 'Air Terjun Sipiso-piso', 'Air Terjun Madakaripura', 'a'),
(2091, 15, 'Siapakah yang menjadi Ketua Sinode GMIM terlama?', 'Ds. E.A.A. de Vreede', 'Ds. A.Z.R. Wenas', 'Pdt. Dr. Hein Arina', 'Pdt. Dr. W.A. Roeroe', 'd'),
(2091, 16, 'Siapakah yang menulis kitab Efesus?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a'),
(2091, 17, 'Jika pada periode 2010 – 2014 jumlah BPMS GMIM adalah 14 orang, berapa orangkah pada periode sekarang ini :', '21 orang', '15 orang', '14 orang', '12 orang', 'b'),
(2091, 18, 'Apakah bunyi dari Injil Matius 10:16 ?', 'Aku datang untuk melemparkan api ke bumi dan betapakah Aku harapkan, api itu telah menyala!', 'Tetapi kamu bukan demikian. Kamu telah belajar mengenal Kristus.', 'Lihat, Aku mengutus kamu seperti domba ke tengah-tengah serigala, sebab itu hendaklah kamu cerdik seperti ular dan tulus seperti merpati.', 'Karena bukan kamu yang berkata-kata, melainkan Roh Bapamu; Dia yang akan berkata-kata di dalam kamu.', 'c'),
(2091, 19, 'Hasil dari 27^(2/3) + 100^0 + 64^(1/6) - 64^(1/3) adalah', '16', '12', '10', '8', 'b'),
(2091, 20, 'Siapa yang mencetuskan Reformasi Gereja pada tahun 1517?', 'Martin Luther', 'Yohanes Calvin', 'John Knox', 'Ulrich Zwingli', 'a'),
(2091, 21, 'Apa singkatan dari LKRG?', 'Latihan Kader Remaja Gereja', 'Latihan Kepemimpinan Remaja Gereja', 'Latihan Kreativitas Remaja Gereja', 'Latihan Ketrampilan Remaja Gereja', 'a'),
(2091, 22, 'Who is that woman? ...... her before, but I can''t remember where.', 'I''ve see', 'I saw', 'I see', 'I''ve seen', 'd'),
(2091, 23, 'Misi pelayanan Remaja GMIM adalah ...', 'Menjadikan remaja GMIM yang berakar, bertumbuh, dan berbuah bagi Kristus', 'Menjadikan remaja GMIM yang pintar dan berprestasi', 'Menjadikan remaja GMIM yang kaya dan terkenal', 'Menjadikan remaja GMIM yang patuh pada orang tua', 'a'),
(2091, 24, 'Apa kepanjangan dari P3SDM?', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'Perencanaan, Pengorganisasian, Pengawasan SDM', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'a'),
(2091, 25, 'Interaksi yang dikategorikan simbiosis mutualisme ditunjukkan oleh...', '1 dan 2', '1 dan 3', '3 dan 4', '2 dan 4', 'c'),
(2091, 26, 'Tuan rumah Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2025 adalah ...', 'Wilayah Sinel', 'Wilayah Airmadidi', 'Wilayah Tomohon', 'Wilayah Tondano', 'a'),
(2091, 27, 'Sebelum menjadi Ketua KPRS pada periode saat ini, Pnt. Ir. D.Moody Rondonuwu MT pada periode sebelumnya menjadi KPRS pada jabatan apa?', 'Ketua Bidang Minat dan Bakat', 'Ketua Bidang Data dan Umum', 'Ketua Bidang Pelayanan Siswa', 'Semua salah', 'b'),
(2091, 28, 'Proses masuknya udara melalui saluran pernafasan yang tepat adalah . . . .', 'trakea - pulmo - bronkus - bronkiolus', 'trakea - bronkus - bronkiolus - pulmo', 'trakea - pulmo - bronkiolus - bronkus', 'trakea - bronkiolus - bronkus - pulmo', 'b'),
(2091, 29, 'Dalam Tata Dasar Bab II Pasal 6 Ayat 1, penyelenggaraan panggilan GMIM bersumber dari ...', 'Pola pelayanan dan pemerintahan Kristus', 'Tata Gereja GMIM', 'Kesaksian Alkitab', 'Yesus Kristus', 'a'),
(2091, 30, 'Siapa Menteri Pertahanan Indonesia periode 2024-2029?', 'Sjafrie Sjamsoeddin', 'Prabowo Subianto', 'Ryamizard Ryacudu', 'Juwono Sudarsono', 'a'),
(2091, 31, 'Apa nama taman laut terkenal di Sulawesi Utara?', 'Bunaken', 'Raja Ampat', 'Wakatobi', 'Derawan', 'a'),
(2091, 32, 'GMIM sebagai gereja mandiri ditata dalam sistem …', 'Episkopal', 'Kongregasional', 'Presbiterial Sinodal', 'Sinodal', 'c'),
(2091, 33, 'Pada tanggal berapakah pemilihan kepala daerah serentak di Indonesia tahun 2024', '27 November 2024', '25 Oktober 2024', '25 November 2024', '27 Oktober 2024', 'a'),
(2091, 34, 'Di bawah ini adalah 5 Negara kerajaan yang benar, kecuali:', 'Inggris, Arab Saudi, Denmark, Swedia dan Kamboja', 'Inggris, Arab Saudi, Belanda, Denmark dan Maroko', 'Maroko, Kamboja, Yordania, Swedia dan Spanyol', 'Inggris, Arab Saudi, Australia, Thailand dan Belanda', 'd'),
(2091, 35, 'Negara ASEAN yang tidak memiliki laut adalah ...', 'Laos', 'Kamboja', 'Thailand', 'Myanmar', 'a'),
(2091, 36, 'Apa arti Katekisasi Baptisan?', 'Pengajaran bagi calon baptisan', 'Pengajaran sidi', 'Pengajaran pernikahan', 'Pengajaran umum', 'a'),
(2091, 37, 'Siapakah yang menulis kitab Filipi?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'c'),
(2091, 38, 'Siapakah Ketua KPRS periode 2022-2027?', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Edward Saragih', 'Pnt. Melky R. Pattiwael', 'b'),
(2091, 39, 'Apa yang dimaksud dengan Presbiterial Sinodal?', 'Kepemimpinan kolektif para penatua dengan musyawarah', 'Kepemimpinan satu uskup', 'Kepemimpinan kongregasi independen', 'Kepemimpinan karismatik', 'a'),
(2091, 40, 'Kegiatan Pesta Seni Remaja GMIM tahun 2014 dilaksanakan pada :', '5-6 September 2014 di Wilayah Pineleng', '5-6 September 2014 di Wilayah Pinaesaan', '5-6 September 2014 di Wilayah Pakolor Indah', 'Semua jawaban salah', 'a'),
(2091, 41, 'Apa warna dasar selempang finalis tingkat Rayon?', 'Hitam dengan tulisan perak', 'Ungu dengan tulisan perak', 'Hitam dengan tulisan emas', 'Ungu dengan tulisan emas', 'a'),
(2091, 42, 'Siapakah yang menulis kitab Nehemia?', 'Nehemia', 'Ezra', 'Zerubabel', 'Hagai', 'a'),
(2091, 43, 'Tata Gereja GMIM 2007 terdiri dari :', '1 Tata Dasar, 8 Peraturan', '1 Tata Dasar, 7 Peraturan', '1 Tata Dasar, 9 Peraturan', '1 Tata Dasar, 10 Peraturan', 'a'),
(2091, 44, 'Siapakah yang disebut sebagai Pembawa damai dalam Khotbah di Bukit?', 'Setiap orang percaya', 'Hanya nabi', 'Hanya pendeta', 'Hanya rasul', 'a'),
(2091, 45, 'Piala Dunia 2022 diselenggarakan di negara ...', 'Brasil', 'Jerman', 'Rusia', 'Qatar', 'd'),
(2091, 46, 'Apa warna dasar selempang untuk finalis Remaja Teladan tingkat Sinode?', 'Ungu dengan tulisan perak', 'Ungu dengan tulisan emas', 'Hitam dengan tulisan emas', 'Hitam dengan tulisan perak', 'c'),
(2091, 47, 'Sakramen Baptisan Kudus dalam GMIM dilayankan ...', 'Sekali seumur hidup', 'Setiap tahun', 'Setiap kali bertobat', 'Sebelum menikah', 'a'),
(2091, 48, 'Tarian tradisional Minahasa yang menggambarkan sukacita panen adalah ...', 'Tari Maengket', 'Tari Kabasaran', 'Tari Cakalele', 'Tari Gantar', 'a'),
(2091, 49, 'Berapa jumlah pasal dalam kitab Yesaya?', '66', '52', '50', '60', 'a'),
(2091, 50, 'Proses fotosintesis menghasilkan ...', 'Energi panas', 'Protein dan lemak', 'Karbon dioksida dan air', 'Oksigen dan glukosa', 'd'),
-- Paket 2
(2092, 1, 'Rumusan masalah yang tepat sesuai tema Meningkatkan prestasi belajar siswa dengan membaca bersama adalah...', 'Siapa sajakah yang prestasi belajarnya meningkat?', 'Kapan kita dapat meningkatkan prestasi belajar?', 'Bagaimanakah upaya peningkatan prestasi belajar dengan membaca bersama?', 'Apakah dengan belajar dapat meningkatkan prestasi belajar bersama?', 'c'),
(2092, 2, 'Apa yang dimaksud dengan Remaja Teladan menurut Pola Baku GMIM?', 'Remaja usia 12-16 tahun yang berprestasi akademik, berwawasan luas, dan berkelakuan baik', 'Remaja yang memiliki orang tua kaya', 'Remaja yang populer di lingkungan gereja', 'Remaja yang menjadi pengurus komisi remaja', 'a'),
(2092, 3, 'Salah satu hal yang sangat penting dan harus diperhatikan seorang calon pemeran ialah memahami ciri-ciri tokoh yang hendak diperankan, kecuali ....', 'Biologis', 'Psikologis', 'Sosiologis', 'Estetik', 'd'),
(2092, 4, 'GMIM sebagai Gereja Bagian Mandiri dari Gereja Protestan di Indonesia sejak ...', '17 September 1934', '30 September 1934', '12 Juni 1831', '28 Oktober 1928', 'b'),
(2092, 5, 'Siapakah yang disebut sebagai Juru Selamat dunia?', 'Yesus Kristus', 'Musa', 'Nabi Muhammad', 'Buddha', 'a'),
(2092, 6, 'Apa warna liturgi untuk masa Adven?', 'Ungu', 'Putih', 'Merah', 'Hijau', 'a'),
(2092, 7, 'Siapakah yang menciptakan Mars Remaja GMIM?', 'Pnt. Jantje Wowiling Sajow', 'Pnt. Dwight Moody Rondonuwu', 'Pnt. dr. Michaela Paruntu', 'Pdt. Hein Arina', 'a'),
(2092, 8, 'Berikut ini adalah anggota Komisi Pelayanan Remaja Sinode GMIM periode 2014-2018 yang baru pertama kali kecuali :', 'Pnt. Melky R. Pattiwael, SIK. MSI', 'Pnt. Santi G. Luntungan, ST', 'Pnt. Cerry Lumangkan', 'Pnt. Charles Mamelas', 'c'),
(2092, 9, 'Salah satu aspek yang dinilai dalam Pemilihan Remaja Teladan adalah ...', 'Pelayanan Holistik', 'Kekayaan orang tua', 'Popularitas di media sosial', 'Jumlah teman', 'a'),
(2092, 10, 'Contoh gerak lurus berubah beraturan dipercepat yang benar adalah...', '1 dan 2', '1 dan 3', '2 dan 3', '2 dan 4', 'b'),
(2092, 11, 'Kepanjangan yang benar dari Bidang P3SDM adalah :', 'Pembinaan, Pengkaderan dan Pengembangan Sumber Daya Manusia', 'Pemberdayaan, Pembinaan dan Pengembangan Sumber Daya Manusia', 'Pengkaderan, Pemberdayaan dan Pengembangan Sumber Daya Manusia', 'Pengembangan, Pembinaan dan Pengkaderan Sumber Daya Manusia', 'a'),
(2092, 12, 'Perang Dunia II dimulai pada tahun:', '1939', '1945', '1950', '1914', 'a'),
(2092, 13, 'Mazmur 23:1-6 judul perikopnya adalah :', 'Doa dalam Pergumulan', 'Tuhan, gembalaku yang baik', 'Doa pada malam hari', 'Dalam Perlindungan Tuhan', 'b'),
(2092, 14, 'Siapakah yang menulis kitab Amsal 31 tentang istri yang cakap?', 'Yeremia', 'Musa', 'Salomo (tradisi)', 'Daud', 'c'),
(2092, 15, 'Perikop terpendek dalam Mazmur adalah ...', 'Mazmur 117:1-2', 'Mazmur 23:1-6', 'Mazmur 1:1-6', 'Mazmur 150:1-6', 'a'),
(2092, 16, 'Siapakah Ketua KPRS periode 2022-2027?', 'Pnt. dr. Michaela E. Paruntu, MARS', 'Pnt. Ir. Dwight Moody Rondonuwu', 'Pnt. Melky R. Pattiwael', 'Pnt. Edward Saragih', 'a'),
(2092, 17, 'Sidang Majelis Sinode Istimewa (SMSI) ke 78 dimana pada hari pertama membahas perubahan Tata Gereja 2007 dilaksanakan pada :', '17-18 Mei 2016', '18-19 Mei 2016', '15-17 Mei 2016', '15-18 Mei 2016', 'b'),
(2092, 18, 'Siapa Wakil Presiden Indonesia periode 2019-2024?', 'Ma''ruf Amin', 'Jusuf Kalla', 'Boediono', 'Try Sutrisno', 'a'),
(2092, 19, 'Yang merupakan faktor produksi asli adalah....', '1 dan 2', '2 dan 3', '1 dan 4', '1 dan 3', 'a'),
(2092, 20, 'Berapa jumlah orang yang dibaptis pada hari Pentakosta?', '120 orang', '12 orang', '5.000 orang', '3.000 orang', 'd'),
(2092, 21, 'Apakah judul perikop Efesus 4:17-24 yang merupakan pembacaan Alkitab warga GMIM pada tanggal 19-25 Juni 2022?', 'Kesatuan jemaat dan karunia yang berbeda-beda', 'Manusia baru', 'Hidup sebagai anak-anak terang', 'Taat dan kasih', 'b'),
(2092, 22, 'Apa yang dimaksud dengan Parousia?', 'Kedatangan Tuhan kedua kali', 'Kenaikan Yesus', 'Kelahiran Yesus', 'Kebangkitan Yesus', 'a'),
(2092, 23, 'Siapakah yang disebut sebagai Bapak Reformasi Gereja?', 'Martin Luther', 'Yohanes Calvin', 'John Knox', 'Ulrich Zwingli', 'a'),
(2092, 24, 'Apa tema MTPJ minggu Pentakosta?', 'Pencurahan Roh Kudus', 'Kebangkitan Yesus', 'Kenaikan Yesus', 'Kelahiran Yesus', 'a'),
(2092, 25, 'Negara terkecil di dunia adalah?', 'Monaco', 'Sealand', 'Vatikan', 'Kongo', 'c'),
(2092, 26, 'What is the purpose of a safety notice at airport?', 'To give the message to all readers', 'To ban the use of hand phone at the airport', 'To warn people not to carry hand phone', 'To remind passengers not to carry hand phone on the plane', 'd'),
(2092, 27, 'Sesuai Peraturan tentang Sinode pasal 30 ayat 2, maka Rapat Komisi dipimpin oleh :', 'Ketua dan Sekretaris Komisi', 'Anggota Komisi yang ditunjuk', 'Ketua Komisi', 'Ketua, Sekretaris dan Asisten Bendahara', 'a'),
(2092, 28, 'Bersorak-sorailah, hai puteri Sion, bertempik-soraklah, hai Israel!... Nats ini terdapat dalam Kitab :', 'Zefanya', 'Roma', 'Hosea', 'Ibrani', 'a'),
(2092, 29, 'Siapakah nama ketua sinode orang Minahasa pertama yang dikukuhkan dalam sidang sinode Mei tahun 1942', 'Ds. A. Z. R. Wenas', 'Ds. A. Y. R. Wenas', 'Ds. Y. A. Z. Wenas', 'Ds. Y. Z. R. Wenas', 'a'),
(2092, 30, 'Siapakah Ketua Komisi Pelayanan Remaja Wilayah Tanahwangko II terpilih periode 2018-2022?', 'Pnt. Meillany Mongilala, S.T', 'Pnt. DR. Fietber Raco, S.Pd. M.Si', 'Pnt. Melky Pattiwael', 'Pnt. Stevie Kaligis', 'a'),
(2092, 31, 'Pembukaan Tata Gereja GMIM 2021 menyatakan bahwa GMIM adalah bagian dari ...', 'Gereja Katolik', 'Gereja Pentakosta', 'Gereja Protestan di Indonesia', 'Gereja Orthodox', 'c'),
(2092, 32, 'Slogan yang tepat sesuai dengan ilustrasi kepala sekolah tentang kebersihan lingkungan adalah...', 'Sampah musuh kita, bersih sahabat kita', 'Kebersihan sekolah merupakan kewajiban semua siswa', 'Jagalah kebersihan kelas dan lingkungan kelas masing-masing', 'Setiap hari kita harus menjaga kebersihan lingkungan sekolah kita', 'a'),
(2092, 33, 'Lengkapi Nats: Jangan takut, Kamu mencari Yesus orang Nazaret yang disalibkan itu. ... Ia tidak ada disini. Lihat! Inilah tempat mereka membaringkan Dia.', 'Ia telah bangkit', 'Ia telah dibangkitkan', 'Ia sudah bangkit', 'Ia sudah dibangkitkan', 'b'),
(2092, 34, 'Tujuan Mahasiswa, pemuda, dan pelajar mencetuskan TRITURA adalah...', 'Mengukuhkan Supersemar', 'Menyelenggarakan aksi Demonstrasi', 'Merebut basis kekuatan PKI', 'Membersihkan kabinet', 'd'),
(2092, 35, 'Berdasarkan Lukas 2:52, Model remaja GMIM yang diharapkan menjadi remaja seperti Yesus terdiri dari aspek?', 'Aspek Sosial dan Spiritual, Aspek Fisik', 'Spiritual dan Intelektual, Aspek Fisik', 'Intelektual dan sosial', 'Aspek Fisik, Intelektual, Spiritual dan Sosial', 'd'),
(2092, 36, 'Siapakah yang disebut sebagai Bapa Orang Percaya?', 'Abraham', 'Musa', 'Daud', 'Adam', 'a'),
(2092, 37, 'Ada 2 negara yang tidak menanggapi aksi-aksi yang dilakukan rakyat Indonesia yang menuntut untuk kembali ke Negara Kesatuan. Dua negara tersebut adalah …', 'Negara Indonesia Timur dan Kalimantan', 'Negara Jawa Timur dan Negara Pasundan', 'Negara Sumatera Timur dan Negara Indonesia Timur', 'Negara Madura dan Negara Jawa Timur', 'c'),
(2092, 38, 'Gunung tertinggi di Indonesia adalah ...', 'Puncak Jaya', 'Gunung Kerinci', 'Gunung Rinjani', 'Gunung Semeru', 'a'),
(2092, 39, 'Siapakah nama ayah dari Samuel dalam Perjanjian Lama?', 'Elkana', 'Hana', 'Imamat', 'Saul', 'a'),
(2092, 40, 'Siapakah yang menulis surat kepada jemaat di Filipi?', 'Paulus', 'Petrus', 'Yohanes', 'Yakobus', 'a'),
(2092, 41, 'Apakah yang dimaksud dengan Presbiterial Sinodal?', 'Sistem kepemimpinan kolektif para penatua dengan musyawarah', 'Sistem kepemimpinan satu uskup', 'Sistem kepemimpinan yang terpusat', 'Sistem kepemimpinan yang demokratis', 'a'),
(2092, 42, 'Yang bukan merupakan sifat gelombang elektromagnetik adalah....', 'memerlukan medium', 'tidak menyimpang dalam medan listrik', 'arah getarannya tegak lurus arah rambatan', 'dapat dipantulkan dan dibiaskan', 'a'),
(2092, 43, 'Mayoritas negara-negara maju berada di belahan bumi bagian ....', 'Selatan', 'Utara', 'Timur', 'Tengah', 'b'),
(2092, 44, 'Siapakah Yang menulis Surat kepada jemaat Korintus dan Efesus?', 'Paulus kepada Jemaat Korintus dan Petrus kepada Jemaat Efesus', 'Petrus kepada Jemaat Korintus dan Jemaat Efesus', 'Petrus kepada Jemaat Korintus dan Paulus kepada Jemaat Efesus', 'Paulus kepada Jemaat Korintus dan Jemaat Efesus', 'd'),
(2092, 45, 'Siapakah yang menulis kitab 2 Tesalonika?', 'Yohanes', 'Petrus', 'Paulus', 'Yakobus', 'c'),
(2092, 46, 'Kata hiperbola dalam kalimat memiliki arti ...', 'Perbandingan yang berlebihan', 'Gambaran yang nyata', 'Makna yang tersembunyi', 'Simbolisme yang mendalam', 'a'),
(2092, 47, 'Kitab Hosea terletak antara Kitab-Kitab apakah :', 'Daniel - Yoel', 'Yoel - Amos', 'Nahum - Habakuk', 'Zefanya - Hagai', 'b'),
(2092, 48, 'Hari Ulang Tahun ke-55 Provinsi Sulawesi Utara jatuh pada tanggal?', '22 September 2019', '23 September 2019', '24 September 2019', '25 September 2019', 'b'),
(2092, 49, 'Hari Persatuan Remaja GMIM diperingati setiap tanggal ...', '28 Januari', '30 September', '17 Agustus', '1 April', 'a'),
(2092, 50, 'Tema Bulanan sesuai MTPJ Bulan April 2016 adalah :', 'Berjalan Bersama Yesus Yang telah bangkit', 'Diutus untuk membebaskan', 'Kebangkitan Yesus Mengubah Manusia', 'Pemulihan Dunia', 'a'),
-- Paket 3
(2093, 1, 'Bobot penilaian untuk tahap Kompetisi Potensi Diri adalah ...', '25%', '35%', '20%', '15%', 'a'),
(2093, 2, 'Dari himpunan di atas yang merupakan himpunan kosong adalah…', 'Himpunan A dan B', 'Himpunan B dan C', 'Himpunan A dan C', 'Himpunan A, B, dan C', 'c'),
(2093, 3, 'The synonym of difficult is ...', 'Easy', 'Hard', 'Simple', 'Light', 'b'),
(2093, 4, 'Apa warna liturgi untuk masa Paskah?', 'Merah', 'Putih', 'Hijau', 'Ungu', 'b'),
(2093, 5, 'Ketua Sinode GMIM yang pertama yang adalah orang pribumi adalah :', 'Ds. A. Z. R. Wenas', 'Ds. R. M. Luntungan', 'Ds. M. Sondakh', 'Pdt. DR. W. A. Roeroe', 'a'),
(2093, 6, 'Pembukaan Tata Gereja GMIM 2021 menyatakan bahwa GMIM adalah bagian dari ...', 'Gereja Protestan di Indonesia', 'Gereja Katolik', 'Gereja Pentakosta', 'Gereja Orthodox', 'a'),
(2093, 7, 'Propinsi terdiri dari gabungan dari kabupaten/kota. Jumlah Kabupaten/Kota di Sulawesi Utara adalah...', '12', '13', '14', '15', 'd'),
(2093, 8, 'Bidang P3SDM dalam KPRS memiliki kepanjangan ...', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Perencanaan, Pengorganisasian, dan Pengawasan SDM', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'a'),
(2093, 9, 'Berikut ini hal-hal yang perlu diperhatikan seorang pewawancara, kecuali ....', 'gunakan bahasa yang sopan', 'diawali wawancara dengan ucapan selamat', 'arahkan pandangan ke narasumber', 'menyanjung tinggi narasumber', 'd'),
(2093, 10, 'Berapa banyak rusuk yang dimiliki kubus?', '12 buah', '16 buah', '32 buah', '10 buah', 'a'),
(2093, 11, 'Siapa Wakil Presiden Indonesia periode 2024-2029?', 'Gibran Rakabuming Raka', 'Boediono', 'Ma''ruf Amin', 'Jusuf Kalla', 'a'),
(2093, 12, 'Siapakah nama anak dari Daud dengan Batsyeba yang menjadi raja?', 'Salomo', 'Absalom', 'Amnon', 'Adonia', 'a'),
(2093, 13, 'Indonesia merdeka pada tanggal ...', '17 Agustus 1945', '1 Juni 1945', '10 November 1945', '28 Oktober 1928', 'a'),
(2093, 14, 'Tuan rumah pelaksanaan Perkemahan Kreatif Remaja Sinode (PKRS) tahun 2023 adalah?', 'Wilayah Amurang 4', 'Wilayah Tengah', 'Wilayah Amurang 3', 'Wilayah Amurang 1', 'd'),
(2093, 15, 'Apa tema Misi Remaja GMIM?', 'Remaja Kreatif', 'Remaja Bagi Kristus', 'Berakar, Bertumbuh, Berbuah bagi Kristus', 'Menjadi Teladan', 'c'),
(2093, 16, 'Kepanjangan yang benar dari Bidang LKRG adalah:', 'Latihan Kepemimpinan Remaja GMIM', 'Latihan Ketrampilan Remaja Gereja', 'Latihan Kader Remaja Gereja', 'Latihan Kegenerasian Remaja Gereja', 'c'),
(2093, 17, 'Berapa jumlah pasal dalam kitab Bilangan?', '40', '30', '34', '36', 'd'),
(2093, 18, 'Gelar atribut Remaja Teladan Intelegensia diukur dari ...', '100% nilai wawancara', '50% nilai wawancara dan 50% nilai karantina', '100% nilai tes tertulis', '50% nilai tes tertulis dan 50% nilai psikotes karantina', 'd'),
(2093, 19, 'Siapakah yang berani tidak menajiskan diri dengan makanan raja Babel?', 'Daniel', 'Yusuf', 'Musa', 'Daud', 'a'),
(2093, 20, 'Apa arti Katekisasi Pernikahan?', 'Pengajaran bagi calon pengantin', 'Pengajaran baptisan', 'Pengajaran sidi', 'Pengajaran umum', 'a'),
(2093, 21, 'Siapakah nama anak dari Yakub dari Lea?', 'Ruben, Simeon, Lewi, Yehuda', 'Yusuf', 'Benyamin', 'Dan', 'a'),
(2093, 22, 'Berapa bobot nilai Grand Final?', '5%', '15%', '20%', '25%', 'c'),
(2093, 23, 'Semboyan Reformasi Gereja Sola Fide berarti ...', 'Keselamatan hanya oleh iman', 'Keselamatan hanya oleh kasih karunia', 'Keselamatan hanya oleh Alkitab', 'Kemuliaan hanya bagi Tuhan', 'a'),
(2093, 24, 'Di manakah makam penginjil Ulfers berada?', 'Tomohon', 'Tondano', 'Kakas', 'Langowan', 'a'),
(2093, 25, 'Cara yang dapat dilakukan untuk mengatasi pencemaran yang terjadi di daerah perkotaan adalah ....', 'mengurangi produksi kendaraan', 'melarang pengusaha mendirikan pabrik', 'menghentikan penggunaan bahan bakar minyak', 'melakukan reboisasi di sepanjang jalan kota', 'd'),
(2093, 26, 'Negara yang tidak pernah mengalami penjajahan di Asia Tenggara adalah ...', 'Thailand', 'Indonesia', 'Malaysia', 'Vietnam', 'a'),
(2093, 27, 'Siapakah nama ayah dan ibu dari Samuel?', 'Abraham dan Sara', 'Amram dan Yokhebed', 'Elkana dan Hana', 'Yusuf dan Maria', 'c'),
(2093, 28, 'Kepanjangan dari PKRS adalah ...', 'Perkemahan Kreatif Remaja Sinode', 'Perkemahan Kader Remaja Sinode', 'Pekan Kreativitas Remaja Sinode', 'Pesta Kesenian Remaja Sinode', 'a'),
(2093, 29, 'Pendeta yang diangkat sebagai pekerja GMIM harus berusia minimal berapa tahun?', '25 tahun', '23 tahun', '27 tahun', '30 tahun', 'a'),
(2093, 30, 'Bidang P3SDM dalam KPRS singkatan dari ...', 'Perencanaan, Pengorganisasian, dan Pengawasan SDM', 'Pelayanan, Pengembangan, dan Pemberdayaan SDM', 'Pembinaan, Pengkaderan, dan Pengembangan Sumber Daya Manusia', 'Pendidikan, Pelatihan, dan Pengembangan SDM', 'c'),
(2093, 31, 'What are the speakers going to do (about Bruno Mars show)?', 'To stay at home', 'To see Bruno Mars show', 'To arrange their free time', 'To watch Bruno Mars at home', 'b'),
(2093, 32, 'Apa arti Gelar Atribut dalam Pemilihan Remaja Teladan?', 'Gelar khusus selain juara utama', 'Gelar juara utama', 'Penghargaan peserta', 'Sertifikat partisipasi', 'a'),
(2093, 33, 'Siapakah yang menulis kitab Ratapan?', 'Daniel', 'Yesaya', 'Yehezkiel', 'Yeremia', 'd'),
(2093, 34, 'Negara yang disebut sebagai Negeri Sakura adalah ...', 'Jepang', 'Korea Selatan', 'China', 'Taiwan', 'a'),
(2093, 35, 'Siapakah yang menjadi raja Israel yang membangun tembok Yerusalem?', 'Nehemia', 'Ezra', 'Zerubabel', 'Yosua', 'a'),
(2093, 36, 'Hari Persatuan Remaja GMIM yang dilaksanakan setiap tanggal 28 Januari diperingati juga sebagai hari apa?', 'Hari Kebersamaan Remaja GMIM', 'Hari Pembina Remaja GMIM', 'Hari Remaja GMIM', 'Hari Ulang Tahun Komisi Pelayanan Remaja Sinode', 'd'),
(2093, 37, 'Apa arti Pelayanan Kategorial?', 'Pelayanan berdasarkan kategori usia dan status', 'Pelayanan umum', 'Pelayanan khusus', 'Pelayanan harian', 'a'),
(2093, 38, 'Apakah kepanjangan dari NZG?', 'Nederlands Zendeling Genootschap', 'Nederlands Zending Genootschap', 'Nederland Zending Genootschap', 'Nederlanden Zending Genootschap', 'b'),
(2093, 39, 'Tema bulan Maret dan Tema Mingguan 17-23 Maret 2019 adalah?', 'Akulah yang awal dan yang akhir, dan ketaatan paripurna', 'Ketaatan paripurna, dan Akulah yang awal dan yang akhir', 'Tuhan adalah Alfa dan Omega, dan Ketaatan Paripurna', 'Dialah Tuhan yang awal dan yang akhir, dan kesetiaan', 'a'),
(2093, 40, 'Lima ekor sapi menghabiskan rumput seluas 5 kali ukuran lapangan sepak bola dalam waktu 5 hari. Berapa hari 1 ekor sapi menghabiskan 1 lapangan?', '1 hari', '3 hari', '5 hari', '7 hari', 'c'),
(2093, 41, 'Apa yang dimaksud dengan Leiturgia?', 'Kesaksian', 'Pelayanan kasih', 'Persekutuan', 'Ibadah dan penyembahan', 'd'),
(2093, 42, 'Rahmat ..... all of his friends to the celebration next week.', 'Will invite', 'Invites', 'Invited', 'Invitation', 'a'),
(2093, 43, 'Hasil dari 14 × 3 - 18 + 24 ÷ 4 adalah ...', '30', '32', '28', '34', 'a'),
(2093, 44, 'Apa tema Misi Remaja GMIM?', 'Berakar, bertumbuh, dan berbuah bagi Kristus', 'Remaja Bagi Kristus', 'Menjadi Teladan', 'Remaja Kreatif dan Inovatif', 'a'),
(2093, 45, 'Semboyan Reformasi Sola Gratia berarti ...', 'Keselamatan hanya oleh Alkitab', 'Keselamatan hanya oleh iman', 'Kemuliaan hanya bagi Tuhan', 'Keselamatan hanya oleh kasih karunia', 'd'),
(2093, 46, 'Siapakah penginjil yang datang ke tanah Minahasa pada tahun 1817?', 'Pdt. A.Z.R. Wenas', 'J.G. Schwarz', 'Ds. E.A.A. de Vreede', 'Johann Friedrich Riedel', 'd'),
(2093, 47, 'Deret bilangan: 2 4 6 8 10 ... bilangan selanjutnya adalah?', '12', '22', '44', '55', 'a'),
(2093, 48, 'Apa arti Pelayanan Lansia dalam struktur GMIM?', 'Pelayanan untuk usia 60 tahun ke atas', 'Pelayanan remaja', 'Pelayanan pemuda', 'Pelayanan anak', 'a'),
(2093, 49, 'Siapakah yang dilempar ke dalam gua singa karena tetap berdoa kepada Tuhan?', 'Daniel', 'Daud', 'Yusuf', 'Musa', 'a'),
(2093, 50, 'Apa arti Jemaat dalam struktur GMIM?', 'Persekutuan orang percaya di suatu tempat', 'Bangunan gereja', 'Majelis gereja', 'Organisasi gereja', 'a');
