-- TAHUN 2018 - Soal 1 s.d 80
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2018, 1, 'Judul Perikop Markus 16 : 1-8 adalah', 'Kebangkitan Yesus', 'Yesus di salibkan', 'Perintah untuk memberitakan Injil', 'Yesus dikuburkan', 'a'),
(2018, 2, 'Lengkapi Nats: "Jangan takut, Kamu mencari Yesus orang Nazaret yang disalibkan itu. ... Ia tidak ada disini. Lihat! Inilah tempat mereka membaringkan Dia."', 'Ia telah bangkit', 'Ia telah dibangkitkan', 'Ia sudah bangkit', 'Ia sudah dibangkitkan', 'b'),
(2018, 3, 'Kitab yang terletak diantara Kitab Nehemia dan Ayub adalah Kitab :', 'Mazmur', 'Ester', 'Amsal', 'Ezra', 'b'),
(2018, 4, '"Demikianlah tinggal ketiga hal ini, yaitu iman, pengharapan dan kasih, dan yang paling besar diantaranya ialah Kasih." Nats ini terdapat dalam :', 'I Korintus 13:1', 'I Korintus 13:13', 'I Korintus 13:3', 'I Korintus 1:13', 'b'),
(2018, 5, 'Lengkapi Nats: "Jangan seorang pun menganggap engkau rendah karena engkau muda. Jadilah teladan bagi orang-orang percaya, dalam ..."', 'Perkataanmu, dalam tingkah ujarmu, dalam kasihmu, dalam kesetiaanmu dan dalam kesucianmu', 'Perkataanmu, dalam tingkah lakumu, dalam kesetiaanmu, dalam kasihmu dan dalam kesucianmu', 'Tingkah lakumu, dalam perkataanmu, dalam kasihmu, dalam kesetiaanmu dan dalam kesucianmu', 'Tingkah lakumu, dalam perkataanmu, dalam kesetiaanmu, dalam kasihmu dan dalam kesucianmu', 'b'),
(2018, 6, 'Tema Mingguan untuk 29 April – 05 Mei 2018 adalah :', 'Sinergisitas antar Pelayan dan Lembaga Pelayanan', 'Kasih Mengutuhkan Pelayanan', 'Doa dan Puasa Menopang Kesinambungan Pelayanan', 'Pemimpin yang bijaksana mendengar setiap aspirasi', 'b'),
(2018, 7, 'Menurut I Raja 12:17, yang menjadi Raja hanya atas orang Israel yang diam di kota-kota Yehuda adalah :', 'Yerobeam', 'Rehabeam', 'Abiam', 'Asa', 'b'),
(2018, 8, 'Nats : "Dengan apakah seorang muda mempertahankan kelakuannya bersih? Dengan menjaganya sesuai dengan firman-Mu" terdapat dalam Kitab :', 'Amsal', 'Mazmur', 'I Timotius', 'II Timotius', 'b'),
(2018, 9, 'Mazmur 23:1-6 judul perikopnya adalah :', 'Doa dalam Pergumulan', 'Tuhan, gembalaku yang baik', 'Doa pada malam hari', 'Dalam Perlindungan Tuhan', 'b'),
(2018, 10, 'Nats : "Janganlah kamu menjadi serupa dengan dunia ini, tetapi berubahlah oleh pembaharuan budimu..." terdapat dalam kitab :', 'I Korintus', 'II Korintus', 'Roma', 'I Timotius', 'c'),
(2018, 11, 'Pasal berapakah dari Kitab Mazmur yang paling banyak ayatnya :', '117', '118', '119', '120', 'c'),
(2018, 12, 'Perikop terpendek dalam Kitab Mazmur adalah :', '117:1-2', '117:1', '117:1-3', '17:1-2', 'a'),
(2018, 13, 'Ayat terpendek dalam Alkitab adalah :', 'Yohanes 11:35', '1 Tesalonika 5:17', '1 Tesalonika 5:16', '1 Tesalonika 5:15', 'a'),
(2018, 14, 'Berikut ini adalah Kitab-Kitab Nabi Kecil, KECUALI :', 'Yoel', 'Hagai', 'Ezra', 'Zakharia', 'c'),
(2018, 15, 'Sampai dengan Tata Gereja 2007, GMIM telah memiliki berapa Tata Gereja ?', '10', '12', '11', '13', 'c'),
(2018, 16, 'Yang karena kemampuan dan keteladanannya dipercayakan untuk memberikan nasihat kepada Majelis jemaat diminta atau tidak diminta adalah :', 'Penasehat', 'Penasihat Majelis Jemaat', 'Penasehat Jemaat', 'Tua-Tua Jemaat', 'b'),
(2018, 17, 'Perangkat Pelayanan yang membantu BPMJ melaksanakan bidang pelayanan kategorial adalah :', 'Komisi Pelayanan Kategorial BIPRA Sinode', 'Komisi Pelayanan Kategorial', 'Komisi Pelayanan Kategorial BIPRA Jemaat', 'Komisi Pelayanan Kategorial BIPRA Wilayah', 'b'),
(2018, 18, 'Perangkat Pelayanan yang membantu BPMW untuk melaksanakan pelayanan bidang tertentu adalah:', 'Komisi Pelayanan BIPRA Wilayah', 'Kelompok Fungsional Jemaat', 'Komisi Kerja Wilayah', 'Komisi Kerja Bidang Wilayah', 'c'),
(2018, 19, 'Berikut adalah Peraturan-Peraturan dalam Tata Gereja GMIM 2016, KECUALI', 'Peraturan tentang Jemaat', 'Peraturan tentang Pelayan Khusus', 'Peraturan Tentang Sinode', 'Peraturan tentang Komisi Kategorial', 'd'),
(2018, 20, 'Peraturan tentang Jemaat Bab VIII adalah :', 'Pelayanan Kategorial', 'Pelayanan Komisi Kerja', 'Badan Pengawas Perbendaharaan', 'Majelis Jemaat', 'a'),
(2018, 21, 'Sesuai Tata Gereja 2016, Usia Remaja yang adalah anggota GMIM :', '12 tahun sampai dengan 17 tahun', '12 tahun sampai dengan 17 tahun 364 hari', '12 tahun sampai dengan 16 tahun', '12 tahun sampai dengan 16 tahun 364 hari', 'd'),
(2018, 22, 'Sesuai Peraturan Tentang Jemaat Pasal 30 ayat 1, Rapat Komisi Pelayanan Kategorial dilaksanakan sekurang-kurangnya :', 'Sekali dalam sebulan', 'Sekali dalam 3 bulan', 'Sekali dalam 2 bulan', 'semua salah', 'a'),
(2018, 23, 'Sesuai Peraturan tentang Jemaat Pasal 30 ayat 11, Komisi Mempertanggungjawabkan pelaksanaan tugasnya kepada :', 'Sidi Jemaat', 'Badan Pekerja Majelis Jemaat', 'Majelis Jemaat', 'Konsultasi Pelayanan', 'b'),
(2018, 24, 'Sesuai Peraturan tentang Wilayah pasal 17 ayat 2, maka Rapat Komisi dipimpin oleh :', 'Ketua Komisi', 'Ketua dan Sekretaris Komisi', 'Ketua, Sekretaris dan Asisten Bendahara', 'Anggota Komisi tertua dan termuda', 'b'),
(2018, 25, 'Sesuai Peraturan tentang Sinode pasal 30 ayat 2, maka Rapat Komisi dipimpin oleh :', 'Ketua dan Sekretaris Komisi', 'Anggota Komisi yang ditunjuk', 'Ketua Komisi', 'Ketua, Sekretaris dan Asisten Bendahara', 'a'),
(2018, 26, 'Tahun 1860, lebih dari 50% penduduk Minahasa sudah menjadi Kristen sehingga terbentuk 10 Pos Pekabaran Injil yaitu :', 'Tondano, Langoan, Amurang, Tomohon, Kema, Tanawangko, Kumelembuai, Sonder, Ratahan dan Talawaan', 'Tondano, Kawangkoan, Amurang, Tomohon, Kema, Tanawangko, Kumelembuai, Sonder, Ratahan dan Talawaan', 'Talawaan, Ratahan, Tondano, Tumpaan, Tanawangko, Tomohon, Amurang, Sonder, Kumelembuai, Kema', 'Amurang, Sonder, Kumelembuai, Kema, Talawaan, Ratahan, Tondano, Tanawangko, Tomohon, Motoling', 'b'),
(2018, 27, 'Ketua Badan Pekerja Sinode yang menjabat dua kali adalah :', 'Ds. R. M. Luntungan', 'Ds. A. Z. R. Wenas', 'Ds. M. Sondakh', 'Pdt. K. H. Rondo, M.Th', 'b'),
(2018, 28, 'Ketua Badan Pekerja Majelis Sinode sekarang ini : Pdtr. Dr. Hein Arina sebelumnya menjabat sebagai :', 'Wakil Ketua Bidang Ajaran Pembinaan dan Penggembalaan', 'Wakil Ketua Bidang Hubungan Kerjasama', 'Wakil Ketua Bidang Pengembangan Sumber Daya', 'Ketua BPMJ GMIM Sion Winangun', 'a'),
(2018, 29, 'Sebelum menjadi Wakil Ketua Bidang Ajaran, Pembinaan dan Penggembalaan BPMS Periode 2018-2022, Pdtr. Anthonius D. Sompe, M. Teol adalah :', 'Sekretaris Departemen Ajaran', 'Sekretaris Departemen Pembinaan', 'Sekretaris Departemen Penggembalaan', 'Sekretaris Departemen Pekerja GMIM', 'a'),
(2018, 30, 'Menurut Buku Kerja 2018, Data s.d. Januari 2018, GMIM terdiri dari berapa Wilayah dan Jemaat :', '126 Wilayah, 968 Jemaat', '125 Wilayah, 986 Jemaat', '125 Wilayah, 968 Jemaat', '126 Wilayah, 986 Jemaat', 'd'),
(2018, 31, 'Berikut ini adalah Wilayah Paling Baru di GMIM, KECUALI :', 'Bitung XII', 'Tondano Lima', 'Remboken Satu', 'Langowan Lima', 'd'),
(2018, 32, 'Sesuai Buku Almanak Kristen Indonesia (BAKI) 2017, Anggota PGI ke-5 adalah :', 'Gereja Masehi Injili Sangihe Talaud (GMIST)', 'Gereja Masehi Injili Minahasa (GMIM)', 'Gereja Kalimantan Evangelis (GKE)', 'Gereja Protestan Maluku (GPM)', 'b'),
(2018, 33, 'Tema Pelayanan GMIM : "Tuhan mengangkat kita dari Samudera Raya" :', 'Matius 17:20b', 'Mazmur 70:2b', 'Mazmur 71:20b', 'Mazmur 17:20b', 'c'),
(2018, 34, 'Mengapa tanggal 28 Januari ditetapkan sebagai Hari Persatuan Remaja GMIM :', 'Tanggal Pelaksanaan Konsultasi Pertama Komisi Remaja Sinode GMIM', 'Tanggal Terpilihnya Pengurus Komisi Remaja Sinode yang Pertama', 'Tanggal Lahirnya Ketua Komisi Remaja Sinode yang pertama', 'Tanggal Ditetapkannya Tata Gereja GMIM yang memuat pembentukan Komisi Pelayanan Khusus Remaja', 'a'),
(2018, 35, 'Jika Rapat Pemilihan Komisi Pelayanan Remaja Sinode periode 2018-2022 dilaksanakan pada tanggal 3 Maret 2018 maka Pelayanan sebelumnya dilaksanakan pada :', '7 Maret 2014', '17 Maret 2014', '20 Februari 2014', '20 Maret 2014', 'd'),
(2018, 36, 'Dimanakah Pemilihan Kembali terjadi untuk Pengurus Komisi Pelayanan Remaja Sinode GMIM periode 2005-2010 dilaksanakan :', 'Auditorium Kantor Sinode GMIM di Tomohon', 'Auditorium Kantor Gubernur Sulut di Manado', 'Gedung Bukit Inspirasi Tomohon', 'Wale neh Tou Minahasa di Tondano', 'c'),
(2018, 37, 'Sekretaris Pertama Komisi Pelayanan Remaja Sinode GMIM adalah :', 'Pnt. Ir. Diana Makagiansar Pioh', 'Pnt. Ir. Wenny Pantouw', 'Pnt. Edward Timbuleng', 'Pnt. Jessy Wuisan', 'a'),
(2018, 38, 'Berikut adalah nama-nama bidang KPRS GMIM Periode 2018-2022, KECUALI :', 'Bidang Pengembangan Minat dan Bakat (PMB)', 'Bidang Pembinaan, Pengkaderan dan Pengembangan Sumber Daya Manusia (P3SDM)', 'Bidang Pelayanan Siswa (Pelsis)', 'Bidang Pelayanan Siswa dan Retel', 'd'),
(2018, 39, 'Anggota KPRS GMIM periode 2018-2022 yang juga ketua Bidang PMB adalah :', 'Pnt. Rinaldo G. Memah', 'Pnt. Melky Nender', 'Pnt. dr. Bonny F. Rompas', 'Pnt. Haris Sedua', 'b'),
(2018, 40, 'Siapakah Ketua Komisi Pelayanan Remaja Wilayah Tanahwangko II terpilih periode 2018-2022?', 'Pnt. Meillany Mongilala, S.T', 'Pnt. DR. Fietber Raco, S.Pd. M.Si', 'Pnt. Melky Pattiwael', 'Pnt. Stevie Kaligis', 'a'),
(2018, 41, 'Salah satu kalimat tanya yang tepat diajukan pewawancara adalah', 'Apakah pelaksanaan pentas seni sudah Anda pikirkan masak-masak?', 'Bagaimana dampak pentas seni terhadap kreativitas siswa ini, Bu?', 'Bagaimana cara Ibu mendapatkan dana untuk pembiayaan pentas seni ini?', 'Bagaimana pendapat Ibu terhadap pentas seni ini?', 'c'),
(2018, 42, 'Ide pokok wawancara tersebut adalah ....', 'Sebab-sebab Pak Sareno meninggal dunia', 'Sebab-sebab Pak Sareno sakit', 'Usaha yang dilakukan Pak Sareno untuk sembuh', 'Usaha para dukun untuk menyembuhkan Pak Sareno', 'a'),
(2018, 43, 'Berikut ini hal-hal yang perlu diperhatikan seorang pewawancara, kecuali ....', 'gunakan bahasa yang sopan', 'diawali wawancara dengan ucapan selamat', 'arahkan pandangan ke narasumber', 'menyanjung tinggi narasumber', 'd'),
(2018, 44, 'Alasan yang kurang logis dalam pengungkapan cita-cita di atas terdapat pada nomor ....', '(1)', '(3)', '(2)', '(4)', 'a'),
(2018, 45, 'Salah satu hal yang sangat penting dan harus diperhatikan seorang calon pemeran ialah memahami ciri-ciri tokoh yang hendak diperankan, kecuali ....', 'Biologis', 'Psikologis', 'sosiologis', 'estetik', 'd'),
(2018, 46, 'Berikut adalah berkaitan dengan pementasan drama, kecuali ....', 'tata rias', 'tata musik', 'tata lampu', 'tata busana', 'b'),
(2018, 47, 'Could you tell me your surname?', 'Would you like me to spell it?', 'Do you like it?', 'How do I say it?', 'How do you know it?', 'a'),
(2018, 48, 'I hope it doesn''t rain.', 'Of course not.', 'Sure, it does.', 'Will it be heavy?', 'So do I.', 'd'),
(2018, 49, 'Let''s go by bus.', 'It''ll take too long.', 'We''ll buy a ticket.', 'The train is expensive.', 'I don''t know where it is.', 'a'),
(2018, 50, 'Shall we go out for pizza tonight?', 'I know that.', 'Please don''t go.', 'I''ll pass, I''m too tired.', 'I see.', 'c'),
(2018, 51, 'What was the man and his wife prayed for? (Kebo Iwa story)', 'A house', 'A kingdom', 'A child', 'Wealth', 'c'),
(2018, 52, 'The word "his" in line 5 refers to?', 'Buffalo', 'Kebo Iwa''s father', 'The Baby Boy', 'Kebo Iwa', 'c'),
(2018, 53, 'Perbandingan uang Raka dan uang Sekar adalah 3:2. Jika uang Adi dan Ida berjumlah Rp150.000, berapa masing-masing uang Adi dan Ida?', 'Rp80.000 dan Rp60.000', 'Rp90.000 dan Rp60.000', 'Rp90.000 dan Rp70.000', 'Rp100.000 dan Rp80.000', 'b'),
(2018, 54, 'Angga mempunyai uang Rp4.500.000 dan ia berniat membeli sebuah handycam seharga Rp2.500.000 sebelum diskon 20%. Berapa sisa uang Angga saat ini?', 'Rp1.000.000', 'Rp1.200.000', 'Rp1.300.000', 'Rp1.400.000', 'a'),
(2018, 55, 'Bentuk sederhana dari (3√2 + 2√3)(3√2 - 2√3) adalah', '6', '12', '18', '24', 'a'),
(2018, 56, 'Rumus suku ke-n dari barisan 15, 13, 11, 9, ... adalah', 'Un = 17 - 2n', 'Un = 16 - 2n', 'Un = 15 - 2n', 'Un = 14 - 2n', 'a'),
(2018, 57, 'Dalam sebuah kotak terdapat 5 bola merah dan 4 bola putih. Peluang terambil 2 bola merah dan 1 bola putih adalah', '10/21', '20/63', '30/63', '40/63', 'd'),
(2018, 58, 'Diketahui deret aritmatika dengan suku ke-3 = 9 dan suku ke-7 = 21. Jumlah 10 suku pertama adalah', '120', '150', '180', '210', 'c'),
(2018, 59, 'Persamaan garis yang melalui titik (2,3) dan sejajar dengan garis 2x + 3y = 6 adalah', '2x + 3y = 12', '2x + 3y = 13', '3x + 2y = 12', '3x + 2y = 13', 'b'),
(2018, 60, 'Nilai x yang memenuhi pertidaksamaan |x - 3| < 2 adalah', '1 < x < 5', 'x < 1 atau x > 5', '1 < x < 5', 'x < 1 atau x > 5', 'a'),
(2018, 61, 'Diketahui sin A = 3/5 dan A sudut lancip. Nilai tan A adalah', '3/4', '4/3', '3/5', '4/5', 'a'),
(2018, 62, 'Besar sudut terkecil yang dibentuk jarum jam pada pukul 04.30 adalah', '45°', '60°', '75°', '90°', 'a'),
(2018, 63, 'Usaha yang dilakukan oleh resultan ketiga gaya tersebut adalah . . .', '7,5 joule', '17,5 joule', '30 joule', '70 joule', 'd'),
(2018, 64, 'Jika benda seberat 500 N dinaikkan ke atas setinggi 4 m menggunakan bidang miring sepanjang 16 m, maka kuasa yang digunakan adalah . . .', '125 N', '250 N', '500 N', '2000 N', 'a'),
(2018, 65, 'Rumus kimia yang benar untuk magnesium hidroksida dan natrium sulfat masing-masing adalah nomor . . .', '(1) dan (2)', '(1) dan (3)', '(2) dan (4)', '(3) dan (4)', 'c'),
(2018, 66, 'Sekjen Perserikatan Bangsa-Bangsa (United Nation) sekarang ini adalah :', 'Ban Ki-moon', 'Anton Guterres', 'Antonio Guterres', 'Antonio Guiterres', 'c'),
(2018, 67, 'Panitia kecil yang dibentuk pada sidang BPUPKI 1 diketuai oleh . . .', 'Moh. Hatta', 'Ir. Soekarno', 'Moh. Yamin', 'Mr. Ahmad Subarja', 'b'),
(2018, 68, 'Berapa lama Indonesia dijajah oleh Belanda dan Jepang?', '350 tahun dan 3,5 tahun', '35 tahun dan 3,5 tahun', '350 tahun dan 35 tahun', '3,5 tahun dan 35 tahun', 'a'),
(2018, 69, 'Titik-titik pengukuran ketinggian suatu tempat digunakan . . .', 'Titik Trigulasi', 'Titik Kontur', 'Titik Proyeksi', 'Titik Ketinggian', 'a'),
(2018, 70, 'Siapakah Gubernur Sulawesi Utara periode 2000 - 2005?', 'Drs. Adolf Jouke Sondakh', 'Cornelius J Rantung', 'H. V Worang', 'E. E Mangindaan', 'a'),
(2018, 71, 'Negara terkecil di dunia adalah?', 'Monaco', 'Sealand', 'Vatikan', 'Kongo', 'c'),
(2018, 72, 'Negara kecil yang sangat kaya dan benderanya sama dengan Belanda adalah?', 'Monako', 'Luxemburg', 'Sealand', 'Kongo', 'b'),
(2018, 73, 'Kota yang adalah pusat keuangan Amerika Serikat adalah?', 'Washington DC', 'Los Angeles', 'New York', 'California', 'c'),
(2018, 74, 'Sudut terkecil yang dibentuk jam pada pukul 04.00 adalah?', '45 derajat', '90 derajat', '60 derajat', '120 derajat', 'd'),
(2018, 75, 'Danau terbesar di dunia adalah?', 'Laut Kaspia', 'Danau Huron', 'Danau Victoria', 'Danau Toba', 'a'),
(2018, 76, 'Ledakan bintang di galaksi disebut?', 'Supernova', 'Super moon', 'Blue Supermoon', 'Supergalaksi', 'a'),
(2018, 77, 'Siapakah tokoh asal Sulawesi Utara yang ditetapkan sebagai Pahlawan Nasional pada tanggal 6 November 2013?', 'Jahja Daniel Dharma', 'Bernard Wilhelm Lapian', 'Lambertus Nicodemus Palar', 'Robert Wolter Monginsidi', 'a'),
(2018, 78, 'Kapan Pemilihan Kepala Daerah serentak 2018 akan diselenggarakan dan berapa daerah yang akan menyelenggarakannya?', '27 Juni 2018 dan 161 daerah', '27 Juni 2018 dan 171 daerah', '27 Juli 2018 dan 161 daerah', '27 Juli 2018 dan 151 daerah', 'b'),
(2018, 79, 'Sekjen Perserikatan Bangsa-Bangsa (United Nation) sekarang ini adalah :', 'Ban Ki-moon', 'Anton Guterres', 'Antonio Guterres', 'Antonio Guiterres', 'c'),
(2018, 80, 'Dokter yang terkenal dengan praktik "cuci otak" adalah :', 'Prof. Dr. Ilham Oetama Marsis', 'Mayjen dr. Terawan Agus Putranto', 'a dan b benar', 'a dan c salah', 'b');
