-- TAHUN 2021 - Soal 1 s.d 50
INSERT INTO soal_tes (tahun, nomor_soal, teks_soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES
(2021, 1, 'Ide pokok paragraf tentang strategi mengatasi wabah merokok adalah . . .', 'strategi mengatasi wabah merokok', 'saran membatasi strategi merokok', 'wabah merokok yang merajalela', 'penelitian tentang dampak merokok', 'a'),
(2021, 2, 'Kalimat utama pada paragraf tentang stasiun televisi dan wayang kulit terdapat pada nomor . . .', '(1)', '(2)', '(3)', '(4)', 'a'),
(2021, 3, 'Kalimat penjelas yang tidak padu dalam paragraf tentang Mars adalah kalimat nomor…', '(1)', '(2)', '(3)', '(5)', 'd'),
(2021, 4, 'Kata baku yang tepat untuk melengkapi paragraf tentang KIR adalah . . .', 'keanggautaan, khususnya, berisiko', 'anggota, khusus, risiko', 'keanggotaan, kekhususan, risiko', 'beranggota, dikhususkan, berisiko', 'b'),
(2021, 5, 'Salah satu bukti kebenaran dari teori Lempeng Tektonik adalah fenomena....', 'pasang surut air laut', 'fenomena lumpur panas Lapindo', 'erosi oleh angin pada bukit gundul', 'tsunami', 'd'),
(2021, 6, 'Planet M yang dijuluki Bintang timur dan Bintang Senja sebenarnya adalah....', 'Yupiter', 'Neptunus', 'Venus', 'Mars', 'c'),
(2021, 7, 'Planet X yang memiliki karakteristik planet terestrial, disebut planet merah, mengandung debu besi teroksidasi adalah....', 'Merkurius', 'Venus', 'Yupiter', 'Mars', 'd'),
(2021, 8, 'Tumbukan lempeng Indo-Australia dan lempeng Eurasia mengakibatkan wilayah Indonesia sering mengalami....', 'gempa vulkanik dan angin topan', 'gempa tektonik dan banjir', 'gempa tektonik dan gejala vulkanik', 'banjir dan kebanjiran', 'c'),
(2021, 9, 'Peter wanted to buy five ...... at the shop yesterday.', 'briefs', 'brivees', 'pen', 'book', 'a'),
(2021, 10, 'One of the ...... in the classroom is my friend.', 'student', 'girl', 'teacher', 'boys', 'd'),
(2021, 11, 'How many ...... are there in the seminar?', 'people', 'attendant', 'manager', 'employee', 'a'),
(2021, 12, 'The ...... were arrested last week.', 'thieves', 'thief', 'thiefs', 'law-breaker', 'a'),
(2021, 13, '"Inilah permulaan Injil tentang Yesus Kristus, Anak Allah." Kalimat ini adalah kalimat pembukaan dari Injil ...', 'Matius', 'Markus', 'Lukas', 'Yohanes', 'b'),
(2021, 14, 'Apakah nama lain yang diberikan kepada Daniel?', 'Belsyazar', 'Darius', 'Beltsazar', 'Koresh', 'c'),
(2021, 15, '"Orang yang mendengar firman itu, lalu kekuatiran dunia ini dan tipu daya kekayaan menghimpit firman itu sehingga tidak berbuah" adalah laksana benih yang ditaburkan di ...', 'Pinggir jalan', 'Tanah yang berbatu-batu', 'Tengah semak duri', 'Tanah yang baik', 'c'),
(2021, 16, 'Berikut adalah nama-nama anak perempuan Ayub, kecuali ...', 'Yemima', 'Kezia', 'Abisag', 'Kerenhapukh', 'c'),
(2021, 17, 'Di manakah terdapat air yang tidak dapat diminum oleh orang Israel karena rasanya yang pahit?', 'Mara', 'Elim', 'Masa', 'Meriba', 'a'),
(2021, 18, 'Siapakah nama ayah dan ibu dari Samuel?', 'Abraham dan Sara', 'Amram dan Yokhebed', 'Elkana dan Hana', 'Yusuf dan Maria', 'c'),
(2021, 19, 'Berapakah jumlah orang yang menerima perkataan Petrus dan memberi diri dibaptis pada hari Pentakosta?', '120 orang', '3000 orang', '5000 orang', '12 orang', 'b'),
(2021, 20, 'GMIM sebagai gereja Tuhan ditata dalam sistem presbiterial sinodal. Kepala gerejanya adalah ...', 'Ketua BPMS', 'Rasul-rasul', 'Nabi-nabi', 'Yesus Kristus', 'd'),
(2021, 21, 'GMIM sebagai gereja Tuhan melayankan sakramen, yakni ...', 'Sakramen Baptisan Kudus', 'Sakramen Perjamuan Kudus', 'Sakramen Baptisan Kudus dan Sakramen Perjamuan Kudus', 'Sakramen Baptisan Kudus, Sakramen Perjamuan Kudus, dan Sakramen Pernikahan Kudus', 'c'),
(2021, 22, 'Himpunan penyelesaian dari pertidaksamaan |x + 2| < 5 adalah', '-7 ≤ x ≤ -3', '7 ≤ x ≤ 3', '-7 ≤ x ≤ 3', '3 ≤ x ≤ 7', 'c'),
(2021, 23, 'Pengakuan Iman Nicea-Konstantinopel dibuka dengan kalimat ...', 'Aku percaya kepada satu Allah, Bapa yang mahakuasa, Pencipta langit dan bumi.', 'Aku percaya kepada Allah, Bapa yang mahakuasa, Khalik langit dan bumi.', 'Kami mengaku bahwa Tuhan Allah yang kekal itu: Esa, Berdaulat; Bapa Pencipta dan Pemelihara alam semesta.', 'Bapa kami yang di sorga, dikuduskanlah nama-Mu, datanglah kerajaan-Mu, jadilah kehendak-Mu, di bumi seperti di sorga.', 'a'),
(2021, 24, 'Dalam pengajaran GMIM tentang baptisan kudus, baptisan adalah ...', 'Tanda perjanjian antara Allah dengan orang-orang yang dipanggil-Nya, serta keturunannya.', 'Pengganti sunat sebagai tanda perjanjian.', 'Dilakukan dalam nama Allah Bapa, Anak, dan Roh Kudus.', 'Semuanya benar.', 'd'),
(2021, 25, 'Nilai x yang memenuhi pertidaksamaan |x - 1| ≥ 6 adalah', 'x ≥ 7 atau x ≥ 5', 'x ≥ 7 atau x ≤ -5', 'x ≤ -7 atau x ≤ -5', 'x ≥ 2 atau x ≤ 5', 'b'),
(2021, 26, 'Seseorang dapat menerima sakramen Perjamuan Kudus bila ...', 'Sudah berusia 17 tahun ke atas.', 'Sudah menikah.', 'Sudah diteguhkan sebagai anggota sidi jemaat.', 'Sudah mendapat izin dari orang tua.', 'c'),
(2021, 27, 'Siapakah yang dimaksud dengan Imago Dei itu?', 'Manusia, laki-laki dan perempuan.', 'Hewan', 'Tumbuh-tumbuhan', 'Semuanya benar', 'a'),
(2021, 28, 'Semboyan Reformasi Gereja adalah sebagai berikut, kecuali …', 'Sola Fide', 'Sola Gratia', 'Ora et Labora', 'Soli Deo Gloria', 'c'),
(2021, 29, 'Wakil presiden wanita pertama dalam sejarah AS, serta wakil presiden Amerika pertama dari keturunan Afrika dan Asia-Amerika adalah :', 'Elizabeth Ann Warren', 'Kamala Devi Harris', 'Alexandra Ocasio-Cortez', 'Oprah Gail Winfrey', 'b'),
(2021, 30, 'Semboyan Reformasi Gereja "Sola Fide" mengandung maksud …', 'Keselamatan hanya oleh iman.', 'Keselamatan hanya oleh anugerah.', 'Keselamatan oleh iman dan perbuatan baik.', 'Keselamatan oleh perbuatan baik.', 'a'),
(2021, 31, 'Kabinet yang dibentuk pada periode 2019-2024 disebut dengan kabinet :', 'Kabinet Gotong Royong', 'Kabinet Indonesia', 'Kabinet Kerja', 'Kabinet Indonesia Maju', 'd'),
(2021, 32, 'Visi remaja GMIM adalah:', 'Remaja Bagi Kristus.', 'Kristus Bagi Remaja', 'Remaja Bertumbuh dalam Kristus', 'Remaja Berdoa dan Bekerja', 'a'),
(2021, 33, 'Menteri Pendidikan dan Kebudayaan yang merupakan pendiri GOJEK adalah :', 'Nadiem Anwar Makarim', 'Wishnutama Kusubandio', 'Sandiaga Uno', 'Erick Thohir', 'a'),
(2021, 34, 'Misi remaja GMIM adalah:', 'menjadikan remaja GMIM yang bertumbuh, dan berbuah bagi Kristus.', 'menjadikan remaja GMIM yang berakar, dan berbuah bagi Kristus', 'menjadikan remaja GMIM yang berbuah, bertumbuh, dan berakar bagi Kristus', 'menjadikan remaja GMIM yang berakar, bertumbuh, dan berbuah bagi Kristus', 'd'),
(2021, 35, 'Himpunan penyelesaian dari pertidaksamaan |2x + 1| < 5 adalah', '-3 ≤ x ≤ -2', '3 ≤ x ≤ 3', '-3 ≤ x ≤ 2', '3 ≤ x ≤ 2', 'c'),
(2021, 36, 'Nama jenis virus yang menyebabkan COVID-19 adalah:', 'SARS-CoV', 'SARS-CoV-2', 'MERS-CoV', 'HCoV-HKU1', 'b'),
(2021, 37, 'SIKAT akronim dari:', 'Sistem Informasi Kegiatan Teknis', 'Sistem Informasi Komunikasi Terpadu', 'Sistem Informasi Kegiatan Terpadu', 'Sistem Informasi Kegiatan Terkini', 'c'),
(2021, 38, 'Tuan rumah Olimpiade Musim Panas 2020 adalah:', 'Beijing', 'Seoul', 'Rio de Janeiro', 'Tokyo', 'd'),
(2021, 39, 'Berdasarkan arahnya, evolusi dapat dibedakan menjadi dua, yaitu', 'Makroevolusi dan mikroevolusi', 'Progresif dan regresif', 'Konvergen dan divergen', 'Kimia dan biologi', 'b'),
(2021, 40, 'Dibawah ini yang tidak termasuk ciri remaja Kristen adalah:', 'menempatkan Tuhan sebagai yang pertama dan terutama dalam hidup', 'bertindak dengan penuh pertimbangan dan mendasarkannya pada kehendak Tuhan', 'memahami betul kehendak Tuhan yang seperti yang disampaikan dalam Alkitab dan ajaran gereja', 'Enggan bertanggung jawab atas segala tindakan, tutur kata dan sikap yang dilakukan.', 'd'),
(2021, 41, 'Kepanjangan yang benar dari Bidang LKRG adalah:', 'Latihan Kepemimpinan Remaja GMIM', 'Latihan Ketrampilan Remaja Gereja', 'Latihan Kader Remaja Gereja', 'Latihan Kegenerasian Remaja Gereja', 'c'),
(2021, 42, 'Seutas tali panjangnya 40 m digetarkan transversal, cepat rambat gelombang 50 m/s. Jika gaya tegang 2,5 N, massa tali adalah ... kg.', '0,03', '0,04', '0,08', '0,09', 'b'),
(2021, 43, 'Siapakah Ketua Bidang Data Base & Umum Periode 2010-2014 yang juga menjabat wakil Sekretaris KPRS?', 'Edward Eddy Timbuleng', 'Pnt. Fietberg Raco, SPd', 'Ruddy Marck Ratag', 'Pnt. Meksi Sahensolar', 'c'),
(2021, 44, 'Kelompok tumbuhan yang menunjukkan variasi individu dalam satu spesies adalah...', 'Jambu Bangkok, jambu mente dan nanas bogor', 'Mangga gadung, manga manalagi dan manga golek', 'Cabe rawit, terong dan tomat', 'Padi, jagung dan gandum', 'b'),
(2021, 45, 'Gelombang transversal merambat dari A ke B dengan cepat rambat 12 m/s pada frekuensi 4 Hz. Jika jarak AB = 18 m, banyaknya gelombang sepanjang AB adalah', '9', '8', '7', '6', 'd'),
(2021, 46, 'Kegiatan apakah yang dilaksanakan di GMIM Baitel Tuutu Tondano 2 pada tahun 2019?', 'Ibadah Agung HUT KPRS GMIM', 'Ibadah PASKAH Remaja GMIM', 'Ibadah Hari Persatuan Remaja GMIM', 'Ibadah Pesta Seni Remaja GMIM', 'b'),
(2021, 47, 'Di manakah Ibadah Hari Persatuan Remaja GMIM dan HUT KPRS GMIM ke 31 dilaksanakan :', 'GMIM Pinel Kakas Wil Kakas I', 'GMIM Sion Noongan Wil Langowan Kelelondei', 'GMIM Daniel Karumenga Wil Langowan II', 'GMIM Sion Rumbia Wil Pinaesaan', 'c'),
(2021, 48, 'Remaja GMIM ideal berdasarkan Lukas 2:52 memiliki 4 Dimensi :', 'Dimensi Fisik, Dimensi Spiritual, Dimensi Iman dan Dimensi Sosial', 'Dimensi Fisik, Dimensi Pengetahuan, Dimensi Iman dan Dimensi Spiritual', 'Dimensi Fisik, Dimensi Pengetahuan, Dimensi Iman dan Dimensi Sosial', 'Dimensi Fisik, Dimensi Pengetahuan, Dimensi Mental dan Dimensi Sosial', 'c'),
(2021, 49, 'Planet-planet luar ditunjukkan nomor.... (Yupiter, Merkurius, Venus, Saturnus, Bumi, Uranus)', '1), 2), dan 3)', '1), 4), dan 6)', '2), 3), dan 4)', '2), 5), dan 6)', 'b'),
(2021, 50, 'Berikut adalah perkataan-perkataan Yesus ketika di atas kayu salib, kecuali ...', 'Ibu, inilah, anakmu!', 'Aku haus!', 'Ya Bapa, ampunilah mereka, sebab mereka tidak tahu apa yang mereka perbuat.', 'Hai puteri-puteri Yerusalem, janganlah kamu menangisi Aku, melainkan tangisilah dirimu sendiri dan anak-anakmu!', 'd');
